### PR TITLE
DDF-2767: Removed bower.

### PR DESCRIPTION
**Pull request by djblue**
#### What does this PR do?

Removes bower.

#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged)?

@andrewkfiedler 
@AzGoalie 
@brendan-hofmann 

#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).

@stustison 
@pklinef

#### How should this be tested? (List steps with links to updated documentation)

- Pull down https://github.com/djblue/webjars/tree/DDF-2767 and build.
- Pull down the PR changes and do a quick build.
- Bring up all the uis and open the network tab in the devtools.
- Make sure everything loads.
- Since there are a lot of changes, it might be helpful to review each commit separately.

NOTE: https://github.com/djblue/webjars/tree/DDF-2767 needs to be merged and released before this PR can be merged.

#### Any background context you want to provide?

Bower is causing issues with reproducible and stable builds. To fix this issue, bower is being removed and dependencies are being resolved using npm or webjars.

#### What are the relevant tickets?

[DDF-2767](https://codice.atlassian.net/browse/DDF-2767)

#### Checklist:
- [ ] Documentation Updated
- [ ] Change Log Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by brendan-hofmann** [comment]
Saw a couple of 404s on the catalog ui. 
image

**Comment by pklinef** [comment]
https://github.com/codice/webjars/pull/1 must be merged and deployed before this PR can be merged.

**Comment by djblue** [comment]
One of those is related to #1620, and the fix is already up. I will fix the one related to `jquery.multiselect.css`.

**Comment by brendan-hofmann** [comment]
Clicked around in all the UIs, didn't see any more 404s aside from the date time picker in catalog ui, but that is a known issue.

**Comment by pklinef** [comment]
@djblue can you rebase and verify that the date picker is now working correctly?

**Comment by adimka** [comment]
Built and manual confirmed via the testing instructions. 👍

**Pull request merged**
