### PR TITLE
DDF-3047 Enable system restart from installer

### PR DESCRIPTION
**Pull request by clockard**
### What does this PR do?
Enable system restart from installer

* There is an issue with the karaf.bat file such that restart doesn’t work on windows. We submitted a fix for it and it will be in karaf 4.1.2. Hold off on merging until we upgrade to karaf 4.1.2 

#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged)?
@mcalcote @coyotesqrl 

#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).

@pklinef
@shaundmorris
#### How should this be tested? (List steps with links to updated documentation)
Verify that after install the system comes back up without the need to manually restart it.

#### What are the relevant tickets?
[DDF-3047](https://codice.atlassian.net/browse/DDF-3047)

### CODE REVIEW

**Comment by clockard** [comment]
build now

**Comment by mcalcote** [comment]
Hero'd on Windows, confirmed works with the bugfixes in karaf 4.1.2

**Comment by shaundmorris** [comment]
We were waiting to merge this after upgrading DDF to Karaf 4.1.2.

**Comment by rzwiefel** [comment]
Dependent PR is up! 
https://github.com/codice/ddf/pull/2241

**Comment by clockard** [comment]
build now

**Comment by clockard** [comment]
build now

**Pull request merged**
