### PR TITLE
DDF-1446: Disables owasp dependency-check on docs

### PR DESCRIPTION
**Pull request by vinamartin**
Sets the execution phase of the owasp dependency-check plugin to none on docs projects so that it is not run.

@lessarderic 
@ricklarsen 
@tbatie 
@shaundmorris

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/130)

### CODE REVIEW

**Comment by shaundmorris** [comment]
@vinamartin Not sure if the configuration skip approaches is any better but what you have looks good.  Do we also need something like this in ddf/distribution/docs or does OWASP not run on that module? :+1: http://stackoverflow.com/questions/7821152/disable-a-maven-plugin-defined-in-a-parent-pom

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/130)

**Comment by vinamartin** [comment]
@shaundmorris As far as I can figure out, there isn't a skip tag applicable to this issue: https://jeremylong.github.io/DependencyCheck/dependency-check-maven/configuration.html 

Looks like inside of distribution/docs, the OWASP dependency-check plugin isn't defined at all. Seems to me it isn't running there.

**Comment by lessarderic** [comment]
@shaundmorris, @vinamartin is right. There's unfortunately no such skip flag. You can turn it of for certain types of dependencies, but not all of them.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/130)

**Comment by lessarderic** [comment]
:+1:

**Comment by lessarderic** [comment]
Can you try removing the <configuration> sections and see if that still works?

**Comment by vinamartin** [comment]
@lessarderic Removed the configuration sections since they're no longer needed and everything seems to be working.

**Comment by shaundmorris** [comment]
Cool. @vinamartin, @lessarderic thanks for the update

**Comment by tbatie** [comment]
Reviewed and built successfully :+1:

**Pull request merged**
