### PR TITLE
DDF-2606 Fixes subject retrieval from request properties. 

### PR DESCRIPTION
**Pull request by outcastrift**
#### What does this PR do?
Fixes subject retrieval from request properties. 
#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged)?
@harrison-tarr 
@rzwiefel 
#### Select at least one member from relevant component team(s) from below (at least one component team member needs to approve the PR).

[Security](https://github.com/orgs/codice/teams/security)
[Data](https://github.com/orgs/codice/teams/data)

#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@pklinef
@stustison
#### How should this be tested? (List steps with links to updated documentation)
Run all integration tests. 
#### Any background context you want to provide?
None
#### What are the relevant tickets?
https://codice.atlassian.net/browse/DDF-2606
#### Checklist:
- [ ] Documentation Updated
- [ ] Change Log Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by rzwiefel** [comment]
This already fixed in https://github.com/codice/ddf/pull/1338

**Comment by harrison-tarr** [comment]
@rzwiefel Is that going to be backported to 2.9.x? If not, I think this is a great candidate to be backported to fix this bug.

**Comment by rzwiefel** [comment]
Yeah this probably should be backported. @outcastrift If you want to backport this PR for 2.9.x that would be awesome 👍

**Comment by harrison-tarr** [comment]
To do that, make a PR against the `2.9.x` branch instead of `master`. 
The easiest way to do that, in my opinion, is to checkout the `2.9.x` branch locally as, for example, `2.9.x-DDF-2606`. Then, cherry-pick this commit from `DDF-2606` onto `2.9.x-DDF-2606`, and then push up `2.9.x-DDF-2606` and open a PR against `2.9.x`

**Comment by pklinef** [comment]
@rzwiefel Since you did #1338, can you backport the fix to 2.9.x?

**Comment by rzwiefel** [comment]
These changes have been backported here ( https://github.com/codice/ddf/pull/1518 ). This PR may now be closed

**Comment by coyotesqrl** [comment]
Closing as dupe.

**Pull request closed without merging**
