### PR TITLE
DDF-2113 Move subject role check for admin into getSystemSubject()

### PR DESCRIPTION
**Pull request by roelens8**
#### What does this PR do? 
Moves the subject role check from runWithSubjectOrElevate() into getSystemSubject() within the Security class. 

#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?
@ryeats @coyotesqrl @bcwaters @tbatie @jckilmer 
#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@pklinef
@stustison
#### How should this be tested?
PRBS.
#### Any background context you want to provide?
There are some operations that require the system subject, but are not associated with a user. These operations cannot retrieve the system subject due to not having a java subject containing an admin role. In order to fix this, I have added a method that creates a java subject with an admin role and can run an action using that subject.
#### What are the relevant tickets?
DDF-2113
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [X] Update / Add Integration Tests

### CODE REVIEW

**Comment by coyotesqrl** [comment]
👍

**Comment by stustison** [comment]
👍

**Comment by tbatie** [comment]
:+1:

**Comment by adimka** [comment]
Heroed and reviewed. 👍

**Pull request merged**
