### PR TITLE
DDF-3264 Removing wagon-webdav-jackrabbit build extension

### PR DESCRIPTION
**Pull request by oconnormi**
#### What does this PR do?

Removes an unnecessary build extension

#### Who is reviewing it? 
@LinkMJB @mcalcote 

#### Select relevant component teams: 
@codice/build 

#### Choose 2 committers to review/merge the PR. 
(please choose ONLY two committers from below, delete the rest)
@shaundmorris 
@clockard 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by bdeining** [comment]
build now

**Comment by bdeining** [comment]
build now

**Comment by clockard** [comment]
build now

**Comment by shaundmorris** [comment]
build now

**Comment by oconnormi** [comment]
build now

**Comment by oconnormi** [comment]
build now

**Pull request merged**
