### PR TITLE
DDF-3999 Fixed Multipolygon handling on the 2d map

### PR DESCRIPTION
**Pull request by bdeining**
#### What does this PR do?
Fixed Multipolygon handling on the 2d map.
#### Who is reviewing it? 

@leo-sakh @djblue 
#### Select relevant component teams: 
https://github.com/orgs/codice/teams
#### Ask 2 committers to review/merge the PR and tag them here.

@andrewkfiedler
@millerw8
#### How should this be tested?
Build / Install / Construct and `anyGeo` query with a 3d array (multipolygon) / verify it is drawn correctly and the query is sent to the backend with a buffer correctly

#### What are the relevant tickets?
[](https://codice.atlassian.net/browse/)
#### Screenshots
before
screen shot 2018-09-13 at 10 31 26 am
after
screen shot 2018-09-18 at 11 07 11 am

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by bdeining** [comment]
hero should verify single polygon also works as expected

**Comment by Schachte** [comment]
build now

**Comment by willwill96** [comment]
Starting hero

**Comment by willwill96** [comment]
🎉 Hero Successful 🎉 

1. Quickbuilt and installed 
2. Created a multi-polygon `anyGeo` search, each having it's own buffer. 
3. Verified by looking at network messages and a third-party map application that the polygons being sent and drawn are the same.

Image from Intrigue:
intrigue screenshot


Image from third-party map (using the same coordinates sent over the network): 
wicket screenshot

**Comment by willwill96** [comment]
🎉 Hero Successful 🎉 

1. Quickbuilt and installed 
2. Created a multi-polygon `anyGeo` search, each having it's own buffer. 
3. Verified by looking at network messages and a third-party map application that the polygons being sent and drawn are the same.

Image from Intrigue: 
intrigue screenshot


Image from third-party map (using the same coordinates sent over the network): 
wicket screenshot

**Pull request merged**
