### PR TITLE
DDF-2197: Remove all maven repositories other than maven central and …

### PR DESCRIPTION
**Pull request by tbatie**
#### What does this PR do?
Removes maven repos that are not trusted. 
#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?
@bcwaters 
@vinamartin 
#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@coyotesqrl
@stustison
#### How should this be tested?
Clear .m2 and ensure dependencies only come from either maven central or the codice nexus
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

…codice nexus

### CODE REVIEW

**Comment by coyotesqrl** [comment]
:+1:

**Comment by vinamartin** [comment]
👍

**Comment by bcwaters** [comment]
👍

**Comment by stustison** [comment]
👍

**Comment by shaundmorris** [comment]
might want to sync with @harrison-tarr on https://github.com/codice/ddf/pull/843 basically this makes some of the work in 843 obsolete.

**Pull request merged**
