### PR TITLE
DDF-1507 Added Fix for CSW ResultType query and related iTests

### PR DESCRIPTION
**Pull request by EIrwin**
Additionally had to make some refactorings in order to not use
embeeded classes due to failed equality comparisons with serialized
ResultType class.

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/207)

### CODE REVIEW

**Comment by bdeining** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/207)

**Comment by kcwire** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

<sup>**[catalog/spatial/csw/spatial-csw-endpoint/pom.xml, line 113 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/207#-K-KYoeItY9mVyb9z6gO)** ([raw file](https://github.com/codice/ddf/blob/253d4fe08e067fd50bd7d2a9618b0fdf847a3119/catalog/spatial/csw/spatial-csw-endpoint/pom.xml#L113)):</sup>
probably a good idea to add the specific version number here, and the other dependencies we know we need (ie all the net.opengis.* stuff)


---

<sup>**[catalog/spatial/csw/spatial-csw-schema-bindings/pom.xml, line 67 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/207#-K-KZ9x76cTTIezgHvcw)** ([raw file](https://github.com/codice/ddf/blob/253d4fe08e067fd50bd7d2a9618b0fdf847a3119/catalog/spatial/csw/spatial-csw-schema-bindings/pom.xml#L67)):</sup>
We may want to move this to thirdparty. It shouldn't changed often if ever and then we can tag specific version numbers when we want to use it instead of always just latest.

Thoughts?


---

<sup>**[catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/GetRecordsResponseConverter.java, line 153 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/207#-K-K_Y0HjVOr00OQ586w)** ([raw file](https://github.com/codice/ddf/blob/253d4fe08e067fd50bd7d2a9618b0fdf847a3119/catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/GetRecordsResponseConverter.java#L153)):</sup>
it's a little confusing whether what `nextRecord` should be set to and technically the `nextRecord` attribute is optional.  We may be better leaving it out when the ResultType is "hits"

http://schemas.opengis.net/csw/2.0.2/CSW-discovery.xsd


---

<sup>**[distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestCatalog.java, line 414 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/207#-K-Ka3ZHuvzprWEDEHYY)** ([raw file](https://github.com/codice/ddf/blob/253d4fe08e067fd50bd7d2a9618b0fdf847a3119/distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestCatalog.java#L414)):</sup>
How about asserting all three different ResultType Options here?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/207)

**Comment by EIrwin** [comment]
<sup>**[distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestCatalog.java, line 0 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/207#-K-Ka3ZHuvzprWEDEHYY)** ([raw file](https://github.com/codice/ddf/blob/253d4fe08e067fd50bd7d2a9618b0fdf847a3119/distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestCatalog.java#L0)):</sup>
Was the plan in the long run, was just trying to get an initial test in for release. I will add these real quick


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/207)

**Comment by EIrwin** [comment]
<sup>**[catalog/spatial/csw/spatial-csw-schema-bindings/pom.xml, line 0 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/207#-K-KZ9x76cTTIezgHvcw)** ([raw file](https://github.com/codice/ddf/blob/253d4fe08e067fd50bd7d2a9618b0fdf847a3119/catalog/spatial/csw/spatial-csw-schema-bindings/pom.xml#L0)):</sup>
Your call


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/207)

**Comment by jrnorth** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

<sup>**[catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/GetRecordsResponseConverter.java, line 153 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/207#-K-KfMAyqSNZs68GfsU0)** ([raw file](https://github.com/codice/ddf/blob/253d4fe08e067fd50bd7d2a9618b0fdf847a3119/catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/GetRecordsResponseConverter.java#L153)):</sup>
Could this just be added to the `if` case above? It's the same condition.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/207)

**Comment by wmcnalli** [comment]
Reviewed 4 of 7 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/207)

**Comment by bdeining** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/207)

**Comment by bdeining** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/207)

**Comment by EIrwin** [comment]
This PR has been replaced by [#240](https://github.com/codice/ddf/pull/240)

**Pull request closed without merging**
