### PR TITLE
[19.x] DDF-5324 Upgrades Guava to 25.1 and forces opensaml to use the same version

### PR DESCRIPTION
**Pull request by Lambeaux**
#### What does this PR do?
See https://github.com/codice/ddf/pull/5379

#### Who is reviewing it? 
@brianfelix 
@mojogitoverhere 

#### Ask 2 committers to review/merge the PR and tag them here.
@bdeining
@stustison

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by Lambeaux** [comment]
Build now.

**Comment by bdeining** [comment]
build now

**Comment by bdeining** [comment]
build now

**Comment by Lambeaux** [comment]
Build now.

**Comment by bdeining** [comment]
build now

**Comment by Lambeaux** [comment]
Build now.

**Pull request merged**
