### PR TITLE
DDF-1485: Add new constant to use as a key for storing namespace decl…

### PR DESCRIPTION
**Pull request by jrnorth**
…arations

@kcwire 
@beyelerb is the hero
@wmcnalli 
@jlcsmith

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/168)

### CODE REVIEW

**Comment by kcwire** [comment]
Reviewed 10 of 10 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/168)

**Comment by kcwire** [comment]
:+1:

**Comment by millerw8** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/CswConstants.java, line 71 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/168#-JysLKcqRfvNmHFizAH8)** ([raw file](https://github.com/codice/ddf/blob/b2b97165e96c65203899ec9f11fde1fca770a2a6/catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/CswConstants.java#L71)):</sup>
weird formatting

---

<sup>**[catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/XStreamAttributeCopier.java, line 142 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/168#-JysOhfQbpayNRcI5SmB)** ([raw file](https://github.com/codice/ddf/blob/18c2b1689fc7e1ac41876a1adc0ff7bc821e17ff/catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/XStreamAttributeCopier.java#L142)):</sup>
So this requires a delimiter and the old way did not.  Does this break anything, in particular with regards to the default namespace?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/168)

**Comment by millerw8** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/168)

**Comment by jrnorth** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/XStreamAttributeCopier.java, line 142 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/168#-JysOhfQbpayNRcI5SmB)** ([raw file](https://github.com/codice/ddf/blob/18c2b1689fc7e1ac41876a1adc0ff7bc821e17ff/catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/XStreamAttributeCopier.java#L142)):</sup>
It probably would; I'll change it back.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/168)

**Comment by wmcnalli** [comment]
:+1: 

---

Reviewed 7 of 10 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/168)

**Comment by kcwire** [comment]
PR builds and all tests pass.

**Pull request merged**
