### PR TITLE
DDF-4367 Fix search results merging in Intrigue

### PR DESCRIPTION
**Pull request by mdang8**
#### What does this PR do?

Fixes an issue when making searches in Intrigue where there are 250+ results returned. The counts at the bottom of the result list now match with the expected number of results. The queued results are changed to reset instead of being added because the add operation is slow enough that it can cause partial merges to happen and results being removed. The issue was more commonly observed on Firefox browsers than Chrome because the operation was finishing outside of the default auto-merge time threshold.

#### Who is reviewing it? 

@emmberk @kcover @peterhuffer @pvargas @brianfelix 

#### Select relevant component teams: 

@codice/ui 

#### Ask 2 committers to review/merge the PR and tag them here.

@andrewkfiedler
@clockard 

#### How should this be tested?

- Open Intrigue in a Chrome browser
- Ingest 265 (or any number greater than 250) metacards using the UI uploader
- Start a wildcard search and verify that the results text at the top query details box reads `265 results`
- Verify that the results label text at the bottom of the results list reads `250 results` or `1-25 of 265`
- Click the arrow button to proceed to the next pages until it reaches the end and the button changes to `More`
- Verify that the results label text reads `226-250 of 265`
- Click the `More` button and verify that the results label text at the bottom of the results list reads `15 results` or `251-265 of 265`
- Re-run the search and verify that the results are consistent with the above
- Remove the uploaded metacards through the console
- Upload 600 (or any number greater than 500) new metacards, repeat the process, and verify it still works
- Duplicate the same process in a Firefox browser and verify that everything works

#### What are the relevant tickets?
[DDF-4367](https://codice.atlassian.net/browse/4367)

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by andrewkfiedler** [comment]
build now

**Comment by mdang8** [comment]
build now

**Comment by mdang8** [comment]
@pvargas There seems to be a bug that only occurs on the initial search immediately after ingesting a new set of metacards. I made a change that should hopefully fix that. Can you re-hero?

**Comment by clockard** [comment]
build now

**Comment by clockard** [comment]
Would this be a straight cherry pick to the release branch 2.13.x? If so we should backport it.

**Pull request merged**
