### PR TITLE
DDF-4008 Update jetty to 9.3.24.v20180605

### PR DESCRIPTION
**Pull request by kcover**
Link to 2.13.x PR: #3497 

#### Who is reviewing it? 

@peterhuffer @emmberk @oconnormi @brjeter

#### Ask 2 committers to review/merge the PR and tag them here.

@clockard
@stustison

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by clockard** [comment]
build now

**Comment by clockard** [comment]
build now

**Comment by kcover** [comment]
rebased
build now

**Comment by oconnormi** [comment]
I was able to hero this successfully 🎉

**Pull request merged**
