### PR TITLE
DDF-3762 Improved color scheme of sea theme

### PR DESCRIPTION
**Pull request by idperez**
#### What does this PR do?
Changes default colors of the sea theme
#### Who is reviewing it? 
@lcrosenbu 
@alexaabrd 
#### Select relevant component teams: 
https://github.com/orgs/codice/teams
#### Choose 2 committers to review/merge the PR. 
(please choose ONLY two committers from below, delete the rest)
@andrewkfiedler
@bdeining
#### What are the relevant tickets?
[DDF-3762](https://codice.atlassian.net/browse/ddf-3762)
#### Screenshots (if appropriate)
old colors:

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by vinamartin** [comment]
❓ What's the motivation for this change since we support the ability to create custom themes?

**Comment by bdeining** [comment]
@vinamartin the old color scheme was not consistent with regards to buttons, etc.

**Comment by bdeining** [comment]
screen shot 2018-04-13 at 4 56 00 pm
screen shot 2018-04-13 at 4 55 42 pm
screen shot 2018-04-13 at 4 55 33 pm

**Comment by bdeining** [comment]
Verified on Firefox / Chrome.  Will verify on IE11

**Comment by bdeining** [comment]
Verified on IE11.  Build now

**Pull request merged**
