### PR TITLE
DDF-4828 fix Incorrect buffer for Polygons

### PR DESCRIPTION
**Pull request by andrewzimmer**
#### What does this PR do?
Currently polygons are being buffered as linestrings causing the buffer the extend both inward/outward. This gives the buffer the appearance of being split between the two directions, and this can also result in inner shapes being created within the polygon that appear to be "holes" in the search area
With this fix, the polygon will only buffer outward and another polygon with dotted lines will be added to represent the originally drawn shape (demo video below)
#### Who is reviewing it? 
@Bdthomson @hayleynorton @lamhuy 
#### Select relevant component teams: 
@codice/ui 
#### Ask 2 committers to review/merge the PR and tag them here.
@andrewkfiedler
@djblue 
#### How should this be tested?
- build / install / run
- ingest records with location data
- create several `anyGeo` searches with different polygons and verify that the correct results 
- repeat many times with different shapes/buffers on both 2d/3d maps
#### What are the relevant tickets?
For GH Issues:
Fixes: #4828 

#### Screenshots
demo video:
[buffer-2d-3d.mp4.zip](https://github.com/codice/ddf/files/3184222/buffer-2d-3d.mp4.zip)

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by andrewzimmer** [comment]
build now

**Comment by willwill96** [comment]
Hero Successful
Tested making several geos with buffers on both 2d and 3d maps and verified expected functionality
Verified that multipolygons were drawn correctly in the same way by ingesting gazetteer data and using keyword geos

LGTM!

**Comment by willwill96** [comment]
❓ It looks like these changes only affect the way the polygons are drawn on the 2D and 3D maps. Do we need to update the way that polygons are queried against as well? I'm worried that we are no longer accurately representing what is being queried against with these changes.

**Comment by andrewzimmer** [comment]
With these changes the polygons should more accurately reflect whats currently being queried. And these changes only really affect what is being drawn inside the polygon, the outer polygon shape remains the same as it was before. Is there a specific example you are thinking of?

**Comment by andrewzimmer** [comment]
@willwill96 I posted a screenshot on the github issue, the query does not behave as a lineString search

**Pull request merged**
