### PR TITLE
[2.13.x hotfix] DDF-4457-hotfix Fix file system encryption issues

### PR DESCRIPTION
**Pull request by bakejeyner**
#### What does this PR do?
Fixes a bug introduced by #4502.

The file system encryption PR changed what was getting returned on ingest. Originally, the response would contain an input stream + size containing the plaintext content. However, due to the file system encryption changes, the response contains the **encrypted** input stream + size. This was breaking downstream tests that were expecting the plaintext input stream + size to be returned.

The PR also had an issue with writing encrypted resources. The chunk size was 128 and **every** write would result in 128 bytes being written, even if the original resource didn't have 128 bytes left.

#### Who is reviewing it? 
@ahoffer 
@blen-desta 
@brjeter 
@garrettfreibott 
@stustison 

#### How should this be tested?
1. Build this DDF branch
1. Build Alliance `1.1.x` (make sure the DDF version in Alliance `1.1.X` is `2.13.8-SNAPSHOT`)
1. Run the  `ImagingTest` under `<alliance_home>\distribution\test\itests\test-itests-alliance`: `mvn clean verify -nsu -D it.test=ImagingTest`

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by bakejeyner** [comment]
build now

**Comment by bakejeyner** [comment]
☝️ CI failed on maven download.

**Comment by bakejeyner** [comment]
build now

**Comment by bakejeyner** [comment]
build now

**Comment by brjeter** [comment]
build now

**Comment by tyler30clemens** [comment]
Hero Successful ✅

**Pull request merged**
