### PR TITLE
[2.13.x] DDF-4223 Updated AC debugger to the latest version

### PR DESCRIPTION
**Pull request by paouelle**
#### What does this PR do?
It updates the AC debugger's backdoor to the latest version such that it would be compatible with the latest debugger.

#### Who is reviewing it? 
@jhunzik 
@ethantmanns 
@tyler30clemens 

#### Select relevant component teams: 
@codice/test 

#### Ask 2 committers to review/merge the PR and tag them here.
@figliold
@tbatie

#### How should this be tested?

- unzip DDF
- comment out the `"file:/platform-migration/platform-migratable-api"` section in the  default.policy file
- start DDF
- attach the latest version of the debugger with the `--debug --continuous --wait` options
- perform a migration:export from the command shell
- verify that the debugger is able to analyze the security issues and that the migration export succeeded

#### What are the relevant tickets?
[DDF-4223](https://codice.atlassian.net/browse/DDF-4223)

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by paouelle** [comment]
build now

**Comment by paouelle** [comment]
build now - seems flaky, no changes to code and passes locally

**Comment by paouelle** [comment]
build now

**Comment by ethantmanns** [comment]
Successfully heroed ✅

**Pull request merged**
