### PR TITLE
DDF-3957 Attach catalog-ui-search src code zip

### PR DESCRIPTION
**Pull request by alexaabrd**
#### What does this PR do?
Attach catalog-ui-search src code zip so that it can be extensible
#### Who is reviewing it? 
@SmithJosh @vinamartin @Variadicism 
#### Ask 2 committers to review/merge the PR and tag them here. If you don't know who to ask, you can request reviews in https://groups.google.com/forum/#!forum/ddf-developers .
@brendan-hofmann
@rzwiefel
#### What are the relevant tickets?
[DDF-3957](https://codice.atlassian.net/browse/DDF-3957)
#### Checklist:
- [n/a] Documentation Updated
- [n/a] Update / Add Unit Tests
- [n/a] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by alexaabrd** [comment]
build now

**Comment by alexaabrd** [comment]
build now

**Comment by mackncheesiest** [comment]
Wait why are we doing this? We have OSGi in Javaland. Why aren't we just factoring needed pieces out into interface modules (like, say, the recently formed [catalog-ui-search-api](https://github.com/codice/ddf/tree/master/catalog/ui/catalog-ui-search-api)) and using new OSGi service implementations to inject extensibility? 

Barring that, why aren't we exporting needed packages/classes from here in order to use them downstream?

This isn't even including the pom with the source code, so it will basically be impossible to rebuild without needing to manually keep some downstream pom in sync with changes to this module's one

**Comment by alexaabrd** [comment]
@mackncheesiest we want to make a customized version of this bundle so that it has less runtime imports and can withstand ddf upgrades without upgrading the bundle itself. Basically we want to have a stagnant intrigue ui that doesn't upgrade when dib upgrades, so we need the same implementation wrapped in a more robust bundle.

**Comment by alexaabrd** [comment]
@mackncheesiest we want to make a customized version of this bundle so that it has less runtime imports and can withstand ddf upgrades without upgrading the bundle itself. Basically we want to have a stagnant intrigue ui that doesn't upgrade when ddf upgrades, so we need the same implementation wrapped in a more robust bundle.

**Pull request merged**
