### PR TITLE
DDF-2024: Added a log statement for CatalogTransformerException in th…

### PR DESCRIPTION
**Pull request by AzGoalie**
#### What does this PR do?
Adds a log statement explaining why the transformation failed in the catalog:dump command.
#### Who is reviewing it?
@brendan-hofmann @ahoffer @Lambeaux @stustison
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

…e dump command

### CODE REVIEW

**Comment by Lambeaux** [comment]
:+1:

**Comment by ahoffer** [comment]
Added logging to that failed to metacard transformer failure did not happen silently.
NOTES:
1. Has potential to spam the log. If you try to ingest 10,000 without having the right security settings, you will get 10,000 errors in the log. However, we need to do _something_. Not logging anything cost us tons of developer time trying to figure out why the process failed. 
2. In the context of a dump command, if the transformation fails, you will get an empty file for each metacard. Travis is addressing this in a separate ticket.

**Comment by ahoffer** [comment]
:+1:

**Comment by brendan-hofmann** [comment]
@ahoffer has a good point. I think we need to bin up the errors and only log once at the end of the command. Other than that, lgtm.

**Comment by AzGoalie** [comment]
Shouldn't it log a message for each metacard though? Case: There are metacards with valid security markings, and some without security markings. We would wan't to know which ones we couldn't dump/transform.

**Comment by ahoffer** [comment]
:+1: f0f2175ec981e23a8b7520d24a795281deac19a3

**Comment by harrison-tarr** [comment]
Probably not worth it to do it now, but will we look into making maybe an additional log? Like Aaron said, we don't want to spam the log. Maybe it's time for an `dump` log or a `egest` log to parallel the ingest log. Or maybe we rename the `ingest` log to `ingest/egest` log. Also maybe in the meantime (I have no idea how feasible this is) you could count up all the unique reasons for failure and then log those at the end. So you wouldn't have 10000 messages that all say "missing security markings" you could say "you missed security markings on 10000 metacards"

**Comment by AzGoalie** [comment]
With the latest changes it wont spam the log unless you have debug turned on. It will print 1 message per batch.

**Comment by shaundmorris** [comment]
@AzGoalie can you please squash the commits on this PR?

**Comment by shaundmorris** [comment]
👍

**Comment by stustison** [comment]
:+1:

**Pull request merged**
