### PR TITLE
DDF-1979: added Resource Management to default install profile

### PR DESCRIPTION
**Pull request by jlcsmith**
#### What does this PR do?
Adds Resource Management Application to default install profile
#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?
@bdeining @lcrosenbu 
#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@lessarderic 
#### How should this be tested?
Verify resource management app is installed by default
#### Any background context you want to provide?
2 important bugs were fixed making this app a candidate app for the default install profile:
https://codice.atlassian.net/browse/DDF-2368
https://codice.atlassian.net/browse/DDF-2386

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by lessarderic** [comment]
Do we have to enable this app by default? Couldn't we just let people that want to use it create their own profile or have a different profile (e.g., resource management)?

Also, is this app documented somewhere and has unit and integration tests? How about the query monitor feature? I would think these are important, especially if we make it a default app.

**Comment by jlcsmith** [comment]
@lessarderic - we certainly could leave it out of the default profile.  I wasn't sure if there was a consensus on when an app was eligible.   Looks like we are missing documentation so that would be a good thing to add.  We should probably discuss the integration tests a bit more to see where they make sense.

**Comment by lessarderic** [comment]
@jlcsmith, should we create separate tickets for this or update DDF-1979 to add documentation and integration tests?

**Comment by jlcsmith** [comment]
I'd just assume we use separate tickets.  I can create them

**Comment by jlcsmith** [comment]
Closing this PR until the other tickets are complete

**Pull request closed without merging**
