### PR TITLE
DDF-1606: added note to security docs for claims handlers.

### PR DESCRIPTION
**Pull request by ricklarsen**
@stustison @clockard @vinamartin @djblue

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/294)

### CODE REVIEW

**Comment by vinamartin** [comment]
:+1: 
selfie-0

**Comment by clockard** [comment]
:+1:

**Comment by stustison** [comment]
lgtm

**Comment by roelens8** [comment]
:+1:

**Pull request merged**
