### PR TITLE
DDF-3279 Revert "DDF-3279 Upgrade to Solr 6.6.1 (#2305)"

### PR DESCRIPTION
**Pull request by vinamartin**
This reverts commit f0ae85bb9a51e97fac899f8908eca23a16912545.
Inconsistent build issues seem to have started occurring after this commit. 

#### Choose 2 committers to review/merge the PR. 
(please choose ONLY two committers from below, delete the rest)
@lessarderic
@rzwiefel

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by vinamartin** [comment]
build now

**Comment by rzwiefel** [comment]
@stustison Will need to sign off on this if we choose to go forward with revert.

**Comment by rzwiefel** [comment]
I would also **love** to confirm from multiple people on multiple platforms if possible -  since only a couple have encountered this.

**Comment by rzwiefel** [comment]
Build failed because docs hasn't deployed yet

**Comment by vinamartin** [comment]
build now

**Comment by vinamartin** [comment]
Instead of reverting, we should attempt to fix the issues. Closing out this PR.

**Pull request closed without merging**
