### PR TITLE
DDF-04746 transform js - use object shorthand where possible

### PR DESCRIPTION
**Pull request by rymach**
`jscodeshift -t ../js-codemod/transforms/object-shorthand.js ui/packages/catalog-ui-search/**/*`

#### Select relevant component teams: 
@codice/ui 

#### Ask 2 committers to review/merge the PR and tag them here.

@andrewkfiedler
@bdeining
@jrnorth
@djblue 

#### What are the relevant tickets?
For Jira:
[](https://codice.atlassian.net/browse/)

For GH Issues:
Fixes: #04746

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by rymach** [comment]
build now

**Comment by mojogitoverhere** [comment]
build now

**Comment by djblue** [comment]
build now

**Comment by djblue** [comment]
build now

**Comment by bdeining** [comment]
build now

**Comment by rymach** [comment]
build now

**Comment by gjvera** [comment]
### 🎉 Hero Successful 🎉 
Tested UI functionality as follows
- Created a workspace 
- Renamed the workspace and saved
- shared the workspace 
- tested all visualizations (2D map, 3D map, table, histogram, inspector)
- tested all the themes
- tested uploading and notifications
- created result forms
- went to sources page
- search form editor functioned as well

LGTM!!
### Note: 
I ran into an unrelated issue on the search form editor where I could not save a search form. It was unrelated to this PR. @rymach is gonna put up a separate small pr to fix it.

**Pull request merged**
