### PR TITLE
Revert "DDF-3738 Move "Add Visual" menu to be in-line with other action menu options"

### PR DESCRIPTION
**Pull request by brendan-hofmann**
Reverts codice/ddf#3138
Spoke with @andrewkfiedler and we'd like to incubate this and some related changes in a prototype area of the UI for now, rather than going directly into the UI in an incremental state. New pull requests will be opened for the prototype area.

### CODE REVIEW

**Comment by brendan-hofmann** [comment]
build now

**Comment by bdeining** [comment]
How much work is it to move this to be experimental?  Is it really worth an entire revert?

**Comment by brendan-hofmann** [comment]
We don't want it in the 2.12 release so this is the safer option.

**Comment by brendan-hofmann** [comment]
Failure is spurious, flaky tests.
```
22:23:25 Failed tests: 
22:23:25   TestSingleSignOn.testSessionManagement:743->loginUser:645 1 expectation failed.
22:23:25 Expected status code <200> doesn't match actual status code <404>.
22:23:25 
22:23:25   TestSingleSignOn.testLogout:561->loginUser:645 1 expectation failed.
22:23:25 Expected status code <200> doesn't match actual status code <404>.
22:23:25 
22:23:25   TestSingleSignOn.testRedirectFlow:550 1 expectation failed.
22:23:25 Expected status code <200> doesn't match actual status code <404>.
```

**Pull request merged**
