### PR TITLE
DDF-3621 Fixed test case to work on Windows

### PR DESCRIPTION
**Pull request by paouelle**
#### What does this PR do?
Fixes a test case that fails on Windows.

#### Who is reviewing it? 
(please choose AT LEAST two reviewers that need to approve the PR before it can get merged)
@emanns95 
@peterhuffer 
@jhunzik 

#### Select relevant component teams: 
https://github.com/orgs/codice/teams
#### Ask 2 committers to review/merge the PR and tag them here. If you don't know who to ask, you can request reviews in https://groups.google.com/forum/#!forum/ddf-developers .
(please choose ONLY two committers from below, delete the rest)
@brendan-hofmann
@figliold

#### How should this be tested? (List steps with links to updated documentation)
run the tests on windows

#### What are the relevant tickets?
[DDF-3621](https://codice.atlassian.net/browse/DDF-3621)
#### Checklist:
- [ ] Documentation Updated
- [x] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by bdeining** [comment]
build now

**Comment by paouelle** [comment]
build now

**Comment by shaundmorris** [comment]
@paouelle just curious if you looked at this page: https://codice.atlassian.net/wiki/spaces/DDF/pages/19365892/Windows+Compatibility. I see this is in the test area so not sure how fully applicable it is or up-to-date it is at this point.

**Comment by paouelle** [comment]
@shaundmorris I did. In this case, the directory is created internally from code by extracting it from a URL so I don't have much say in how it comes back.

**Pull request merged**
