### PR TITLE
DDF-1433 Modified the ingest command to ignore hidden files, and adde…

### PR DESCRIPTION
**Pull request by bdeining**
…d a -i ignore option to ignore specified file

extensions and patterns.

@kcwire 
@jrnorth 
@emanns95
@kguerriero
@jlcsmith 
@millerw8 
@beyelerb
-hero @wmcnalli

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/127)

### CODE REVIEW

**Comment by wmcnalli** [comment]
Unit tests?

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/IngestCommand.java, line 216 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/127#-JxA_SAvsKYAMt-e2acz)** ([raw file](https://github.com/codice/ddf/blob/8df43989df1574471927bfa7c4e22da9edddbe8a/catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/IngestCommand.java#L216)):</sup>
Can we make this only print the failed count if failed count > 1? 

---

<sup>**[catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/IngestCommand.java, line 217 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/127#-JxA_h7xw7loMch9j1FV)** ([raw file](https://github.com/codice/ddf/blob/8df43989df1574471927bfa7c4e22da9edddbe8a/catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/IngestCommand.java#L217)):</sup>
Probably only want to print this if the user specified a -i arg.  I don't think we need to alert them that some hidden files were ignored.  Consider printing a color other than red since it's not really an error.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/127)

**Comment by jrnorth** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

<sup>**[catalog/core/catalog-core-commands/src/test/java/org/codice/ddf/commands/catalog/TestIngestCommand.java, line 49 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/127#-JxGAB5_gyP17HCZqaHu)** ([raw file](https://github.com/codice/ddf/blob/ec2894b0afbc14af65950ba9f53b4a1141e49b1a/catalog/core/catalog-core-commands/src/test/java/org/codice/ddf/commands/catalog/TestIngestCommand.java#L49)):</sup>
A lot of the same setup logic is performed in each of these tests; it could be moved into an @Before method.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/127)

**Comment by kcwire** [comment]
:+1: 

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/127)

**Comment by jrnorth** [comment]
:+1: 

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/127)

**Comment by andrew-fiedler** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/IngestCommand.java, line 219 \[r4\]](https://reviewable.io:443/reviews/codice/ddf/127#-JxH4Ua1KpGrPZOWx5zx)** ([raw file](https://github.com/codice/ddf/blob/a4ee4ed4bb517c63d9f508807ca4c93fab0368d1/catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/IngestCommand.java#L219)):</sup>
With parameterized logging, you should be able to get rid of INGEST_LOGGER.isWarnEnabled(). http://www.slf4j.org/faq.html#logging_performance

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/127)

**Comment by kguerriero** [comment]
Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/127)

**Comment by emanns95** [comment]
:+1:

---

Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/127)

**Comment by kcwire** [comment]
Looking to merge today if there are no objections.

**Comment by andrew-fiedler** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[catalog/core/catalog-core-commands/src/test/java/org/codice/ddf/commands/catalog/TestIngestCommand.java, line 45 \[r5\]](https://reviewable.io:443/reviews/codice/ddf/127#-Jy9CAPUZi5ILAnnJ2Uu)** ([raw file](https://github.com/codice/ddf/blob/ac9ee00f49fb9b9e9e60d1ca629eed303ea9cb60/catalog/core/catalog-core-commands/src/test/java/org/codice/ddf/commands/catalog/TestIngestCommand.java#L45)):</sup>
You'll want to rename this method to setup.

https://codice.atlassian.net/wiki/display/DDF/Unit+Testing

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/127)

**Comment by lessarderic** [comment]
<sup>**[catalog/core/catalog-core-commands/src/test/java/org/codice/ddf/commands/catalog/TestIngestCommand.java, line 45 \[r5\]](https://reviewable.io:443/reviews/codice/ddf/127#-Jy9CAPUZi5ILAnnJ2Uu)** ([raw file](https://github.com/codice/ddf/blob/ac9ee00f49fb9b9e9e60d1ca629eed303ea9cb60/catalog/core/catalog-core-commands/src/test/java/org/codice/ddf/commands/catalog/TestIngestCommand.java#L45)):</sup>
And this class to IngestCommandTest :-)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/127)

**Comment by bdeining** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[catalog/core/catalog-core-commands/src/test/java/org/codice/ddf/commands/catalog/TestIngestCommand.java, line 45 \[r5\]](https://reviewable.io:443/reviews/codice/ddf/127#-Jy9CAPUZi5ILAnnJ2Uu)** ([raw file](https://github.com/codice/ddf/blob/ac9ee00f49fb9b9e9e60d1ca629eed303ea9cb60/catalog/core/catalog-core-commands/src/test/java/org/codice/ddf/commands/catalog/TestIngestCommand.java#L45)):</sup>
The other test classes in this package follow this "Test_____Command" pattern.  Should I leave it to follow the pattern already established, or change them all to ____CommandTest?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/127)

**Pull request merged**
