### PR TITLE
DDF-1738 made relaystate optional

### PR DESCRIPTION
**Pull request by stustison**
@codice/security 

@djblue can hero (run build)

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/codice/ddf/pull/400" target="_blank">ReviewNinja

**Comment by coyotesqrl** [comment]
:+1:

**Comment by djblue** [comment]
Built with no problems. LGTM :+1:

**Comment by oscaritoro** [comment]
Is there no need to update 'ddf/platform/security/idp/security-idp-server/src/main/java/org/codice/ddf/security/idp/binding/redirect/RedirectValidator.java' ?

**Pull request merged**
