### PR TITLE
DDF-1636: Completed code that handles floats and doubles in .config files

### PR DESCRIPTION
**Pull request by lessarderic**
Added all the code to properly handle floats and doubles in .config files, as well as arrays and vectors. Updated integration tests accordingly.

@andrewkfiedler 
@figliold 
@oconnormi 
@garrettfreibott (hero)
@brendan-hofmann 

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/332)

### CODE REVIEW

**Comment by lessarderic** [comment]
Still need to add unit tests so the Bamboo build will not pass right now.

**Comment by figliold** [comment]
:+1: 


---

Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/332)

**Comment by lessarderic** [comment]
Ok, all changes committed and ready for final review.

**Comment by oconnormi** [comment]
<sup>**[platform/platform-configuration-listener/src/main/java/org/codice/ddf/configuration/store/ConfigurationFilesPoller.java, line 124 \[r6\]](https://reviewable.io:443/reviews/codice/ddf/332#-K308dvlGqSaYM3cB5_I)** ([raw file](https://github.com/codice/ddf/blob/1384086574fdbfb9e8a2bf2f0b025618af6666d0/platform/platform-configuration-listener/src/main/java/org/codice/ddf/configuration/store/ConfigurationFilesPoller.java#L124)):</sup>
Is this enough time, does it depend on the OS?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/332)

**Comment by oconnormi** [comment]
<sup>**[platform/platform-configuration-listener/src/test/java/org/codice/ddf/configuration/store/felix/PropertyConverterNoConversionParametrizedTest.java, line 72 \[r6\]](https://reviewable.io:443/reviews/codice/ddf/332#-K30BWAJ8LPU9inEDJwY)** ([raw file](https://github.com/codice/ddf/blob/1384086574fdbfb9e8a2bf2f0b025618af6666d0/platform/platform-configuration-listener/src/test/java/org/codice/ddf/configuration/store/felix/PropertyConverterNoConversionParametrizedTest.java#L72)):</sup>
Looks like this file doesn't have a trailing newline, not sure if we care about that but all the other ones have them


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/332)

**Comment by oconnormi** [comment]
Reviewed 9 of 15 files at r1, 2 of 2 files at r2, 2 of 4 files at r4, 10 of 10 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/332)

**Comment by garrettfreibott** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[platform/platform-configuration-listener/src/main/java/org/codice/ddf/configuration/store/ConfigurationFilesPoller.java, line 124 \[r6\]](https://reviewable.io:443/reviews/codice/ddf/332#-K308dvlGqSaYM3cB5_I)** ([raw file](https://github.com/codice/ddf/blob/1384086574fdbfb9e8a2bf2f0b025618af6666d0/platform/platform-configuration-listener/src/main/java/org/codice/ddf/configuration/store/ConfigurationFilesPoller.java#L124)):</sup>
It's dependent on the OS. Some notify once the file is done writing, and others (like ubuntu) seem to notify when the file is immediately created but before it's finished writing it out. Waiting 1 second was enough time for bamboo's ubuntu machine to pass reliably.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/332)

**Comment by brendan-hofmann** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[platform/platform-configuration-listener/src/main/java/org/codice/ddf/configuration/store/ConfigurationFilesPoller.java, line 124 \[r6\]](https://reviewable.io:443/reviews/codice/ddf/332#-K308dvlGqSaYM3cB5_I)** ([raw file](https://github.com/codice/ddf/blob/1384086574fdbfb9e8a2bf2f0b025618af6666d0/platform/platform-configuration-listener/src/main/java/org/codice/ddf/configuration/store/ConfigurationFilesPoller.java#L124)):</sup>
Behaviors like this are also dependent on a given fileystem/OS combo, just to make things more confusing...


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/332)

**Comment by lessarderic** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[platform/platform-configuration-listener/src/main/java/org/codice/ddf/configuration/store/ConfigurationFilesPoller.java, line 124 \[r6\]](https://reviewable.io:443/reviews/codice/ddf/332#-K308dvlGqSaYM3cB5_I)** ([raw file](https://github.com/codice/ddf/blob/1384086574fdbfb9e8a2bf2f0b025618af6666d0/platform/platform-configuration-listener/src/main/java/org/codice/ddf/configuration/store/ConfigurationFilesPoller.java#L124)):</sup>
We'll see how this works but I'm thinking of opening a tech debt ticket to replace this crappy Java file monitoring class with something else in the future.


---

<sup>**[platform/platform-configuration-listener/src/test/java/org/codice/ddf/configuration/store/felix/PropertyConverterNoConversionParametrizedTest.java, line 72 \[r6\]](https://reviewable.io:443/reviews/codice/ddf/332#-K30BWAJ8LPU9inEDJwY)** ([raw file](https://github.com/codice/ddf/blob/1384086574fdbfb9e8a2bf2f0b025618af6666d0/platform/platform-configuration-listener/src/test/java/org/codice/ddf/configuration/store/felix/PropertyConverterNoConversionParametrizedTest.java#L72)):</sup>
Guess I missed that one. Since this is the only comment that requires a change and the compiler and checkstyle are happy, do you mind if I just leave it this way for now?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/332)

**Comment by garrettfreibott** [comment]
:+1: Built and passed! :shipit:

**Pull request merged**
