### PR TITLE
DDF-2261 Transition all npm dependencies to Codice Nexus

### PR DESCRIPTION
**Pull request by bcwaters**
#### What does this PR do?
Updates the root pom to configure the maven front-end plugin to use the Codice Npm Registry
#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?
@tbatie @ryeats 
#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@coyotesqrl
@stustison
#### How should this be tested?
Build DDF to ensure that all npm dependencies required are pulled down
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by coyotesqrl** [comment]
If it passes heroing, 👍

**Comment by tbatie** [comment]
:+1: Hero'd successfully. Cleared all of my node modules, and did a quick build. Searched the build logs for any 'npm install' line pointing to a registry other than codice, found none.

**Comment by tbatie** [comment]
We should definitely wait on this pr until we have a passing bamboo

**Comment by bcwaters** [comment]
Bamboo now passes for this PR, the current failure is the out of memory failure.

**Pull request merged**
