### PR TITLE
Java 17 and Camel Update

### PR DESCRIPTION
**Pull request by clockard**
#### What does this PR do?
Updates the camel version to fix CDM. 
Fixed several of the csw itests that were broken on the 2.29.x branch and ignored ones not easily fixed. Follow up ticket is https://github.com/codice/ddf/issues/6798
Updated java version to 17

Depends on https://github.com/codice/docker-ddf-base/pull/4

#### How should this be tested?

Good build

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by clockard** [comment]
build now

**Comment by clockard** [comment]
build now

**Review by vinamartin — APPROVED** [review]

**Comment by clockard** [comment]
build now

**Review by ahoffer — APPROVED** [review]

**Comment by clockard** [comment]
build now

**Comment by clockard** [comment]
build now

**Comment by clockard** [comment]
build now

**Pull request merged**
