### PR TITLE
DDF-6305 Fix running DDF as a windows service

### PR DESCRIPTION
**Pull request by bakejeyner**
#### What does this PR do?
Allows for sshing into the service and updates documentation with warnings when installing.

#### Who is reviewing it? 
@blen-desta 
@emmberk 
@garrettfreibott 
@SmithJosh 
@stustison 

#### How should this be tested?
Follow the documentation on starting DDF as a windows service (make sure to adhere to the warnings). Should run like a normal DDF instance, including the ability to ssh into the karaf console.

#### What are the relevant tickets?
Fixes: #6305

#### Checklist:
- [x] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by bakejeyner** [comment]
build now

**Review by emmberk — APPROVED** [review]

**Review by garrettfreibott — APPROVED** [review]

**Comment by bakejeyner** [comment]
build now
(failed on the docker module, re-running to see if it was a fluke)

**Comment by bakejeyner** [comment]
Hero ✔️ on my machine

**Review by blen-desta — APPROVED** [review]

**Review by ricklarsen — APPROVED** [review]
reviewed docs changes

**Pull request merged**
