### PR TITLE
DDF-1500 Fix sts client config injection

### PR DESCRIPTION
**Pull request by brendan-hofmann**
This fixes a minor issue that was missed in the original DDF-1500 pull request. Bundles that need the internal sts client config should be using the ldap filter to ensure they get the correct one every time.

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/203)

### CODE REVIEW

**Comment by brendan-hofmann** [comment]
@harrison-tarr @ahoffer @stustison

**Comment by harrison-tarr** [comment]
:thumbsup: 


---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/203)

**Comment by ahoffer** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/203)

**Comment by ahoffer** [comment]
Hero-ing in progress.


---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/203)

**Comment by ahoffer** [comment]
I hero-ed this PR using PB.
The build was successful. 
I installed the features:

```
DDF :: Security :: CAS :: Clientsecurity-cas-client	
DDF :: Security :: CAS :: CXF Servlet Filtersecurity-cas-cxfservletfilter		
DDF :: Security :: CAS :: Implementationsecurity-cas-impl	
DDF :: Security :: CAS :: Token Validatorsecurity-cas-tokenvalidator
```

which all showed as "Active" after installation.
The only error in the log was:

```
| ERROR | qtp1439661729-88 | wss4j.common.NamePasswordCallbackHandler   65 | j-ws-security-common | Unsupported callback type org.apache.karaf.jaas.modules.publickey.PublickeyCallback`
```

which Brendan assures me is unrelated and can be explained by Scott.

**Comment by stustison** [comment]
This change doesn't make any sense to me. We definitely need the ldap filters on the references to pull in the correct STS client configs, but why did you remove the client config?

**Comment by pklinef** [comment]
Why did you delete all of security-sts-clientconfig?  That was the only bundle that provided the sts client configuration service.  Also, you are using a service filter but there is no service with that property set.

**Comment by pklinef** [comment]
Disregard my previous comment.

https://github.com/codice/ddf/blob/40e40117e599e0ed300506c6076cb207faefc46a/platform/security/sts/security-sts-realm/src/main/resources/OSGI-INF/blueprint/blueprint.xml#L97
https://github.com/codice/ddf/blob/40e40117e599e0ed300506c6076cb207faefc46a/platform/security/sts/security-sts-realm/src/main/resources/OSGI-INF/blueprint/blueprint.xml#L57

**Comment by rzwiefel** [comment]
:+1:

**Pull request merged**
