### PR TITLE
DDF-1482: Removed XLoggerWrapper from CachingFederationSytrategyLogger

### PR DESCRIPTION
**Pull request by millerw8**
[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/166)

### CODE REVIEW

**Comment by jrnorth** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/166)

**Comment by kcwire** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/166)

**Comment by kcwire** [comment]
@pklinef any objections to this?

**Comment by pklinef** [comment]
Looks good to me

**Comment by jlcsmith** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/166)

**Pull request merged**
