### PR TITLE
[2.13.x] DDF-4209 Upgrade spring-ldap-core to address vulnerabilities

### PR DESCRIPTION
**Pull request by kcover**
#### What does this PR do?

Upgrades spring-ldap-core to address vulnerabilities.

#### Who is reviewing it? 

@peterhuffer @emmberk @oconnormi 

#### Select relevant component teams: 

@codice/security 

#### Ask 2 committers to review/merge the PR and tag them here.

@clockard
@rzwiefel
@tbatie

#### What are the relevant tickets?

[DDF-4209](https://codice.atlassian.net/browse/DDF-4209)

#### How should this be tested?

Install DDF and test logging in through LDAP

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by kcover** [comment]
build now

**Comment by kcover** [comment]
build now

**Comment by kcover** [comment]
build now

**Comment by kcover** [comment]
going to see if the download fails one more time

**Comment by kcover** [comment]
build now

**Comment by kcover** [comment]
build now

**Comment by kcover** [comment]
build now

**Comment by peterhuffer** [comment]
Successful hero. Connected to an Active Directory server with the LDAP Wizard and set up `/search/catalog` web context policy to require login via the LDAP realm and verified logging in with an LDAP user.

**Pull request merged**
