### PR TITLE
DDF-04543 Upgrade tika bundle version

### PR DESCRIPTION
**Pull request by bakejeyner**
#### What does this PR do?
Upgrades the version of the third party tika bundle to avoid Jackson CVEs.

#### Who is reviewing it? 

@blen-desta
@garrettfreibott
@stustison
@vinamartin

#### How should this be tested?
1. [Build this branch of `third-party`](https://github.com/codice/thirdparty/pull/30)
1. Build this branch of DDF.
1. Build + standard install Alliance `1.1.x`, making sure that the `ddf.version` in Alliance's root pom is `2.13.7-SNAPSHOT`.
1. In `Admin Console -> All -> Features`, install `MpegtsInputTransformer` and `MpegtsStreaming`.
1. On the karaf command line, run `catalog:ingest -t mpegts <path_to_ts_file>`, where `<path_to_ts_file>` is a path to an `mpegts` file. Message me if an mpegts file is needed. The resource should ingest without error.
1. Through Intrigue, ingest a PDF. It should ingest without error.

#### What are the relevant tickets?
Fixes: #4543

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by tyler30clemens** [comment]
Hero Successful ✅

**Comment by vinamartin** [comment]
build now

**Comment by bakejeyner** [comment]
Waiting for artifacts from https://github.com/codice/thirdparty/pull/30 to deploy before attempting CI.

**Comment by bakejeyner** [comment]
build now

**Comment by bakejeyner** [comment]
build now

**Comment by bakejeyner** [comment]
build now
(🤞 flaky)

**Pull request merged**
