### PR TITLE
DDF-1415 Remove cometd endpoint’s dependency on the cache

### PR DESCRIPTION
**Pull request by pklinef**
- Made cometd endpoint normalize relevance and distance without blocking
  on the cache.
- Refactored search related classes in cometd endpoint to improve reuse
  and cohesion.
- Created FilteringSolrIndex to index only fields used by a given query.
- Added ability to create in-memory embedded Solr servers.
- Changed Solr related logging to reduce noise.
- Made all Solr field lookups go through the DynamicSchemaResolver so it
  is possible to determine what fields are being used.
- Fixed sorting for non-point radius spatial queries.
- Added update query mode to cache query results without blocking the
  catalog response.
- Fixed bug where exceptions thrown while searching the cache did not
  close the result queue.
- Fixed bug where SolrCache would fail if sorting by distance.

@coyotesqrl @rzwiefel @stustison 

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/117)

### CODE REVIEW

**Comment by coyotesqrl** [comment]
Review status: 0 of 38 files reviewed at latest revision, 24 unresolved discussions, some commit checks failed.

---

<sup>**[catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/DynamicSchemaResolver.java, line 91 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-JwwiO86MeUFrpjSDQNt)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/DynamicSchemaResolver.java#L91)):</sup>
It wouldn't be a big stretch to add Guava to this submodule and initialize in place with
`    private static final Map<String, String> ANY_FIELD_MAP = ImmutableMap
            .of(Metacard.ANY_TEXT, Metacard.METADATA + "_txt_tokenized", Metacard.ANY_GEO,
                    Metacard.GEOGRAPHY + "_geo_index");`

---

<sup>**[catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/DynamicSchemaResolver.java, line 373 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-JwwlDy9rOCAk_E-xXAM)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/catalog/core/catalog-core-solr/src/main/java/ddf/catalog/source/solr/DynamicSchemaResolver.java#L373)):</sup>
A comment here, or javadoc at declaration, explaining the updated logic would be helpful. I can suss out the change, but it would be nice to see it documented.

---

<sup>**[catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CachingFederationStrategy.java, line 187 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-JwwgAv7wUPUO2UypZP5)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CachingFederationStrategy.java#L187)):</sup>
What do you think about (not in this PR, obviously) updating `QueryResponseImpl` so it implements `Closeable`, deprecating this `closeResultQueue` method, and migrating over to try-with-resources?

---

<sup>**[catalog/ui/search-ui/search-endpoint/pom.xml, line 261 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-Jwxr810NM9MsLjfBRRM)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/catalog/ui/search-ui/search-endpoint/pom.xml#L261)):</sup>
Shouldn't this be in the `process-resources` phase?

---

<sup>**[catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/controller/search/QueryRunnable.java, line 72 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-Jwy2a9TBI1CkkMXZUxM)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/controller/search/QueryRunnable.java#L72)):</sup>
`ImmutableMap.of()` would be more compact.

---

<sup>**[catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/controller/search/QueryRunnable.java, line 89 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-Jwy3PJCXc-NbOaUAYhj)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/controller/search/QueryRunnable.java#L89)):</sup>
Is this class threadsafe?

---

<sup>**[catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/controller/search/QueryRunnable.java, line 137 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-Jwy42W_gnxpBAKRtnhv)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/controller/search/QueryRunnable.java#L137)):</sup>
Save `SPATIAL_CONTEXT.readShapeFromWkt(searchWkt).getCenter()` outside loop.

---

<sup>**[catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/controller/search/QueryRunnable.java, line 192 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-Jwy69qkwhyt6EdtgKym)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/controller/search/QueryRunnable.java#L192)):</sup>
Is there any advantage to adding a token between those two values? Could a (reasonable) situation arise where the lack of a token caused two results to collide?

---

<sup>**[catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/controller/search/SourceQueryRunnable.java, line 150 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-Jwy20j7j8_G8uFrMJdK)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/controller/search/SourceQueryRunnable.java#L150)):</sup>
Could probably collapse these two methods into one.

---

<sup>**[catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/controller/search/WktExtractionFilterDelegate.java, line 24 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-Jwy82vMzHurlBdOXJFR)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/controller/search/WktExtractionFilterDelegate.java#L24)):</sup>
Is this just a dummy implementation?

---

<sup>**[catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/controller/SearchController.java, line 132 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-Jwy-TVI2UJB2porbi-C)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/controller/SearchController.java#L132)):</sup>
I think it probably makes sense to add inline workflow comments to this method. Looking at it cold, it takes a minute or two to figure out what futures are being built up and why. It's not that difficult to follow, but short declarations of intent like, "Initialize the in-memory Solr in a Future to its startup time is masked by I/O and other processing" would make this very readable.

---

<sup>**[catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/model/Search.java, line 259 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-JwxOgEwR_9QEbvSHX76)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/model/Search.java#L259)):</sup>
You aren't referencing the key but to pull each status out; could be switched to `queryStatus.values()`.

---

<sup>**[catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/model/Search.java, line 296 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-JwxRErvU6_ETLN5ysaS)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/model/Search.java#L296)):</sup>
Could we document these methods where we're modifying collections passed in? Particularly ones like this, where it's a side-effect. With the `addObject` method, it's immediately obvious that we're modifying a param but with this one it take a second to see it. A short javadoc comment would be good enough for me. I can't think of any good doc-type annotation to indicate immutability/mutability or I'd suggest that route.

---

<sup>**[catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/model/Search.java, line 327 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-JwxYSCFZmSyvGbiD0kY)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/model/Search.java#L327)):</sup>
Only because this is a very long code review and my mind is a little warped...

http://www.imdb.com/title/tt0094612/

---

<sup>**[catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/model/Search.java, line 360 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-JwxbJLTHgA9Mbm9RWek)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/model/Search.java#L360)):</sup>
Constants to be consistent.

---

<sup>**[catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/solr/FilteringDynamicSchemaResolver.java, line 109 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-Jwxm-fL6fBeRXtsDRu5)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/solr/FilteringDynamicSchemaResolver.java#L109)):</sup>
This is intended as a `String.contains`? Could we get false matches ever?

---

<sup>**[catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/solr/FilteringSolrIndex.java, line 41 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-Jwxn3FCz9P0Z22v-zI3)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/solr/FilteringSolrIndex.java#L41)):</sup>
Is this ctor only for test injection? Maybe make it package-private and comment on that fact?

---

<sup>**[catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/solr/FilteringSolrIndex.java, line 50 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-JwxoinznfdTmYUfZGZ8)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/solr/FilteringSolrIndex.java#L50)):</sup>
I don't understand this at all. The `getInstance()` method is synch so only one instance can be created and passed around, but its use is wide open. There's nothing I can see preventing a second thread from calling `ConfigurationStore.getInstance().setInMemory(false)` before you've created your file proxy below. Should these be thread local or maybe abandon the `uniqueInstance` notion?

Am I missing something obvious?

Are you getting away with this because the ctor of `ConfigurationFileProxy` only uses the `dataDirectoryPath` and that's the same everywhere?

---

<sup>**[catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/solr/FilteringSolrIndex.java, line 58 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-Jwxrkr8Os50q1mdW7op)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/solr/FilteringSolrIndex.java#L58)):</sup>
Consts.

---

<sup>**[catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/solr/FilteringSolrIndex.java, line 64 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-JwxsMrEcpKXHnpY_pY2)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/solr/FilteringSolrIndex.java#L64)):</sup>
Synchro here not sufficient without synchro on `query` and `shutdown` methods.

---

<sup>**[platform/solr/platform-solr-server-standalone/src/main/resources/solr/conf/solrconfig-inmemory.xml, line 108 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-Jwwu-ZyjcJV9oF_yove)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/platform/solr/platform-solr-server-standalone/src/main/resources/solr/conf/solrconfig-inmemory.xml#L108)):</sup>
This looks like a replacement parameter but I can't see where its value comes from. Is it at all a problem that we're using the same replacement param in this file and in other solr config files? Would the `dataDir`s stomp on each other?

---

<sup>**[platform/solr/platform-solr-server-standalone/src/main/resources/solr/conf/solrconfig-inmemory.xml, line 838 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-JwwuftPJWGrZZSUuq0t)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/platform/solr/platform-solr-server-standalone/src/main/resources/solr/conf/solrconfig-inmemory.xml#L838)):</sup>
Should this example be removed/commented out?

---

<sup>**[platform/solr/solr-factory/pom.xml, line 55 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-JwwzoJpCNlOaoycTeKv)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/platform/solr/solr-factory/pom.xml#L55)):</sup>
Coverage went down because of the addition of the in-memory Solr, correct? Shouldn't we add tests to confirm those branches are all working correctly rather than just dropping our current coverage numbers?

---

<sup>**[platform/solr/solr-factory/src/main/java/org/codice/solr/factory/SolrServerFactory.java, line 294 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-JwwzDIEFxcCYcNBpdtc)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/platform/solr/solr-factory/src/main/java/org/codice/solr/factory/SolrServerFactory.java#L294)):</sup>
What is the result of a null `dataDirPath` in the case where it _should_ be a file-backed Solr? It would just be a non-RAM-backed in-memory Solr, right? Does that cause problems?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/117)

**Comment by coyotesqrl** [comment]
Finished my first pass over all but Tests and Docs. I figured it'd be better to publish my comments now since I'm out tomorrow and maybe some of these will drive analysis/review thoughts for someone else.

**Comment by coyotesqrl** [comment]
Review status: 0 of 38 files reviewed at latest revision, 25 unresolved discussions, some commit checks failed.

---

<sup>**[catalog/ui/search-ui/search-endpoint/src/test/groovy/org/codice/ddf/ui/searchui/query/solr/FilteringDynamicSchemaResolverTest.groovy, line 161 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-Jx5cH70-q62IH7Z8DNA)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/catalog/ui/search-ui/search-endpoint/src/test/groovy/org/codice/ddf/ui/searchui/query/solr/FilteringDynamicSchemaResolverTest.groovy#L161)):</sup>
Should be `!contains("foo_txt")`, right?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/117)

**Comment by coyotesqrl** [comment]
Review status: 0 of 38 files reviewed at latest revision, 25 unresolved discussions, some commit checks failed.

---

<sup>**[catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/solr/FilteringDynamicSchemaResolver.java, line 109 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-Jwxm-fL6fBeRXtsDRu5)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/solr/FilteringDynamicSchemaResolver.java#L109)):</sup>
Would it be safer to affix underscores to the string under test?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/117)

**Comment by rzwiefel** [comment]
Review status: 0 of 38 files reviewed at latest revision, 28 unresolved discussions, some commit checks failed.

---

<sup>**[catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CachingFederationStrategy.java, line 187 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-JwwgAv7wUPUO2UypZP5)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/cache/solr/impl/CachingFederationStrategy.java#L187)):</sup>
I'd say +1 to try-with-resources.

---

<sup>**[catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/controller/SearchController.java, line 172 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-Jx5FgOltfLzKHn4ONJu)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/controller/SearchController.java#L172)):</sup>
Can someone who knows what they're doing here confirm that with a enterprise (local + 1 site) there will be only 1 sourceId, but since it also does local search it should normalize? (because I thought local search didn't  add a sourceid)

---

<sup>**[catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/model/Search.java, line 296 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-JwxRErvU6_ETLN5ysaS)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/model/Search.java#L296)):</sup>
@Mutable +1

---

<sup>**[catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/solr/FilteringSolrIndex.java, line 64 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-JwxsMrEcpKXHnpY_pY2)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/solr/FilteringSolrIndex.java#L64)):</sup>
Also need Documentation on this! (which could explain why only this needs sync?)

---

<sup>**[catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/solr/FilteringSolrIndex.java, line 85 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-Jx5n5mVw9ZV6Qrh6Bp1)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/solr/FilteringSolrIndex.java#L85)):</sup>
I don't know, maybe it isn't appropriate, but I do love a more functional way of doing this (now that we have java 8.. )
```java
return results.stream()
                .filter(r -> r != null && r.getMetacard() != null)
                .map(Result::getMetacard)
                .collect(Collectors.toList());
```

---

<sup>**[catalog/ui/search-ui/search-endpoint/src/test/groovy/org/codice/ddf/ui/searchui/query/solr/FilteringDynamicSchemaResolverTest.groovy, line 83 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-Jx5oz5q3Sh_HFvA5ZOx)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/catalog/ui/search-ui/search-endpoint/src/test/groovy/org/codice/ddf/ui/searchui/query/solr/FilteringDynamicSchemaResolverTest.groovy#L83)):</sup>
Shouldn't these hardcoded suffixes actually be using the SchemaFields.java class values? you could even use some GString interpolation to keep it readable.
if you static import the few fields.. `"id$TEXT_SUFFIX", "metacard_type_name$TEXT_SUFFIX"...` even import aliasing them since they are used so much in here perhaps

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/117)

**Comment by coyotesqrl** [comment]
Review status: 0 of 38 files reviewed at latest revision, 28 unresolved discussions, some commit checks failed.

---

<sup>**[catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/solr/FilteringSolrIndex.java, line 85 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-Jx5n5mVw9ZV6Qrh6Bp1)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/solr/FilteringSolrIndex.java#L85)):</sup>
Did I miss the memo that said we could target Java 8?!?!?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/117)

**Comment by coyotesqrl** [comment]
Reviewed 38 of 38 files at r1.
Review status: all files reviewed at latest revision, 28 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/117)

**Comment by rzwiefel** [comment]
<sup>**[catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/controller/SearchController.java, line 132 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-Jwy-TVI2UJB2porbi-C)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/controller/SearchController.java#L132)):</sup>
'..in a Future so* its startup..' ?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/117)

**Comment by coyotesqrl** [comment]
Review status: all files reviewed at latest revision, 28 unresolved discussions, some commit checks failed.

---

<sup>**[catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/controller/SearchController.java, line 132 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-Jwy-TVI2UJB2porbi-C)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/controller/SearchController.java#L132)):</sup>
Yes.  Typo. :)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/117)

**Comment by rzwiefel** [comment]
<sup>**[catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/solr/FilteringSolrIndex.java, line 85 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-Jx5n5mVw9ZV6Qrh6Bp1)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/solr/FilteringSolrIndex.java#L85)):</sup>
I guess not.. I'll just keep on hoping then.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/117)

**Comment by rzwiefel** [comment]
Reviewed 36 of 38 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 27 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/117)

**Comment by rzwiefel** [comment]
Built okay with PRBS.

**Comment by pklinef** [comment]
Review status: 29 of 39 files reviewed at latest revision, 16 unresolved discussions, some commit checks pending.

---

<sup>**[catalog/ui/search-ui/search-endpoint/pom.xml, line 261 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-Jwxr810NM9MsLjfBRRM)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/catalog/ui/search-ui/search-endpoint/pom.xml#L261)):</sup>
I found a better way to do this which will hopefully make it clearer what is being done without so much being copied and pasted when solr config files are need for unit tests.

---

<sup>**[catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/controller/search/QueryRunnable.java, line 89 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-Jwy3PJCXc-NbOaUAYhj)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/controller/search/QueryRunnable.java#L89)):</sup>
It is suppose to be.

https://locationtech.github.io/spatial4j/apidocs/index.html?com/spatial4j/core/context/SpatialContext.html

---

<sup>**[catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/controller/search/WktExtractionFilterDelegate.java, line 24 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-Jwy82vMzHurlBdOXJFR)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/controller/search/WktExtractionFilterDelegate.java#L24)):</sup>
No, it will visit the filter and extract any WKT used if the filter contains spatial operations.

---

<sup>**[catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/solr/FilteringDynamicSchemaResolver.java, line 109 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-Jwxm-fL6fBeRXtsDRu5)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/solr/FilteringDynamicSchemaResolver.java#L109)):</sup>
This was intentional.  For example, if the query uses the has_case index field, I need to include the root field which the Solr schema will copy into the has_case field.  I don't know which fields will use copy field so I will match all fields that share the same prefix.

---

<sup>**[catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/solr/FilteringSolrIndex.java, line 50 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-JwxoinznfdTmYUfZGZ8)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/solr/FilteringSolrIndex.java#L50)):</sup>
ConfigurationStore is a shared singleton per classloader/bundle.  This should be the only kind of Solr instance created in this bundle so it is safe.  Some day I want to make ConfigurationStore not be a singleton but this is safe in OSGi until then.

---

<sup>**[catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/solr/FilteringSolrIndex.java, line 64 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-JwxsMrEcpKXHnpY_pY2)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/catalog/ui/search-ui/search-endpoint/src/main/java/org/codice/ddf/ui/searchui/query/solr/FilteringSolrIndex.java#L64)):</sup>
The provider is thread safe but since force auto commit is enabled there can be performance issues and warnings logged if too many threads try to commit at the same time.  I will add a comment about that.

---

<sup>**[platform/solr/platform-solr-server-standalone/src/main/resources/solr/conf/solrconfig-inmemory.xml, line 108 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-Jwwu-ZyjcJV9oF_yove)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/platform/solr/platform-solr-server-standalone/src/main/resources/solr/conf/solrconfig-inmemory.xml#L108)):</sup>
This value is relative to the Solr home which we do always change when using the SolrServerFactory.

---

<sup>**[platform/solr/platform-solr-server-standalone/src/main/resources/solr/conf/solrconfig-inmemory.xml, line 838 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-JwwuftPJWGrZZSUuq0t)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/platform/solr/platform-solr-server-standalone/src/main/resources/solr/conf/solrconfig-inmemory.xml#L838)):</sup>
This started from the default solrconfig.xml file.  At some point we should go through this file and remove all of the extra features we do not use.  These request handlers are less of a concern with an in memory embedded solr since no one can access them.  This is more of a problem for the solr wab which does not use this config.

---

<sup>**[platform/solr/solr-factory/pom.xml, line 55 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-JwwzoJpCNlOaoycTeKv)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/platform/solr/solr-factory/pom.xml#L55)):</sup>
That method takes over 2 seconds to run which greatly increases unit test run time for little value.  I was able to cover those lines with powermock but even that took nearly 2 seconds.  An in memory solr server is created in a similar way in the catalog solr core unit tests so any issues should be caught there.

---

<sup>**[platform/solr/solr-factory/src/main/java/org/codice/solr/factory/SolrServerFactory.java, line 294 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/117#-JwwzDIEFxcCYcNBpdtc)** ([raw file](https://github.com/codice/ddf/blob/c910b4e11869da6fafb16c5737a1fb4b1eac0419/platform/solr/solr-factory/src/main/java/org/codice/solr/factory/SolrServerFactory.java#L294)):</sup>
Right, it would use a default file based data directory relative to the Solr home.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/117)

**Comment by rzwiefel** [comment]
Built okay :+1:

**Pull request merged**
