### PR TITLE
DDF-2968 Allow associations view for remote results

### PR DESCRIPTION
**Pull request by andrewkfiedler**
Closing https://github.com/codice/ddf/pull/1929 in favor of this rebase since it's been so long.  

@bdeining 
@rzwiefel 
@jlcsmith

### CODE REVIEW

**Comment by rzwiefel** [comment]
@andrewkfiedler Do we want to close this until it is prioritized again? (since the corresponding backend PR's have also been closed)

**Comment by coyotesqrl** [comment]
@andrewkfiedler Tagging again to ask on the status of this PR. Should it be updated and completed so it can be merged, or should it be closed at this time?

**Comment by andrewkfiedler** [comment]
This is waiting on https://github.com/codice/ddf/pull/1910 which appears to have been closed.

**Comment by rzwiefel** [comment]
Closing since its on hold with no immediate plans of being worked.  We can re-open if need be.

**Pull request closed without merging**
