### PR TITLE
[2.19.x] G-20635 - udpates the country code converter version

### PR DESCRIPTION
**Pull request by kcwire**
@jrnorth
@millerw8

### CODE REVIEW

**Comment by kcwire** [comment]
build now

**Review by jlcsmith — APPROVED** [review]

**Review by jrnorth — APPROVED** [review]

**Comment by pklinef** [comment]
build now

**Review by millerw8 — APPROVED** [review]

**Comment by kcwire** [comment]
build now

**Comment by kcwire** [comment]
build now

**Comment by kcwire** [comment]
build now

**Comment by phuffer-gr** [comment]
Classic.

**Pull request merged**
