### PR TITLE
[2.16.x] DDF-05271 Fix OCSP Checker to only revoke certificates that contain a revoked certificate status

### PR DESCRIPTION
**Pull request by roelens8**
Refer to https://github.com/codice/ddf/pull/5272 for more information

### CODE REVIEW

**Comment by roelens8** [comment]
build now

**Comment by beyelerb** [comment]
build now

**Comment by JoaquinNadal** [comment]
build now

**Comment by roelens8** [comment]
build now

**Comment by roelens8** [comment]
build now

**Pull request merged**
