### PR TITLE
[2.11.x] DDF-2824 fixed install prereq caption & migration api titles

### PR DESCRIPTION
**Pull request by ricklarsen**
#### What does this PR do?

- fixes table caption for Installation Prerequisites
- fixes title ordering in migration API docs

#### Who is reviewing it? 
@mcalcote @vinamartin @ahoffer @garrettfreibott 

#### Choose 2 committers to review/merge the PR. 

@clockard
@coyotesqrl
@lessarderic
@pklinef
@ricklarsen - Documentation
@rzwiefel
@shaundmorris

#### How should this be tested? (List steps with links to updated documentation)

- builds are successful. 
- content updated.

#### What are the relevant tickets?
[DDF-2824](https://codice.atlassian.net/browse/DDF-2824)

#### Screenshots (if appropriate)

html-format
pdf-format

#### Checklist:
- [x] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests
#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by ricklarsen** [comment]
build now

**Comment by ricklarsen** [comment]
build now

**Comment by ricklarsen** [comment]
build now

**Comment by mcalcote** [comment]
Would a dagger symbol `†` make sense to use instead of triple asterisk?

**Comment by ricklarsen** [comment]
@mcalcote Changed to be &ast;, &dagger;, &Dagger;

**Comment by ricklarsen** [comment]
build now

**Pull request merged**
