### PR TITLE
[2.11.x] DDF-3262 Increase Solr string indexing size and exclude attributes

### PR DESCRIPTION
**Pull request by pklinef**
#### What does this PR do?
Backport of https://github.com/codice/ddf/pull/2355

#### Choose 2 committers to review/merge the PR. 
@jlcsmith
@rzwiefel

### CODE REVIEW

**Comment by pklinef** [comment]
build now

**Comment by jlcsmith** [comment]
build now

**Comment by rzwiefel** [comment]
build now

**Comment by gordocanchola** [comment]
Manual testing successfully hero'd

**Comment by gordocanchola** [comment]
build now

**Pull request merged**
