### PR TITLE
[2.19.x] G-7486 Change gazetteer placeholder text to "Pan to a city, country, or coordinate"

### PR DESCRIPTION
**Pull request by rymach**
backport of https://github.com/codice/ddf-ui/pull/70

#### What are the relevant tickets?
Fixes: #____

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by rymach** [comment]
build now

**Review by Lambeaux — APPROVED** [review]

**Review by jordanwilking — APPROVED** [review]
Could be worth making this a bit more generic than "Pan". We're using ddf-ui, so this doesn't effect us, but we found some good usages for the gazetteer without an accompanying map. 

I think we went with "Enter a [...]"

**Comment by rymach** [comment]
build now

**Comment by rymach** [comment]
build now

**Review by mojogitoverhere — APPROVED** [review]

**Pull request merged**
