### PR TITLE
DDF-1480: Documented Use of CSW Transactions

### PR DESCRIPTION
**Pull request by EIrwin**
Added documentation for CWS Transaction sub operations
insert,update and delete

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/161)

### CODE REVIEW

**Comment by EIrwin** [comment]
@jrnorth @kguerriero @kcwire 

hero is @jrnorth

**Comment by kcwire** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

<sup>**[catalog/spatial/docs/src/main/resources/IntContents.adoc, line 948 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/161#-Jyj4d4g9izifa5jE8Vl)** ([raw file](https://github.com/codice/ddf/blob/d1fb1a92a52264d0d13a4c0898e680e2ae3bb678/catalog/spatial/docs/src/main/resources/IntContents.adoc#L948)):</sup>
Might say it only supports the HTTP POST since there is no KVP operations

---

<sup>**[catalog/spatial/docs/src/main/resources/IntContents.adoc, line 1168 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/161#-Jyj5BvIdcnKpIC_TfQh)** ([raw file](https://github.com/codice/ddf/blob/d1fb1a92a52264d0d13a4c0898e680e2ae3bb678/catalog/spatial/docs/src/main/resources/IntContents.adoc#L1168)):</sup>
wgs81 or wgs84?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/161)

**Comment by EIrwin** [comment]
<sup>**[catalog/spatial/docs/src/main/resources/IntContents.adoc, line 948 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/161#-Jyj4d4g9izifa5jE8Vl)** ([raw file](https://github.com/codice/ddf/blob/d1fb1a92a52264d0d13a4c0898e680e2ae3bb678/catalog/spatial/docs/src/main/resources/IntContents.adoc#L948)):</sup>
Updated

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/161)

**Comment by EIrwin** [comment]
<sup>**[catalog/spatial/docs/src/main/resources/IntContents.adoc, line 1168 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/161#-Jyj5BvIdcnKpIC_TfQh)** ([raw file](https://github.com/codice/ddf/blob/d1fb1a92a52264d0d13a4c0898e680e2ae3bb678/catalog/spatial/docs/src/main/resources/IntContents.adoc#L1168)):</sup>
ahhh....got it and fixed it.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/161)

**Comment by wmcnalli** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[catalog/spatial/docs/src/main/resources/IntContents.adoc, line 948 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/161#-JymDe17UDbqWPViszEP)** ([raw file](https://github.com/codice/ddf/blob/4d6dc3db7b61040204dbf690de747db2f4f0b88a/catalog/spatial/docs/src/main/resources/IntContents.adoc#L948)):</sup>
Grammar nazi:  ... since there *are* no KVP operations.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/161)

**Comment by beyelerb** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[catalog/spatial/docs/src/main/resources/IntContents.adoc, line 1168 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/161#-Jyj5BvIdcnKpIC_TfQh)** ([raw file](https://github.com/codice/ddf/blob/d1fb1a92a52264d0d13a4c0898e680e2ae3bb678/catalog/spatial/docs/src/main/resources/IntContents.adoc#L1168)):</sup>
PropertyIsLessThanOrEqualTo? Doesn't make sense for wgs84

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/161)

**Comment by EIrwin** [comment]
<sup>**[catalog/spatial/docs/src/main/resources/IntContents.adoc, line 948 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/161#-Jyj4d4g9izifa5jE8Vl)** ([raw file](https://github.com/codice/ddf/blob/d1fb1a92a52264d0d13a4c0898e680e2ae3bb678/catalog/spatial/docs/src/main/resources/IntContents.adoc#L948)):</sup>
Ok, got it

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/161)

**Comment by EIrwin** [comment]
<sup>**[catalog/spatial/docs/src/main/resources/IntContents.adoc, line 1168 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/161#-Jyj5BvIdcnKpIC_TfQh)** ([raw file](https://github.com/codice/ddf/blob/d1fb1a92a52264d0d13a4c0898e680e2ae3bb678/catalog/spatial/docs/src/main/resources/IntContents.adoc#L1168)):</sup>
There are a few examples I have seen where I got this from, but I agree it doesn't make sense so I changed it to 84.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/161)

**Comment by wmcnalli** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

<sup>**[catalog/spatial/docs/src/main/resources/IntContents.adoc, line 1168 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/161#-Jyj5BvIdcnKpIC_TfQh)** ([raw file](https://github.com/codice/ddf/blob/d1fb1a92a52264d0d13a4c0898e680e2ae3bb678/catalog/spatial/docs/src/main/resources/IntContents.adoc#L1168)):</sup>
I think he was saying the PropertyIsLessThanOrEqualTo operator on the SpatialReferenceSystem property is not a good example.  IIRC, SpatialReferenceSystem is a discrete set of values - EPSG:4326, WGS-84 etc.  

PropertyIsLike or PropertyIsEqualTo is more appropriate for that particular property. 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/161)

**Comment by EIrwin** [comment]
<sup>**[catalog/spatial/docs/src/main/resources/IntContents.adoc, line 1168 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/161#-Jyj5BvIdcnKpIC_TfQh)** ([raw file](https://github.com/codice/ddf/blob/d1fb1a92a52264d0d13a4c0898e680e2ae3bb678/catalog/spatial/docs/src/main/resources/IntContents.adoc#L1168)):</sup>
Alright, I changed this to PropertyIsEqualTo and changed the value back to WGS-84.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/161)

**Comment by jrnorth** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

<sup>**[catalog/spatial/docs/src/main/resources/IntContents.adoc, line 1013 \[r4\]](https://reviewable.io:443/reviews/codice/ddf/161#-JynVQNz2i5JuX9yblIy)** ([raw file](https://github.com/codice/ddf/blob/8de061e4e987fcb0625c2449097f0338cbeb24dd/catalog/spatial/docs/src/main/resources/IntContents.adoc#L1013)):</sup>
Might want to point out that you'll only get an `InsertResult` if you specified `verboseResponse="true"` in the request.

---

<sup>**[catalog/spatial/docs/src/main/resources/IntContents.adoc, line 1029 \[r4\]](https://reviewable.io:443/reviews/codice/ddf/161#-JynVzPQPFG7fUuQdu_T)** ([raw file](https://github.com/codice/ddf/blob/8de061e4e987fcb0625c2449097f0338cbeb24dd/catalog/spatial/docs/src/main/resources/IntContents.adoc#L1029)):</sup>
I think this should be reorganized - take sentences 2 and 3 and put them at the end. Also, it would probably be good to be a bit more specific about how removing properties works. A property is removed _only_ if the `RecordProperty` contains a `Name` but not a `Value`. 'missing' could mean that an empty `Value` element will remove the corresponding property, but that's not the case.

---

<sup>**[catalog/spatial/docs/src/main/resources/IntContents.adoc, line 1033 \[r4\]](https://reviewable.io:443/reviews/codice/ddf/161#-Jyo0cWn0vYxGwcKzGSc)** ([raw file](https://github.com/codice/ddf/blob/8de061e4e987fcb0625c2449097f0338cbeb24dd/catalog/spatial/docs/src/main/resources/IntContents.adoc#L1033)):</sup>
You'll want to mention that you can replace a _specific_ record in the catalog with a new record. If your update request contains a `<csw:Record>` rather than a set of `<RecordProperty>`s plus a `<Constraint>` , the existing record with the same ID will be replaced with the new record.

---

<sup>**[catalog/spatial/docs/src/main/resources/IntContents.adoc, line 1051 \[r4\]](https://reviewable.io:443/reviews/codice/ddf/161#-JynY52I_k4U2IqPpz5h)** ([raw file](https://github.com/codice/ddf/blob/8de061e4e987fcb0625c2449097f0338cbeb24dd/catalog/spatial/docs/src/main/resources/IntContents.adoc#L1051)):</sup>
Use the identifier returned in the example insert response above.

---

<sup>**[catalog/spatial/docs/src/main/resources/IntContents.adoc, line 1168 \[r4\]](https://reviewable.io:443/reviews/codice/ddf/161#-Jyo2EjHo9-fPQ2XPNqv)** ([raw file](https://github.com/codice/ddf/blob/8de061e4e987fcb0625c2449097f0338cbeb24dd/catalog/spatial/docs/src/main/resources/IntContents.adoc#L1168)):</sup>
"shows a delete request for all records with..."

---

<sup>**[catalog/spatial/docs/src/main/resources/IntContents.adoc, line 1191 \[r4\]](https://reviewable.io:443/reviews/codice/ddf/161#-Jyo2mW-6bNuuDvz8mCB)** ([raw file](https://github.com/codice/ddf/blob/8de061e4e987fcb0625c2449097f0338cbeb24dd/catalog/spatial/docs/src/main/resources/IntContents.adoc#L1191)):</sup>
"with _a_ title"

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/161)

**Comment by EIrwin** [comment]
<sup>**[catalog/spatial/docs/src/main/resources/IntContents.adoc, line 1031 \[r4\]](https://reviewable.io:443/reviews/codice/ddf/161#-JynVzPQPFG7fUuQdu_T)** ([raw file](https://github.com/codice/ddf/blob/8de061e4e987fcb0625c2449097f0338cbeb24dd/catalog/spatial/docs/src/main/resources/IntContents.adoc#L1031)):</sup>
Is this more like what you think it should be?

The Update sub-operation is a method to specify values used to change existing information in the catalog. If individual record property values are specified in the Update element, using the RecordProperty element, then those individual property values of a catalog record are replaced. The RecordProperty contains a Name and Value element. The Name element is used to specify the name of the record property to be updated. The Value element contains the value that will be used to update the record in the catalog. The values in the Update will completely replace those that are already in the record. A property is removed only if the RecordProperty contains a Name but not a Value.

If not, please change and let me know.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/161)

**Comment by jrnorth** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

<sup>**[catalog/spatial/docs/src/main/resources/IntContents.adoc, line 1029 \[r4\]](https://reviewable.io:443/reviews/codice/ddf/161#-JynVzPQPFG7fUuQdu_T)** ([raw file](https://github.com/codice/ddf/blob/8de061e4e987fcb0625c2449097f0338cbeb24dd/catalog/spatial/docs/src/main/resources/IntContents.adoc#L1029)):</sup>
Looks good.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/161)

**Comment by jrnorth** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

<sup>**[catalog/spatial/docs/src/main/resources/IntContents.adoc, line 992 \[r6\]](https://reviewable.io:443/reviews/codice/ddf/161#-JzBQcep-vXOYNRpDg2V)** ([raw file](https://github.com/codice/ddf/blob/4d57bf61a145da1677ec5d74d72292bda8c9771f/catalog/spatial/docs/src/main/resources/IntContents.adoc#L992)):</sup>
Nitpick: "true" should be surrounded by quotation marks.

---

<sup>**[catalog/spatial/docs/src/main/resources/IntContents.adoc, line 1031 \[r6\]](https://reviewable.io:443/reviews/codice/ddf/161#-JzBQnPOpN4tlWxeGFYW)** ([raw file](https://github.com/codice/ddf/blob/4d57bf61a145da1677ec5d74d72292bda8c9771f/catalog/spatial/docs/src/main/resources/IntContents.adoc#L1031)):</sup>
Whenever you refer to the actual `Update` element in the request rather than the Update transaction in general, you should surround it with ` for consistency. Specifically, I would recommend changing this in your second sentence.

---

<sup>**[catalog/spatial/docs/src/main/resources/IntContents.adoc, line 1033 \[r6\]](https://reviewable.io:443/reviews/codice/ddf/161#-JzBRdTsvdKzGXUYCsN3)** ([raw file](https://github.com/codice/ddf/blob/4d57bf61a145da1677ec5d74d72292bda8c9771f/catalog/spatial/docs/src/main/resources/IntContents.adoc#L1033)):</sup>
"which" instead of "that". Also, surround "Constraint" with `. Finally, I would say something like "a subset of records in the catalog" rather than "a specific record or group of records".

---

<sup>**[catalog/spatial/docs/src/main/resources/IntContents.adoc, line 1044 \[r6\]](https://reviewable.io:443/reviews/codice/ddf/161#-JzBT3uWZFXLuHXrGKkV)** ([raw file](https://github.com/codice/ddf/blob/4d57bf61a145da1677ec5d74d72292bda8c9771f/catalog/spatial/docs/src/main/resources/IntContents.adoc#L1044)):</sup>
I'd remove the `verboseResponse="true"` attribute in all the examples that aren't Inserts, since it won't do anything for Updates or Deletes.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/161)

**Comment by kcwire** [comment]
@EIrwin @jrnorth I'd like to merge this today - please let me know when this is ready to go.

**Comment by EIrwin** [comment]
Changes were made and pushed. Should be good to go pending feedback from review.

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/161)

**Comment by jrnorth** [comment]
The generated HTML and PDF docs look good. Just address the typo I pointed out and it's good to go.

---

Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

<sup>**[catalog/spatial/docs/src/main/resources/IntContents.adoc, line 1086 \[r7\]](https://reviewable.io:443/reviews/codice/ddf/161#-JzBrAmfHy_4t0MfCD25)** ([raw file](https://github.com/codice/ddf/blob/07d9128befcace0c6ce76de7128f4de247fc7003/catalog/spatial/docs/src/main/resources/IntContents.adoc#L1086)):</sup>
There's a copyright symbol here.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/161)

**Comment by EIrwin** [comment]
<sup>**[catalog/spatial/docs/src/main/resources/IntContents.adoc, line 1086 \[r7\]](https://reviewable.io:443/reviews/codice/ddf/161#-JzBrAmfHy_4t0MfCD25)** ([raw file](https://github.com/codice/ddf/blob/07d9128befcace0c6ce76de7128f4de247fc7003/catalog/spatial/docs/src/main/resources/IntContents.adoc#L1086)):</sup>
Removed the `@` symbol

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/161)

**Comment by jrnorth** [comment]
:+1:

---

Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/161)

**Comment by bdeining** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[catalog/spatial/docs/src/main/resources/IntContents.adoc, line 251 \[r8\]](https://reviewable.io:443/reviews/codice/ddf/161#-JzCLUCc0FB91y0UwNXk)** ([raw file](https://github.com/codice/ddf/blob/1ee7ca4383b2d2dd11c9615c86a4ddcb0fd72f59/catalog/spatial/docs/src/main/resources/IntContents.adoc#L251)):</sup>
The OpenGIS spec makes no mention of OutputSchema for DescribeRecord operations (10.6).  Should this be "schemaLanguage"?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/161)

**Comment by EIrwin** [comment]
<sup>**[catalog/spatial/docs/src/main/resources/IntContents.adoc, line 251 \[r8\]](https://reviewable.io:443/reviews/codice/ddf/161#-JzCLUCc0FB91y0UwNXk)** ([raw file](https://github.com/codice/ddf/blob/1ee7ca4383b2d2dd11c9615c86a4ddcb0fd72f59/catalog/spatial/docs/src/main/resources/IntContents.adoc#L251)):</sup>
I am not sure, I do not have a thorough understanding of it, so you would know better than me.

Let me know if we need to make this change.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/161)

**Comment by bdeining** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[catalog/spatial/docs/src/main/resources/IntContents.adoc, line 251 \[r8\]](https://reviewable.io:443/reviews/codice/ddf/161#-JzCLUCc0FB91y0UwNXk)** ([raw file](https://github.com/codice/ddf/blob/1ee7ca4383b2d2dd11c9615c86a4ddcb0fd72f59/catalog/spatial/docs/src/main/resources/IntContents.adoc#L251)):</sup>
I think this should be schemaLanguage ( the code validates schema languages in a DescribeRecord request ), but we should wait for another opinion

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/161)

**Comment by jlcsmith** [comment]
<sup>**[catalog/spatial/docs/src/main/resources/IntContents.adoc, line 1218 \[r8\]](https://reviewable.io:443/reviews/codice/ddf/161#-JzCU9zRPzBpMg3LFAE_)** ([raw file](https://github.com/codice/ddf/blob/1ee7ca4383b2d2dd11c9615c86a4ddcb0fd72f59/catalog/spatial/docs/src/main/resources/IntContents.adoc#L1218)):</sup>
This is a nit, but in this example you are declaring a bunch of namespaces that are never used.  This is unnecessary and just clutters up the document.  Did this actually get generated by DDF?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/161)

**Comment by jlcsmith** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/161)

**Comment by jlcsmith** [comment]
<sup>**[catalog/spatial/docs/src/main/resources/IntContents.adoc, line 1218 \[r8\]](https://reviewable.io:443/reviews/codice/ddf/161#-JzCU9zRPzBpMg3LFAE_)** ([raw file](https://github.com/codice/ddf/blob/1ee7ca4383b2d2dd11c9615c86a4ddcb0fd72f59/catalog/spatial/docs/src/main/resources/IntContents.adoc#L1218)):</sup>
If this is generated by DDF this way, we should clean this up (separate ticket)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/161)

**Comment by bdeining** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

<sup>**[catalog/spatial/docs/src/main/resources/IntContents.adoc, line 540 \[r8\]](https://reviewable.io:443/reviews/codice/ddf/161#-JzChEM_OSY3-rO3M-Ak)** ([raw file](https://github.com/codice/ddf/blob/1ee7ca4383b2d2dd11c9615c86a4ddcb0fd72f59/catalog/spatial/docs/src/main/resources/IntContents.adoc#L540)):</sup>
There's an extra question mark in this request (csw??) :sunglasses: 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/161)

**Comment by EIrwin** [comment]
<sup>**[catalog/spatial/docs/src/main/resources/IntContents.adoc, line 1218 \[r8\]](https://reviewable.io:443/reviews/codice/ddf/161#-JzCU9zRPzBpMg3LFAE_)** ([raw file](https://github.com/codice/ddf/blob/1ee7ca4383b2d2dd11c9615c86a4ddcb0fd72f59/catalog/spatial/docs/src/main/resources/IntContents.adoc#L1218)):</sup>
I believe this was residual namespaces copied from a bad example. I copied them in and forgot to remove them.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/161)

**Pull request closed without merging**
