### PR TITLE
DDF-3624 refactor WFS sources to ensure no bundles are embedded

### PR DESCRIPTION
**Pull request by GabrielFabian**
#### What does this PR do?
Refactors WFS to remove all embedded bundles

#### Who is reviewing it? 
(please choose AT LEAST two reviewers that need to approve the PR before it can get merged)
@bdeining @jlcsmith @millerw8 @troymohl 

#### Select relevant component teams: 
https://github.com/orgs/codice/teams
#### Choose 2 committers to review/merge the PR. 
(please choose ONLY two committers from below, delete the rest)
@bdeining
@jlcsmith 

#### How should this be tested? (List steps with links to updated documentation)
Full build, integration tests should be sufficient.

#### What are the relevant tickets?
[DDF-3624] (https://codice.atlassian.net/browse/DDF-3624)

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by jlcsmith** [comment]
@GabrielFabian - can you also take a look at the https://github.com/codice/ddf/tree/master/catalog/spatial/wfs/spatial-wfs-source?  I don't think it should be a bundle either

**Comment by jlcsmith** [comment]
also https://github.com/codice/ddf/tree/master/catalog/spatial/wfs/spatial-wfs-api

**Comment by GabrielFabian** [comment]
@jlcsmith spatial-wfs-source has been refactored as a jar, but it looks like the spatial-wfs-api is a valid bundle.

**Comment by jlcsmith** [comment]
build now

**Comment by jlcsmith** [comment]
build now

**Comment by bdeining** [comment]
build now

**Comment by bdeining** [comment]
build now

**Comment by jlcsmith** [comment]
build now

**Comment by GabrielFabian** [comment]
build now

**Pull request merged**
