### PR TITLE
DDF-3986 Fixing map-layers metatype path

### PR DESCRIPTION
**Pull request by Bdthomson**
#### What does this PR do?
- Fixes the path that the `admin-module` reducer gives when updating configuration for map layer calls.
- Adds `m2` script to package.json for installing module into `m2` for hot deploys.
- Fixes `GoldenLayout` require statement that was preventing `admin-layout` from loading.
#### Who is reviewing it? 

@AzGoalie 
@alanchampion 

#### Select relevant component teams: 
https://github.com/orgs/codice/teams
#### Ask 2 committers to review/merge the PR and tag them here.

@djblue 
@jlcsmith 

#### How should this be tested?

- Verify that you see the map layers configuration in `Admin UI > Catalog > Map Layers` and you can update the configuration without getting an error.
 
#### What are the relevant tickets?
[DDF-3986](https://codice.atlassian.net/browse/DDF-3986)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by jlcsmith** [comment]
build now

**Comment by andrewkfiedler** [comment]
Might be worth pulling that m2 command up to the ace package so each sub package has access, although a similar command might already exist.

**Comment by jlcsmith** [comment]
Hero successful - successfully saved map layers via the Admin Map Layer plugin

**Comment by Bdthomson** [comment]
build now

**Comment by djblue** [comment]
@andrewkfiedler the one issue with that is that not all ui projects build the same way

**Pull request merged**
