### PR TITLE
DDF-2189 [2.9.x]: Updated code to compare 2 metacards using attributes instead of using the hashcodes

### PR DESCRIPTION
**Pull request by lessarderic**
#### What does this PR do?
Back-port of https://github.com/codice/ddf/pull/966 to 2.9.x.
#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?
@shaundmorris 
@bdeining
#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@coyotesqrl
@pklinef
#### How should this be tested?
* Run the full suite of integration tests.
* Try download the same metacard resource twice and make sure no NPE is thrown and the resource downloads successfully.

#### Checklist:
- [ ] Documentation Updated
- [x] Update / Add Unit Tests
- [x] Update / Add Integration Tests

### CODE REVIEW

**Comment by coyotesqrl** [comment]
👍

**Comment by shaundmorris** [comment]
👍

**Comment by bdeining** [comment]
:+1:

**Comment by lessarderic** [comment]
Manually tested resource download using distribution built by Bamboo and everything looks good.

@coyotesqrl, you can merge this PR when you're ready.

**Pull request merged**
