### PR TITLE
[2.13.x]DDF-04838 Clarify that new workspaces inherit search filters

### PR DESCRIPTION
**Pull request by ahoffer**
#### What does this PR do?
Updates documentation to clarify Intrigue behavior.
#### Who is reviewing it? 
@brjeter  @austinsteffes @tyler30clemens 
#### Select relevant component teams: 
@codice/docs 
#### Ask 2 committers to review/merge the PR and tag them here.
@brjeter
@vinamartin

#### How should this be tested?
1. Build documentation
2. Open documentation.html
3. Inspect section "11.2.1. Creating a Workspace in Intrigue" for errors and fitness to purpose (see also attached screenshot)

#### What are the relevant tickets?
Fixes: #4838 

#### Screenshots
image

#### Checklist:
- [X] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by johnsliao** [comment]
Is it a good idea to put a screenshot in from a documentation-maintenance perspective? If the UI changes, then it might become outdated.

**Comment by tyler30clemens** [comment]
To me, it does seem like the image could be a bit of overkill if the note is being added as well, but if it is a very common misunderstanding, I believe the image is worth it. Although that is a good point, there are other examples of images for the UI that have the potential to need updating if they become outdated. Ideally when changes are made, the respective documentation would be updated along with those changes.

**Comment by ahoffer** [comment]
My personal opinion is that the image is helpful. As developers we use the term "filter" for both the "things that gets assembled from the query terms and the other meaning, "the thing that hides results in the UI". I chose to include an image to disambiguate the meanings.

**Comment by ahoffer** [comment]
build now

**Comment by tyler30clemens** [comment]
Hero Successful ✅

image

**Comment by johnsliao** [comment]
Sounds good 👍 . Thanks

**Pull request merged**
