### PR TITLE
[2.26.x] Add endpoint to test for the downloadability of a local resource

### PR DESCRIPTION
**Pull request by glenhein**
#### What does this PR do?

Add endpoint to test for the downloadability of a local resource.

#### How should this be tested?

Upload two local products. For one of the products, manually delete the resource file in data/content. 

Using the following CURL as a guide (adjust for you installation), try hitting the endpoint for
each product. The product that was manually delete should return a 404. For the other product, the endpoint should return a 200.

```
curl \
  --verbose \
  --get \
  --insecure "https://localhost:8993/services/catalog/doesExist/<metacardID>/<sourceID>"
``` 

#### What are the relevant tickets?
Fixes: #____

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by glenhein** [comment]
I think this has to be re-visited because it does not cover a use case for a downstream project.

**Comment by glenhein** [comment]
build now

**Comment by glenhein** [comment]
build now

**Review by jlcsmith — APPROVED** [review]

**Comment by glenhein** [comment]
build now

**Comment by glenhein** [comment]
build now

**Comment by glenhein** [comment]
build now

**Comment by jlcsmith** [comment]
Hero successful - verified endpoint works correctly for local and and non-local sources where content is and is not in the local content provider.

**Pull request merged**
