### PR TITLE
DDF-2509: Added Contributor License Agreement (CLA) badge to README

### PR DESCRIPTION
**Pull request by shaundmorris**
#### What does this PR do?
Adds a Contributor License Agreement (CLA) badge to the README
#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?
@andygoodson 

#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@kcwire
@lessarderic
@michaelmenousek

#### How should this be tested?
This PR does not involve any build/runtime code. To test it should ask on PRs to submit a CLA if one has not been submitted. 
#### Any background context you want to provide?
This is a process improvement as opposed to sending emails for CLAs
#### What are the relevant tickets?
DDF-2509
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by lessarderic** [comment]
Created PR https://github.com/codice/ddf/pull/1310 and made sure license/cla check showed up.

:shipit:

**Comment by shaundmorris** [comment]
Build was successful, just a change to the README.md file

**Comment by bdeining** [comment]
Do we also need this in Alliance?

**Comment by shaundmorris** [comment]
@bdeining good question. It would make sense to have in Alliance as well since it would be the same CLA and it is easy to check during PR reviews.

**Pull request merged**
