### PR TITLE
DDF-3668 Resolved maven build warnings

### PR DESCRIPTION
**Pull request by idperez**
#### What does this PR do?
The current nightly builds of DDF contain various warnings. These warnings may lead to build instability. This PR addresses them.

All of the warnings are either dependencies with missing versions or duplications in the same pom.
#### Who is reviewing it? 
@brjeter @bakejeyner @blen-desta 
#### Choose 2 committers to review/merge the PR. 
@coyotesqrl
@shaundmorris 
#### Any background context you want to provide?
Maven warnings can be seen in the latest DDF nightly builds https://jenkins.phx.connexta.com/job/DDF-Jobs/job/master/job/Linux/
#### What are the relevant tickets?
[DDF-3668](https://codice.atlassian.net/browse/)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by idperez** [comment]
build now

**Comment by oconnormi** [comment]
Just as an fyi, this is the same failure we are seeing on many other prs against master. while it says that the cause was "coverage checks not met" it is actually due to something happening during the tests for `spatial-wfs-v1_0_0-source` which is causing the jvm to exit

```19:29:25 Process Exit Code: 0
19:29:25 Crashed tests:
19:29:25 org.codice.ddf.spatial.ogc.wfs.v110.catalog.source.WfsSourceTest
19:29:25 org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
19:29:25 Command was /bin/sh -c cd /jenkins/workspace/DDF-Jobs/pr/Linux/catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source && /jenkins/tools/hudson.model.JDK/jdk8-latest/jre/bin/java -javaagent:/root/.m2/repository/org/jacoco/org.jacoco.agent/0.8.0/org.jacoco.agent-0.8.0-runtime.jar=destfile=/jenkins/workspace/DDF-Jobs/pr/Linux/catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/target/jacoco.exec -Djava.awt.headless=true -noverify -jar /jenkins/workspace/DDF-Jobs/pr/Linux/catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/target/surefire/surefirebooter8977271846662282661.jar /jenkins/workspace/DDF-Jobs/pr/Linux/catalog/spatial/wfs/1.1.0/spatial-wfs-v1_1_0-source/target/surefire 2018-03-12T18-28-45_806-jvmRun1 surefire3438476175099395418tmp surefire_1468967471302834833120tmp
19:29:25 Process Exit Code: 0
19:29:25 Crashed tests:
19:29:25 org.codice.ddf.spatial.ogc.wfs.v110.catalog.source.WfsSourceTest
19:29:25 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:679)
19:29:25 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
19:29:25 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:279)
19:29:26 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:243)
19:29:26 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1077)
19:29:26 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:907)
19:29:26 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:785)
19:29:26 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
19:29:26 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
19:29:26 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
19:29:26 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
19:29:26 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
19:29:26 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
19:29:26 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
19:29:26 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
19:29:26 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
19:29:26 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
19:29:26 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
19:29:26 	at org.jvnet.hudson.maven3.launcher.Maven33Launcher.main(Maven33Launcher.java:129)
19:29:26 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
19:29:26 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
19:29:26 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19:29:26 	at java.lang.reflect.Method.invoke(Method.java:498)
19:29:26 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
19:29:26 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
19:29:26 	at jenkins.maven3.agent.Maven33Main.launch(Maven33Main.java:176)
19:29:26 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
19:29:26 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
19:29:26 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19:29:26 	at java.lang.reflect.Method.invoke(Method.java:498)
19:29:26 	at hudson.maven.Maven3Builder.call(Maven3Builder.java:139)
19:29:26 	at hudson.maven.Maven3Builder.call(Maven3Builder.java:70)
19:29:26 	at hudson.remoting.UserRequest.perform(UserRequest.java:207)
19:29:26 	at hudson.remoting.UserRequest.perform(UserRequest.java:53)
19:29:26 	at hudson.remoting.Request$2.run(Request.java:358)
19:29:26 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
19:29:26 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
19:29:26 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
19:29:26 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)```

**Comment by idperez** [comment]
build now

**Comment by idperez** [comment]
build now

**Comment by coyotesqrl** [comment]
build now

**Comment by idperez** [comment]
build now

**Pull request merged**
