### PR TITLE
DDF-2867 moved documentation out of 'documentation' profile

### PR DESCRIPTION
**Pull request by ricklarsen**
#### What does this PR do?

Eliminates the documentation profile from the `distribution/docs` and `distribution/ddf` pom.xml files. 

#### Who is reviewing it?

@mcalcote @vinamartin @Lambeaux @jrnorth @oconnormi 

#### Select at least one member from relevant component team(s) from below.

[Build](https://github.com/orgs/codice/teams/build)
[Docs](https://github.com/orgs/codice/teams/docs)

#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).

@coyotesqrl
@figliold
@lessarderic
@pklinef
@shaundmorris

#### How should this be tested? (List steps with links to updated documentation)

- Run `mvn clean` from top level directory (optional, but helps confirm whether module is running or not.)
- build on a clean repo with the command `mvn clean install -pl \!distribution/docs`. Expected results: no `target` directory created in distribution/docs module; download of previous snapshot artifacts into repository for `ddf/docs`
- unzip distribution zip. The `documentation` directory should have a full set of documentation html and pdf. Open the `documentation.html` file, scroll to the very bottom of the page and check the _last updated_ date.
- build again without the `-pl` flag. (`mvn clean install`). Expected results: target directory created in `distribution/docs` with complete artifacts, newly built artifacts in the repository.

#### Any background context you want to provide?

"Skipping" documentation by disabling the profile still causes an incomplete selection of artifacts to be generated, which can cause unexpected behavior if: a) a following build does not 'clean', b) during incremental builds. 

#### What are the relevant tickets?
[DDF-2867](https://codice.atlassian.net/browse/DDF-2867)
#### Screenshots (if appropriate)
n/a
#### Checklist:
- [x] Documentation Updated - kinda?
- [ ] Change Log Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by vinamartin** [comment]
Make sure to update the README which references the documentation profile

**Comment by Lambeaux** [comment]
Hero'd and works as expected 👍

**Comment by ricklarsen** [comment]
test this please

**Comment by vinamartin** [comment]
Manually verified.

**Pull request merged**
