### PR TITLE
DDF-1702 Fixed CSS inconsistencies in catalog-admin-module-sources

### PR DESCRIPTION
**Pull request by bdeining**
@shane-voisard 
@kcwire
@millerw8 is hero

Screenshots :  https://codice.atlassian.net/browse/DDF-1702

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/codice/ddf/pull/374" target="_blank">ReviewNinja

**Comment by stustison** [comment]
Can you please do this same change to ddf/platform/admin/ui/src/main/webapp/templates/configuration/configurationItem.handlebars so that they stay in sync.

**Comment by bdeining** [comment]
Added the same change to ddf/platform/admin/ui/src/main/webapp/templates/configuration/configurationItem.handlebars

**Comment by stustison** [comment]
:+1:

**Comment by millerw8** [comment]
pulled down built and verified changes appropriately address the issue.

**Pull request merged**
