### PR TITLE
DDF-3874 Update master to next development version

### PR DESCRIPTION
**Pull request by clockard**
#### What does this PR do?
What the title says
#### Who is reviewing it? 

@coyotesqrl
@lessarderic
@shaundmorris

#### What are the relevant tickets?
[DDF-3874](https://codice.atlassian.net/browse/DDF-3874)

### CODE REVIEW

**Comment by clockard** [comment]
build now

**Comment by shaundmorris** [comment]
Since we have `-pl !distribution/docs` this PR build will fail right? We would have to manually deploy that for the first time or something like that since there won't be a 2.13-SNAPSHOT version of the docs.

**Comment by clockard** [comment]
I think you are correct @shaundmorris.

**Comment by clockard** [comment]
@shaundmorris I am going to bypass the CI build so this can be merged. We need to make sure this gets in right away.

**Pull request merged**
