### PR TITLE
DDF-1329: Remove unused DDF maven profiles

### PR DESCRIPTION
**Pull request by tbatie**
- Removed ddf-release profile

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/68)

### CODE REVIEW

**Comment by tbatie** [comment]
@roelens8 @lessarderic @coyotesqrl

**Comment by coyotesqrl** [comment]
:+1:

**Comment by lessarderic** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/68)

**Comment by roelens8** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/68)

**Comment by roelens8** [comment]
Was able to build DDF successfully. Looks good.

**Pull request merged**
