### PR TITLE
DDF-1192: Temporarily added OWASP exclusions since pom doesn't use the right ddf-parent version.

### PR DESCRIPTION
**Pull request by lessarderic**
@shaundmorris, @pklinef

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/36)

### CODE REVIEW

**Comment by shaundmorris** [comment]
Review status: all files reviewed, all discussions resolved, some commit checks pending.
Reviewed files:
- distribution/pom.xml @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/36)

**Comment by pklinef** [comment]
Rebase your branch to remove the merge commit.

**Comment by pklinef** [comment]
:+1:

**Comment by lessarderic** [comment]
@pklinef: Giving up on removing commit messages from the history until you give Git training :-)

**Comment by shaundmorris** [comment]
I merged manually. Did it slightly off but was able to rebase into a single commit using https://github.com/tj/git-extras/blob/master/Commands.md#git-squash.

**Pull request closed without merging**
