### PR TITLE
DDF-3301 Publicize constants in FacetProperties.

### PR DESCRIPTION
**Pull request by Variadicism**
#### What does this PR do?
This change publicizes some constants in `FacetProperties` for faceted queries. (See [DDF-3301](https://codice.atlassian.net/browse/DDF-3301)).
#### Who is reviewing it?
@adimka 
@mackncheesiest 
@glenhein 
@mojogitoverhere 
#### Select relevant component teams:
https://github.com/orgs/codice/teams
#### Choose 2 committers to review/merge the PR.
@bdeining 
@millerw8 
#### How should this be tested?
Build the DDF module `catalog/core/catalog-core-api-impl`. (A full DDF build works, too.)
#### What are the relevant tickets?
[DDF-3301](https://codice.atlassian.net/browse/DDF-3301)
#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by Variadicism** [comment]
Those would be questions for @adimka. They're outside the scope of this little fix.

**Comment by adimka** [comment]
We're not required to mark anything that's not in the API as experimental.
I have no problem doing so, if we feel it'd be helpful in some way.

**Comment by adimka** [comment]
build now

**Comment by Variadicism** [comment]
From what I can tell by looking at other classes, usually it's the class itself that is marked as experimental, not values within the class. My ticket and goal is to modify these constants; notations on the class at large seem outside the scope of the ticket "Publicize constants in FacetProperties". Additionally, other classes in the same package are not marked as such, which means that marking this class would be inconsistent behavior. If we're concerned about marking these as experimental, there should be a separate ticket and another pull request to add experimental warnings to all the similarly unmarked classes.

**Comment by mackncheesiest** [comment]
Looks like we will need to do some rebasing because of the code reformatting though

**Comment by Variadicism** [comment]
@mackncheesiest Done!

**Comment by Variadicism** [comment]
build now

**Pull request merged**
