### PR TITLE
DDF-2172 Change repositories to https

### PR DESCRIPTION
**Pull request by harrison-tarr**
#### What does this PR do?
Makes maven downloads go through https instead of http
#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?
@ahoffer @spearskw @tbatie 
#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@jaymcnallie
@stustison 
#### What are the relevant tickets?
DDF-2172
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by shaundmorris** [comment]
@harrison-tarr I believe those Codice repositories are residual from when these modules were separate git repositories. If they have tree up to the root pom they will inherit the repositories. Meaning you should just be able to remove them.

**Comment by spearskw** [comment]
:+1:

**Comment by shaundmorris** [comment]
@harrison-tarr thanks for removing the unnecessary Codice Repository declarations. Did anybody notice any performance impacts on the speed of the build?

**Comment by harrison-tarr** [comment]
The build is slower, don't think it was too much slower

**Comment by ahoffer** [comment]
👍

**Comment by stustison** [comment]
👍

**Comment by shaundmorris** [comment]
The bamboo build was success but has a failure state due to GC OOM.

**Comment by bcwaters** [comment]
Successfully hero'd this PR

**Comment by shaundmorris** [comment]
@harrison-tarr this PR has merge conflicts now that need to be resolved :-(

**Pull request merged**
