### PR TITLE
DDF-3739 switched to using the karaf-maven-plugin

### PR DESCRIPTION
**Pull request by oconnormi**
#### What does this PR do?
Potential alternate approach for #3170 
Further changes related to #3164 and #2896 

* Moves all `.cfg` and `.config` files from each feature into the module for the bundle each belongs to. This is to avoid an issue that occurs during the integration-test phase where those files haven't yet been installed in the local repo.
* Moves to using the karaf-maven-plugin to generate and verify features files

#### Who is reviewing it? 
@mackncheesiest
@emanns95 
@tbatie
@Lambeaux
@ryeats

#### Select relevant component teams: 
@codice/test 
@codice/build 
#### Choose 2 committers to review/merge the PR. 

@rzwiefel
@figliold
@pklinef

#### How should this be tested? (List steps with links to updated documentation)

Full CI Build

#### What are the relevant tickets?

[DDF-3739](https://codice.atlassian.net/browse/DDF-3739)

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by oconnormi** [comment]
Just gonna see what happens 🤞 
Build Now

**Comment by oconnormi** [comment]
Added testResources to ensure `features.xml` and `dependencies.properties` are both in the test container's classpath

**Comment by oconnormi** [comment]
Build Now

**Comment by oconnormi** [comment]
Fixed bad dependency on non-existent jar
Build Now

**Comment by oconnormi** [comment]
Accidentally removed the `configfile` references for solr, added back in.

Build Now

**Comment by oconnormi** [comment]
fixed a features file I missed when renaming them to feature.xml for use by karaf-maven-plugin

Build Now

**Comment by oconnormi** [comment]
One last time, to check the most recent changes

Build Now

**Comment by mackncheesiest** [comment]
Network error while fetching a ddf-support artifact. Trying again.

build now

**Pull request merged**
