### PR TITLE
DDF-1524 Replace configurations values with system properties

### PR DESCRIPTION
**Pull request by clockard**
- Added new PropertyResolver that replaces system property variables in strings
 - Replaced hardcoded blueprint values (like urls) with system property variables
 - Replaced hardcoded metatype values with system property varialbes
 - Updated PropertiesLoader to do system property variable replacement
 - Updated all places that load property files to use the PropertiesLoader

@pklinef @stustison @ricklarsen @AzGoalie 

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/248)

### CODE REVIEW

**Comment by AzGoalie** [comment]
prbs built and passed tests
:+1:

**Comment by stustison** [comment]
An interesting test with this would be to change the port or hostname and see if you can start up DDF. That was, ultimately, the point of doing all this work.

**Comment by clockard** [comment]
I have tested changing the ports and and that works. Changing the host still requires you to update your certs which will be done via the installer once DDF-1525 is finished. I have manually changed the certs  and tested the host name change and that works as well.

**Comment by stustison** [comment]
:+1:

**Comment by ricklarsen** [comment]
Reviewed 82 of 82 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/248)

**Comment by ricklarsen** [comment]
:+1:

**Pull request merged**
