### PR TITLE
DDF-2134 Moves /cometd context beneath the /search context, to /search/cometd

### PR DESCRIPTION
**Pull request by coyotesqrl**
#### What does this PR do?
Moves the `/cometd` context.

#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?
@tbatie @ryeats 

#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@kcwire
@pklinef

#### How should this be tested?
Full build and itests; install and ingest; ensure that search UI works correctly.

#### Any background context you want to provide?
Currently, the webcontext policy for the `/search` and `/cometd` contexts must be kept in lockstep. As there is no reason for the `/cometd` context to be directly beneath the root, this move will simplify security configuration for our users.

#### What are the relevant tickets?
DDF-2134

#### Screenshots (if appropriate)
N/A

#### Checklist:
- [X] Documentation Updated
- [X] Update / Add Unit Tests
- [X] Update / Add Integration Tests

### CODE REVIEW

**Comment by pklinef** [comment]
:+1:

**Comment by bradh** [comment]
Since this is an API break for a [documented interface](https://codice.atlassian.net/wiki/display/DDF27x/Using+the+CometD+Endpoint+for+Asynchronous+Communication), it probably needs a transition strategy and perhaps a DDF 3.0 release.

**Comment by kcwire** [comment]
@bradh the API hasn't changed, just the path that it is accessed from.  I don't think this requires a major release.

**Comment by kcwire** [comment]
👍

**Comment by bradh** [comment]
I still think the change breaks client code, which should not happen in a minor release.

**Comment by pklinef** [comment]
Generally we have not required a major version change for moving context paths.  The current documentation does not give the context path, just the format of the messages.  We should add a note about this change on the DDF 2.10 release page so developers know to update their clients to the new location.

**Comment by roelens8** [comment]
👍  Hero'd.

**Comment by mrmateo** [comment]
@pklinef - the current documentation _does_ give the context path:
http://codice.org/ddf/integrating.html
```
1.5.4. Integrating with the Asynchronous Capabilities Endpoint
The following section shows examples of integration. 
The channels are used for clients to subscribe, followed by examples of request and responses. 
There is only one endpoint hosted at <DDF_IP>:<DDF_PORT_NUMBER>/cometd
```

Was there another part of the documentation you were looking at? This was the main section I found that contains information about the cometd endpoint.

I would agree with @bradh , as this is a documented API/endpoint. I'm genuinely curious, what were some of the other context paths that have been changed in a minor version?

**Comment by stustison** [comment]
@bradh @mrmateo This context path is actually causing a security configuration issue. The fact is that a lot of people are configuring security for the search ui incorrectly because they aren't aware that they need to also configure /cometd. Because this is actually causing security issues, I'd say that trumps any client backwards compatibility issues.

**Comment by pklinef** [comment]
@mrmateo I did a quick Github search and it failed to find that line.  I should have just looked again at Richard's changes in this PR since he changed that line in the documentation.  https://github.com/codice/ddf/search?l=asciidoc&q=%2Fcometd&utf8=%E2%9C%93

We have changed mbeans which will change the Jolokia context path but I do not think we document that as a context path for integration.  Context paths provided by Karaf and other upstream projects can also change from upstream version upgrades but integrators should not be using those either.  CometD is different from those examples since it is documented for system to system and system to browser integration.

My assumption is that clients should not only be configurable for host and port but also for the context path of the API.  That is how all of the out of the box sources work already for this reason.  The API is the message format which we should not change in a backwards incompatible way in a minor version.  The root context path of the API should not be considered part of the API.  

We could investigate if the proxy route could be used to make an alias from the old path to the new path in the case that a client has hard coded the full context path for some reason.  I think we would need to make our proxy routes able to proxy single sign on information if the target is to the same domain.

**Comment by bradh** [comment]
In an ideal world, the solution to a breaking API change (which it is, although we can argue about how "big" the API change is) is to increase major version. I recognise that this might not be desirable though.

I think the compromise is to provide advance notice to anyone who is known to be using the endpoint (even in a DDF-only scenario, where backends and front-ends don't always match for version), and to make explicit mention of this in the release notes.

**Comment by mrmateo** [comment]
Thanks for the background and explanations @stustison and @pklinef . Sounds good to me.

**Comment by coyotesqrl** [comment]
While it is outside the scope of this work, it should be possible to either create a Jetty rewrite rule to automatically redirect references to `/cometd` to `/search/cometd` or to create a Camel route to proxy requests.

If any clients have been written that have hard coded references to the current path, we can create a sample in the SDK module for the Camel proxy solution.

**Comment by pklinef** [comment]
@coyotesqrl Please start a 2.10 release page under https://codice.atlassian.net/wiki/display/DDF/DDF+Documentation and add a note about the cometd path change.

**Pull request merged**
