### PR TITLE
DDF-3838 Updates lowBandwidth param for router changes

### PR DESCRIPTION
**Pull request by mackncheesiest**
#### What does this PR do?
Somewhere along the line, either #3326 or #3357 made it so that attempting to use Intrigue with the `?lowBandwidth` URL param caused it to fail to load because of a listener that was firing due to the `router.set({lowBandwidth: ...})` event happening before router initialization was complete.

Rather than move this assignment to [the updateRoute](https://github.com/codice/ddf/blob/995e80b248a0f0369720dd1bcc27482aeb0db780/ui/packages/catalog-ui-search/src/main/webapp/js/router.js#L93-L97) method which is presumably called after all the necessary router information is extracted, this PR sets the parameter in the `defaults` object of the `router.js`.

I did this because, once set, that parameter will never change without triggering a full page refresh and/or navigation. It's not intended to be dynamic like the rest of the router model values. I'd be fine with moving it somewhere different if people disagree, though.

#### Who is reviewing it? 
(please choose AT LEAST two reviewers that need to approve the PR before it can get merged)
@adimka @middlets719 @djblue 

#### Select relevant component teams: 
https://github.com/orgs/codice/teams
#### Ask 2 committers to review/merge the PR and tag them here. If you don't know who to ask, you can request reviews in https://groups.google.com/forum/#!forum/ddf-developers .
(please choose ONLY two committers from below, delete the rest)
@andrewkfiedler
@millerw8

#### How should this be tested? (List steps with links to updated documentation)
- Verify that the UI loads when given the lowBandwidth parameter (i.e. `https://localhost:8993/search/catalog?lowBandwidth`)
- Verify that the 2D and 3D maps present confirmation dialogues before loading when that parameter is present

#### What are the relevant tickets?
[DDF-3838](https://codice.atlassian.net/browse/DDF-3838)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by mackncheesiest** [comment]
build now

**Comment by LinkMJB** [comment]
build now

**Comment by mackncheesiest** [comment]
build now

**Comment by middlets719** [comment]
Starting Hero

**Comment by middlets719** [comment]
Hero passed.  
Tested on chrome&firefox with admin&guest users.
Verified 2D and 3D maps present confirmation dialogues before loading.  
Verified that selecting confirmation will display the map.  
Navigated to multiple screen and verified ?lowBandwidth persisted 
Performed spot checking without ?lowBandwidth option enabled

**Pull request merged**
