### PR TITLE
[2.20.x] DDF-5888 Checkbox performance improvements

### PR DESCRIPTION
**Pull request by stevenmalmgren**
#### What does this PR do?
Updates checkboxes to React so they don't have to render for each result card in the results view.
#### What are the relevant tickets?
Fixes: #5888

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by jlcsmith** [comment]
Please add issue number to the PR/commit

**Comment by stevenmalmgren** [comment]
build now

**Comment by stevenmalmgren** [comment]
build now

**Comment by jlcsmith** [comment]
@stevenmalmgren  - can you update the commits with an issue #?

**Comment by jlcsmith** [comment]
Hero successful - Verified no regressions or observable performance issues with result list view

**Pull request merged**
