### PR TITLE
DDF-3986 Adding config to features and pom

### PR DESCRIPTION
**Pull request by Bdthomson**
#### What does this PR do?
- Adds new config files to features and pom file to enable them on startup. This was missed in https://github.com/codice/ddf/pull/3467
#### Who is reviewing it? 

@Schachte 
@brianfelix 
#### Select relevant component teams: 
https://github.com/orgs/codice/teams
#### Ask 2 committers to review/merge the PR and tag them here.

@andrewkfiedler 
@bdeining 

#### How should this be tested?

Ensure that on startup in Admin UI > Search UI you see all the new configs filled out (have a config section filled out that you can delete). Before the values would be filled out but you would have to hit save for them to trigger.
#### What are the relevant tickets?
[](https://codice.atlassian.net/browse/)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by Bdthomson** [comment]
build now

**Comment by Bdthomson** [comment]
build now

**Comment by GabrielFabian** [comment]
hero build in progress

**Comment by GabrielFabian** [comment]
Hero build successful 🎉 
LGTM.

Build DDF. 
profile:install standard
admin configs were set as shown below by default

screen shot 2018-08-22 at 10 08 39 am

**Pull request merged**
