### PR TITLE
DDF-1644 Updated checkstyle plugin version for java 8 support and fixed resulting checkstyle errors.

### PR DESCRIPTION
**Pull request by clockard**
@vinamartin @ricklarsen @djblue

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/327)

### CODE REVIEW

**Comment by vinamartin** [comment]
lgtm :+1:

**Comment by ricklarsen** [comment]
lgtm

**Comment by djblue** [comment]
:+1:

**Comment by oscaritoro** [comment]
lgtm :+1:

**Comment by shaundmorris** [comment]
:+1:  I was able to confirm a successful build (including no checkstyle errors)

**Pull request merged**
