### PR TITLE
DDF-04998 Limit Filter Attribute Depth on Search Form Reloading

### PR DESCRIPTION
**Pull request by bennuttle**
#### What does this PR do?
Prevent a deeply nested structure representing a filter's attributes in Search Forms. This remedies an issue where the form fails to load after a few successive reloads.
#### Who is reviewing it? 
@djblue 
@adimka 
@jrnorth 
@gjvera 
@BernardIgiri 
@leo-sakh 

#### Select relevant component teams: 
@codice/ui

#### Ask 2 committers to review/merge the PR and tag them here.
@adimka 
@bdeining 

#### How should this be tested?
1. Create a search form with a geography-based filter (`location` or `anyGeo` for example).
2. Draw an arbitrary shape on the map, save the form.
3. Navigate back to the 'Search Forms' view and re-load the form repeatedly.
4. Verify that the form continues to populate all fields appropriately.
5. Ensure other uses of search forms (workspace ad-hoc search) still work as intended.

#### What are the relevant tickets?
Fixes: #4998 

#### Screenshots
**Before**
Screen Shot 2019-06-19 at 4 07 01 PM
**After**
Screen Shot 2019-06-19 at 4 05 58 PM

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by jrnorth** [comment]
I'll hero this.

**Comment by jrnorth** [comment]
build now

**Comment by bennuttle** [comment]
build now

**Comment by jrnorth** [comment]
Connection failure.
build now

**Comment by jrnorth** [comment]
build now

**Comment by djblue** [comment]
### Local hero successful :tada: 
- `yarn install`
- `yarn test`
- `yarn start`
- verified by creating a search form with a polygon and point radius

**Pull request merged**
