### PR TITLE
DDF-1655 Added spatial-geocoding-admin-module dependency to spatial app

### PR DESCRIPTION
**Pull request by bdeining**
@pklinef 
@kcwire 
@jaymcnallie

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/codice/ddf/pull/442" target="_blank">ReviewNinja

**Comment by jlcsmith** [comment]
:+1:

**Comment by harrison-tarr** [comment]
:+1:

**Comment by jaymcnallie** [comment]
!star

**Pull request merged**
