### PR TITLE
[2.18.x] DDF-5513 Fix anyGeo bounding box not updating correctly

### PR DESCRIPTION
**Pull request by zta6**
#### What does this PR do?
Fixes a bug where updating a bounding box in an anyGeo search didn't the bounding box in the query. 

#### Who is reviewing it? 

@andrewzimmer 
@willwill96 
@hayleynorton 

#### Select relevant component teams: 
@codice/ui 

#### Ask 2 committers to review/merge the PR and tag them here.
@bdeining
@bdthomson

#### How should this be tested?

1. Ingest multiple pieces of data with location information. 
2. Create an anyGeo bounding box search that will return some of the ingested data
3. Run the search
4. Edit the search, draw a new bounding box that should return a different piece of data
5. re-run the search
6. verify that the search returns results within the new, updated bounding box.
7. Test anyGeo querying with other geo types and make sure they still function correctly. 
8. Test some basic AOI functionality with bounding boxes and make sure that they still function correctly. 

#### What are the relevant tickets?
Fixes: #5513 

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by zta6** [comment]
build now

**Comment by zta6** [comment]
build now

**Comment by zta6** [comment]
build now

**Comment by bdeining** [comment]
Hero Successful 🎉

verified cannot reproduce error
verified after editing search geo, correct results are returned

**Pull request merged**
