### PR TITLE
DDF-5178 Migrated map drawing library to DDF.

### PR DESCRIPTION
**Pull request by BernardIgiri**
#### What does this PR do?
Moves map drawing library to DDF.
#### Who is reviewing it? 
@jrnorth @samuelechu @bakejeyner 
#### Select relevant component teams: 
@codice/ui 
#### Ask 2 committers to review/merge the PR and tag them here.
@AzGoalie
@djblue

#### How should this be tested?
Run `yarn storybook` from `ui/packages/catalog-ui-search`
And inspect all of the components in the `map-drawing` folder.
Verify that all of the controls work.
Run `yarn test` from `ui/packages/catalog-ui-search`

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by rymach** [comment]
will this new drawing interface show up in the ddf ui?

**Comment by jrnorth** [comment]
All header comments need to be updated to the Codice header.

**Comment by vinamartin** [comment]
Is it possible to provide some documentation/diagrams for how this code works?

**Comment by BernardIgiri** [comment]
@vinamartin I added storybook stories add a [readme.md](https://github.com/codice/ddf/blob/817abb9faa4f6aafce97452d0c4cd6664416f396/ui/packages/catalog-ui-search/src/main/webapp/map-drawing/readme.md) file. You can see the stories by running `yarn storybook` from the `ui/packages/catalog-ui-search` folder.

**Comment by andrewkfiedler** [comment]
Could we move part or all of this into a standalone library?

**Comment by BernardIgiri** [comment]
> Could we move part or all of this into a standalone library?

@andrewkfiedler I'm open to that idea. Although it is not completely independent of our code base. It does rely heavily on styled components for the React parts for example.

**Pull request closed without merging**
