### PR TITLE
DDF-5136 Remove sign in for Guest users

### PR DESCRIPTION
**Pull request by blen-desta**
#### What does this PR do?
The only configuration that will allow guest access is:
1. `/=` with `Allow Guest Access` checked
2. `/=PKI` with `Allow Guest Access` checked

The other authentication types: `BASIC`, `OIDC` and `SAML` are terminating and don't allow guest access.

If `/=PKI` is configured the only solution is to close and reopen the browser.
If Guest access is the only one configured, there isn't a way to log in so we'll show:

Screen Shot 2019-07-30 at 10 38 20 AM
Screen Shot 2019-07-30 at 10 38 29 AM

#### Who is reviewing it? 
@bakejeyner 
@SmithJosh 

#### Select relevant component teams: 
@codice/security 

#### Ask 2 committers to review/merge the PR and tag them here.
@djblue 
@stustison 

#### How should this be tested?
Verify guest user behavior:
1. Change the authentication type to `/=` and check `Allow Guest Access`
2. Go to Intrigue, you should see `Guest` instead of `Sign In` in the top right corner
3. When clicking `Guest` you should not see a `Sign Out` button

Verify logged in user behavior:
1. Configure `SAML`, `OIDC`, and/or `BASIC` as the auth type
2. Go to Intrigue and log in, you should see your username in the top right corner
3. When clicking the username you should see the user's email and a `Sign Out` button

#### What are the relevant tickets?
Fixes: https://github.com/codice/ddf/issues/5136

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by blen-desta** [comment]
@SmithJosh `OIDC` and `SAML` don't allow guest access right so the only way you can see that login page is if you had just Guest configured. I'll look into it some more and see.

**Comment by SmithJosh** [comment]
@blen-desta Ah, ok. If only guest access is allowed, imo it seems wrong to allow users to sign-in at all.

**Comment by blen-desta** [comment]
build now

**Comment by garrettfreibott** [comment]
Hero'd :+1:

**Pull request merged**
