### PR TITLE
DDF-2167 Removed refs to DdfConfigurationWatcher from docs

### PR DESCRIPTION
**Pull request by ricklarsen**
#### What does this PR do?

Removed refs to deprecated DdfConfigurationWatcher from docs.

#### Who is reviewing it?

@bdeining @spearskw @jrnorth @mcalcote @Lambeaux 
#### Choose 2 committers to review/merge the PR.

@lessarderic
@shaundmorris

#### How should this be tested?
Documentation doesn't break build and renders correctly

#### What are the relevant tickets?
DDF-2167
https://codice.atlassian.net/browse/DDF-2167

#### Checklist:
- [x] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by shaundmorris** [comment]
👍  I only found references to DdfConfigurationWatcher in catalog/integrating, catalog/extending, and security/integrating

**Comment by ricklarsen** [comment]
@shaundmorris I think some of them had been removed by others since this ticket was created.

**Comment by bdeining** [comment]
:+1:

**Comment by spearskw** [comment]
👍

**Pull request merged**
