### PR TITLE
[2.19.x] DDF-5505 Allow editing of DMS Decimals

### PR DESCRIPTION
**Pull request by zta6**
#### What does this PR do?
Allows for the editing/manual entry of DMS decimals. 
Allows three places of decimal precision, which is equivalent to the 6 digits of precision that we along in the Decimal Degrees format. 

#### Who is reviewing it? 
@andrewzimmer 
@hayleynorton 

#### Select relevant component teams: 
@codice/ui 

#### Ask 2 committers to review/merge the PR and tag them here.
@bdeining
@djblue
#### How should this be tested?

Verify that when performing an anyGeo search with a Bounding Box or Pt. Rad geo you are able to manually enter decimals in the DMS coordinate input boxes. Also verify that converting back and forth between DMS and other coordinate formats works properly. Verify that there is never more than 3 digits of decimal precision displayed to the user.

#### What are the relevant tickets?
Fixes: #5505 

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by zta6** [comment]
build now

**Comment by zta6** [comment]
build now

**Comment by zta6** [comment]
build now

**Comment by zta6** [comment]
build now

**Comment by zta6** [comment]
build now

**Comment by bdeining** [comment]
heroing

**Comment by bdeining** [comment]
looks good

**Pull request merged**
