### PR TITLE
DDF-3103 Upgrade JavaScript packages to latest bug-fix versions

### PR DESCRIPTION
**Pull request by albany551**
#### What does this PR do?

- Upgrades the following javascript packages to the latest versions:
  - bootstrap
  - cesium
  - eonasdan-bootstrap-datetimepicker
  - jquery
  - jquery-ui
  - moment
  - q

- Removes the dependency on the full lodash package by letting the Backbone ecosystem use actual underscore, not lodash as a substitute.
  - adds latest lodash.merge for the single usage of that method (which is not in underscore)

#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged)?
@andrewkfiedler
@djblue

#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@andrewkfiedler
@pklinef

#### How should this be tested? (List steps with links to updated documentation)
- Manual regression test of major features

#### What are the relevant tickets?
[](https://codice.atlassian.net/browse/DDF-3103)

#### Checklist:
- [ ] Documentation Updated
- [ ] Change Log Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by bdeining** [comment]
build now

**Comment by bdeining** [comment]
Successfully hero'd and tested the following features: 

- Admin UI Plugins
- Metatypes
- Intrigue

1. Metacard Edit (single)
2. Metacard Edit (bulk)
3. Clustering
4. Histograms
5. 2D map
6. 3D map
7. login / logout
8. upload
9. workspace save
10. workspace rename
11. workspace cloning
12. UI notifications
13. Associations - Local
14. Archive
15. Restore
16. Display names
17. Hidden attributes
18. Basic Search - keyword
19. Basic Search - temporal
20. Basic Search - geospatial
21. Basic Search - datatype
22. Search federation 
23. Filtering
24. Advanced Search
25. Search Status
26. Download - single
27. Download - multi
28. Results Preview Attributes
29. Page Size
30. Allow Editing

**Comment by andrewkfiedler** [comment]
Okay, I figured it out.  We're using `_.debounce` in a few places under the impression that it's `lodash.debounce`.

**Comment by bdeining** [comment]
build now

**Pull request merged**
