### PR TITLE
DDF-1930: Fixed branding logos which weren't being read from fragment bundles

### PR DESCRIPTION
**Pull request by millerw8**
Changed getEntry to getResource because getEntry is not finding resources in the bundle fragments since karaf 4.0.4 upgrade

### CODE REVIEW

**Comment by millerw8** [comment]
@jrnorth @shane-voisard @kcwire @jaymcnallie

**Comment by kcwire** [comment]
LGTM. - I'll checkout the distro as soon as bamboo is done.

**Comment by jrnorth** [comment]
:+1:

**Comment by coyotesqrl** [comment]
:+1:

**Pull request merged**
