### PR TITLE
DDF-3996 updating default.policy to give admin-core-jolokia read access to the schematron validator

### PR DESCRIPTION
**Pull request by Kjames5269**
#### What does this PR do?
Allows jolokia read access to <DDF_HOME>/etc/ddf.services.schematron.SchematronValidationService-SchematronValidators.ddms20.validation.config
#### Who is reviewing it? 
@bakejeyner 
@ahoffer 
#### Select relevant component teams: 
https://github.com/orgs/codice/teams
#### Ask 2 committers to review/merge the PR and tag them here.

@clockard
@coyotesqrl 
#### How should this be tested?
Step 1 Install DDF
After installing run `chmod -R 750 etc`
start DDF
https://localhost:8993/admin/?dev=true
install the standard profile.

It should install successfully with no read permission errors from 
```<DDF_HOME>/etc/ddf.services.schematron.SchematronValidationService-SchematronValidators.ddms20.validation.config```

#### What are the relevant tickets?
[DDF-3996](https://codice.atlassian.net/browse/DDF-3996)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by shaundmorris** [comment]
❓ I'm a little confused does this configuration exist in DDF?

**Comment by bakejeyner** [comment]
@shaundmorris I'm not sure what you mean by "configuration". This PR only updates the `default.policy` file to give jolokia needed permissions during installation.

**Comment by bakejeyner** [comment]
build now

**Comment by shaundmorris** [comment]
Ah okay thanks @bakejeyner , for some reason I didn't think ddf.services.schematron.SchematronValidationService-SchematronValidators.ddms20.validation.config was in DDF but maybe I am missing it.

**Comment by clockard** [comment]
@shaundmorris is correct. I just glossed over that part. This permission should be added to the downstream projects policy and not ddf

**Comment by bakejeyner** [comment]
@shaundmorris @clockard great catch!

**Comment by bakejeyner** [comment]
Closed because moving fix to upstream project.

**Pull request closed without merging**
