### PR TITLE
DDF-2824 updated dependency list

### PR DESCRIPTION
**Pull request by ricklarsen**
#### What does this PR do?

updates the dependency list for version 2.13.x.

#### Who is reviewing it? 

@mcalcote @ahoffer @garrettfreibott @austinsteffes 

#### Ask 2 committers to review/merge the PR and tag them here.

@clockard
@coyotesqrl
@lessarderic
@ricklarsen - Documentation
@rzwiefel
@shaundmorris

#### How should this be tested?

verify content/formatting (versions derived from `mvn dependency-list` command)

#### What are the relevant tickets?
[DDF-2824](https://codice.atlassian.net/browse/DDF-2824)

#### Checklist:
- [x] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by ricklarsen** [comment]
build now

**Comment by ricklarsen** [comment]
build now

**Comment by ricklarsen** [comment]
previous build: yarn error.
rerunning build now

**Comment by clockard** [comment]
jetty has also been updated from 9.3.14.v20161028 to 9.3.24.v20180605

**Comment by clockard** [comment]
@ahoffer We exclude them because we don't use them. By excluding them we reduce our distro size, avoid falls security vulnerability findings, and ensure no one accidentally starts using that version again.

**Comment by clockard** [comment]
build now

**Pull request merged**
