### PR TITLE
DDF-5458 suppressed OWASP false positivies

### PR DESCRIPTION
**Pull request by shaundmorris**
#### What does this PR do?
Suppresses false positives, please see notes on the file to see you agree with the findings.

#### Select relevant component teams: 
@codice/security 
@codice/solr 

#### Ask 2 committers to review/merge the PR and tag them here.

@vinamartin 
@jrnorth 

#### How should this be tested?
Build passes

#### Any background context you want to provide?
The suppression file has a note on why these are suppressed

#### What are the relevant tickets?
Fixes: #5458 

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

---
This change is [Reviewable](https://reviewable.io/reviews/codice/ddf/5464)

### CODE REVIEW

**Comment by vinamartin** [comment]
build now

**Comment by shaundmorris** [comment]
build now

**Comment by shaundmorris** [comment]
build now

**Comment by shaundmorris** [comment]
build now

**Comment by shaundmorris** [comment]
build now

**Comment by andrewkfiedler** [comment]
I think it's worth looking into pushing the CVE check into a separate status check than the builds if we have time.  That would also make testing the suppression faster (I think 🤔 ).

**Comment by shaundmorris** [comment]
@andrewkfiedler I agree, need to re-evaluate this flow and process.

**Comment by shaundmorris** [comment]
Merged, still had a build failure with unable to download the NVD CVE data. This is only suppression file changes and need to revisit more dependency upgrades (Jackson) and the build process here to be more efficient while still providing the value of securing our dependencies.

**Pull request merged**
