### PR TITLE
[2.21.x] DDF-5597 updated dependency-check properties for local NVD (#5654)

### PR DESCRIPTION
**Pull request by shaundmorris**
* DDF-5597 updated dependency-check properties

* DDF-5597 added back dependency-check maven version

#### What does this PR do?
Backport to 2.21.x

#### Who is reviewing it? 

@AdamBurstynski 
@TonyMorrison 
@LinkMJB 
@mojogitoverhere 

#### Select relevant component teams: 
@codice/build 
@codice/continuous-integration 
@codice/security 

#### Ask 2 committers to review/merge the PR and tag them here.

@brjeter
@oconnormi 

#### How should this be tested?

Build passes and uses local NVD with the owasp profile

#### What are the relevant tickets?
Fixes: #5597 

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

---
This change is [Reviewable](https://reviewable.io/reviews/codice/ddf/5725)

### CODE REVIEW

**Comment by shaundmorris** [comment]
build now

**Comment by shaundmorris** [comment]
build now

**Comment by LinkMJB** [comment]
build now

**Comment by shaundmorris** [comment]
Build now

last error: Remote call to JNLP4-connect connection

**Pull request merged**
