### PR TITLE
DDF-3894 fixed result sorting with modified date as primary and id as secondary

### PR DESCRIPTION
**Pull request by lamhuy**
fixed result sorting with modified date as primary and id as secondary

NATURAL_ORDER is omitted by SolrClient, hence results are not sorted

When SolrClient return unsorted result combining with paging, duplicate results are returned on the second page. Resulting in missing result set.

replacing with SortByImpl to specify property to sort by.

Who is reviewing it?
@millerw8
@bdeining
@rzwiefel

Select relevant component teams:
https://github.com/orgs/codice/teams

Ask 2 committers to review/merge the PR and tag them here. If you don't know who to ask, you can request reviews in https://groups.google.com/forum/#!forum/ddf-developers .
@millerw8
@bdeining
@rzwiefel

How should this be tested? (List steps with links to updated documentation)
Navigate with workspace or use this link
https://localhost:9902/search/catalog/internal/workspaces
With developer tool, verify the number of workspace returned is the same for each refresh
Additional verification can be done looking log
log:set DEBUG ddf.catalog.source.solr
See SOLR DOC
Ensure this list is exactly the same order each refresh

Any background context you want to provide?
What are the relevant tickets?
https://codice.atlassian.net/browse/DDF-3894

Note follow up ticket to address other usage of NATURAL_ORDER
https://codice.atlassian.net/projects/DDF/issues/DDF-3904

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by lamhuy** [comment]
Additional usage of NATURAL_ORDER that could have similar bug is reference here to be addressed by a follow up ticket
https://codice.atlassian.net/projects/DDF/issues/DDF-3904

**Comment by lamhuy** [comment]
build now

**Comment by willwill96** [comment]
Starting hero

**Comment by willwill96** [comment]
Hero Build Successful!

**Pull request merged**
