### PR TITLE
Revert "DDF-4481 Add the IS EMPTY operator in search queries"

### PR DESCRIPTION
**Pull request by Schachte**
Reverts codice/ddf#4281

This PR wasn't rebased and broke geojson filter tree preservation.

### CODE REVIEW

**Comment by vinamartin** [comment]
❓ Reason for this revert?

**Comment by rzwiefel** [comment]
We should probably include reason for revert in description 😁

**Comment by djblue** [comment]
build now

**Comment by cantstoptheunk** [comment]
This PR that got merged caused something that @Schachte wrote in `filter.view.js` to be reverted. Thus this PR is being reverted so that I can rebase the PR and get it re-approved/merged in.

**Pull request merged**
