### PR TITLE
DDF-1770: Expose ConfigurationMigrationService as an MBean/Jolokia service

### PR DESCRIPTION
**Pull request by lessarderic**
Reviewers:
@andrewkfiedler
@oconnormi 
@bantillo 
@garrettfreibott 
@lambeaux
@figliold

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/codice/ddf/pull/435" target="_blank">ReviewNinja

**Comment by andrewkfiedler** [comment]
Decided to try and hit the service and was having trouble passing in a path.  I think we'll need to update it to take into account what we're allowed to pass over jolokia.

I was looking at this as a reference for jolokia:
https://jolokia.org/reference/html/protocol.html#serialization-request

Here's how I was trying to hit the service:
https://localhost:8993/jolokia/exec/org.codice.ddf.configuration.migration.ConfigurationMigrationManager:service=configuration-migration/etc!/exported

On a side note, the ```!``` is for escaping, since ```/``` is used to separate arguments.

**Comment by stustison** [comment]
You can only use primitives, Lists, Maps, and Strings with Jolokia.

**Comment by figliold** [comment]
:+1:

**Comment by figliold** [comment]
prbs passed

**Pull request merged**
