### PR TITLE
DDF-1646 Adds general templates for configuring MSF, services, and source types

### PR DESCRIPTION
**Pull request by andrewkfiedler**
- Adds general templates for configuring Managed Service Factories and Services.
 - Adds templates for each of the current source types.

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/329)

### CODE REVIEW

**Comment by andrewkfiedler** [comment]
@figliold, @oconnormi

**Comment by lessarderic** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

<sup>**[distribution/ddf-common/src/main/resources/etc/templates/example.ManagedServiceFactory.1.config, line 2 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/329#-K2nu8BruQ1pnMf-gKDn)** ([raw file](https://github.com/codice/ddf/blob/1d60db1d1dfcd15223343bbacdf355c50566d138/distribution/ddf-common/src/main/resources/etc/templates/example.ManagedServiceFactory.1.config#L2)):</sup>
I don't think we need an `id` property. @figliold, @oconnormi?

Applies to all config files.


---

<sup>**[distribution/ddf-common/src/main/resources/etc/templates/example.ManagedServiceFactory.1.config, line 11 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/329#-K2nvM_vIlvFZsgaAQ1s)** ([raw file](https://github.com/codice/ddf/blob/1d60db1d1dfcd15223343bbacdf355c50566d138/distribution/ddf-common/src/main/resources/etc/templates/example.ManagedServiceFactory.1.config#L11)):</sup>
This may be a better set of properties for the sample files:
```
property.string="string"
property.boolean.true=B"true"
property.boolean.false=B"false"
property.int=I"10"
property.long=L"100"
property.float=F"10.5"
property.double=D"100.1234"

property.array.strings=["A","B","C"]
property.array.booleans=["true","false"]
property.array.ints=I["10","20","30"]
property.array.longs=L["100","200","300"]
property.array.floats=F["1.1","2.2","3.3"]
property.array.doubles=D["1.123","2.234","3.345"]
```

Do you think we should also have examples for vectors (negative cardinality)?


---

<sup>**[distribution/ddf-common/src/main/resources/etc/templates/sources/Csw_Connected_Source.1.config, line 1 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/329#-K2nwarfcPO81RJbN3QD)** ([raw file](https://github.com/codice/ddf/blob/1d60db1d1dfcd15223343bbacdf355c50566d138/distribution/ddf-common/src/main/resources/etc/templates/sources/Csw_Connected_Source.1.config#L1)):</sup>
Is this `0` a valid property here?

We also need to add `service.factoryPid` property at the top.


---

<sup>**[distribution/ddf-common/src/main/resources/etc/templates/sources/Csw_Connected_Source.1.config, line 9 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/329#-K2nx73WrjzW_cuO4Ekg)** ([raw file](https://github.com/codice/ddf/blob/1d60db1d1dfcd15223343bbacdf355c50566d138/distribution/ddf-common/src/main/resources/etc/templates/sources/Csw_Connected_Source.1.config#L9)):</sup>
Not sure if we need those `id` properties.


---

<sup>**[distribution/ddf-common/src/main/resources/etc/templates/sources/Csw_Federated_Source.1.config, line 1 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/329#-K2nx3AacGWGXqDAeVe4)** ([raw file](https://github.com/codice/ddf/blob/1d60db1d1dfcd15223343bbacdf355c50566d138/distribution/ddf-common/src/main/resources/etc/templates/sources/Csw_Federated_Source.1.config#L1)):</sup>
`service.factoryPid` missing.


---

<sup>**[distribution/ddf-common/src/main/resources/etc/templates/sources/OpenSearchSource.1.config, line 1 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/329#-K2nxF-oYd6Xr4EnfAmK)** ([raw file](https://github.com/codice/ddf/blob/1d60db1d1dfcd15223343bbacdf355c50566d138/distribution/ddf-common/src/main/resources/etc/templates/sources/OpenSearchSource.1.config#L1)):</sup>
`0` ?

Applies to the other config files as well.


---

<sup>**[distribution/ddf-common/src/main/resources/etc/templates/sources/OpenSearchSource.1.config, line 7 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/329#-K2nxKCAahiq9wcLAu5W)** ([raw file](https://github.com/codice/ddf/blob/1d60db1d1dfcd15223343bbacdf355c50566d138/distribution/ddf-common/src/main/resources/etc/templates/sources/OpenSearchSource.1.config#L7)):</sup>
I'd move `service.factoryPid` at the top.

Applies to the other config files as well.


---

<sup>**[distribution/ddf-common/src/main/resources/etc/templates/sources/OpenSearchSource.1.config, line 8 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/329#-K2nxHWgw6a-mHI9O1wK)** ([raw file](https://github.com/codice/ddf/blob/1d60db1d1dfcd15223343bbacdf355c50566d138/distribution/ddf-common/src/main/resources/etc/templates/sources/OpenSearchSource.1.config#L8)):</sup>
Remove `service.pid`.

Applies to the following config files as well.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/329)

**Comment by lessarderic** [comment]
@stustison, @pklinef , should we also have some templates for the security configuration?


---

Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/329)

**Comment by oconnormi** [comment]
<sup>**[distribution/ddf-common/src/main/resources/etc/templates/example.ManagedServiceFactory.1.config, line 2 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/329#-K2nu8BruQ1pnMf-gKDn)** ([raw file](https://github.com/codice/ddf/blob/1d60db1d1dfcd15223343bbacdf355c50566d138/distribution/ddf-common/src/main/resources/etc/templates/example.ManagedServiceFactory.1.config#L2)):</sup>
I think you're right @lessarderic, unless the MSF configs need to read the id out for some reason. Is the id generated factory once the MSF is created?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/329)

**Comment by oconnormi** [comment]
<sup>**[distribution/ddf-common/src/main/resources/etc/templates/example.ManagedServiceFactory.1.config, line 11 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/329#-K2nvM_vIlvFZsgaAQ1s)** ([raw file](https://github.com/codice/ddf/blob/1d60db1d1dfcd15223343bbacdf355c50566d138/distribution/ddf-common/src/main/resources/etc/templates/example.ManagedServiceFactory.1.config#L11)):</sup>
We probably should. Even if we were to standardize around one type of cardinality, third parties could still use either and it would probably be good to show an example of how they are formatted


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/329)

**Comment by lessarderic** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

<sup>**[distribution/ddf-common/src/main/resources/etc/templates/example.ManagedServiceFactory.1.config, line 11 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/329#-K2nvM_vIlvFZsgaAQ1s)** ([raw file](https://github.com/codice/ddf/blob/1d60db1d1dfcd15223343bbacdf355c50566d138/distribution/ddf-common/src/main/resources/etc/templates/example.ManagedServiceFactory.1.config#L11)):</sup>
Ok, here's what that would look like (btw, there was a _B_ missing in front of the boolean array above):
```
property.string="string"
property.boolean.true=B"true"
property.boolean.false=B"false"
property.int=I"10"
property.long=L"100"
property.float=F"10.5"
property.double=D"100.1234"

property.array.strings=["A","B","C"]
property.array.booleans=B["true","false"]
property.array.ints=I["10","20","30"]
property.array.longs=L["100","200","300"]
property.array.floats=F["1.1","2.2","3.3"]
property.array.doubles=D["1.123","2.234","3.345"]

property.vector.strings=("A","B","C")
property.vector.booleans=B("true","false")
property.vector.ints=I("10","20","30")
property.vector.longs=I("100","200","300")
property.vector.floats=F("1.1","2.2","3.3")
property.vector.doubles=D("1.123","2.234","3.345")
```


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/329)

**Comment by lessarderic** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

<sup>**[distribution/ddf-common/src/main/resources/etc/templates/example.ManagedServiceFactory.1.config, line 11 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/329#-K2nvM_vIlvFZsgaAQ1s)** ([raw file](https://github.com/codice/ddf/blob/1d60db1d1dfcd15223343bbacdf355c50566d138/distribution/ddf-common/src/main/resources/etc/templates/example.ManagedServiceFactory.1.config#L11)):</sup>
Ok, looks like my coffee hasn't kicked in yet... The value of `property.vector.longs` should start with an `L`, not an `I`.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/329)

**Comment by andrewkfiedler** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

<sup>**[distribution/ddf-common/src/main/resources/etc/templates/example.ManagedServiceFactory.1.config, line 2 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/329#-K2nu8BruQ1pnMf-gKDn)** ([raw file](https://github.com/codice/ddf/blob/1d60db1d1dfcd15223343bbacdf355c50566d138/distribution/ddf-common/src/main/resources/etc/templates/example.ManagedServiceFactory.1.config#L2)):</sup>
I thought it was necessary for certain MSF configs.


---

<sup>**[distribution/ddf-common/src/main/resources/etc/templates/example.ManagedServiceFactory.1.config, line 11 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/329#-K2nvM_vIlvFZsgaAQ1s)** ([raw file](https://github.com/codice/ddf/blob/1d60db1d1dfcd15223343bbacdf355c50566d138/distribution/ddf-common/src/main/resources/etc/templates/example.ManagedServiceFactory.1.config#L11)):</sup>
Thanks, I'll switch it out.


---

<sup>**[distribution/ddf-common/src/main/resources/etc/templates/sources/Csw_Connected_Source.1.config, line 1 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/329#-K2nwarfcPO81RJbN3QD)** ([raw file](https://github.com/codice/ddf/blob/1d60db1d1dfcd15223343bbacdf355c50566d138/distribution/ddf-common/src/main/resources/etc/templates/sources/Csw_Connected_Source.1.config#L1)):</sup>
I'm not sure.  It showed up when I saved it off.


---

<sup>**[distribution/ddf-common/src/main/resources/etc/templates/sources/OpenSearchSource.1.config, line 8 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/329#-K2nxHWgw6a-mHI9O1wK)** ([raw file](https://github.com/codice/ddf/blob/1d60db1d1dfcd15223343bbacdf355c50566d138/distribution/ddf-common/src/main/resources/etc/templates/sources/OpenSearchSource.1.config#L8)):</sup>
Should I remove it or change it to OpenSearchSource.1?   


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/329)

**Comment by lessarderic** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

<sup>**[distribution/ddf-common/src/main/resources/etc/templates/sources/Csw_Connected_Source.1.config, line 1 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/329#-K2nwarfcPO81RJbN3QD)** ([raw file](https://github.com/codice/ddf/blob/1d60db1d1dfcd15223343bbacdf355c50566d138/distribution/ddf-common/src/main/resources/etc/templates/sources/Csw_Connected_Source.1.config#L1)):</sup>
Can you check what's in the metatype.xml for those? If it doesn't show up there, it's probably not needed. We should also try to configure the endpoints by creating config files from the templates to make sure the templates are valid. That'll also help us confirm that those properties aren't needed.


---

<sup>**[distribution/ddf-common/src/main/resources/etc/templates/sources/OpenSearchSource.1.config, line 8 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/329#-K2nxHWgw6a-mHI9O1wK)** ([raw file](https://github.com/codice/ddf/blob/1d60db1d1dfcd15223343bbacdf355c50566d138/distribution/ddf-common/src/main/resources/etc/templates/sources/OpenSearchSource.1.config#L8)):</sup>
We should remove those.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/329)

**Comment by andrewkfiedler** [comment]
Tested dropping all the templates in.  Everything was processed correctly.

**Comment by lessarderic** [comment]
:+1: 


---

Reviewed 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

<sup>**[distribution/ddf-common/src/main/resources/etc/templates/example.ManagedServiceFactory.1.config, line 2 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/329#-K2nu8BruQ1pnMf-gKDn)** ([raw file](https://github.com/codice/ddf/blob/1d60db1d1dfcd15223343bbacdf355c50566d138/distribution/ddf-common/src/main/resources/etc/templates/example.ManagedServiceFactory.1.config#L2)):</sup>
Since those seem to map to the metatype file's `name` attribute, let's keep them and put them at the top of the files.

Sorry for all the back-and-forth on this :-(


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/329)

**Comment by figliold** [comment]
looks good :thumbsup: 


---

Reviewed 1 of 11 files at r1, 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

<sup>**[distribution/ddf-common/src/main/resources/etc/templates/example.ManagedServiceFactory.1.config, line 2 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/329#-K2nu8BruQ1pnMf-gKDn)** ([raw file](https://github.com/codice/ddf/blob/1d60db1d1dfcd15223343bbacdf355c50566d138/distribution/ddf-common/src/main/resources/etc/templates/example.ManagedServiceFactory.1.config#L2)):</sup>
@lessarderic, we don't need the id property.


---

<sup>**[distribution/ddf-common/src/main/resources/etc/templates/example.Service.config, line 23 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/329#-K2sFcZipeRPXg0dgqn2)** ([raw file](https://github.com/codice/ddf/blob/e9dbb8287487808ff2a73fe07582b566a83cc7d8/distribution/ddf-common/src/main/resources/etc/templates/example.Service.config#L23)):</sup>
should we name this file example.ManagedService.config instead?


---

<sup>**[distribution/ddf-common/src/main/resources/etc/templates/sources/Csw_Federated_Source.1.config, line 6 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/329#-K2sGiF1tWF4DUPI6M8I)** ([raw file](https://github.com/codice/ddf/blob/e9dbb8287487808ff2a73fe07582b566a83cc7d8/distribution/ddf-common/src/main/resources/etc/templates/sources/Csw_Federated_Source.1.config#L6)):</sup>
should we put an example url here?


---

<sup>**[distribution/ddf-common/src/main/resources/etc/templates/sources/Wfs_v1_0_0_Connected_Source.1.config, line 6 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/329#-K2sGnPFDO7G6841eE8G)** ([raw file](https://github.com/codice/ddf/blob/e9dbb8287487808ff2a73fe07582b566a83cc7d8/distribution/ddf-common/src/main/resources/etc/templates/sources/Wfs_v1_0_0_Connected_Source.1.config#L6)):</sup>
Should we put some properties in the array above to show the format?  I can also see leaving it empty to show the format of an empty array.  Thoughts?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/329)

**Comment by lessarderic** [comment]
@andrewkfiedler, can you double check the asciidoc (ManContent) to make sure we cover the `service.factoryPid`, `service.pid` and `id` properties clearly, as well as the file name naming conventions? For the name, maybe we should recommend using the `id` instead of the `service.pid`, that way things would be consistent with what shows up in the Admin UI. For MSF config files, @figliold suggested we use `ddf` in the name on top of the sequential number (e.g., `id.ddf.#.config`) to prevent potential name collisions.

**Pull request merged**
