### PR TITLE
[2.11.x] DDF-3473 fixed logging

### PR DESCRIPTION
**Pull request by rzwiefel**
#### What does this PR do?
Modifies a logging statement from info -> debug since if a system is triggering this notification, every single request/login was spamming the log
#### Who is reviewing it? 
@ahoffer 
#### Select relevant component teams: 
@codice/security 
#### Choose 2 committers to review/merge the PR. 
anyone
#### What are the relevant tickets?
https://codice.atlassian.net/browse/DDF-3473

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by rzwiefel** [comment]
If think its critical that we log at info so that an admin sees, we can change this to log it at info once per restart and then log at debug after that.

**Comment by rzwiefel** [comment]
build now

**Comment by rzwiefel** [comment]
build now

**Comment by ahoffer** [comment]
build now

> 20:59:12 Caused by: java.lang.NullPointerException
> 20:59:12 	at org.apache.maven.shared.dependency.graph.internal.DefaultDependencyGraphBuilder.buildDependencyGraph(DefaultDependencyGraphBuilder.java:60)
> 20:59:12 	at org.apache.felix.bundleplugin.BundlePlugin.buildDependencyGraph(BundlePlugin.java:350)
> 20:59:12 	at org.apache.felix.bundleplugin.BundlePlugin.execute(BundlePlugin.java:375)
> 20:59:12 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)

**Pull request merged**
