### PR TITLE
DDF-1491: Fix TestSolrCommands.testSolrBackupNumToKeep()

### PR DESCRIPTION
**Pull request by lessarderic**
Refactored the test to make it pass :-)

I've ran the PR build for this change multiple times and the test hasn't failed a single time so I'm hoping this will take care of it.

@shaundmorris, @kcwire, @wmcnalli, please review. I'll merge to master as soon as it's been approved.

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/197)

### CODE REVIEW

**Comment by kcwire** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSolrCommands.java, line 97 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/197#-K-57ysd0UIwSBFYLUgd)** ([raw file](https://github.com/codice/ddf/blob/fc94d8e407e9dd95de57cdf5d595c9e777898763/distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSolrCommands.java#L97)):</sup>
Why sleep between the 2nd and 3rd but not the 1st & second? Doesn't the waitForBackupFilesToBeCreated() method do that for you?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/197)

**Comment by lessarderic** [comment]
I cannot wait for a fixed number of files to exist before assuming I can move on. Solr creates a third backup file, then deletes the first one. Which means that we go from 2 files, to 3 then back to 2. Not only that, we could not see the third file if the backup happens fast. Thus can’t just wait until file 3 is there.

**Comment by kcwire** [comment]
:+1: 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/197)

**Comment by lessarderic** [comment]
Problem was in `waitForFirstFileToBeDeleted()` where I used `contains()` instead of `containsAll()`. PR build didn't fail after that change was made so merging to master.

**Pull request merged**
