### PR TITLE
DDF-4215 ValidationFilterPlugin will show a metacard with an error/wa…

### PR DESCRIPTION
**Pull request by lamhuy**
#### What does this PR do?
DDF-4215 ValidationFilterPlugin will show a metacard with an error/warning if showErrors/Warning is true OR the user has the role

#### Who is reviewing it? 
@ethantmanns 
@peterhuffer 
@bdeining 

#### Ask 2 committers to review/merge the PR and tag them here.
@bdeining 
@millerw8 

#### How should this be tested?

Use DDF image upload to upload an image twice
Reconfigure Duplication Validation configure to mark duplicate as error
Upload the same image again
Configure Validation PreFederation Filter Plugin to ShowError and ShowWarning
Configure Metacard Validity with uncheck filterError and uncheck filterWarning
Use UI to search with *
Three records should be returned. One marked with warning and one with error
Reconfigure Validation Filter Plugin to uncheck ShowWarning
UI Search result in 2 record, 1 as error
Reconfigure Validation Filter plugin to uncheck ShowError
UI Search result in 1 record
Logout and login as localhost
UI search result in 3 records, 1 error and 1 warning 

#### What are the relevant tickets?
https://codice.atlassian.net/browse/DDF-4215

#### Checklist:
- [ ] Documentation Updated
- [x] Update / Add Unit Tests
- [x] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by brendan-hofmann** [comment]
build now

**Comment by brendan-hofmann** [comment]
Seems like this fixes a regression and should be backported as well?

**Comment by ethantmanns** [comment]
@brendan-hofmann This plugin doesn't exist in the release branch. This functionality is part of `CachingFederationStrategy` in `2.13.x` and doesn't make any assertions on user roles

**Comment by lamhuy** [comment]
build now

**Comment by lamhuy** [comment]
build now

**Comment by ethantmanns** [comment]
@lamhuy I think this is going to no longer be necessary due to https://github.com/codice/ddf/pull/3909

**Pull request closed without merging**
