### PR TITLE
Upgrade Tika to 1.26

### PR DESCRIPTION
**Pull request by abel-connexta**
#### What does this PR do?
Upgrade Apache Tika to 1.26 and upgraded depencies to be in sync with what Tika uses.

This PR depends on https://github.com/codice/thirdparty/pull/131

#### Who is reviewing it? 

@kentmorrissey
@shaundmorris
@zta6
@SmithJosh
#### How should this be tested?

1. Build https://github.com/codice/thirdparty/pull/131
2. Build this PR branch and run DDF
3. Download this set of assorted file types: https://github.com/codice/ddf/tree/master/catalog/transformer/catalog-transformer-tika-input/src/test/resources.
4. Test the Tika input transformer by ingesting those files from the Karaf shell.
`admin@root()> catalog:ingest -t tika "/path/to/test/resources"`
5. Test the video input transformer
`admin@root()> catalog:ingest -t video "/path/to/test/resources/testMP4.m4a"`
6. Test the pdf input transformer
`admin@root()> catalog:ingest -t pdf "/path/to/test/resources/testPDF.pdf"`

#### What are the relevant tickets?
Fixes: #____

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by abel-connexta** [comment]
build now

**Review by SmithJosh — APPROVED** [review]

**Review by mazarag2 — APPROVED** [review]

**Review by zta6 — APPROVED** [review]

**Comment by zta6** [comment]
heroing

**Comment by zta6** [comment]
🎉 Hero Succesful 🎉 
Verified all three transformers ingest properly

**Comment by abel-connexta** [comment]
build now

**Review by shaundmorris — APPROVED** [review]

**Pull request merged**
