### PR TITLE
DDF-2824 fixed names of plugins in docs

### PR DESCRIPTION
**Pull request by ricklarsen**
#### What does this PR do?

The Security Logging plugin was misnamed in the templated docs, and the Security Plugin was missing. This PR fixes both issues.

#### Who is reviewing it? 

@mcalcote @vinamartin @emmberk @Lambeaux @jrnorth 

#### Choose 2 committers to review/merge the PR. 

@clockard
@lessarderic
@stustison

#### How should this be tested? (List steps with links to updated documentation)

- docs module builds successfully
- plugin sections display correctly.

#### What are the relevant tickets?
[DDF-2824](https://codice.atlassian.net/browse/DDF-2824)

#### Checklist:
- [x] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by emanns95** [comment]
There's a spot in `catalog-framework-intro-contents.adoc` that has some links to plugins that need to be updated. Currently dead links

**Comment by ricklarsen** [comment]
build now

**Comment by ricklarsen** [comment]
build now

**Comment by ricklarsen** [comment]
build now

**Comment by ricklarsen** [comment]
build now

**Comment by ricklarsen** [comment]
build now

**Comment by ricklarsen** [comment]
build now

**Pull request merged**
