### PR TITLE
Revert "remove non-existent dependency (#5213)" and restores source

### PR DESCRIPTION
**Pull request by rzwiefel**
This reverts commit e8135dbeefb21226312182d457eb331b8da8fb24 and restores the source for
the module that is needed.

### Context
The source was mistakenly deleted for security-sts-usernametokenvalidator. However since the feature file and corresponding pom dependency still existed and it was able to find the jar magically because there was a snapshot version built it continued to work (even though the code was deleted). When the feature file reference was removed however the tokenvalidator that was being registered by the ghost bundle all of a sudden stopped working. This adds back the source for usernametokenvalidator and puts back the featurefile references as well since the source now exists again!

@bakejeyner @blen-desta @mcat97 @nsuvarna @samuelechu @jlcsmith

### CODE REVIEW

**Comment by jlcsmith** [comment]
build now

**Comment by jlcsmith** [comment]
Verified via hot deploying security-sts-usernametokenvalidator bundle into DDF.  Logs in are now succesful

**Comment by rzwiefel** [comment]
Download failure build now

**Comment by rzwiefel** [comment]
Build now

**Comment by BernardIgiri** [comment]
Build now.

**Comment by rzwiefel** [comment]
Since this is a build breaker and all build steps passed (up till owasp) merging.

**Pull request merged**
