### PR TITLE
[2.19.x] G-9209 fix Search form editor fails to save form with linestring geo

### PR DESCRIPTION
**Pull request by andrewzimmer**
#### What does this PR do?
fixes bug search form editor fails to save form with a 0 buffer for linestring or polygon

#### Who is reviewing it? 
@abel-connexta @zta6 @hayleynorton 

#### How should this be tested?
- build / install / run
- Go to search form editor and verify search forms can be saved with linestrings/polygons geos with a 0 buffer
- attempt other buffer values such as a blank value and verify the form saves
#### What are the relevant tickets?
Fixes: #____

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Review by hayleynorton — APPROVED** [review]

**Review by abel-connexta — APPROVED** [review]

**Comment by andrewzimmer** [comment]
build now

**Comment by andrewzimmer** [comment]
build now

**Comment by zta6** [comment]
hero in progress

**Comment by zta6** [comment]
🎉 Hero Successful 🎉 
verified no errors saving search forms with linestring/polys with various buffer values

**Comment by andrewzimmer** [comment]
build now

**Comment by andrewzimmer** [comment]
build now

**Review by cassandrabailey293 — APPROVED** [review]

**Pull request merged**
