### PR TITLE
DDF-1870 added the user.attributes file to the system properties update

### PR DESCRIPTION
**Pull request by stustison**
#### What does this PR do?
Updates the user.attributes file during the install
#### Who is reviewing it?
@pklinef @gordocanchola @clockard @coyotesqrl @mcalcote
#### How should this be tested?
Run itests @mcalcote can hero
#### Checklist:
- [ ] Documentation Updated
- [x] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by coyotesqrl** [comment]
:+1:

**Comment by clockard** [comment]
LGTM :+1:

**Comment by pklinef** [comment]
:+1:

**Comment by mcalcote** [comment]
All itests pass, was able to build successfully :+1:

**Pull request merged**
