### PR TITLE
Ddf 1383 certificates documentation update

### PR DESCRIPTION
**Pull request by ahoffer**
@stustison @ricklarsen @clockard @brianfelix @shaundmorris 

Review changes to the documentation.
Build the PDF and HTML files from the ASCII Doc files.
Open the generated PDF or HTML file (ddf/distribution/docs/target/docs).
All changes are within the section titled "Configure DDF with New Certificates".

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/96)

### CODE REVIEW

**Comment by stustison** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[distribution/docs/src/main/resources/ManContents.adoc, line 1348 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/96#-Jw2l2JBUz_4C-l3RIGw)** ([raw file](https://github.com/codice/ddf/blob/07739e025620c778460d852e044abb7694c6127b/distribution/docs/src/main/resources/ManContents.adoc#L1348)):</sup>
We should list the URLs to the two web applications at this point.

---

<sup>**[distribution/docs/src/main/resources/ManContents.adoc, line 1431 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/96#-Jw2lD9oQyqXJzc8vAdV)** ([raw file](https://github.com/codice/ddf/blob/07739e025620c778460d852e044abb7694c6127b/distribution/docs/src/main/resources/ManContents.adoc#L1431)):</sup>
We should not be telling them to use the FQDN as the password. They should be choosing a difficult password at this point.

---

<sup>**[distribution/docs/src/main/resources/ManContents.adoc, line 1434 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/96#-Jw2lQ0srcT4mlHuDTkO)** ([raw file](https://github.com/codice/ddf/blob/07739e025620c778460d852e044abb7694c6127b/distribution/docs/src/main/resources/ManContents.adoc#L1434)):</sup>
Should this still be {branding}_HOME instead of hardcoded to DDF_HOME?

---

<sup>**[distribution/docs/src/main/resources/ManContents.adoc, line 1579 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/96#-Jw2m8gNDmlaH2qNsisT)** ([raw file](https://github.com/codice/ddf/blob/07739e025620c778460d852e044abb7694c6127b/distribution/docs/src/main/resources/ManContents.adoc#L1579)):</sup>
Remove this TODO

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/96)

**Comment by clockard** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

<sup>**[distribution/docs/src/main/resources/ManContents.adoc, line 1562 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/96#-Jw2tQ4Bk00FTjfuNlLG)** ([raw file](https://github.com/codice/ddf/blob/07739e025620c778460d852e044abb7694c6127b/distribution/docs/src/main/resources/ManContents.adoc#L1562)):</sup>
'By default'  not 'y default'

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/96)

**Comment by clockard** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/96)

**Comment by clockard** [comment]
:+1:

**Comment by ahoffer** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

<sup>**[distribution/docs/src/main/resources/ManContents.adoc, line 1348 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/96#-Jw2l2JBUz_4C-l3RIGw)** ([raw file](https://github.com/codice/ddf/blob/07739e025620c778460d852e044abb7694c6127b/distribution/docs/src/main/resources/ManContents.adoc#L1348)):</sup>
Is it OK to hard code the port to 8933 when I include the URLs? Does the port number ever change? 

---

<sup>**[distribution/docs/src/main/resources/ManContents.adoc, line 1431 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/96#-Jw2lD9oQyqXJzc8vAdV)** ([raw file](https://github.com/codice/ddf/blob/07739e025620c778460d852e044abb7694c6127b/distribution/docs/src/main/resources/ManContents.adoc#L1431)):</sup>
how about:

\<FQDN>=\<PASSWORD>,group,admin,manager,viewer,webconsole</pre>

If the password is set to something other than the USER, if there any additional configuration that administrators need to make?

---

<sup>**[distribution/docs/src/main/resources/ManContents.adoc, line 1434 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/96#-Jw2lQ0srcT4mlHuDTkO)** ([raw file](https://github.com/codice/ddf/blob/07739e025620c778460d852e044abb7694c6127b/distribution/docs/src/main/resources/ManContents.adoc#L1434)):</sup>
I spoke with Rick about this. Currently we have no way of replacing the {branding} tag if it code/preformatted blocks. He suggested I continue to use DDF in these situations. 

Rick believe there is a way to do the substitution with maven. Currently, everything is still branded DDF and no one has written a ticket for it.

---

<sup>**[distribution/docs/src/main/resources/ManContents.adoc, line 1562 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/96#-Jw2tQ4Bk00FTjfuNlLG)** ([raw file](https://github.com/codice/ddf/blob/07739e025620c778460d852e044abb7694c6127b/distribution/docs/src/main/resources/ManContents.adoc#L1562)):</sup>
Thanks. :-)

---

<sup>**[distribution/docs/src/main/resources/ManContents.adoc, line 1579 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/96#-Jw2m8gNDmlaH2qNsisT)** ([raw file](https://github.com/codice/ddf/blob/07739e025620c778460d852e044abb7694c6127b/distribution/docs/src/main/resources/ManContents.adoc#L1579)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/96)

**Comment by ahoffer** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

<sup>**[distribution/docs/src/main/resources/ManContents.adoc, line 1348 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/96#-Jw2l2JBUz_4C-l3RIGw)** ([raw file](https://github.com/codice/ddf/blob/07739e025620c778460d852e044abb7694c6127b/distribution/docs/src/main/resources/ManContents.adoc#L1348)):</sup>
Oops. 8993.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/96)

**Comment by ahoffer** [comment]
Updated the documentation based on feedback received from reviewers on reviewable.io.

**Comment by ricklarsen** [comment]
<sup>**[distribution/docs/src/main/resources/ManContents.adoc, line 1434 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/96#-Jw2lQ0srcT4mlHuDTkO)** ([raw file](https://github.com/codice/ddf/blob/07739e025620c778460d852e044abb7694c6127b/distribution/docs/src/main/resources/ManContents.adoc#L1434)):</sup>
Asciidoctor ignores any asciidoctor syntax inside a code block. Maven does filter the files to add a version number currently. We could replace the asciidoctor variable with maven property that will get resolved before asciidoctor renders anything.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/96)

**Comment by ricklarsen** [comment]
<sup>**[distribution/docs/src/main/resources/ManContents.adoc, line 1580 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/96#-Jw3zCDNH2vxDAvmqUeK)** ([raw file](https://github.com/codice/ddf/blob/4a4105343252bb16f02618892a46073413c52e51/distribution/docs/src/main/resources/ManContents.adoc#L1580)):</sup>
If I'm reading this sentence correctly, it should read "Concatenate the certificate from the issuer, all intermediate certificate authorities, and the root authority into a text file." for better parallel construction. (I removed the second 'from').

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/96)

**Comment by ricklarsen** [comment]
:+1: LGTM!

**Comment by ahoffer** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

<sup>**[distribution/docs/src/main/resources/ManContents.adoc, line 1582 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/96#-Jw3zCDNH2vxDAvmqUeK)** ([raw file](https://github.com/codice/ddf/blob/4a4105343252bb16f02618892a46073413c52e51/distribution/docs/src/main/resources/ManContents.adoc#L1582)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/96)

**Comment by ahoffer** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

<sup>**[distribution/docs/src/main/resources/ManContents.adoc, line 1348 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/96#-Jw2l2JBUz_4C-l3RIGw)** ([raw file](https://github.com/codice/ddf/blob/07739e025620c778460d852e044abb7694c6127b/distribution/docs/src/main/resources/ManContents.adoc#L1348)):</sup>
Reviewable is not showing the URLs to me. They are there in the last commit. I must not be using Reviewable correctly.

---

<sup>**[distribution/docs/src/main/resources/ManContents.adoc, line 1431 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/96#-Jw2lD9oQyqXJzc8vAdV)** ([raw file](https://github.com/codice/ddf/blob/07739e025620c778460d852e044abb7694c6127b/distribution/docs/src/main/resources/ManContents.adoc#L1431)):</sup>
Done.

---

<sup>**[distribution/docs/src/main/resources/ManContents.adoc, line 1562 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/96#-Jw2tQ4Bk00FTjfuNlLG)** ([raw file](https://github.com/codice/ddf/blob/07739e025620c778460d852e044abb7694c6127b/distribution/docs/src/main/resources/ManContents.adoc#L1562)):</sup>
Done.

---

<sup>**[distribution/docs/src/main/resources/ManContents.adoc, line 1577 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/96#-Jw2m8gNDmlaH2qNsisT)** ([raw file](https://github.com/codice/ddf/blob/07739e025620c778460d852e044abb7694c6127b/distribution/docs/src/main/resources/ManContents.adoc#L1577)):</sup>
Done.

---

<sup>**[distribution/docs/src/main/resources/ManContents.adoc, line 1580 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/96#-Jw3zCDNH2vxDAvmqUeK)** ([raw file](https://github.com/codice/ddf/blob/4a4105343252bb16f02618892a46073413c52e51/distribution/docs/src/main/resources/ManContents.adoc#L1580)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/96)

**Comment by stustison** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

<sup>**[distribution/docs/src/main/resources/ManContents.adoc, line 1348 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/96#-Jw2l2JBUz_4C-l3RIGw)** ([raw file](https://github.com/codice/ddf/blob/07739e025620c778460d852e044abb7694c6127b/distribution/docs/src/main/resources/ManContents.adoc#L1348)):</sup>
8993 is fine because that is the default. If they have gone in and changed it to 443 or something, they should know that they did that.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/96)

**Comment by stustison** [comment]
:+1:

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/96)

**Comment by shaundmorris** [comment]
Verified build of documentation. Like the additions in the important terms section.

**Pull request merged**
