### PR TITLE
DDF-4120 remove unused dependency

### PR DESCRIPTION
**Pull request by lamhuy**
#### What does this PR do?
Remove dependency that's no longer available
This is breaking mvn release process. 
#### Ask 2 committers to review/merge the PR and tag them here.
@bdeining 
@troymohl 

#### How should this be tested?
Full CI build

#### What are the relevant tickets?
This dependency was introduced in 
https://codice.atlassian.net/browse/DDF-4120

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by lamhuy** [comment]
build now

**Comment by vinamartin** [comment]
Is it possible to update the ticket # to relate this back to the PR that brought this back in? It looks like it might have been DDF-4120.

**Comment by lamhuy** [comment]
build now

**Comment by lamhuy** [comment]
build now

**Comment by lamhuy** [comment]
build now

**Comment by lamhuy** [comment]
build now

**Pull request merged**
