### PR TITLE
[2.19.x] DDF-5471 Fix anyText filtering of query results

### PR DESCRIPTION
**Pull request by zta6**
#### What does this PR do?
Fixes anyText filtering of query results. Previously an anyText filter would hide all the query results, even if some of them did match the anyText condition. 

#### Who is reviewing it? 

@andrewzimmer 
@hayleynorton 

#### Select relevant component teams: 
@codice/ui 

#### Ask 2 committers to review/merge the PR and tag them here.
@bdeining
@djblue

#### How should this be tested?

Execute a query that returns multiple results
Apply an anyText filter that will narrow down the number of search results
Verify that the proper results are shown. (Previously all results would be hidden regardless of the condition in the anyText filter))

#### What are the relevant tickets?
Fixes: #5471 

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by zta6** [comment]
build now

**Comment by andrewzimmer** [comment]
Hero Successful 🎉 
- Verified filtering with anytext shows the correct results

**Comment by andrewzimmer** [comment]
build now

**Comment by zta6** [comment]
build now

**Comment by zta6** [comment]
build now

**Pull request merged**
