### PR TITLE
DDF-4457 Encrypt file system storage

### PR DESCRIPTION
**Pull request by bakejeyner**
**NOTE: This is a straight cherry-pick of [the 2.13.x PR](https://github.com/codice/ddf/pull/4502)**

Uncomment this block and include PR # of change against 2.13.x where appropriate.
When doing so, it is reasonable to delete much of the rest of the PR description, leaving only:
- This uncommented block with link to 2.13.x PR
- Reviewers tagged
- Teams tagged
- Committers tagged
- The link to the "Notes on Review Process"

##### ABBREVIATED REVIEW BETWEEN 2.13.X AND MASTER IS IN EFFECT
Link to 2.13.x PR: #4502
____

#### What does this PR do?
Updates the `FileSystemStorageProvider` to encrypt the content it writes to disk.

#### Who is reviewing it? 
@blen-desta 
@coyotesqrl 
@garrettfreibott 
@stustison 

#### What are the relevant tickets?
For Jira:
[DDF-4457](https://codice.atlassian.net/browse/DDF-4457)

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [x] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by bakejeyner** [comment]
build now

**Comment by bakejeyner** [comment]
build now
(pomfix issue, passed locally with change)

**Comment by bakejeyner** [comment]
build now
(both `install-profiles` and `testFilterPluginWarningsOnly` passed locally, 🤞 that CI is just flaky)

**Comment by tyler30clemens** [comment]
Hero Successful ✅

**Pull request merged**
