### PR TITLE
DDF-2009 Clean up app prereqs

### PR DESCRIPTION
**Pull request by jckilmer**
#### What does this PR do?
Adds feature dependencies so that higher level features do not need to depend on full apps but only the required features.
#### Who is reviewing it?
@coyotesqrl @ryeats @tbatie @roelens8 @bcwaters 
#### How should this be tested?
Install and test the affected features and apps.
#### Any background context you want to provide?
n/a
#### What are the relevant tickets?
https://codice.atlassian.net/browse/DDF-2009
#### Screenshots (if appropriate)
n/a
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by ryeats** [comment]
:+1:

**Comment by tbatie** [comment]
:+1:

**Comment by coyotesqrl** [comment]
LGTM

**Comment by roelens8** [comment]
:+1:

**Comment by bcwaters** [comment]
I successfully hero'd this.

**Comment by shaundmorris** [comment]
Was there a noticeable difference at startup?

**Comment by jckilmer** [comment]
No unfortunately there was not. The only difference is that the affected features can be independently installed.

**Pull request closed without merging**
