### PR TITLE
DDF-2425 Updated Imagery Provider Examples

### PR DESCRIPTION
**Pull request by bdeining**
#### What does this PR do?
This PR updates examples for imagery providers in the Standard Search UI
#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?
@ricklarsen
#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@jlcsmith
@kcwire
#### What are the relevant tickets?
https://codice.atlassian.net/browse/DDF-2425
#### Screenshots (if appropriate)
https://codice.atlassian.net/browse/DDF-2425
#### Checklist:
- [X] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by jlcsmith** [comment]
👍

**Comment by stustison** [comment]
Before adding these to our documentation, have we actually tested to make sure that all of these types work for both maps?

**Comment by bdeining** [comment]
@stustison These examples were created from testing them in the Standard Search UI.  The only imagery provider that wasn't able to be tested was Google Earth, since that requires an Enterprise License.

**Comment by bdeining** [comment]
@stustison Updated the PR to annotate which imagery providers work where

**Pull request merged**
