### PR TITLE
DDF-2549: DDF projects should reference project.version for mvn release plugin

### PR DESCRIPTION
**Pull request by troymohl**
#### What does this PR do?
Updates ddf.version to project.version for DDF modules in order for the mvn release plugin to run correctly.

#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged)?
@bdeining 
@peterhuffer 

#### Select at least one member from relevant component team(s) from below (at least one component team member needs to approve the PR).
@oconnormi 

#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@coyotesqrl
@pklinef

#### How should this be tested? (List steps with links to updated documentation)
Run:
mvn release:prepare
Once you choose a version number for the release and the pom files are updated the release will start building. Previously it would fail while updating pom files.

#### What are the relevant tickets?
https://codice.atlassian.net/browse/DDF-2549

#### Checklist:
- [ ] Documentation Updated
- [ ] Change Log Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by jlcsmith** [comment]
It looks like ddf.version was added here: https://github.com/codice/ddf/commit/44ad14daea7bac8a92f912c15287f5fe37649f3b.  I wonder if we can get rid of it or move it from the root pom so this issue doesn't happen again.

**Comment by troymohl** [comment]
@shaundmorris The error message was:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.1:prepare (default-cli) on project ddf: The version could not be updated: ${ddf.version} -> [Help 1]

I didn't have much to go on, so I just replaced places that used ddf.version instead of project.version and gave it a try.

**Comment by troymohl** [comment]
@coyotesqrl It appears to be referenced in the documentation (.adoc) files. I think those could be changed to use `project.version` if we want to get rid of the `ddf.version` definition from DDF.

**Comment by ricklarsen** [comment]
The `ddf.version` variable does have a use case in the documentation for custom distributions.

**Comment by peterhuffer** [comment]
Successfully heroed.
Ran `mvn release:prepare` and successfully got to the compilation stage.

**Comment by shaundmorris** [comment]
@ricklarsen the docs cannot use ${project.version} correct? I'm wondering if we should move the ddf.version property to the docs module to prevent this issue going forward.

**Comment by ricklarsen** [comment]
I have no problem with moving it to the docs module or at least commenting not to use, except for docs.

**Comment by troymohl** [comment]
@shaundmorris  @ricklarsen Moved definition of `ddf.version` to the docs module and removed from the root pom.xml

**Pull request merged**
