### PR TITLE
DDF-439 added integration test to verify solr:backup command

### PR DESCRIPTION
**Pull request by wmcnalli**
@kcwire 
@jlcsmith 
@millerw8 
@beyelerb 
@jrnorth 
@kguerriero
@emanns95

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/88)

### CODE REVIEW

**Comment by jlcsmith** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/88)

**Comment by kcwire** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/88)

**Comment by jrnorth** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/88)

**Comment by kguerriero** [comment]
Reviewed 6 of 7 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/88)

**Comment by kcwire** [comment]
Reviewed 6 of 7 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[catalog/core/catalog-core-solrcommands/pom.xml, line 66 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/88#-Jvzed32DY39W0Ih2rxk)** ([raw file](https://github.com/codice/ddf/blob/74296c83ee33b8bbd5774341921c61ec5fae2001/catalog/core/catalog-core-solrcommands/pom.xml#L66)):</sup>
didn't see any json in here.

---

<sup>**[catalog/core/catalog-core-solrcommands/pom.xml, line 71 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/88#-JvzefYeWZAOeSFrtCVH)** ([raw file](https://github.com/codice/ddf/blob/74296c83ee33b8bbd5774341921c61ec5fae2001/catalog/core/catalog-core-solrcommands/pom.xml#L71)):</sup>
log4j?

---

<sup>**[catalog/core/catalog-core-solrcommands/pom.xml, line 77 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/88#-JvzemH2Q7dXD_fWfCo-)** ([raw file](https://github.com/codice/ddf/blob/74296c83ee33b8bbd5774341921c61ec5fae2001/catalog/core/catalog-core-solrcommands/pom.xml#L77)):</sup>
wiremock?

---

<sup>**[catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/BackupCommand.java, line 51 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/88#-Jvze7zKHUDsPLct2Di9)** ([raw file](https://github.com/codice/ddf/blob/74296c83ee33b8bbd5774341921c61ec5fae2001/catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/BackupCommand.java#L51)):</sup>
can't you just set a default value for the @Option?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/88)

**Comment by wmcnalli** [comment]
Review status: 6 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

<sup>**[catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/BackupCommand.java, line 51 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/88#-Jvze7zKHUDsPLct2Di9)** ([raw file](https://github.com/codice/ddf/blob/74296c83ee33b8bbd5774341921c61ec5fae2001/catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/BackupCommand.java#L51)):</sup>
Not in the annotation, but you can set the variable to a default and the option passed in will overwrite it... fixed.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/88)

**Comment by jlcsmith** [comment]
<sup>**[catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/BackupCommand.java, line 34 \[r4\]](https://reviewable.io:443/reviews/codice/ddf/88#-Jw3gqc6Zq2fnBdUGZSf)** ([raw file](https://github.com/codice/ddf/blob/c528d2f3ed3860ebbd6f56a1ab0c85c91166241a/catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/BackupCommand.java#L34)):</sup>
Is there a convention we should be sticking to here?  It seems like most of the catalog commands use "-<single letter>" or "--<verbose name" ... like -d and --dir

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/88)

**Comment by wmcnalli** [comment]
Review status: 6 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/BackupCommand.java, line 34 \[r4\]](https://reviewable.io:443/reviews/codice/ddf/88#-Jw3gqc6Zq2fnBdUGZSf)** ([raw file](https://github.com/codice/ddf/blob/c528d2f3ed3860ebbd6f56a1ab0c85c91166241a/catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/BackupCommand.java#L34)):</sup>
Yes.. i'll fix those.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/88)

**Comment by jlcsmith** [comment]
<sup>**[catalog/core/pom.xml, line 116 \[r4\]](https://reviewable.io:443/reviews/codice/ddf/88#-Jw3i06gWEwM1V56vuiC)** ([raw file](https://github.com/codice/ddf/blob/c528d2f3ed3860ebbd6f56a1ab0c85c91166241a/catalog/core/pom.xml#L116)):</sup>
formatting

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/88)

**Comment by jlcsmith** [comment]
Reviewed 4 of 7 files at r2, 1 of 1 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/88)

**Comment by beyelerb** [comment]
Reviewed 1 of 1 files at r1, 4 of 7 files at r2, 1 of 1 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

<sup>**[catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/BackupCommand.java, line 110 \[r4\]](https://reviewable.io:443/reviews/codice/ddf/88#-Jw3nppTwRwLe8r0qkIF)** ([raw file](https://github.com/codice/ddf/blob/c528d2f3ed3860ebbd6f56a1ab0c85c91166241a/catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/BackupCommand.java#L110)):</sup>
Is port always in the map? If not, check for it and don't put in the ':' or port.

---

<sup>**[catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/SolrCommands.java, line 100 \[r4\]](https://reviewable.io:443/reviews/codice/ddf/88#-Jw3o9tsbhD4oGhSzThr)** ([raw file](https://github.com/codice/ddf/blob/c528d2f3ed3860ebbd6f56a1ab0c85c91166241a/catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/SolrCommands.java#L100)):</sup>
Reformatting issue?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/88)

**Comment by wmcnalli** [comment]
Review status: 5 of 8 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/88)

**Comment by wmcnalli** [comment]
Review status: 5 of 8 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

<sup>**[catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/BackupCommand.java, line 110 \[r4\]](https://reviewable.io:443/reviews/codice/ddf/88#-Jw3nppTwRwLe8r0qkIF)** ([raw file](https://github.com/codice/ddf/blob/c528d2f3ed3860ebbd6f56a1ab0c85c91166241a/catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/BackupCommand.java#L110)):</sup>
Good point.  Fixed.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/88)

**Comment by jrnorth** [comment]
LGTM

**Pull request merged**
