### PR TITLE
DDF-4476 removing throttle from result selector view

### PR DESCRIPTION
**Pull request by gjvera**
#### What does this PR do?
Removes throttle from result selector view
#### Who is reviewing it? 
@mojogitoverhere @Bdthomson @willwill96 

#### Select relevant component teams: 
@codice/ui 
#### Ask 2 committers to review/merge the PR and tag them here.

@bdeining 
@djblue 
#### How should this be tested?
ingest some data 
run a while card search 
click the play button several times 
ensure all results are returned and there is no flickering
create a list with some of the results 
ensure results are returned in the list with no flickering or delay

#### What are the relevant tickets?
[DDF-4476](https://codice.atlassian.net/browse/DDF-4476)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by vinamartin** [comment]
❓ What was the reason for introducing the throttling in the first place?

**Comment by gjvera** [comment]
@vinamartin The original problem was that when a user had the table view open, when results were populated it would send a lot of network requests to update the users preferences every time the table rendered. So, we decided to throttle the result view so the preference requests wouldn't be sent as often. But I added something else to only change the users preferences if the preferences had changed. So, the throttle is no longer necessary.

**Comment by mojogitoverhere** [comment]
build now

**Comment by mojogitoverhere** [comment]
hero in progress

**Comment by mojogitoverhere** [comment]
## 🎉 Hero build was successful! 🎉 ##

Search results and target lists no longer flicker or incorrectly show no results when the play button is pressed. Verified in downstream project.

**Pull request merged**
