### PR TITLE
DDF-4826 Broaden scope of karaf deployer blueprint policy

### PR DESCRIPTION
**Pull request by rzwiefel**
Increased scope from ddfhome/etc/definitions to ddfhome/etc

#### What does this PR do?
Broaden scope of karaf deployer blueprint policy
#### Who is reviewing it? 
@stustison @jordanwilking @bellcc @tbatie @glenhein 
#### Select relevant component teams: 
@codice/security 

#### How should this be tested?
- Ensure CI Passes
- Build and install locally and ensure it installs correctly. Insure config files inside of `<DDF_HOME>/etc` are read successfully. Add Config to test if none exist.

#### What are the relevant tickets?
Fixes: #4826

#### Checklist:
- [NA] Documentation Updated
- [NA] Update / Add Threat Dragon models
  - Deployer must be able to read all configurations under ETC
- [NA] Update / Add Unit Tests
- [NA] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by rzwiefel** [comment]
build now

**Comment by tyler30clemens** [comment]
I just noticed this PR/issue, but I recently put up this same change to the 2.13.x branch (#4830) under a separate issue (#4829). Do you plan to port to 2.13.x at all? Or should we just keep them separate and close them respective to their branch/issue?

**Comment by tyler30clemens** [comment]
I recently put up a PR for the 2.13.x branch (#4830) with this change. Closing my issue as duplicate and referencing it to this respective issue and PR as well.

**Comment by rzwiefel** [comment]
Unsure if failures related - Build now

**Comment by jlcsmith** [comment]
build now

**Comment by jlcsmith** [comment]
CI builds are failing for unrelated reasons.  Merging based on manual builds and the fact this was already merged into 2.13.x

**Pull request merged**
