### PR TITLE
DDF-1826 updated IngestPlugin to implement AccessPlugin instead of PreIngestPlugin

### PR DESCRIPTION
**Pull request by stustison**
@codice/security 

@mcalcote can hero

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/codice/ddf/pull/490" target="_blank">ReviewNinja

**Comment by mcalcote** [comment]
Ran the full build without issue. Changes look good.

**Comment by oscaritoro** [comment]
Might need to figure out why bamboo build failed, but otherwise LGTM :+1:

**Comment by mcalcote** [comment]
Build Success with updates. :+1:

**Pull request merged**
