### PR TITLE
[2.13.x] DDF-4703 updated docs module to add version checking

### PR DESCRIPTION
**Pull request by ricklarsen**
#### What does this PR do?

Reconfigures the directory structure of the documentation build to include version number to prevent issues on quickbuilds or releases

#### Who is reviewing it? 
@ahoffer @austinsteffes @Kjames5269 

#### Select relevant component teams: 

@codice/build 
@codice/docs 

#### Ask 2 committers to review/merge the PR and tag them here.

@brjeter
@clockard
@lessarderic
@mcalcote
@ricklarsen - Documentation

#### How should this be tested?

- check out `master` branch
- build docs module with `mvn clean install`
- check out this branch
- build docs module with `mvn install` (leave previous build artifacts in target directory)

#### What are the relevant tickets?

For GH Issues:
#4703

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by ricklarsen** [comment]
build now

**Comment by brjeter** [comment]
Hero Successful ✅

**Comment by brjeter** [comment]
build now

**Comment by brjeter** [comment]
✅ Hero successful

**Pull request merged**
