### PR TITLE
DDF-3942: ArcGIS Tile Layer Not Rendering Correctly

### PR DESCRIPTION
**Pull request by dcruver**
Modified the AGM source to include a function to map tile position to URL correctly.

#### What does this PR do?
This fix adds a tiling function to the AGM source

#### Who is reviewing it? 
@djblue 
@AzGoalie 

#### Select relevant component teams: 
https://github.com/orgs/codice/teams/ui

#### Ask 2 committers to review/merge the PR and tag them here. If you don't know who to ask, you can request reviews in https://groups.google.com/forum/#!forum/ddf-developers .
(please choose ONLY two committers from below, delete the rest)
@andrewkfiedler
@millerw8

#### How should this be tested? (List steps with links to updated documentation)
1) build and deploy the catalog-ui-search bundle
2) In the admin console (Search UI -> Configuration -> org.codice.ddf.catalog.ui.config) under Imagery Providers insert the following:
[ 
    {"parameters":{"transparent":false,"format":""},
     "name":"ArcGIS",
     "order":0,
     "url":"https://services.arcgisonline.com/arcgis/rest/services/ESRI_Imagery_World_2D/MapServer/",
     "proxyEnabled":false,
     "withCredentials":true,
     "type":"AGM",
     "show":true,
     "projection":"EPSG:4326",
     "alpha":1}
]

3) In the admin console (Search UI -> Configuration -> org.codice.ddf.catalog.ui.config) under Map Projection, enter "EPSG:4326" (this is the default value)

4) in Intrigue, verify that the new layer appears in the 'Layers' dropdown:
image

5) in Intrigue, verify that the 2D map shows every continent:
image

#### What are the relevant tickets?
[DDF-3942](https://codice.atlassian.net/browse/DDF-3942)

#### Screenshots (if appropriate)
Prior to this change, the 2D map appeared like this:

image

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by bdeining** [comment]
Do we need this change is Cesium as well?

**Comment by jlcsmith** [comment]
❓ does this work for EPSG:4326 as well?

**Comment by dcruver** [comment]
@bdeining - Cesium doesn't seem to have this problem
@jlcsmith  - I updated the test instructions to use EPSG:4326

**Comment by gjvera** [comment]
🎉 Hero Successful 🎉 
Build UI search bundle and configured as instructed. 
2D map came up with every continent 

LG2M!

**Comment by jlcsmith** [comment]
build now

**Pull request merged**
