### PR TITLE
[2.19.x] DDF-UI-157-160-161 DMS geo search bug fixes

### PR DESCRIPTION
**Pull request by hayleynorton**
#### What does this PR do?
This PR fixes three issues:
- codice/ddf-ui#157 UTM/UPS coordinates were being automatically cleared if an invalid value was entered
- codice/ddf-ui#160 DMS coordinate fields were not populating on draw
- codice/ddf-ui#161 DMS underscore placeholders were present if there was less than 3-decimal-point precision 
#### Who is reviewing it? 
@andrewzimmer @cassandrabailey293 @gjvera @willwill96 @zta6 
#### Select relevant component teams: 
@codice/ui 
#### Ask 2 committers to review/merge the PR and tag them here.
@bdeining 
@shaundmorris 
#### What are the relevant tickets?
Fixes: codice/ddf-ui#157
Fixes: codice/ddf-ui#160
Fixes: codice/ddf-ui#161
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by bdeining** [comment]
build now

**Comment by hayleynorton** [comment]
build now

**Comment by Lambeaux** [comment]
Was going to merge but didn't see any note about a hero. Slack me when ready 👍

**Comment by cassandrabailey293** [comment]
> Was going to merge but didn't see any note about a hero. Slack me when ready 👍

Hero Started 👍

**Comment by cassandrabailey293** [comment]
Hero Successful 🎉 
verified that the three issues are fixed and no regression

**Comment by bdeining** [comment]
build now

**Comment by bdeining** [comment]
i think this needs a rebase

**Comment by hayleynorton** [comment]
build now

**Pull request merged**
