### PR TITLE
DDF-5727 Grab Correct Modified Attribute for Search Forms

### PR DESCRIPTION
**Pull request by willwill96**
#### What does this PR do?
Corrects attribute being grabbed for search forms application

#### Who is reviewing it? 
@andrewzimmer 
@hayleynorton 
@zta6 
@cassandrabailey293 

#### Ask 2 committers to review/merge the PR and tag them here.
@bdeining 
@djblue 

#### How should this be tested?
1. Create a few search forms
2. Modify one of the search forms
3. Refresh search forms page and verify that the modified date of that search form is updated

#### What are the relevant tickets?
Fixes: #5727 

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by bdeining** [comment]
build now

**Comment by cassandrabailey293** [comment]
hero in progress

**Comment by willwill96** [comment]
build now

**Comment by willwill96** [comment]
build now

**Comment by willwill96** [comment]
build now

**Comment by willwill96** [comment]
build now

**Comment by cassandrabailey293** [comment]
hero successful 🎉 

verified that the `dateModified` attribute in the response when reloading the Search Forms page is updated after modifying the search form

**Comment by andrewzimmer** [comment]
build now

**Comment by willwill96** [comment]
build now

**Comment by willwill96** [comment]
build now

**Comment by bdeining** [comment]
build now

**Comment by willwill96** [comment]
build now

**Pull request merged**
