### PR TITLE
DDF-3866 Added ws-security for poller and jolokia to default policy

### PR DESCRIPTION
**Pull request by emanns95**
#### What does this PR do?
Adds recursive ws-security permission to source poller and jolokia.

#### Who is reviewing it? 
(please choose AT LEAST two reviewers that need to approve the PR before it can get merged)
@SmithJosh 
@peterhuffer 
@oconnormi 

#### Select relevant component teams: 
https://github.com/orgs/codice/teams/security
#### Ask 2 committers to review/merge the PR and tag them here. If you don't know who to ask, you can request reviews in https://groups.google.com/forum/#!forum/ddf-developers .
(please choose ONLY two committers from below, delete the rest)
@coyotesqrl
@stustison
#### What are the relevant tickets?
[DDF-3866](https://codice.atlassian.net/browse/DDF-3866)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by emanns95** [comment]
build now

**Comment by SmithJosh** [comment]
Successfully hero'd 💯

**Comment by emanns95** [comment]
Racy tests...
build now

**Comment by emanns95** [comment]
internal CI error
build now

**Comment by emanns95** [comment]
```
Yarn Error

Error Installing packages from yarn.
Note: If this cause shows up, but no other yarn related failure is listed please find the more specific log message and create a new failure cause for it. Thanks!
```
I'll try again tomorrow lol

**Comment by emanns95** [comment]
Let's try this again
build now

**Comment by emanns95** [comment]
OWASP (should be suppressed now)
build now

**Comment by emanns95** [comment]
build now

**Comment by emanns95** [comment]
build now

**Pull request merged**
