### PR TITLE
DDF-5269 Improve styling and layout for Search Button and User

### PR DESCRIPTION
**Pull request by adimka**
#### What does this PR do?
Adjusts spacing/styling for the Search button and the User section. Corrects uneven spacing around the Search button text, and allows for correct spacing and text overflow behavior in the User icon. 

#### Who is reviewing it? 

@TeresaHudson @samuelechu @gordocanchola 
#### Ask 2 committers to review/merge the PR and tag them here.

@djblue
@vinamartin

#### How should this be tested?

UI build, open UI and ensure Search button spacing and User icon spacing is correct.
#### What are the relevant tickets?
Part of: #5269

#### Screenshots

image
image

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by mojogitoverhere** [comment]
build now

**Comment by mojogitoverhere** [comment]
build now

**Comment by adimka** [comment]
build now

**Comment by samuelechu** [comment]
ts spacing/styling for the Search button and the User section. Corrects uneven spacing around the Search button text, and allows for correct spacing and text overflow behavior in the User icon.

Hero successful, verified that:

**Comment by vinamartin** [comment]
This looks good to me, I will merge after @samuelechu 's comment is addressed.

**Pull request merged**
