### PR TITLE
[2.13.x]DDF-4812 Fix user sessions expiring prematurely

### PR DESCRIPTION
**Pull request by brjeter**
#### What does this PR do?
Updates the "expiry" for the session across all contexts, so that the session is refreshed in all contexts.
#### Who is reviewing it? 
@kcover @ahoffer @tyler30clemens @austinsteffes 
#### Ask 2 committers to review/merge the PR and tag them here.
@clockard 
@stustison 
@troymohl 
#### How should this be tested?
- Install DDF
- Go to Intrigue and leave it idle for 11 minutes
- Make sure no red dialog boxes pop up saying "logged out" from the 9-11 minute mark

#### What are the relevant tickets?
Fixes: #4812  

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by brjeter** [comment]
build now

**Comment by brjeter** [comment]
build now

**Comment by brjeter** [comment]
build now

**Comment by brjeter** [comment]
build now

**Comment by tyler30clemens** [comment]
Hero Successful ✅
verified after 15 min (default expiration time) the session expiring notification pops up and logs the user out as expected with no premature session expiration

**Pull request merged**
