### PR TITLE
[2.16.x] DDF-5143 add more robust ingest logging (#5144)

### PR DESCRIPTION
**Pull request by austinsteffes**
master PR here: https://github.com/codice/ddf/pull/5144

What does this PR do?
Adds more robust ingest logging

Who is reviewing it?
@tyler30clemens
@Kjames5269

Ask 2 committers to review/merge the PR and tag them here.
@brjeter
@clockard

How should this be tested?
Any background context you want to provide?
What are the relevant tickets?
Fixes: #5143

Screenshots
Checklist:
  Documentation Updated
  Update / Add Threat Dragon models
  Update / Add Unit Tests
  Update / Add Integration Tests
Notes on Review Process
Please see Notes on Review Process for further guidance on requirements for merging and abbreviated reviews.

Review Comment Legend:
✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist.
❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by austinsteffes** [comment]
build now

**Comment by brjeter** [comment]
✅ Hero successful, per steps followed from the master PR

**Comment by brjeter** [comment]
I aborted the build since itests were timing out.
build now

**Comment by brjeter** [comment]
I aborted the build since itests were timing out.
build now

**Comment by austinsteffes** [comment]
build now

**Pull request merged**
