### PR TITLE
DDF-1471 Fixed various default <select> options in the UI 

### PR DESCRIPTION
**Pull request by bdeining**
(Coordinate Order, Force Spatial Filter Type, Admin UI Style)
Tested on Internet Explorer, FireFox, and Chrome

@kcwire 
@jrnorth is hero
@jlcsmith 
@wmcnalli 

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/164)

### CODE REVIEW

**Comment by wmcnalli** [comment]
Looking at some other metatype files in the baseline, it's inconsistent whether we set the default attribute of the `<AD>` to match the value or the label attribute of the `<Option>` element.  Specifically - https://github.com/codice/ddf/blob/b9ebd98882622169caf9244b5fb1a0487e1c456f/platform/platform-configuration/src/main/resources/OSGI-INF/metatype/metatype.xml 
https://github.com/codice/ddf/blob/b9ebd98882622169caf9244b5fb1a0487e1c456f/platform/admin/ui/src/main/resources/OSGI-INF/metatype/metatype.xml and
https://github.com/codice/ddf/blob/b9ebd98882622169caf9244b5fb1a0487e1c456f/platform/security/handler/security-handler-anonymous/src/main/resources/OSGI-INF/metatype/metatype.xml
Should those defaults be updated to match the value attribute of the `<Option>` element as opposed to the label?

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/164)

**Comment by bdeining** [comment]
The Option default should be set to the value as opposed to the label.  I just updated the other metatype.xml files that Jay pointed out. 

---

Review status: 3 of 5 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/164)

**Comment by kcwire** [comment]
:+1: 

---

Reviewed 3 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/164)

**Comment by jrnorth** [comment]
Confirmed that the default select options work in Chrome, Firefox, and IE. Build was fine except for some of the failing integration tests we've been seeing; I can try again later when I get a chance. :+1:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/164)

**Pull request merged**
