### PR TITLE
[2.13.x] DDF-1397 Upgrades RRD4J and resolves path issue discovered during upgrade

### PR DESCRIPTION
**Pull request by coyotesqrl**
#### What does this PR do?
Upgrades RRD4J and resolves an issue discovered where incorrect paths were set for the admin console.

*Work inadvertently performed on master branch prior to this backport rather than initially on this release branch. This change should be manually re-verified on this branch.*

#### Who is reviewing it? 
@brjeter @pklinef @blen-desta 

#### Ask 2 committers to review/merge the PR and tag them here.

@clockard
@shaundmorris

- Full CI build
- Metrics should be verified

#### What are the relevant tickets?
[DDF-1397](https://codice.atlassian.net/browse/DDF-1397)

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by shaundmorris** [comment]
As part of the Metrics verified, does that include exporting reports from the Admin console?

**Comment by coyotesqrl** [comment]
@shaundmorris Yes. The path change will resolve the issue with exporting reports from the Admin Console.

**Comment by coyotesqrl** [comment]
build now

**Comment by blen-desta** [comment]
✅ Hero'd successfully. Metrics work

**Comment by coyotesqrl** [comment]
Build now

**Pull request merged**
