### PR TITLE
DDF-04318 Temporarily undo recent websockets change which breaks search when there is an unavailable source

### PR DESCRIPTION
**Pull request by brjeter**
#### What does this PR do?
My recent websockets bug fix broke some error cases, such as having an unavailable source: https://github.com/codice/ddf/pull/4368
This reverts that change temporarily to unblock others, and I will put in a permanent fix later.
#### Who is reviewing it? 
@andrewkfiedler @tbatie @tyler30clemens @austinsteffes 

#### How should this be tested?
- Build DDF (include ui in the build)
- Install DDF
- Create two Opensearch sources, 1 with a madeup hostname and 1 with the default loopback value.
- Go to Intrigue and ingest a couple of records
- Try and execute the default wildcard search
- It should return records but show a red triangle indicating one of the sources is unavailable
#### What are the relevant tickets?
For GH Issues:
Fixes: #4318

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by brjeter** [comment]
build now

**Comment by andrewkfiedler** [comment]
build now

**Comment by andrewkfiedler** [comment]
build now

**Comment by andrewkfiedler** [comment]
Hero worked: 🎉

**Pull request merged**
