### PR TITLE
DDF-2349 Fixed NaN on ingest modal

### PR DESCRIPTION
**Pull request by bdeining**
#### What does this PR do?
This PR fixes a bug where the Ingest Modal in the Standard Search UI initially showed `NaN%` instead of 0.
#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?
@lcrosenbu 
#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@jlcsmith
@kcwire
#### How should this be tested?
Build and Install DDF, ingest through the Standard Search UI and observe no `NaN%` when starting the uploads.
#### What are the relevant tickets?
https://codice.atlassian.net/browse/DDF-2349
#### Screenshots (if appropriate)
https://codice.atlassian.net/browse/DDF-2349
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by shaundmorris** [comment]
@bdeining can we plan on backporting this one as well?

**Comment by bdeining** [comment]
@shaundmorris i'll check 2.9.3 and backport it if needed

**Comment by jlcsmith** [comment]
👍

**Comment by bdeining** [comment]
@shaundmorris Backport : https://github.com/codice/ddf/pull/1297

**Comment by lcrosenbu** [comment]
Built and tested using clean repo. :+1:

**Pull request merged**
