### PR TITLE
Investigate intermittent karaf feature file itest failures

### PR DESCRIPTION
**Pull request by figliold**
#### What does this PR do?
DO NOT MERGE!!!!

Since the feature file itest failures seem to happen in the CI environment,  logging has been added to FeatureUtilities.installFeature(), so we can get a better idea of the state of the container when a failure happens.

#### Select relevant component teams: 
https://github.com/orgs/codice/teams
#### What are the relevant tickets?
[](https://codice.atlassian.net/browse/)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by figliold** [comment]
build now

**Comment by figliold** [comment]
build now

**Comment by figliold** [comment]
build now

**Comment by figliold** [comment]
build now

**Comment by figliold** [comment]
build now

**Comment by figliold** [comment]
build now

**Comment by figliold** [comment]
build now

**Comment by figliold** [comment]
build now

**Comment by figliold** [comment]
build now

**Comment by figliold** [comment]
build now

**Comment by figliold** [comment]
build now

**Comment by figliold** [comment]
build now

**Comment by figliold** [comment]
build now

**Comment by figliold** [comment]
build now

**Comment by figliold** [comment]
build now

**Comment by figliold** [comment]
build now

**Comment by rzwiefel** [comment]
This PR seems to be fairly stale- Any objections against closing this PR?

**Pull request closed without merging**
