### PR TITLE
[2.26.x] Match on any OR for TagsFilterDelegate

### PR DESCRIPTION
**Pull request by stevenmalmgren**
#### What does this PR do?
The TagsFilterDelegate needs to allow for OR to match on any instances so users can query local sources and remote sources that don't have metacard-tags, like cached federated data, at the same time. 
#### What are the relevant tickets?
Fixes: #____

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Review by andrewkfiedler — APPROVED** [review]

**Review by austinsteffes-aus — APPROVED** [review]

**Review by vinamartin — APPROVED** [review]

**Review by derekwilhelm — APPROVED** [review]

**Comment by vinamartin** [comment]
Pulling this down to test.

**Comment by vinamartin** [comment]
build now

**Comment by vinamartin** [comment]
Pulled down and tested by checking the network tab on outgoing queries and the query looks like what I expect. ✅ 
Looks like you may have to update the tests for this change.

**Comment by jlcsmith** [comment]
build now

**Comment by vinamartin** [comment]
❗ Update tests

**Comment by vinamartin** [comment]
build now

**Comment by stevenmalmgren** [comment]
build now

**Comment by vinamartin** [comment]
build now

**Comment by stevenmalmgren** [comment]
build now

**Comment by vinamartin** [comment]
build now

**Comment by austinsteffes-aus** [comment]
build now

**Comment by vinamartin** [comment]
build now

**Comment by vinamartin** [comment]
build now

**Comment by vinamartin** [comment]
This may need to be rebased in order to pass CI.

**Comment by SmithJosh** [comment]
Closing as OBE. These changes were merged in https://github.com/codice/ddf/pull/6481

**Pull request closed without merging**
