### PR TITLE
[2.13.x] DDF-4162 Updated CDM documentation

### PR DESCRIPTION
**Pull request by kof-f**
#### What does this PR do?
This PR adds a note in the CDM documentation to account for when a metacard points to a resource outside of CDM. 

#### Who is reviewing it? 
@emmberk 
@peterhuffer 

#### Select relevant component teams: 
https://github.com/orgs/codice/teams

#### Ask 2 committers to review/merge the PR and tag them here.
@clockard
@ricklarsen 

#### How should this be tested?
Builds successfully. 

#### What are the relevant tickets?
[DDF-4162](https://codice.atlassian.net/browse/DDF-4162)

#### Checklist:
- [x] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by coyotesqrl** [comment]
I suspect this PR is incorrect. It was supposed to be opened against 2.13.x, yes?

**Comment by kof-f** [comment]
> I suspect this PR is incorrect. It was supposed to be opened against 2.13.x, yes?

Yes, you're right. Just changed it with @blen-desta's help!

**Comment by kof-f** [comment]
build now

**Comment by kof-f** [comment]
build now

**Comment by kof-f** [comment]
Just showing you guys I didn't break the docs 😄 
adoc-is-good

**Comment by clockard** [comment]
build now

**Pull request merged**
