### PR TITLE
[2.26.x] Fix TestSecurity#testBasicFederatedAuth

### PR DESCRIPTION
**Pull request by SmithJosh**
#### What does this PR do?
Fixes a race condition in TestSecurity#testBasicFederatedAuth where a CSW source under test wasn't being created in time.

#### Select relevant component teams: 

@codice/security 
@codice/test 
@codice/continuous-integration 

#### How should this be tested?

CI

#### What are the relevant tickets?
Fixes: #____

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by SmithJosh** [comment]
build now

**Review by stevenmalmgren — APPROVED** [review]

**Review by emmberk — APPROVED** [review]

**Review by vinamartin — APPROVED** [review]

**Comment by SmithJosh** [comment]
itests failed because Solr didn't come up. Trying again

build now

**Comment by vinamartin** [comment]
`Condition with alias 'Waiting for CatalogProvider to become available.' didn't complete`

build now

**Comment by SmithJosh** [comment]
Third failure in a row due to Solr. It's not even failing on the same module as these changes 🤔

**Comment by SmithJosh** [comment]
The incremental build is running itests when it shouldn't. I think it's related to these changes that were merged yesterday: https://github.com/codice/ddf/pull/6413. Rebased and trying again.

build now

**Comment by SmithJosh** [comment]
Failed earlier this time. Possibly flakey since it didn't fail the other times, but still related to Solr. Trying again to see what happens. Confirmed at least that the itests were ignored correctly during incremental build on the last run

build now

**Pull request merged**
