### PR TITLE
[2.26.x] DDF-6599 detect an ExceptionReport, log it, and set hit count to -1

### PR DESCRIPTION
**Pull request by glenhein**
What does this PR do?

Note: This PR is a redo of the origin PR https://github.com/codice/ddf/pull/6600, because the PR was accidentally merged prematurely. 

Update the camel route used for WFS to detect the ExceptionReport and throw it so callers can handle it. Update WfsSource to catch the exception, log it, and set the hit count to -1 as per the SourceResponse API.

Who is reviewing it?

@jlcsmith
@derekwilhelm

Select relevant component teams:

@codice/ogc

Ask 2 committers to review/merge the PR and tag them here.

@brendan-hofmann
@pklinef

How should this be tested?

This can only be tested if you have a WFS server that returns an ExceptionReport for the hit count, but sends valid objects for the results query. I do not have a publicly available server for this. However, there is a mock server and test in TestSpatial that reproduces the scenario.

Any background context you want to provide?

This affects a downstream project.

What are the relevant tickets?

Fixes: #6599

Screenshots

Checklist:

  Documentation Updated
  Update / Add Threat Dragon models
  Update / Add Unit Tests
  Update / Add Integration Tests
Notes on Review Process

Please see Notes on Review Process for further guidance on requirements for merging and abbreviated reviews.

Review Comment Legend:

✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist.
❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Review by jlcsmith — APPROVED** [review]

**Comment by jlcsmith** [comment]
build now

**Comment by glenhein** [comment]
build now

**Review by derekwilhelm — APPROVED** [review]

**Comment by glenhein** [comment]
build now

**Review by pklinef — APPROVED** [review]

**Comment by glenhein** [comment]
build now

**Pull request merged**
