### PR TITLE
DDF-2520: Protects FileSystemStorageProvider from null resource URIs

### PR DESCRIPTION
**Pull request by rzwiefel**
#### What does this PR do?

see title.
#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged)?

@jrnorth 
@peterhuffer 
#### Select at least one member from relevant component team(s) from below (at least one component team member needs to approve the PR).

[Core APIs](https://github.com/orgs/codice/teams/core-apis)
#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).

@lessarderic
@stustison

### CODE REVIEW

**Comment by stustison** [comment]
This looks like something that needs back ported.

**Comment by rzwiefel** [comment]
All updates from master PR pulled over.

**Comment by rzwiefel** [comment]
All comments addressed

**Comment by rzwiefel** [comment]
Hero build successful.

**Pull request merged**
