### PR TITLE
DDF-3276 Adds preview tab for results with previews available

### PR DESCRIPTION
**Pull request by andrewkfiedler**
Depends on https://github.com/codice/ddf/pull/2303 for testing.  No issues on which goes in first though, the tab just won't appear without it.

@jlcsmith
@kcwire
@pklinef

### CODE REVIEW

**Comment by jlcsmith** [comment]
build now

**Comment by jlcsmith** [comment]
build now

**Comment by jlcsmith** [comment]
build now

**Comment by clockard** [comment]
build now

**Comment by rzwiefel** [comment]
build now

**Comment by jlcsmith** [comment]
build now

**Comment by rzwiefel** [comment]
build now

**Comment by andrewkfiedler** [comment]
build now

**Comment by jlcsmith** [comment]
pdf-preview

**Pull request merged**
