### PR TITLE
DDF-UI-198 Fix near queries not returning results

### PR DESCRIPTION
**Pull request by zta6**
2.19.x port of https://github.com/codice/ddf-ui/pull/200

What does this PR do?
Fixes a silent error that was causing 'near' queries to fail to return results. 

Who is reviewing it?
@hayleynorton @cassandrabailey293  @andrewzimmer

Select relevant component teams:

Ask 2 committers to review/merge the PR and tag them here.
@bdeining 
@Bdthomson 

How should this be tested?
Build, profile:install
Ingest some metacards
Run some 'near' queries and verify that the proper results are returned. 

Any background context you want to provide?

What are the relevant tickets?
Fixes: DDF-UI-198

Screenshots
Checklist:
 Documentation Updated
 Update / Add Threat Dragon models
 Update / Add Unit Tests
 Update / Add Integration Tests
Notes on Review Process
Please see Notes on Review Process for further guidance on requirements for merging and abbreviated reviews.

Review Comment Legend:
✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist.
❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by zta6** [comment]
build now

**Comment by andrewzimmer** [comment]
I think you'll need to update the spec file because its still expecting a string https://github.com/zta6/ddf/blob/DDF-UI-198_2.19.x/ui/packages/catalog-ui-search/src/main/webapp/react-component/filter/filter-input/filter-text-inputs/filter-near-input/nearFilterHelper.spec.js#L31

**Comment by zta6** [comment]
build now

**Comment by andrewzimmer** [comment]
Hero Successful 🎉 
- verified near query is working as expected

**Pull request merged**
