### PR TITLE
DDF-3719 Add query-settings extensibility

### PR DESCRIPTION
**Pull request by adimka**
#### What does this PR do?
Adds extensibility plugin support to query-settings.
#### Who is reviewing it? 
(please choose AT LEAST two reviewers that need to approve the PR before it can get merged)
@djblue @GabrielFabian @mackncheesiest 
#### Select relevant component teams: 
https://github.com/orgs/codice/teams
#### Ask 2 committers to review/merge the PR and tag them here. If you don't know who to ask, you can request reviews in https://groups.google.com/forum/#!forum/ddf-developers .
(please choose ONLY two committers from below, delete the rest)
@andrewkfiedler
@bdeining
#### How should this be tested? (List steps with links to updated documentation)
CI build, verify UI loads properly, and you can view query settings.
#### What are the relevant tickets?
[DDF-3719](https://codice.atlassian.net/browse/DDF-3719)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by adimka** [comment]
build now

**Comment by mackncheesiest** [comment]
Network issue while downloading CVE artifacts

build now

**Comment by mackncheesiest** [comment]
It's worth noting that the rendering of downstream extensions are [currently gated](https://github.com/adimka/ddf/blob/1470936636cee58eb41e90a1c5bb2361b8e92c96/ui/packages/catalog-ui-search/src/main/webapp/component/query-settings/query-settings.view.js#L97-L100) by `properties.hasExperimentalEnabled()` because of its placement in this function. Is that what we want as intended behavior?

**Comment by mackncheesiest** [comment]
build now

**Comment by mackncheesiest** [comment]
build now

**Comment by mackncheesiest** [comment]
Verified that `query-settings.view.js` still properly loads with these changes in place
image

**Pull request merged**
