### PR TITLE
DDF 1363

### PR DESCRIPTION
**Pull request by ahoffer**
@stustison @AzGoalie 

Implements two MBean services:

```
configureDemoCert(String commonName)
configureDemoCertWithDefaultHostname
```

This commit implements a KeyStoreFile class that duplicates some of the work in the KeystoreEditor class. I don't want to hold this up any longer, though. I can write a separate technical debt ticket to switch over to KeystoreEditor.

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/190)

### CODE REVIEW

**Comment by vinamartin** [comment]
Review status: 0 of 20 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

<sup>**[distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSecurity.java, line 89 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/190#-JzugBjxSR2HItc3VxcS)** ([raw file](https://github.com/codice/ddf/blob/a26ae0abc754408f4380515873a373df66c6e524/distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSecurity.java#L89)):</sup>
Even though this is just a test , if possible, I would recommend not hardcoding the protocol and port. You should be able to find them being used in other tests. 

---

<sup>**[platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/CertificateAuthority.java, line 61 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/190#-JzuiauMIz9bh5gPyLLm)** ([raw file](https://github.com/codice/ddf/blob/a26ae0abc754408f4380515873a373df66c6e524/platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/CertificateAuthority.java#L61)):</sup>
:joy:

---

<sup>**[platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/DemoCertificateAuthority.java, line 17 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/190#-JzujtLIj-cw0lZgRvVF)** ([raw file](https://github.com/codice/ddf/blob/a26ae0abc754408f4380515873a373df66c6e524/platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/DemoCertificateAuthority.java#L17)):</sup>
I wonder if it's better to have these as strings or read in from files. 
Is there any other part of the code that is doing something similar that we could refer to?

---

<sup>**[platform/security/certificate/security-certificate-generator/src/test/java/org/codice/ddf/security/certificate/generator/KeyStoreFileTest.java, line 81 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/190#-JzullbJLynDhEv4Bmf2)** ([raw file](https://github.com/codice/ddf/blob/a26ae0abc754408f4380515873a373df66c6e524/platform/security/certificate/security-certificate-generator/src/test/java/org/codice/ddf/security/certificate/generator/KeyStoreFileTest.java#L81)):</sup>
A little confused with this comment. So basically, if there are no read permissions on a file, you can't access it so it throws an exception?
Could you provide more details? 

---

<sup>**[platform/security/certificate/security-certificate-generator/src/test/java/org/codice/ddf/security/certificate/generator/KeyStoreFileTest.java, line 114 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/190#-JzumJjs_7gWxPRVKxVs)** ([raw file](https://github.com/codice/ddf/blob/a26ae0abc754408f4380515873a373df66c6e524/platform/security/certificate/security-certificate-generator/src/test/java/org/codice/ddf/security/certificate/generator/KeyStoreFileTest.java#L114)):</sup>
There's no implementation in this test.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/190)

**Comment by ahoffer** [comment]
Review status: 0 of 20 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSecurity.java, line 89 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/190#-JzugBjxSR2HItc3VxcS)** ([raw file](https://github.com/codice/ddf/blob/a26ae0abc754408f4380515873a373df66c6e524/distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSecurity.java#L89)):</sup>
I thought about refactoring the parent class `AbstractIntegrationTest` because it defines the these values: 

```
protected static final String SERVICE_ROOT = "https://localhost:" + HTTPS_PORT + "/services";
protected static final String INSECURE_SERVICE_ROOT = "http://localhost:" + HTTP_PORT + "/services";
```

I didn't want to touch too many classes, but it would be a pretty safe refactoring. How about this:
```
protected static final String SECURE_ROOT = "https://localhost:";
protected static final StringINSECURE_ROOT = "http://localhost:";
protected static final String SERVICE_ROOT = SECURE_ROOT + HTTPS_PORT + "/services";
protected static final String INSECURE_SERVICE_ROOT = INSECURE_ROOT + HTTP_PORT + "/services";
```

---

<sup>**[platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/CertificateAuthority.java, line 0 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/190#-JzuiauMIz9bh5gPyLLm)** ([raw file](https://github.com/codice/ddf/blob/a26ae0abc754408f4380515873a373df66c6e524/platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/CertificateAuthority.java#L0)):</sup>
Crying bad or crying good?

---

<sup>**[platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/DemoCertificateAuthority.java, line 0 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/190#-JzujtLIj-cw0lZgRvVF)** ([raw file](https://github.com/codice/ddf/blob/a26ae0abc754408f4380515873a373df66c6e524/platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/DemoCertificateAuthority.java#L0)):</sup>
I thought about that. I decided to make a generic super class, CertificateAuthority that can take external values. The subclass, DemoCertificateAuthority represents a single CA, the one we use to authenticate for testing. I decided I wanted to avoid file I/O because it represents a possible point of failure and external dependency (e.g. outside of JVM). 

A better place for it would be the system.properties file, but that file is not read as part of unit tests. I would have to shift the real functional testing out of the unit tests and into the integration tests if I went that route. Ultimately, I decided string literals was the lesser of evils. But I'm open to discussion on moving the functional testing into the itests.

---

<sup>**[platform/security/certificate/security-certificate-generator/src/test/java/org/codice/ddf/security/certificate/generator/KeyStoreFileTest.java, line 0 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/190#-JzullbJLynDhEv4Bmf2)** ([raw file](https://github.com/codice/ddf/blob/a26ae0abc754408f4380515873a373df66c6e524/platform/security/certificate/security-certificate-generator/src/test/java/org/codice/ddf/security/certificate/generator/KeyStoreFileTest.java#L0)):</sup>
That's exactly right. If you cannot read the file, it throws an exception. It was one of the branches in the file I/O process I needed to account for.

---

<sup>**[platform/security/certificate/security-certificate-generator/src/test/java/org/codice/ddf/security/certificate/generator/KeyStoreFileTest.java, line 0 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/190#-JzumJjs_7gWxPRVKxVs)** ([raw file](https://github.com/codice/ddf/blob/a26ae0abc754408f4380515873a373df66c6e524/platform/security/certificate/security-certificate-generator/src/test/java/org/codice/ddf/security/certificate/generator/KeyStoreFileTest.java#L0)):</sup>
Yikes. Thanks. The functionality is tested in the method `addAndRemoveEntry() ` so I removed the  unused method.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/190)

**Comment by vinamartin** [comment]
Review status: 0 of 20 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSecurity.java, line 89 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/190#-JzugBjxSR2HItc3VxcS)** ([raw file](https://github.com/codice/ddf/blob/a26ae0abc754408f4380515873a373df66c6e524/distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSecurity.java#L89)):</sup>
This will probably be safer so it can be changed later.
However, don't forget a space between String and INSECURE_ROOT or you won't be able to get it to work :thumbsup: 

---

<sup>**[platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/CertificateAuthority.java, line 0 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/190#-JzuiauMIz9bh5gPyLLm)** ([raw file](https://github.com/codice/ddf/blob/a26ae0abc754408f4380515873a373df66c6e524/platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/CertificateAuthority.java#L0)):</sup>
I laughed at this comment

---

<sup>**[platform/security/certificate/security-certificate-generator/src/test/java/org/codice/ddf/security/certificate/generator/KeyStoreFileTest.java, line 0 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/190#-JzumJjs_7gWxPRVKxVs)** ([raw file](https://github.com/codice/ddf/blob/a26ae0abc754408f4380515873a373df66c6e524/platform/security/certificate/security-certificate-generator/src/test/java/org/codice/ddf/security/certificate/generator/KeyStoreFileTest.java#L0)):</sup>
Alright, looks like you can just remove this then. :)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/190)

**Comment by clockard** [comment]
Review status: 0 of 20 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSecurity.java, line 91 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/190#-JzugBjxSR2HItc3VxcS)** ([raw file](https://github.com/codice/ddf/blob/a26ae0abc754408f4380515873a373df66c6e524/distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSecurity.java#L91)):</sup>
You can find some of this in the AbstractIntegrationTest. If you need something that isn't there I would recommend add it there.

---

<sup>**[distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSecurity.java, line 404 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/190#-Jzup2h6WKlhmYN3f4mN)** ([raw file](https://github.com/codice/ddf/blob/b3561d0ed8638959a217ec63975dc6f49e4388c5/distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSecurity.java#L404)):</sup>
Might consider renaming this to something like getKeystoreFilename. Same with the getBackupFilename

---

<sup>**[platform/security/certificate/security-certificate-generator/pom.xml, line 103 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/190#-JzuqETE8gELc1Iw7SKy)** ([raw file](https://github.com/codice/ddf/blob/b3561d0ed8638959a217ec63975dc6f49e4388c5/platform/security/certificate/security-certificate-generator/pom.xml#L103)):</sup>
Haven't looked at the actual code yet but just wanted to make sure that we want .60 coverage as opposed to .75 for new code. 

---

<sup>**[platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/DemoCertificateAuthority.java, line 17 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/190#-JzujtLIj-cw0lZgRvVF)** ([raw file](https://github.com/codice/ddf/blob/a26ae0abc754408f4380515873a373df66c6e524/platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/DemoCertificateAuthority.java#L17)):</sup>
Could you use a system property to just point to the location of demo certs and read them from there? When you are running your unit tests you could just set the system property differently to point to some test resource that has the needed information.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/190)

**Comment by clockard** [comment]
Reviewed 19 of 20 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/190)

**Comment by clockard** [comment]
There is definitely some overlap with earlier work. Make sure we make a ticket to merge the logic and update UI to use this new functionality.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/190)

**Comment by brendan-hofmann** [comment]
Reviewed 19 of 20 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

<sup>**[platform/security/certificate/security-certificate-generator/pom.xml, line 80 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/190#-JzuzbZzKQ-Vy05KmcNQ)** ([raw file](https://github.com/codice/ddf/blob/b3561d0ed8638959a217ec63975dc6f49e4388c5/platform/security/certificate/security-certificate-generator/pom.xml#L80)):</sup>
This is the default behavior, you don't need to specify it. ;) http://felix.apache.org/documentation/subprojects/apache-felix-maven-bundle-plugin-bnd.html

---

<sup>**[platform/security/certificate/security-certificate-generator/pom.xml, line 103 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/190#-JzuqETE8gELc1Iw7SKy)** ([raw file](https://github.com/codice/ddf/blob/b3561d0ed8638959a217ec63975dc6f49e4388c5/platform/security/certificate/security-certificate-generator/pom.xml#L103)):</sup>
.75 is the default still. Sometimes there are exceptions for a ton of getters/setters and whatnot.

---

<sup>**[platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/CertificateAuthority.java, line 57 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/190#-Jzv0v9rzXLEInqEtatB)** ([raw file](https://github.com/codice/ddf/blob/b3561d0ed8638959a217ec63975dc6f49e4388c5/platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/CertificateAuthority.java#L57)):</sup>
Why do you need a package-private constructor?

---

<sup>**[platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/KeyStoreFile.java, line 96 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/190#-Jzv1vSV62saWGB4Ve9g)** ([raw file](https://github.com/codice/ddf/blob/b3561d0ed8638959a217ec63975dc6f49e4388c5/platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/KeyStoreFile.java#L96)):</sup>
The method right above this has such good javadoc, what happened? :( Would be nice if all methods that can return null were documented as such.

---

<sup>**[platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/PkiTools.java, line 45 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/190#-Jzv2Gxm4_Y_JW3UBcvJ)** ([raw file](https://github.com/codice/ddf/blob/b3561d0ed8638959a217ec63975dc6f49e4388c5/platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/PkiTools.java#L45)):</sup>
"that were did not" I think you have an extra word in there.

---

<sup>**[platform/security/certificate/security-certificate-generator/src/test/java/org/codice/ddf/security/certificate/generator/KeyStoreFileTest.java, line 82 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/190#-Jzv3ETns1aft-cSqpHC)** ([raw file](https://github.com/codice/ddf/blob/b3561d0ed8638959a217ec63975dc6f49e4388c5/platform/security/certificate/security-certificate-generator/src/test/java/org/codice/ddf/security/certificate/generator/KeyStoreFileTest.java#L82)):</sup>
This sentence is confusing, but I don't see why you couldn't mock out whatever you're having issues with.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/190)

**Comment by ahoffer** [comment]
Done. Added *Elimate duplicated functionality between the security-certificate-generator and the security-keystoreeditor modules* to DIB-2859 (https://jira.di2e.net/browse/DIB-2859). This ticket is tentatively scheduled for sprint 8.

---

Review status: all files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

<sup>**[distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSecurity.java, line 0 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/190#-Jzup2h6WKlhmYN3f4mN)** ([raw file](https://github.com/codice/ddf/blob/b3561d0ed8638959a217ec63975dc6f49e4388c5/distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSecurity.java#L0)):</sup>
Sounds good. Done.

---

<sup>**[platform/security/certificate/security-certificate-generator/pom.xml, line 0 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/190#-JzuqETE8gELc1Iw7SKy)** ([raw file](https://github.com/codice/ddf/blob/b3561d0ed8638959a217ec63975dc6f49e4388c5/platform/security/certificate/security-certificate-generator/pom.xml#L0)):</sup>
Some reasons code coverage is low are exception handling and MBean overhead . Some exceptions, like the user not having permissions to read the file are difficult to test and probably not very interesting. Also, most of the bean code is boilerplate MBean lifecycle code. It is tested by the integration tests when the application is up and running. Last time I ran  code coverage, the source code got 0.64. I rounded down to 0.60 in the POM file. 

---

<sup>**[platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/DemoCertificateAuthority.java, line 17 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/190#-JzujtLIj-cw0lZgRvVF)** ([raw file](https://github.com/codice/ddf/blob/a26ae0abc754408f4380515873a373df66c6e524/platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/DemoCertificateAuthority.java#L17)):</sup>
The system.properties file is not read as part of unit tests. I would have to shift the real functional testing out of the unit tests and into the integration tests if I went that route. Isolating the bits in a subclass seems the least bad thing to do. 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/190)

**Comment by brendan-hofmann** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

<sup>**[platform/security/certificate/security-certificate-generator/pom.xml, line 103 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/190#-JzuqETE8gELc1Iw7SKy)** ([raw file](https://github.com/codice/ddf/blob/b3561d0ed8638959a217ec63975dc6f49e4388c5/platform/security/certificate/security-certificate-generator/pom.xml#L103)):</sup>
Please don't round down. Put exactly what the current coverage is.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/190)

**Comment by harrison-tarr** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions, all commit checks successful.

---

<sup>**[platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/CertificateGenerator.java, line 54 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/190#-Jzv0cwIXnsRgXbOMjUH)** ([raw file](https://github.com/codice/ddf/blob/b3561d0ed8638959a217ec63975dc6f49e4388c5/platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/CertificateGenerator.java#L54)):</sup>
does this need a declaration as public or private?

---

<sup>**[platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/CertificateGenerator.java, line 77 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/190#-Jzv13uUATnQ8rLbGGTv)** ([raw file](https://github.com/codice/ddf/blob/b3561d0ed8638959a217ec63975dc6f49e4388c5/platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/CertificateGenerator.java#L77)):</sup>
does this happen fast enough that you can immediately register it again?

---

<sup>**[platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/CertificateSigningRequest.java, line 43 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/190#-Jzv1LjtMDK-khd-2cPN)** ([raw file](https://github.com/codice/ddf/blob/b3561d0ed8638959a217ec63975dc6f49e4388c5/platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/CertificateSigningRequest.java#L43)):</sup>
looks like a typo in "Certificate"

---

<sup>**[platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/KeyStoreFile.java, line 92 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/190#-Jzv3KChrleX5iebOoWZ)** ([raw file](https://github.com/codice/ddf/blob/b3561d0ed8638959a217ec63975dc6f49e4388c5/platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/KeyStoreFile.java#L92)):</sup>
this doesn't have it returning null in the error case, unless i'm misreading the code

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/190)

**Comment by clockard** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions, all commit checks successful.

---

<sup>**[platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/DemoCertificateAuthority.java, line 17 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/190#-JzujtLIj-cw0lZgRvVF)** ([raw file](https://github.com/codice/ddf/blob/a26ae0abc754408f4380515873a373df66c6e524/platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/DemoCertificateAuthority.java#L17)):</sup>
Since the system properties file isn't read for the unit tests you could set the needed property just using System.setProperty before you call this class.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/190)

**Comment by ahoffer** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions, all commit checks successful.

---

<sup>**[platform/security/certificate/security-certificate-generator/pom.xml, line 80 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/190#-JzuzbZzKQ-Vy05KmcNQ)** ([raw file](https://github.com/codice/ddf/blob/b3561d0ed8638959a217ec63975dc6f49e4388c5/platform/security/certificate/security-certificate-generator/pom.xml#L80)):</sup>
Removed superfluous <Import-Package> directive.

---

<sup>**[platform/security/certificate/security-certificate-generator/pom.xml, line 103 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/190#-JzuqETE8gELc1Iw7SKy)** ([raw file](https://github.com/codice/ddf/blob/b3561d0ed8638959a217ec63975dc6f49e4388c5/platform/security/certificate/security-certificate-generator/pom.xml#L103)):</sup>
Oh, OK...  Fixed.

---

<sup>**[platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/CertificateAuthority.java, line 0 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/190#-Jzv0v9rzXLEInqEtatB)** ([raw file](https://github.com/codice/ddf/blob/b3561d0ed8638959a217ec63975dc6f49e4388c5/platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/CertificateAuthority.java#L0)):</sup>
IntelliJ turns the constructor, DemoCertificateAuthority, in the subclass red and complains about no default constructor available in the superclass.  So I added one. I can make it package-local or protected.

---

<sup>**[platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/CertificateGenerator.java, line 0 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/190#-Jzv0cwIXnsRgXbOMjUH)** ([raw file](https://github.com/codice/ddf/blob/b3561d0ed8638959a217ec63975dc6f49e4388c5/platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/CertificateGenerator.java#L0)):</sup>
Made it private.

---

<sup>**[platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/CertificateGenerator.java, line 0 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/190#-Jzv13uUATnQ8rLbGGTv)** ([raw file](https://github.com/codice/ddf/blob/b3561d0ed8638959a217ec63975dc6f49e4388c5/platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/CertificateGenerator.java#L0)):</sup>
Good catch.

---

<sup>**[platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/CertificateSigningRequest.java, line 0 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/190#-Jzv1LjtMDK-khd-2cPN)** ([raw file](https://github.com/codice/ddf/blob/b3561d0ed8638959a217ec63975dc6f49e4388c5/platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/CertificateSigningRequest.java#L0)):</sup>
fixed it.

---

<sup>**[platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/DemoCertificateAuthority.java, line 0 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/190#-JzujtLIj-cw0lZgRvVF)** ([raw file](https://github.com/codice/ddf/blob/a26ae0abc754408f4380515873a373df66c6e524/platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/DemoCertificateAuthority.java#L0)):</sup>
Setting the property before calling it would work.
It creates three new dependencies, though. (1) The property name in the properties file needs to match the property name in the unit test, (2) the property itself has to point to the right file, and  (3) the external file that contains the data must exists. If there is anyway I can leave  string literal in the class, I'd like to.  It has the fewest points of possible failure.

---

<sup>**[platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/KeyStoreFile.java, line 0 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/190#-Jzv1vSV62saWGB4Ve9g)** ([raw file](https://github.com/codice/ddf/blob/b3561d0ed8638959a217ec63975dc6f49e4388c5/platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/KeyStoreFile.java#L0)):</sup>
Updated javadoc documents for all public methods.

---

<sup>**[platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/KeyStoreFile.java, line 0 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/190#-Jzv3KChrleX5iebOoWZ)** ([raw file](https://github.com/codice/ddf/blob/b3561d0ed8638959a217ec63975dc6f49e4388c5/platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/KeyStoreFile.java#L0)):</sup>
Thanks. I updated the comments.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/190)

**Comment by clockard** [comment]
Reviewed 10 of 10 files at r3.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

<sup>**[distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/AbstractIntegrationTest.java, line 98 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/190#-JzvyljedH5jeYu20Pbr)** ([raw file](https://github.com/codice/ddf/blob/98e7acbf3bb0bc70543c567baa563f3b2f70beba/distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/AbstractIntegrationTest.java#L98)):</sup>
:+1: 

---

<sup>**[platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/CertificateGenerator.java, line 96 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/190#-JzvxZmOJPB0SNu3lpmX)** ([raw file](https://github.com/codice/ddf/blob/98e7acbf3bb0bc70543c567baa563f3b2f70beba/platform/security/certificate/security-certificate-generator/src/main/java/org/codice/ddf/security/certificate/generator/CertificateGenerator.java#L96)):</sup>
Don't think this log statement is valid anymore

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/190)

**Comment by harrison-tarr** [comment]
Reviewed 1 of 10 files at r3.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/190)

**Comment by clockard** [comment]
Built and ran successfully with the exception of one itest that has a known issue.
I was able to start ddf and exercise the jolokia endpoints successfully.
:+1:

**Comment by AzGoalie** [comment]
Reviewed 7 of 10 files at r3.
Review status: 20 of 21 files reviewed at latest revision, 10 unresolved discussions, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/190)

**Comment by brendan-hofmann** [comment]
:+1: lgtm

---

Reviewed 10 of 10 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/190)

**Pull request merged**
