### PR TITLE
DDF-2446 Fix view/model sync in query multiselects

### PR DESCRIPTION
**Pull request by brendan-hofmann**
#### What does this PR do?
Add refresh calls when Specific Sources or Specific Types are selected.
This keeps them up to the date with the model changes caused by the
other options.
#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?
@andrewkfiedler @emanns95
#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@lessarderic
@pklinef
@shaundmorris
@stustison
#### How should this be tested?
Follow the instructions in the ticket and verify it no longer misbehaves. Test both Types and Sources.
#### What are the relevant tickets?
https://codice.atlassian.net/browse/DDF-2446
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by emanns95** [comment]
LGTM :+1:

**Comment by lessarderic** [comment]
:shipit:

**Comment by pklinef** [comment]
:+1:

**Comment by stustison** [comment]
Are you sure you put enough committers on there? ;) 👍

**Comment by emanns95** [comment]
Verified manually :+1:

**Pull request merged**
