### PR TITLE
DDF-1449 added an admin ui module for editing the system keystore/truststore

### PR DESCRIPTION
**Pull request by stustison**
@clockard @brendan-hofmann @coyotesqrl 

This editor is as done as it is going to get for now. We are going to toss it into Admin UI and we'll see if anyone uses it. It allows you to add and remove the most common keys and certs from the keystore and truststore, such as pem, der, p7b, p12, and jks.

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/147)

### CODE REVIEW

**Comment by clockard** [comment]
Reviewed 66 of 66 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

<sup>**[platform/security/certificate/security-certificate-adminmodule/bower.json, line 32 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy8VjSLTxYi7igD5UVp)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-adminmodule/bower.json#L32)):</sup>
I thought we were trying to avoid using the '~' operator on versions since new versions could cause race conditions

---

<sup>**[platform/security/certificate/security-certificate-adminmodule/Gruntfile.js, line 61 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy8WnMhHhbtS7d2si0T)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-adminmodule/Gruntfile.js#L61)):</sup>
the properties and config js files could be removed here

---

<sup>**[platform/security/certificate/security-certificate-adminmodule/package.json, line 16 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy8WwXCX5D6V2GkAffa)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-adminmodule/package.json#L16)):</sup>
I think we want to avoid using the '~' and '^'

---

<sup>**[platform/security/certificate/security-certificate-adminmodule/src/main/webapp/js/HandlebarsHelpers.js, line 16 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy8_Ne8oMjqQcg2IskM)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-adminmodule/src/main/webapp/js/HandlebarsHelpers.js#L16)):</sup>
looks like moment is missing

---

<sup>**[platform/security/certificate/security-certificate-adminmodule/src/main/webapp/js/model/Certificate.js, line 19 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy8bu9jMLYYHiBDB--I)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-adminmodule/src/main/webapp/js/model/Certificate.js#L19)):</sup>
should backboneassociations be added to the function

---

<sup>**[platform/security/certificate/security-certificate-adminmodule/src/main/webapp/js/model/PrivateKey.js, line 20 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy8cnikn2wGAi9K49Aj)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-adminmodule/src/main/webapp/js/model/PrivateKey.js#L20)):</sup>
Again, does backboneassociations added to the function

---

<sup>**[platform/security/certificate/security-certificate-adminmodule/src/main/webapp/js/view/UploadModal.view.js, line 35 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy8jegf6ZztpFO-zJoW)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-adminmodule/src/main/webapp/js/view/UploadModal.view.js#L35)):</sup>
Why not used the fileSize helper in HandlebarsHelpers.js

---

<sup>**[platform/security/certificate/security-certificate-adminmodule/src/main/webapp/main.js, line 14 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy8WXw-WD0UBm5opuql)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-adminmodule/src/main/webapp/main.js#L14)):</sup>
:+1:  for putting the config in main.js 

---

<sup>**[platform/security/certificate/security-certificate-keystoreeditor/pom.xml, line 97 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy8nVHwdjWVOZCbrpLm)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-keystoreeditor/pom.xml#L97)):</sup>
Shouldn't all new code have a minimum of .75 for all categories?

---

<sup>**[platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java, line 239 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy8rINuWQaPm_i_Zs7Q)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java#L239)):</sup>
Does the number of arguments for this method cause a checkstyle error? I thought it had a limit of 7 arguments.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/147)

**Comment by brendan-hofmann** [comment]
Reviewed 66 of 66 files at r1.
Review status: all files reviewed at latest revision, 24 unresolved discussions, all commit checks successful.

---

<sup>**[platform/security-services-app/src/main/resources/features.xml, line 226 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy9213KJJSpD7TkkV85)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security-services-app/src/main/resources/features.xml#L226)):</sup>
Shouldn't this be part of the security-admin-module or the security app so it gets installed automatically?

---

<sup>**[platform/security/certificate/security-certificate-adminmodule/pom.xml, line 87 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy92GvcVQMx7jfQQGnV)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-adminmodule/pom.xml#L87)):</sup>
Shouldn't this at least be under /services, if not /services/security ?

---

<sup>**[platform/security/certificate/security-certificate-adminmodule/server-impl.js, line 20 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy92Rj5njJFVp5CLhGW)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-adminmodule/server-impl.js#L20)):</sup>
Can we use the https proxy here, now that we've figured it out? It will make development easier for future maintainers. Similar to how standard search ui does it.

---

<sup>**[platform/security/certificate/security-certificate-adminmodule/server.js, line 30 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy92si_2Iej3e8IW3wm)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-adminmodule/server.js#L30)):</sup>
If you fix it in server-impl you'll want to proxy '*' here instead.

---

<sup>**[platform/security/certificate/security-certificate-adminmodule/src/main/java/org/codice/ddf/security/certificate/admin/module/CertificateAdminModule.java, line 26 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy935raxgGGof4a6xIE)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-adminmodule/src/main/java/org/codice/ddf/security/certificate/admin/module/CertificateAdminModule.java#L26)):</sup>
Again, why create a whole new root context for this?

---

<sup>**[platform/security/certificate/security-certificate-adminmodule/src/main/webapp/main.js, line 111 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy93q53KRjXTvZjoVFO)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-adminmodule/src/main/webapp/main.js#L111)):</sup>
Looks like underscore, bootstrap, and HandlebarsHelpers are unused here?

---

<sup>**[platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java, line 116 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy95E9HjKfA27nsHEH6)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java#L116)):</sup>
init() exceptions should probably rethrow as well, I doubt this bean will work if it fails.

---

<sup>**[platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java, line 142 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy95OXSivY6vf5VsVy0)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java#L142)):</sup>
I see the exception is called ignore, but why? Are we that sure they'll never happen? Can't we at least log the exception? Same goes for all the other ignored exceptions.

---

<sup>**[platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java, line 249 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy96GJGdyhZaKGKnZ-0)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java#L249)):</sup>
Not short-circuiting on purpose?

---

<sup>**[platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java, line 279 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy96Lwfdw-QxnveNCNK)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java#L279)):</sup>
Why && instead of || for this one?

---

<sup>**[platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java, line 390 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy96bOTcA1_jM4NqeXo)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java#L390)):</sup>
Why are we catching untyped Exception here?

---

<sup>**[platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java, line 394 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy96imVft4YozPahs7z)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java#L394)):</sup>
Why not try-with-resource?

---

<sup>**[platform/security/certificate/security-certificate-keystoreeditor/src/test/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditorTest.java, line 150 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy98ApuoyP449NphtGD)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-keystoreeditor/src/test/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditorTest.java#L150)):</sup>
Minor quibble, but I like static imports better. Makes the tests a little cleaner to read.

---

<sup>**[platform/security/certificate/security-certificate-keystoreeditor/src/test/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditorTest.java, line 170 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy97_M_RoKAAup5eiG-)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-keystoreeditor/src/test/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditorTest.java#L170)):</sup>
Can we AssertThat(anyOf()) for these two instead? Will give better fail messages.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/147)

**Comment by brendan-hofmann** [comment]
Review status: all files reviewed at latest revision, 24 unresolved discussions, all commit checks successful.

---

<sup>**[platform/security/certificate/security-certificate-keystoreeditor/src/test/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditorTest.java, line 170 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy97_M_RoKAAup5eiG-)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-keystoreeditor/src/test/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditorTest.java#L170)):</sup>
Better question is why doesn't the test know which alias to expect? What part of this is non-deterministic?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/147)

**Comment by stustison** [comment]
Review status: 55 of 66 files reviewed at latest revision, 17 unresolved discussions, some commit checks pending.

---

<sup>**[platform/security-services-app/src/main/resources/features.xml, line 226 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy9213KJJSpD7TkkV85)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security-services-app/src/main/resources/features.xml#L226)):</sup>
Yeah, I can do that.

---

<sup>**[platform/security/certificate/security-certificate-adminmodule/bower.json, line 32 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy8VjSLTxYi7igD5UVp)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-adminmodule/bower.json#L32)):</sup>
Not on the resolutions. These will get updated and move all the transitive dependencies along with it to keep things in sync. We just need to get rid of bower.

---

<sup>**[platform/security/certificate/security-certificate-adminmodule/Gruntfile.js, line 61 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy8WnMhHhbtS7d2si0T)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-adminmodule/Gruntfile.js#L61)):</sup>
Done.

---

<sup>**[platform/security/certificate/security-certificate-adminmodule/pom.xml, line 87 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy92GvcVQMx7jfQQGnV)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-adminmodule/pom.xml#L87)):</sup>
No, services is the CXF root. But it should be under admin probably.

---

<sup>**[platform/security/certificate/security-certificate-adminmodule/server-impl.js, line 0 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy92Rj5njJFVp5CLhGW)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-adminmodule/server-impl.js#L0)):</sup>
There isn't any need to because this never performs a PUT. I did all of my development using grunt, it works.

---

<sup>**[platform/security/certificate/security-certificate-adminmodule/src/main/webapp/js/HandlebarsHelpers.js, line 0 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy8_Ne8oMjqQcg2IskM)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-adminmodule/src/main/webapp/js/HandlebarsHelpers.js#L0)):</sup>
It isn't needed for anything.

---

<sup>**[platform/security/certificate/security-certificate-adminmodule/src/main/webapp/js/model/Certificate.js, line 0 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy8bu9jMLYYHiBDB--I)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-adminmodule/src/main/webapp/js/model/Certificate.js#L0)):</sup>
No, associations gets attached to the Backbone object.

---

<sup>**[platform/security/certificate/security-certificate-adminmodule/src/main/webapp/main.js, line 111 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy93q53KRjXTvZjoVFO)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-adminmodule/src/main/webapp/main.js#L111)):</sup>
They are used, they just aren't attached libs.

---

<sup>**[platform/security/certificate/security-certificate-keystoreeditor/pom.xml, line 97 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy8nVHwdjWVOZCbrpLm)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-keystoreeditor/pom.xml#L97)):</sup>
If it makes sense to do so. I didn't think that it made sense to test my if (filextensions is .crt or .pem or .key or .etc) 15 times just to make sure that it works. The coverage number is a guideline and you should try to hit it whenever possible. That doesn't mean that you should sit there writing meaningless tests.

---

<sup>**[platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java, line 116 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy95E9HjKfA27nsHEH6)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java#L116)):</sup>
I don't want it failing at that point, it will be easier to debug if the MBean comes up but the keystore/truststore are unusable.

---

<sup>**[platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java, line 142 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy95OXSivY6vf5VsVy0)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java#L142)):</sup>
It is ignored because we would only care about the log message above it and we don't need two log messages. This case is only hit if someone is trying to load an uninitialized keystore.

---

<sup>**[platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java, line 239 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy8rINuWQaPm_i_Zs7Q)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java#L239)):</sup>
Doesn't appear to. And if we had that limitation, I would have removed it anyways if I had hit it :)

---

<sup>**[platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java, line 249 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy96GJGdyhZaKGKnZ-0)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java#L249)):</sup>
Nope, that is a typo, thanks.

---

<sup>**[platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java, line 279 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy96Lwfdw-QxnveNCNK)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java#L279)):</sup>
Because DER and PEM have the exact same mime type, which is weird because one is binary and the other is text. But I want to be absolutely certain that the thing they are uploading is actually a DER file, otherwise I want it to run through the PEM parser.

---

<sup>**[platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java, line 390 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy96bOTcA1_jM4NqeXo)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java#L390)):</sup>
To catch everything.

---

<sup>**[platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java, line 394 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy96imVft4YozPahs7z)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java#L394)):</sup>
Because it will clear out the keystore.

---

<sup>**[platform/security/certificate/security-certificate-keystoreeditor/src/test/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditorTest.java, line 170 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy97_M_RoKAAup5eiG-)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-keystoreeditor/src/test/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditorTest.java#L170)):</sup>
They don't have to be in any particular order. I can switch it over to using anyOf instead.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/147)

**Comment by clockard** [comment]
Reviewed 11 of 11 files at r2.
Review status: all files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/147)

**Comment by clockard** [comment]
:+1:

**Comment by brendan-hofmann** [comment]
Reviewed 11 of 11 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

<sup>**[platform/security/certificate/security-certificate-adminmodule/pom.xml, line 87 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy92GvcVQMx7jfQQGnV)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-adminmodule/pom.xml#L87)):</sup>
Derp, I agree, admin is the correct root for it.

---

<sup>**[platform/security/certificate/security-certificate-adminmodule/server-impl.js, line 20 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy92Rj5njJFVp5CLhGW)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-adminmodule/server-impl.js#L20)):</sup>
The point of the https proxy is that it works without *any* configuration of DDF though. Is that still the case?

---

<sup>**[platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java, line 142 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy95OXSivY6vf5VsVy0)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java#L142)):</sup>
Which sounds like a mistake a user could make to me. ;) If you really don't want to log the case with explanation you just gave, maybe at least put a comment in there explaining why all these exceptions are swallowed? It's definitely not standard practice for our code base, and is just going to cause confusion next time someone looks at it.

---

<sup>**[platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java, line 279 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy96Lwfdw-QxnveNCNK)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java#L279)):</sup>
Ah. I didn't get that distinction from the existing comment. You could explain the mimetype gotcha in the comment, perhaps.

---

<sup>**[platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java, line 390 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/147#-Jy96bOTcA1_jM4NqeXo)** ([raw file](https://github.com/codice/ddf/blob/80d77a189a4e70520232b031d811be0b8642d8e2/platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java#L390)):</sup>
I understand that. If there's a reason you're not catching specific, known exceptions though, it could use a comment, since it conflicts with our code style everywhere else.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/147)

**Comment by coyotesqrl** [comment]
Review status: 65 of 66 files reviewed at latest revision, 20 unresolved discussions, some commit checks failed.

---

<sup>**[platform/security/certificate/security-certificate-adminmodule/Gruntfile.js, line 77 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/147#-JyKHdpeCwLOsmB_MFOk)** ([raw file](https://github.com/codice/ddf/blob/73bf16325a554f44bf44048ac0ba63437fecb363/platform/security/certificate/security-certificate-adminmodule/Gruntfile.js#L77)):</sup>
Comment formatting error

---

<sup>**[platform/security/certificate/security-certificate-adminmodule/server-impl.js, line 29 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/147#-JyKJXfPtdyBK22CpB3e)** ([raw file](https://github.com/codice/ddf/blob/73bf16325a554f44bf44048ac0ba63437fecb363/platform/security/certificate/security-certificate-adminmodule/server-impl.js#L29)):</sup>
I assume `readFileSync` will return undefined if the file doesn't exist, yes?

---

<sup>**[platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java, line 115 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/147#-JyKOhD_JiZ5ZwW1kbST)** ([raw file](https://github.com/codice/ddf/blob/73bf16325a554f44bf44048ac0ba63437fecb363/platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java#L115)):</sup>
Are we always using the same type, or should we get `javax.net.ssl.trustStoreType` here?

---

<sup>**[platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java, line 165 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/147#-JyKPaYRerh7M06gP0Qg)** ([raw file](https://github.com/codice/ddf/blob/73bf16325a554f44bf44048ac0ba63437fecb363/platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java#L165)):</sup>
Shouldn't we log a null mBeanServer as an error?

---

<sup>**[platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java, line 242 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/147#-JyKSAgqfRpXHJLyZooN)** ([raw file](https://github.com/codice/ddf/blob/73bf16325a554f44bf44048ac0ba63437fecb363/platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java#L242)):</sup>
It might be a touch more verbose, but I think it'd be cleaner to do very short try-with-resources blocks everywhere you write the output stream and remove the finally block. The instance is only ever used within a single scope and then you're done with it.

---

<sup>**[platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java, line 328 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/147#-JyKTp8oXMROZLWqunD2)** ([raw file](https://github.com/codice/ddf/blob/73bf16325a554f44bf44048ac0ba63437fecb363/platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java#L328)):</sup>
Could probably extract a method for this block as it's *just about* identical to the X509-specific block above.

---

<sup>**[platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java, line 409 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/147#-JyKVHkWf6-yDeFXhP39)** ([raw file](https://github.com/codice/ddf/blob/73bf16325a554f44bf44048ac0ba63437fecb363/platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java#L409)):</sup>
Are we at all worried about someone uploading any sort of file on which they've changed the extension? I'd think that would just fall through to an exception on parsing, but do we have a test to confirm that?

---

<sup>**[platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java, line 487 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/147#-JyKWziEi_P7fexxK4Bw)** ([raw file](https://github.com/codice/ddf/blob/73bf16325a554f44bf44048ac0ba63437fecb363/platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java#L487)):</sup>
I'm not clear about this. In the `init()` method, you allow for the case where the keyStore and trustStore properties may be absolute paths, but here expect them to be relative to `ddf.home`.

---

<sup>**[platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java, line 507 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/147#-JyKYIqNqvElVCD86Bdn)** ([raw file](https://github.com/codice/ddf/blob/73bf16325a554f44bf44048ac0ba63437fecb363/platform/security/certificate/security-certificate-keystoreeditor/src/main/java/org/codice/ddf/security/certificate/keystore/editor/KeystoreEditor.java#L507)):</sup>
Should you synchronize access to this since you're rewriting the file each time?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/147)

**Comment by brendan-hofmann** [comment]
Reviewed 1 of 1 files at r3.
Review status: 64 of 66 files reviewed at latest revision, 18 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/147)

**Pull request merged**
