### PR TITLE
[2.13.x] DDF-4166, DDF-4223  - Port of test dependency changes from master

### PR DESCRIPTION
**Pull request by paouelle**
Uncomment this block and include PR # of change against 2.13.x where appropriate.
When doing so, it is reasonable to delete much of the rest of the PR description, leaving only:
- This uncommented block with link to 2.13.x PR
- Reviewers tagged
- Teams tagged
- Committers tagged
- The link to the "Notes on Review Process"

##### ABBREVIATED REVIEW BETWEEN 2.13.X AND MASTER IS IN EFFECT
Link to master PRs: #3821 and #4060 
____

#### What does this PR do?
It relocates various generic test and maven utilities to codice-test and codice-maven repositories.
Upgrade Jacoco, codice-maven, codice-test versions.

#### Who is reviewing it? 
@AzGoalie
@figliold
@tbatie
@peterhuffer 

#### Select relevant component teams: 
@codice/build 
@codice/test 

#### Ask 2 committers to review/merge the PR and tag them here.
@coyotesqrl
@lessarderic
@clockard 

#### How should this be tested?
successful PR build should be sufficient

#### What are the relevant tickets?
[DDF-4166](https://codice.atlassian.net/browse/DDF-4166)
[DDF-4223](https://codice.atlassian.net/browse/DDF-4223)

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by paouelle** [comment]
build now

**Comment by paouelle** [comment]
Waiting on https://github.com/codice/ddf/pull/4196 to also be committed to the release branch to addresses the new CVEs.

**Comment by clockard** [comment]
@paouelle sounds like this pr is only affecting test related things. I am thinking we may not want to port this to the release branch. We are trying to really restrict the changes going into 2.13.x to needed bug fixes.

**Comment by paouelle** [comment]
This PR impacts no production code. Only testing is impacted and the changes are minor.

**Comment by paouelle** [comment]
build now

**Pull request merged**
