### PR TITLE
DDF-2923 Fixes deleted marker not getting removed

### PR DESCRIPTION
**Pull request by rzwiefel**
#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged)?
@bdeining 
@jlcsmith 
@andrewkfiedler 
#### Select at least one member from relevant component team(s) from below (at least one component team member needs to approve the PR).
[UI](https://github.com/orgs/codice/teams/ui)
[IO](https://github.com/orgs/codice/teams/IO)

#### How should this be tested? (List steps with links to updated documentation)
1. ingest data from the commandline (eg `catalog:ingest -t xml /path/to/metacard.xml`)
2. archive the metacard
3. restore the metacard
4. ensure when a "Search Archived" is performed that no results come up  

https://codice.atlassian.net/browse/DDF-2923

### CODE REVIEW

**Comment by rzwiefel** [comment]
build now

**Comment by bdeining** [comment]
Verified that metacards without content are being archived/restored properly by following the test steps

**Comment by bdeining** [comment]
During hero, metacards without content are successfully restored, but noticed that there are NPEs thrown on Metacards with content

**Comment by jlcsmith** [comment]
Approved once @bdeining's comment is addressed

**Comment by rzwiefel** [comment]
Ironically, this is one of the failure conditions that eric recommended a test case for. This is fixed by https://github.com/codice/ddf/pull/1895, so we can wait for that to get merged first.

**Comment by rzwiefel** [comment]
Merged as part of https://github.com/codice/ddf/pull/1912

**Pull request closed without merging**
