### PR TITLE
DDF-04355 Add allow-same-origin to source-app iframe

### PR DESCRIPTION
**Pull request by rymach**
Fix for #4355 

#### What does this PR do?
Adds  allow-same-origin to iframe sandbox
#### Who is reviewing it? 

@leo-sakh 
@GabrielFabian 

#### Select relevant component teams: 
@codice/security 
@codice/ui 

#### Ask 2 committers to review/merge the PR and tag them here.

@andrewkfiedler
@bdeining

#### How should this be tested?
rerun steps - webapp should work now
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by vinamartin** [comment]
❓ Are we opening ourselves up to any potential security concerns with this change?

**Comment by rymach** [comment]
> ❓ Are we opening ourselves up to any potential security concerns with this change?

None that I know of

**Comment by garrettfreibott** [comment]
❓ What is the need for this adding sandbox exception? If the iframe content is served on the same domain as ddf, then `allow-scripts` perm + `allow-same-origin` would give the full access to ddf's local storage and internal apis. Is this so an external app can access it's own api, or is this so it can access ddf's internal api?

**Comment by rymach** [comment]
> ❓ What is the need for this adding sandbox exception? If the iframe content is served on the same domain as ddf, then `allow-scripts` perm + `allow-same-origin` would give the full access to ddf's local browser storage and internal apis. Is this so an external app can access it's own api, or is this so it can access ddf's internal api?

access it's own

**Comment by rzwiefel** [comment]
@rymach 
>When the embedded document has the same origin as the embedding page, it is **strongly discouraged** to use both allow-scripts and allow-same-origin, as that lets the embedded document remove the sandbox attribute — making it no more secure than not using the sandbox attribute at all.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox

**Comment by rymach** [comment]
I'll add a warning

we could open a new tab, but if the page is hosted at the same origin it would have all the same access

**Comment by rymach** [comment]
build now

**Comment by rymach** [comment]
build now

**Pull request merged**
