### PR TITLE
[2.11.x] DDF-3364 Fix the security-sts-server to successfully start up after restarting DDF when the broker-app is installed

### PR DESCRIPTION
**Pull request by roelens8**
#### What does this PR do?
Backport of https://github.com/codice/ddf/pull/2490
#### Who is reviewing it? 
@ryeats 
@harrison-tarr 
(please choose AT LEAST two reviewers that need to approve the PR before it can get merged)
#### Choose 2 committers to review/merge the PR. 
(please choose ONLY two committers from below, delete the rest)
@jaymcnallie
@stustison
#### How should this be tested? (List steps with links to updated documentation)
1. Run a full build. 
2. Install DDF, install the broker-app. Restart DDF. Make sure the `security-sts-server` bundle has successfully started.

#### What are the relevant tickets?
[DDF-3364](https://codice.atlassian.net/browse/DDF-3364)
#### Checklist:
- [N/A] Documentation Updated
- [N/A] Update / Add Unit Tests
- [N/A] Update / Add Integration Tests
#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by rzwiefel** [comment]
@roelens8 Is this needed for 2.11.0 ?

**Comment by roelens8** [comment]
@rzwiefel 2.11.1 should be fine.

**Comment by roelens8** [comment]
build now

**Comment by harrison-tarr** [comment]
Manually built and heroed 💯 LGTM

**Comment by roelens8** [comment]
build now

**Comment by roelens8** [comment]
build now

**Comment by roelens8** [comment]
build now

**Comment by roelens8** [comment]
build now

**Comment by roelens8** [comment]
build now

**Comment by roelens8** [comment]
build now

**Comment by roelens8** [comment]
build now

**Comment by roelens8** [comment]
build now

**Pull request merged**
