### PR TITLE
DDF-2038 Added NSF and NSIF to NITF Mime Type Configuration

### PR DESCRIPTION
**Pull request by bdeining**
#### What does this PR do?
This PR adds NSIF and NSF to the NITF Custom Mime Types in DDF
#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?
@dcruver
@glenhein 
#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@jlcsmith
@kcwire
#### How should this be tested?
Build DDF and observe that the NITF Custom Mime Type has NSF and NSIF.
#### What are the relevant tickets?
https://codice.atlassian.net/browse/CAL-30
https://codice.atlassian.net/browse/DDF-2038
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by dcruver** [comment]
lgtm

**Comment by jlcsmith** [comment]
Built successfully and verified

**Comment by kcwire** [comment]
-1
I actually disagree with this change.  I believe without this config, when a NITF file is retrieved from a remote system, DDF can return a `Content-Type` header of `application/octet` stream.

@bdeining - if you can verify (i.e. integration tests) this does not occur and DDF still creates the correct `Content-Type` header I will change to a +1.

**Comment by jlcsmith** [comment]
@kcwire - it seems strange to me to have a mime type config for NITF when NITF support is part of the imaging app in Alliance - not DDF.

**Comment by stustison** [comment]
👎 
I agree with Keith. NITF files can certainly exist whether you're using the Alliance imaging app or not. Knowing the mime type should be independent of whether or not you can parse the information from within the file.

**Comment by bdeining** [comment]
Adding NSF and NSIF file types to the NITF Custom MIME Type and keeping it in DDF.

**Comment by kcwire** [comment]
👍

**Comment by stustison** [comment]
Same. 👍

**Pull request merged**
