### PR TITLE
[2.13.x]DDF-4548 Update docs for enforced validator plugin 

### PR DESCRIPTION
**Pull request by austinsteffes**
#### What does this PR do?
Updates doc order for downstream 
#### Who is reviewing it? 

@tyler30clemens 
@jhunzik 
#### Ask 2 committers to review/merge the PR and tag them here.

@brjeter
@ricklarsen - Documentation

#### How should this be tested?

Build successful 
#### Any background context you want to provide?
Updates doc ordering for downstream
#### What are the relevant tickets?
Fixes: #4548 

#### Checklist:
- [X ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by austinsteffes** [comment]
build now

**Comment by vinamartin** [comment]
Overriding codecov/project as I'm not sure how it would have changed from this change.

**Comment by austinsteffes** [comment]
build now

**Comment by austinsteffes** [comment]
build now

**Comment by tyler30clemens** [comment]
Hero Successful ✅

**Comment by austinsteffes** [comment]
build now

**Comment by austinsteffes** [comment]
unrelated build now

**Comment by austinsteffes** [comment]
network connection. build now

**Comment by brjeter** [comment]
⚠️ Please hold on merging until after the DDF 2.13.7 release happening today. I'll comment on this PR once the release is complete.

**Comment by brjeter** [comment]
Release complete; feel free to merge following regular procedures.

**Comment by austinsteffes** [comment]
rebase. build now

**Comment by vinamartin** [comment]
Is this good to merge?

**Pull request merged**
