### PR TITLE
[2.13.x] DDF-4129 Updating netty versions and blacklisting features that use outdated versions

### PR DESCRIPTION
**Pull request by Kjames5269**
#### What does this PR do?
Upgrades Netty 3.9.2 and 4.0.33.
Since v4.0.33 is a transitive dependency used by the karaf-decanter-cassandra I looked into upgrading that. However the newest version 2.0.0 still had the dependency on 4.0.33. Because of this karaf-decanter-cassandra is added to the blacklisted.properties file and Netty v4.0.33 has been added to the list of exclusions. 

#### Who is reviewing it? 
@blen-desta @brjeter 

#### Select relevant component teams: 
https://github.com/orgs/codice/teams
#### Ask 2 committers to review/merge the PR and tag them here.

@clockard
@tbatie

#### What are the relevant tickets?
[DDF-4129](https://codice.atlassian.net/browse/DDF-4129)
#### Screenshots

screen shot 2018-09-13 at 12 48 10 pm
screen shot 2018-09-13 at 12 45 40 pm

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by clockard** [comment]
build now

**Comment by Kjames5269** [comment]
build now

**Comment by LinkMJB** [comment]
build now

**Comment by Kjames5269** [comment]
build now
(features that I didn't touch failed to install)

**Comment by bakejeyner** [comment]
hero ✔️

**Pull request merged**
