### PR TITLE
[2.19.x] DDF-6035 G-8076 Fix result forms

### PR DESCRIPTION
**Pull request by mojogitoverhere**
#### What does this PR do?
Fixes the following issues with result forms:
- Newly created result forms were not able to be used in queries until after a refresh.
- While editing existing forms, the attributes were not being populated correctly.
- The table visualization would throw an error if the `thumbnail` attribute was not included in the attributes of the result form

#### Who is reviewing it? 

@brianfelix 
@Lambeaux 
@kentmorrissey 
@brhumphe 

#### Ask 2 committers to review/merge the PR and tag them here.
@andrewkfiedler
@bdeining

##### Testing that newly created result forms can be used without a refresh
1. Go to `Result Forms` page in Intrigue
2. Create a new result form
3. Navigate to the `Workspaces` page from the hamburger menu without refreshing the page
4. Create a new query and open the `Result Forms` dropdown
5. Notice the new result form is available in the list without a refresh

##### Testing that the attributes of existing forms are populated correctly while editing
1. Go to `Result Forms` page in Intrigue
2. Create a new result form with some attributes
3. Click on the result form that was created from the card view
4. Verify that the attributes shown were the ones that were selected in step 2
5. Refresh the page
6. Again verify that the attributes shown were the ones that were selected in step 2

##### Testing that table visualization renders with or without the `thumbnail` attribute
1. Go to `Result Forms` page in Intrigue
2. Create a new result form with some attributes other than `thumbnail`
3. Go to the `Workspaces` page and run a query with the result form that was created
4. Verify the table renders correctly without a `Thumbnail` column
5. Go back to the `Result Forms` page and add the `thumbnail` attribute to the form created in step 2
6. Run the query again and verify the table renders correctly with the `Thumbnail` column

##### Any other regression testing
1. Ensure result forms are still able to be marked as default
2. Test using a result form with a search form
3. Other things I didn't think of
#### What are the relevant tickets?
Fixes: #6035

### CODE REVIEW

**Comment by mojogitoverhere** [comment]
build now

**Comment by mojogitoverhere** [comment]
fixed formatting
build now

**Comment by mojogitoverhere** [comment]
build now

**Comment by brianfelix** [comment]
Hero was successful. LGTM :+1:

**Comment by mojogitoverhere** [comment]
build now

**Pull request merged**
