### PR TITLE
DDF-3648 Upgraded bouncy castle to 1.59

### PR DESCRIPTION
**Pull request by oconnormi**
#### What does this PR do?

Upgrades bouncy castle from 1.55 to 1.59

#### Who is reviewing it? 

@peterhuffer @emmberk @kcover 

#### Select relevant component teams: 

@codice/security 

#### Choose 2 committers to review/merge the PR. 

@clockard @figliold 

#### What are the relevant tickets?

[DDF-3648](https://codice.atlassian.net/browse/DDF-3648)

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by oconnormi** [comment]
Build Now

**Comment by coyotesqrl** [comment]
Double checking two things:

1. Have you confirmed that all three of these artifacts exist at that version and have not been combined, broken up, or renamed? https://github.com/codice/ddf/blob/0d44894532a58b8b87534b2c02b0676f5a32059c/distribution/kernel/pom.xml#L149-L169
2. Have you confirmed that all of these packages (and no new ones required for operation) exist at this version? https://github.com/codice/ddf/blob/0d44894532a58b8b87534b2c02b0676f5a32059c/distribution/ddf-common/src/main/resources-filtered/etc/custom.properties#L207-L379

**Comment by clockard** [comment]
Need to make sure this is ported to 2.11.x

**Comment by oconnormi** [comment]
@coyotesqrl AFAICT all artifacts stayed the same

**Pull request merged**
