### PR TITLE
DDF-4094, DDF-4095, DDF-4096 Sets up structure for React components, typescript, styled-components, stylelinting. Fixes issues that were preventing hot reloading.

### PR DESCRIPTION
**Pull request by andrewkfiedler**
#### What does this PR do?
 - Sets up the structure for React components going forward.  Components are divided into two categories: presentation and container.  See https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0 for more info. TLDR: Presentational components are all about how things look, container components are all about how things work.  Presentational components should be as decoupled from the rest of the app as possible, basically only accepting some data (props) and showing something based on them.  As a result, you'll typically have a container component that transforms some data and feeds it to a presentational component.  I've converted a good number of components from Marionette to React to show how this split often ends up looking.
 - Sets up styled-components and implements a theme provider so that our React components stay consistent as we migrate.  This is also wrapped around each marionette render so developers in the future don't have to worry about going from Marionette to React.
 - Sets up typescript so that we can get good static analysis going on the frontend from here on out.  All the new components that were migrated utilize typescript, and we should utilize it exclusively going forward.  Even styled components is setup to utilize our theme with typescript, resulting in the availability of autocomplete for our styles.  Now if you change an API and there's an issue, typescript will let you know by failing the build.
 - Sets up stylelinting so that as we write styled-components we get some static analysis of things that will go wrong.
 - Fixes an issue with transitive dependencies that allows us to now start utilizing the react-hot-loader.  See the save-button component for an example of how to use it, it's fairly simple.
 - Adds react component 'marionette-region-container' to make it easy to go from react back into marionette.
 - Adds a higher order component to add the ability to listen to backbone models onto a react component easier.
 - Adds a react implementation of the button component along with a new dev guide outlining how to use it.

#### Who is reviewing it? 
@djblue 
@adimka

### CODE REVIEW

**Comment by djblue** [comment]
build now

**Comment by andrewkfiedler** [comment]
build now

**Comment by andrewkfiedler** [comment]
build now

**Comment by djblue** [comment]
Successfully hero'd:
- `mvn clean install` ui directory
- checked for regressions through manual testing

**Comment by rzwiefel** [comment]
Build on docker container failed.
Build on local Mac OS failed.

I think our build is failing.

**Pull request merged**
