### PR TITLE
DDF-3279 Upgrade to Solr 6.6.1

### PR DESCRIPTION
**Pull request by vinamartin**
#### What does this PR do?
Upgrades to Solr 6.6.1 (http://lucene.apache.org/solr/6_6_1/changes/Changes.html) 
#### Who is reviewing it? 
@figliold @emmberk @rzwiefel @lessarderic
#### Choose 2 committers to review/merge the PR. 
@clockard 
@millerw8 
#### How should this be tested? 
(Instructions from the last upgrade)
Full build.
Configure it to use stand-alone solr, embedded solr, and solr cloud. In all three scenarios, confirm ability to ingest metacards, save workspaces, and query.
#### What are the relevant tickets?
[DDF-3279](https://codice.atlassian.net/browse/DDF-3279)
#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by vinamartin** [comment]
build now

**Comment by figliold** [comment]
:question: Are there any changes to solr-dependencies for this upgrade?
https://github.com/codice/ddf/blob/master/platform/solr/solr-dependencies/pom.xml

**Comment by vinamartin** [comment]
@figliold Where do I check in Solr? 
Everything looked like it was working when I tested it, but I can double check with their stuff.

**Comment by figliold** [comment]
@vinamartin It is kind of a manual process.  You would download the solr zip and compare the solr dependencies in the zip to the ones in solr-dependencies.  This is the last one that @millerw8 did (https://github.com/codice/ddf/pull/2189/files).  You can ask @pklinef, but I don't think there is an easier way to do it.

**Comment by figliold** [comment]
We probably need to make some documentation updates also.

**Comment by millerw8** [comment]
There are a couple of things that make this a bit of a pain and a manual process, one is to check the dependencies @figliold mentioned here: https://github.com/codice/ddf/blob/master/platform/solr/solr-dependencies/pom.xml, and the other is the solr web application is copied into here: https://github.com/codice/ddf/tree/master/platform/solr/platform-solr-server-standalone

For the first:  I went and downloaded the solr version I was replicating, opened the zip, and looked at the server/lib directory and the server/solr-webapp/WEB-INF/lib directories, and confirmed every jar was covered by the dependencies pom, and that when built, all the versions matched.

For the second, I used the webapp directory that comes with solr to replace the webapp inside platform-solr-server-standalone, and confirmed that any old files that neded to be gone were removed, and new ones were added.  Upon check-in, it was pointed out in review that Scott made some custom changes to one of the files for the security settings.  I believe they are in web.xml and discreetly commented on here: https://github.com/codice/ddf/blob/master/platform/solr/platform-solr-server-standalone/src/main/webapp/WEB-INF/web.xml#L167

I am betting there will be no changes though, with a bug-fix release.

**Comment by pklinef** [comment]
@lessarderic I would argue that upgrading from Solr 6.6.0 to 6.6.1 should be done for DDF 2.11 or 2.11.1.

**Comment by vinamartin** [comment]
I've looked through the dependencies and it looks like anything that is new in 6.6.1 was already in the pom.

**Comment by vinamartin** [comment]
build now

**Comment by vinamartin** [comment]
build now

**Comment by ahoffer** [comment]
Passed manual verification


  | Configuration |   |  
-- | -- | -- | --
**Item** | Emdedded | Standalone | Cloud
Workspaces | OK | OK | OK
Ingest | OK | OK | OK
Query | OK | OK | OK
Alerts | OK | OK | OK

For Solr Cloud testing we used OConnor's Solr 6.6.1 docker image (https://github.com/oconnormi/docker-ddf-solr/tree/master/6.6.1)

**Comment by clockard** [comment]
build now

**Comment by vinamartin** [comment]
build now

**Comment by rzwiefel** [comment]
build now

**Pull request merged**
