### PR TITLE
[2.19.x] G-9391 clear search form when user navigates to new workspace

### PR DESCRIPTION
**Pull request by andrewzimmer**
#### What does this PR do?
clears search form when user navigates to new workspace

#### How should this be tested?
- build / run
- open workspace and edit search form with geos/attributes, do not save or run
- switch to a new workspace and verify the search form is cleared and the previously drawn geos do not appear 

#### What are the relevant tickets?
Fixes: #____

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Review by brianfelix — APPROVED** [review]

**Review by mojogitoverhere — APPROVED** [review]
LGTM after @shaundmorris's comment is addressed

**Comment by mojogitoverhere** [comment]
build now

**Comment by mojogitoverhere** [comment]
hero in progress

**Comment by mojogitoverhere** [comment]
I cancelled the previous build
build now

**Comment by andrewzimmer** [comment]
build now

**Comment by andrewzimmer** [comment]
build now

**Comment by andrewzimmer** [comment]
build now

**Comment by mojogitoverhere** [comment]
## 🎉 Hero was successful! 🎉 ##

1. Created two workspaces
2. Created a new query without clicking search
3. Verified the query title, fields, sorts, and result form are reset to their default values when switching between the workspaces

**Comment by mojogitoverhere** [comment]
build now

**Comment by andrewzimmer** [comment]
build now

**Pull request merged**
