### PR TITLE
[2.11.x] DDF-3599 Add common test utilities

### PR DESCRIPTION
**Pull request by paouelle**
#### What does this PR do?
Adds and moved common test utility classes to the libs/test-common project so they can be reused downstream.

#### Who is reviewing it? 
@emanns95 
@tbatie 

#### Select relevant component teams: 
https://github.com/orgs/codice/teams
#### Choose 2 committers to review/merge the PR. 
(please choose ONLY two committers from below, delete the rest)
@bdeining
@clockard
@figliold

#### How should this be tested? (List steps with links to updated documentation)
Run the full build (with itests) to make sure nothing is broken. Impacts no production code; only test code. I would also suggest to also run the full build (with itests) for upstreams projects.

#### What are the relevant tickets?
[DDF-3599](https://codice.atlassian.net/browse/DDF-3599)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by clockard** [comment]
What is the reason for putting this on the release branch? Seems like it should go on master.

**Comment by paouelle** [comment]
build now

**Comment by paouelle** [comment]
build now

**Comment by paouelle** [comment]
build now

**Pull request merged**
