### PR TITLE
DDF-1963: fix for broken table formatting in installation docs

### PR DESCRIPTION
**Pull request by ricklarsen**
#### What does this PR do?

Fixes a formatting error in the pdf version of documentation. 

#### Who is reviewing it?

@mcalcote @Lambeaux @jrnorth 
#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).

@lessarderic
@shaundmorris

#### How should this be tested?

Table on page 15 of the rendered `documentation.pdf` was formerly bleeding off the edge of the page. Table should be contained within page margins now.

#### What are the relevant tickets?
DDF-1963

#### Checklist:
- [x] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by mcalcote** [comment]
Looks alright from the file, screenshot of the new format?

**Comment by ricklarsen** [comment]
screen shot 2016-07-19 at 1 28 48 pm

**Comment by mcalcote** [comment]
LGTM :+1:

**Comment by jrnorth** [comment]
LGTM

**Comment by ricklarsen** [comment]
:shipit: :wink: :wink:

**Comment by shaundmorris** [comment]
👍  @ricklarsen we should back port this to 2.9.x

**Comment by ricklarsen** [comment]
Will backport to 2.9.x

**Pull request merged**
