### PR TITLE
DDF-3365 [2.11.x] Cleans up an unclosed io stream issue in itests.

### PR DESCRIPTION
**Pull request by coyotesqrl**
#### What does this PR do?
Wraps stream access in try-with-resources.

#### Who is reviewing it? 
@blen-desta @vinamartin 

(please choose AT LEAST two reviewers that need to approve the PR before it can get merged)
#### Select relevant component teams: 
https://github.com/orgs/codice/teams
#### Choose 2 committers to review/merge the PR. 
(please choose ONLY two committers from below, delete the rest)
@clockard
@figliold

#### How should this be tested? (List steps with links to updated documentation)
CI build is sufficient as it only impacts itests.

#### What are the relevant tickets?
[DDF-3365](https://codice.atlassian.net/browse/DDF-3365)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests
#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by coyotesqrl** [comment]
build now

**Comment by coyotesqrl** [comment]
build now

**Comment by clockard** [comment]
build now

**Comment by LinkMJB** [comment]
build now

**Pull request merged**
