### PR TITLE
DDF-3279 Remove TestEmbeddedSolr since we are testing that case elsewhere

### PR DESCRIPTION
**Pull request by clockard**
#### What does this PR do?
Removes test classes we no longer need.
#### Who is reviewing it? 
@vinamartin 

#### Choose 2 committers to review/merge the PR. 

@bdeining
@lessarderic

#### How should this be tested? (List steps with links to updated documentation)
Build passes
#### What are the relevant tickets?
[DDF-3279](https://codice.atlassian.net/browse/DDF-3279)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests
#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by clockard** [comment]
build now

**Comment by clockard** [comment]
build now

**Comment by clockard** [comment]
build now

**Comment by pklinef** [comment]
Is there a reason we do not just comment out the annotations on the test classes?  I think we will need these tests again once we fix the Solr server bundle refresh issue.

**Pull request merged**
