### PR TITLE
DDF-1504: Fix NullPointerException in GetRecordById

### PR DESCRIPTION
**Pull request by jrnorth**
@wmcnalli is the hero
@kcwire 
@shane-voisard 
@bdeining

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/191)

### CODE REVIEW

**Comment by bdeining** [comment]
Reviewed 5 of 5 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/191)

**Comment by millerw8** [comment]
Reviewed 5 of 5 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/191)

**Comment by shane-voisard** [comment]
Reviewed 5 of 5 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/191)

**Comment by kcwire** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[catalog/spatial/csw/spatial-csw-endpoint/pom.xml, line 148 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/191#-JzqhuIjRvIBxlIu4yJV)** ([raw file](https://github.com/codice/ddf/blob/a5cec6cbcefda1d462c0e4180035af37d8b534a7/catalog/spatial/csw/spatial-csw-endpoint/pom.xml#L148)):</sup>
anything over .75 and you should remove this.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/191)

**Comment by wmcnalli** [comment]
:+1:  Pull request built and tested.  LGTM.


---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/191)

**Comment by bdeining** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/191)

**Comment by coyotesqrl** [comment]
Review status: 5 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

<sup>**[distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestCatalog.java, line 495 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/191#-K-UtllFQtlgtK3KxWWS)** ([raw file](https://github.com/codice/ddf/blob/a59a2fac1eac0f0fc1336b0874267eb357bf1e84/distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestCatalog.java#L495)):</sup>
It'd be more extensible and a little bit less code below if you changed this to a list/array/varargs of ids. Then you'd just have to check record count against the size of the input and replace your fluent doubled body checks with a shorter fluent call in a loop.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/191)

**Comment by shane-voisard** [comment]
Reviewed 2 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/191)

**Comment by jrnorth** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestCatalog.java, line 495 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/191#-K-UtllFQtlgtK3KxWWS)** ([raw file](https://github.com/codice/ddf/blob/a59a2fac1eac0f0fc1336b0874267eb357bf1e84/distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestCatalog.java#L495)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/191)

**Comment by bdeining** [comment]
Reviewed 2 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/191)

**Pull request merged**
