### PR TITLE
DDF-2564: Updated cometd endpoint to properly startup (#1395)

### PR DESCRIPTION
**Pull request by AzGoalie**
#### What does this PR do?
Fixes the cometd endpoint from failing to initialize on install and reboot.
#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged)?
@brendan-hofmann @coyotesqrl
#### Select at least one member from relevant component team(s) from below (at least one component team member needs to approve the PR).
[Build](https://github.com/orgs/codice/teams/build)
[Docs](https://github.com/orgs/codice/teams/docs)
[UI](https://github.com/orgs/codice/teams/ui)
[Security](https://github.com/orgs/codice/teams/security)
[Continuous Integration](https://github.com/orgs/codice/teams/continuous-integration)
[Solr](https://github.com/orgs/codice/teams/solr)
[IO](https://github.com/orgs/codice/teams/IO)
[OGC](https://github.com/orgs/codice/teams/OGC)
[Data](https://github.com/orgs/codice/teams/data)
[Core APIs](https://github.com/orgs/codice/teams/core-apis)
#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@kcwire
@pklinef
##### On Windows
Extract DDF and install.
Make sure there are no warnings/errors in logs during install related to the search-endpoint or cometd.
After install verify that you can login to the standard search ui.
#### What are the relevant tickets?
[](https://codice.atlassian.net/browse/)
#### Checklist:
- [ ] Documentation Updated
- [ ] Change Log Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

* DDF-2564: Updated cometd endpoint to properly startup

* DDF-2564: Removed transient from static member

### CODE REVIEW

**Comment by AzGoalie** [comment]
This is a cherry pick from the 2.9.x branch https://github.com/codice/ddf/pull/1395

**Comment by emanns95** [comment]
Manually confirmed change on IE11 and Firefox on Windows 👍

**Comment by ricklarsen** [comment]
Should this go into CHANGES.md?

**Comment by AzGoalie** [comment]
Verified that it works on Linux.

**Pull request merged**
