### PR TITLE
DDF-1527 Updated to Java 8 from 7

### PR DESCRIPTION
**Pull request by harrison-tarr**
[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/199)

### CODE REVIEW

**Comment by harrison-tarr** [comment]
@brendan-hofmann @AzGoalie @mverret @NGoss

**Comment by AzGoalie** [comment]
:+1:

**Comment by brendan-hofmann** [comment]
The bamboo build is reporting a compilation error, might want to check that. :(

**Comment by ahoffer** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[platform/mime/core/platform-mime-core-impl/src/main/java/ddf/mime/mapper/MimeTypeToTransformerMapperImpl.java, line 130 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/199#-K-0QCfvVUZYocUevZ9K)** ([raw file](https://github.com/codice/ddf/blob/579146352f781dc7b288123baaed097b381fdac7/platform/mime/core/platform-mime-core-impl/src/main/java/ddf/mime/mapper/MimeTypeToTransformerMapperImpl.java#L130)):</sup>
What does this do?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/199)

**Comment by harrison-tarr** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[platform/mime/core/platform-mime-core-impl/src/main/java/ddf/mime/mapper/MimeTypeToTransformerMapperImpl.java, line 130 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/199#-K-0QCfvVUZYocUevZ9K)** ([raw file](https://github.com/codice/ddf/blob/579146352f781dc7b288123baaed097b381fdac7/platform/mime/core/platform-mime-core-impl/src/main/java/ddf/mime/mapper/MimeTypeToTransformerMapperImpl.java#L130)):</sup>
I don't know. It had a compile error before, now it doesn't. It had an issue with the class casting before.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/199)

**Comment by brendan-hofmann** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[platform/mime/core/platform-mime-core-impl/src/main/java/ddf/mime/mapper/MimeTypeToTransformerMapperImpl.java, line 130 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/199#-K-0QCfvVUZYocUevZ9K)** ([raw file](https://github.com/codice/ddf/blob/579146352f781dc7b288123baaed097b381fdac7/platform/mime/core/platform-mime-core-impl/src/main/java/ddf/mime/mapper/MimeTypeToTransformerMapperImpl.java#L130)):</sup>
You're effectively casting to the same thing twice now, which makes no sense. Class<T>.cast() and (T) should be functionally equivalent.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/199)

**Comment by harrison-tarr** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[platform/mime/core/platform-mime-core-impl/src/main/java/ddf/mime/mapper/MimeTypeToTransformerMapperImpl.java, line 130 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/199#-K-0QCfvVUZYocUevZ9K)** ([raw file](https://github.com/codice/ddf/blob/579146352f781dc7b288123baaed097b381fdac7/platform/mime/core/platform-mime-core-impl/src/main/java/ddf/mime/mapper/MimeTypeToTransformerMapperImpl.java#L130)):</sup>
I agree. When I do the original -- "T service = clazz.cast(bundleContext.getService(ref));" -- I get a compile error. I can do either "T service = (T) clazz.cast(bundleContext.getService(ref));" or my change to make it compile.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/199)

**Comment by pklinef** [comment]
Don't forget to update READMEs and documentation.

**Comment by brendan-hofmann** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[platform/mime/core/platform-mime-core-impl/src/main/java/ddf/mime/mapper/MimeTypeToTransformerMapperImpl.java, line 104 \[r4\]](https://reviewable.io:443/reviews/codice/ddf/199#-K-JYXdvHcteCyT21I-X)** ([raw file](https://github.com/codice/ddf/blob/bb62b64e294eb82ed9a3db496146f797373c3133/platform/mime/core/platform-mime-core-impl/src/main/java/ddf/mime/mapper/MimeTypeToTransformerMapperImpl.java#L104)):</sup>
Why does this line compile and the one you changed doesn't? They seem almost identical.


---

<sup>**[platform/mime/core/platform-mime-core-impl/src/main/java/ddf/mime/mapper/MimeTypeToTransformerMapperImpl.java, line 130 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/199#-K-0QCfvVUZYocUevZ9K)** ([raw file](https://github.com/codice/ddf/blob/579146352f781dc7b288123baaed097b381fdac7/platform/mime/core/platform-mime-core-impl/src/main/java/ddf/mime/mapper/MimeTypeToTransformerMapperImpl.java#L130)):</sup>
If you're going to explicitly cast with `(T)` then the `clazz.cast()` is redundant, so you might as well jus inline the `getService()`. Since `T` and `clazz` are both defined in the method signature though, I don't understand why this breaks now.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/199)

**Comment by AzGoalie** [comment]
Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/199)

**Comment by harrison-tarr** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[platform/mime/core/platform-mime-core-impl/src/main/java/ddf/mime/mapper/MimeTypeToTransformerMapperImpl.java, line 104 \[r4\]](https://reviewable.io:443/reviews/codice/ddf/199#-K-JYXdvHcteCyT21I-X)** ([raw file](https://github.com/codice/ddf/blob/bb62b64e294eb82ed9a3db496146f797373c3133/platform/mime/core/platform-mime-core-impl/src/main/java/ddf/mime/mapper/MimeTypeToTransformerMapperImpl.java#L104)):</sup>
I think it needs to be cast to Object and then to T. It seems to not like the direct to T cast. But I don't know, I just know it didn't work and now it does.

---

<sup>**[platform/mime/core/platform-mime-core-impl/src/main/java/ddf/mime/mapper/MimeTypeToTransformerMapperImpl.java, line 130 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/199#-K-0QCfvVUZYocUevZ9K)** ([raw file](https://github.com/codice/ddf/blob/579146352f781dc7b288123baaed097b381fdac7/platform/mime/core/platform-mime-core-impl/src/main/java/ddf/mime/mapper/MimeTypeToTransformerMapperImpl.java#L130)):</sup>
I don't think I follow. isn't the getService() already inlined?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/199)

**Comment by brendan-hofmann** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[platform/mime/core/platform-mime-core-impl/src/main/java/ddf/mime/mapper/MimeTypeToTransformerMapperImpl.java, line 104 \[r4\]](https://reviewable.io:443/reviews/codice/ddf/199#-K-JYXdvHcteCyT21I-X)** ([raw file](https://github.com/codice/ddf/blob/bb62b64e294eb82ed9a3db496146f797373c3133/platform/mime/core/platform-mime-core-impl/src/main/java/ddf/mime/mapper/MimeTypeToTransformerMapperImpl.java#L104)):</sup>
I'm wondering if additional generics constraints were introduced in Java 8, I've found a little bit but nothing directly related.


---

<sup>**[platform/mime/core/platform-mime-core-impl/src/main/java/ddf/mime/mapper/MimeTypeToTransformerMapperImpl.java, line 130 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/199#-K-0QCfvVUZYocUevZ9K)** ([raw file](https://github.com/codice/ddf/blob/579146352f781dc7b288123baaed097b381fdac7/platform/mime/core/platform-mime-core-impl/src/main/java/ddf/mime/mapper/MimeTypeToTransformerMapperImpl.java#L130)):</sup>
I would expect you could just do `strictlyMatching.add((T) bundleContext.getService(ref))`.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/199)

**Comment by harrison-tarr** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[platform/mime/core/platform-mime-core-impl/src/main/java/ddf/mime/mapper/MimeTypeToTransformerMapperImpl.java, line 104 \[r4\]](https://reviewable.io:443/reviews/codice/ddf/199#-K-JYXdvHcteCyT21I-X)** ([raw file](https://github.com/codice/ddf/blob/bb62b64e294eb82ed9a3db496146f797373c3133/platform/mime/core/platform-mime-core-impl/src/main/java/ddf/mime/mapper/MimeTypeToTransformerMapperImpl.java#L104)):</sup>
I found this: http://www.oracle.com/technetwork/java/javase/8-compatibility-guide-2156366.html you can search for "<T>" and find something that seems applicable

---

<sup>**[platform/mime/core/platform-mime-core-impl/src/main/java/ddf/mime/mapper/MimeTypeToTransformerMapperImpl.java, line 130 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/199#-K-0QCfvVUZYocUevZ9K)** ([raw file](https://github.com/codice/ddf/blob/579146352f781dc7b288123baaed097b381fdac7/platform/mime/core/platform-mime-core-impl/src/main/java/ddf/mime/mapper/MimeTypeToTransformerMapperImpl.java#L130)):</sup>
i think it makes more sense to do it like the other example we've been commenting on.  it's more lines of code, but a little more straightforward.  `  Object service = (bundleContext.getService(ref));
                    T typedService = clazz.cast(service);`

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/199)

**Comment by brendan-hofmann** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

<sup>**[platform/mime/core/platform-mime-core-impl/src/main/java/ddf/mime/mapper/MimeTypeToTransformerMapperImpl.java, line 104 \[r4\]](https://reviewable.io:443/reviews/codice/ddf/199#-K-JYXdvHcteCyT21I-X)** ([raw file](https://github.com/codice/ddf/blob/bb62b64e294eb82ed9a3db496146f797373c3133/platform/mime/core/platform-mime-core-impl/src/main/java/ddf/mime/mapper/MimeTypeToTransformerMapperImpl.java#L104)):</sup>
I didn't find any matches for "". I'd suggest extracting instances of this behavior into a method, with a comment referencing the compatibility guide in detail that explains the change in behavior. That way we'll all know what's going on. ;)


---

<sup>**[platform/mime/core/platform-mime-core-impl/src/main/java/ddf/mime/mapper/MimeTypeToTransformerMapperImpl.java, line 130 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/199#-K-0QCfvVUZYocUevZ9K)** ([raw file](https://github.com/codice/ddf/blob/579146352f781dc7b288123baaed097b381fdac7/platform/mime/core/platform-mime-core-impl/src/main/java/ddf/mime/mapper/MimeTypeToTransformerMapperImpl.java#L130)):</sup>
I'm in favor of consistency. Might even be able to extract a reusable method.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/199)

**Comment by harrison-tarr** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

<sup>**[platform/mime/core/platform-mime-core-impl/src/main/java/ddf/mime/mapper/MimeTypeToTransformerMapperImpl.java, line 104 \[r4\]](https://reviewable.io:443/reviews/codice/ddf/199#-K-JYXdvHcteCyT21I-X)** ([raw file](https://github.com/codice/ddf/blob/bb62b64e294eb82ed9a3db496146f797373c3133/platform/mime/core/platform-mime-core-impl/src/main/java/ddf/mime/mapper/MimeTypeToTransformerMapperImpl.java#L104)):</sup>
I guess you can't edit and I guess the markdown ate what i wrote. It should be "&lt;T&gt;" My understanding is that you can't have implied casts from `Object` type to `T` type anymore. 


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/199)

**Comment by brendan-hofmann** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

<sup>**[platform/mime/core/platform-mime-core-impl/src/main/java/ddf/mime/mapper/MimeTypeToTransformerMapperImpl.java, line 104 \[r4\]](https://reviewable.io:443/reviews/codice/ddf/199#-K-JYXdvHcteCyT21I-X)** ([raw file](https://github.com/codice/ddf/blob/bb62b64e294eb82ed9a3db496146f797373c3133/platform/mime/core/platform-mime-core-impl/src/main/java/ddf/mime/mapper/MimeTypeToTransformerMapperImpl.java#L104)):</sup>
Ah, I see it now. That makes sense.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/199)

**Comment by brendan-hofmann** [comment]
:+1: 


---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r4, 1 of 1 files at r5, 2 of 3 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/199)

**Comment by NGoss** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r4, 1 of 1 files at r5, 2 of 3 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/199)

**Comment by mverret** [comment]
LGTM

**Comment by shaundmorris** [comment]
:+1: did a full build and verified docs

**Comment by shaundmorris** [comment]
@harrison-tarr nice catches in the README and AbstractIntegrationTest

**Comment by brendan-hofmann** [comment]
Heroed successfully. :+1:

**Pull request merged**
