### PR TITLE
DDF-3203 Resolve SonarQube Critical and Blocker Findings in DDF

### PR DESCRIPTION
**Pull request by josephthweatt**
#### What does this PR do?
Addresses vulnerabilities found by SonarQube.

Findings are in the link below. The majority of issues are pertaining to solr, and will not be fixed here. The only issues fixed in DDF are the renaming of certain final values. 
https://sonarcloud.io/project/issues?id=ddf&resolved=false&severities=BLOCKER%2CCRITICAL&types=VULNERABILITY

#### Who is reviewing it? 
@alexaabrd 
@pklinef 
#### Select relevant component teams: 
https://github.com/orgs/codice/teams
#### Choose 2 committers to review/merge the PR. 
@clockard 
@shaundmorris 
 
#### Any background context you want to provide?
This ticket is part of a larger initiative to resolve SonarQube's findings in DDF as well as downstream projects. 
#### What are the relevant tickets?
[DDF-3203](https://codice.atlassian.net/browse/)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests
#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by vinamartin** [comment]
@shaundmorris Is there not a way to provide a suppression for this other than renaming the variables? 
Feels like a hack to me.

**Comment by shaundmorris** [comment]
yes, @vinamartin we can suppress in SonarQube and mark as false positive. @stustison did this for a few these in the past: https://sonarcloud.io/project/issues?id=ddf&resolutions=FALSE-POSITIVE&types=VULNERABILITY

**Comment by vinamartin** [comment]
@shaundmorris @josephthweatt My feeling here is that we should suppress these in SonarQube instead of making this change.

**Comment by josephthweatt** [comment]
@vinamartin okay, if shaun is fine with that we can do that and I'll close this PR

**Pull request closed without merging**
