### PR TITLE
DDF-4221 Workspace owner checks case insensitive

### PR DESCRIPTION
**Pull request by troymohl**
#### What does this PR do?
Updates logic that checks workspace owner to ignore case on checks.

#### Who is reviewing it? 
@gordocanchola 
@djblue 

#### Select relevant component teams: 
@codice/ui 

#### Ask 2 committers to review/merge the PR and tag them here.
@andrewkfiedler
@bdeining 

#### How should this be tested?
Full build with tests.
1. Install and Login to UI as admin
2. Create a workspace 
3. Shutdown system
4. Update <ddf.home>/etc/users.attributes and change the user part of the emailaddress to something like Admin instead of admin
5. Restart system, Login to UI, verify you see previously created workspace.

#### What are the relevant tickets?
[DDF-4221](https://codice.atlassian.net/browse/DDF-4221)

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by Schachte** [comment]
Do we care about making roles case insensitive as well?

**Comment by troymohl** [comment]
@Schachte This code is called by the logic that is evaluates permissions for roles/groups as well.

**Comment by troymohl** [comment]
build now

**Comment by mojogitoverhere** [comment]
Hero build in progress

**Comment by mojogitoverhere** [comment]
## 🎉 Hero build was successful! 🎉 ##

### Results ###
1. Verified user was able to use previously created workspace after shutting down and editing their email address in `users.attributes`
### Notes ###
This LGTM but I'm not super familiar with how the security `PolicyExtension`s work so I would hold off on merging until @stustison gives it a ✅

**Pull request merged**
