### PR TITLE
DDF-4263 Adds password component, fixes slideout bug

### PR DESCRIPTION
**Pull request by andrewkfiedler**
#### What does this PR do?
 - Adds a password component.
 - Fixes slideout bug where going between notifications and the user panel caused the user panel to no longer show up.

#### Who is reviewing it? 
@djblue
@millerw8
@glenhein 
@mojogitoverhere 

#### How should this be tested?
Test logging in and out.

#### What are the relevant tickets?
[DDF-4263](https://codice.atlassian.net/browse/DDF-4263)

#### Screenshots
screen shot 2018-11-06 at 4 55 45 pm
screen shot 2018-11-06 at 4 55 42 pm

### CODE REVIEW

**Comment by glenhein** [comment]
@andrewkfiedler Could you add a hover tool tip to the eye button that says "Show Password" or "Hide Password" (depending on the button state)?

**Comment by andrewkfiedler** [comment]
> @andrewkfiedler Could you add a hover tool tip to the eye button that says "Show Password" or "Hide Password" (depending on the button state)?

Done 🎉

**Comment by andrewkfiedler** [comment]
build now

**Comment by andrewkfiedler** [comment]
build now

**Comment by andrewkfiedler** [comment]
build now

**Comment by andrewkfiedler** [comment]
build now

**Comment by andrewkfiedler** [comment]
build now

**Comment by andrewkfiedler** [comment]
build now

**Comment by mojogitoverhere** [comment]
## 🎉 Hero build was successful! 🎉 ##

### Results ###
1. Verified user sign in works as expected by setting the auth type to `BASIC|GUEST`
	- Show/hide password correctly toggles the visibility of the characters
	- A show/hide password tooltip is shown on hover
2. Verified the Password component works as expected in the Developer guide
### Notes ###
- It might be nice to also have the sign in form submit on `Enter`

**Pull request merged**
