### PR TITLE
DDF-2089 Add mimetypes to streaming transformers

### PR DESCRIPTION
**Pull request by harrison-tarr**
#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?
@AzGoalie @spearskw @bcwaters 
#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@kcwire
@shaundmorris 
#### How should this be tested?
Bamboo should pass
#### What are the relevant tickets?
DDF-2089
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by AzGoalie** [comment]
lgtm

**Comment by shaundmorris** [comment]
@harrison-tarr can you please add a PR title?

**Comment by stustison** [comment]
This looks like a bug to me. Do we need to backport this to 2.9.x?

**Comment by harrison-tarr** [comment]
@stustison Good call. Made a PR on 2.9.x as well: [DDF-2089-2.9.x](https://github.com/codice/ddf/pull/757)

**Comment by bcwaters** [comment]
Successfully built and installed ddf
also started catalog streaming feature

**Comment by kcwire** [comment]
👍

**Pull request merged**
