### PR TITLE
DDF-1264 use platform 2.8.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by wmcnalli**
@kcwire
@millerw8
@pklinef
@wmcnalli
@jlcsmith
@beyelerb
@emanns95
@jrnorth
@coyotesqrl

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/61)

### CODE REVIEW

**Comment by shaundmorris** [comment]
Think you meant use catalog 2.8.0-SNAPSHOT, but :+1:

**Comment by kcwire** [comment]
+1

**Comment by coyotesqrl** [comment]
+1

**Comment by coyotesqrl** [comment]
Pulled; built; tested. Verified.

**Comment by shaundmorris** [comment]
Looks like this got taken care of in: https://github.com/codice/ddf/pull/57 so we can close this PR. Agree?

**Comment by coyotesqrl** [comment]
That looks right to me, @shaundmorris

**Pull request closed without merging**
