### PR TITLE
[2.11.x] DDF-3368 TestSecurity.testCertificateGeneratorService() fails intermittently

### PR DESCRIPTION
**Pull request by lessarderic**
#### What does this PR do?
Removes the test and the CertificateGeneratorMBean since it wasn't being used.

#### Who is reviewing it? 
(please choose AT LEAST two reviewers that need to approve the PR before it can get merged)
@ahoffer 
@emanns95 

#### Choose 2 committers to review/merge the PR. 
(please choose ONLY two committers from below, delete the rest)
@clockard 
@coyotesqrl 

#### How should this be tested? (List steps with links to updated documentation)
Build DDF and all downstream projects and make sure `CertNew.sh` script works as expected.

#### What are the relevant tickets?
[DDF-3368](https://codice.atlassian.net/browse/DDF-3368)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [x] Update / Add Integration Tests
#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by lessarderic** [comment]
build now

**Comment by lessarderic** [comment]
build now

**Comment by lessarderic** [comment]
build now

**Comment by lessarderic** [comment]
build now

**Comment by lessarderic** [comment]
build now

**Comment by lessarderic** [comment]
build now

**Comment by lessarderic** [comment]
build now

**Comment by lessarderic** [comment]
build now

**Comment by lessarderic** [comment]
build now

**Comment by ahoffer** [comment]
There are two unused convenience methods that can now be deleted:
`CertificateCommand` 
    `public static String configureDemoCert(String commonName)`
    `public static String configureDemoCertWithDN(String[] dn)`

**Comment by lessarderic** [comment]
@ahoffer, I'll leave those in there for now since that class is exposed through a `main()` method and packaged in a jar that's used from a script. Those shouldn't be used anywhere but I'd rather keep the clean up to a minimum at this point if it's ok for you.

**Comment by lessarderic** [comment]
Putting this PR on hold since it was most likely caused by the Security Manager, which has now been removed.

**Comment by ahoffer** [comment]
@lessarderic  I agree. Those methods cannot be called from `main()`, but they are exposed through Jolokia.

**Comment by lessarderic** [comment]
This isn't an issue anymore, so closing this PR.

**Pull request closed without merging**
