### PR TITLE
DDF-1384: Changed access modifiers used by CSW application for derive…

### PR DESCRIPTION
**Pull request by jlcsmith**
…d classes

@millerw8 @jlcsmith @kcwire @wmcnalli @beyelerb @emanns95 @kguerriero @shane-voisard

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/98)

Jay's the hero for this one.

### CODE REVIEW

**Comment by kcwire** [comment]
:+1:

**Comment by emanns95** [comment]
:+1:

**Comment by kguerriero** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/98)

**Comment by wmcnalli** [comment]
:+1: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/98)

**Comment by beyelerb** [comment]
:+1: 

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/98)

**Comment by jrnorth** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/98)

**Pull request merged**
