### PR TITLE
[2.13.x] DDF-4120 Fixed refresh result count

### PR DESCRIPTION
**Pull request by austinsteffes**
#### What does this PR do?
Backport of https://github.com/codice/ddf/pull/3769 plus a few additional differences between release/master in order for these changes to work correctly

#### Who is reviewing it? 
@garrettfreibott 
@mcalcote 
@jhunzik 

#### Ask 2 committers to review/merge the PR and tag them here.

@andrewkfiedler
@bdeining
@ricklarsen - Documentation
#### What are the relevant tickets?
[](https://codice.atlassian.net/browse/)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by austinsteffes** [comment]
build now

**Comment by austinsteffes** [comment]
bad rebase cause many people to be added for review. sorry

**Comment by austinsteffes** [comment]
redid the cherry-pick plus additional changes needed to support the cherry-picked commit

**Comment by austinsteffes** [comment]
build now

**Comment by rzwiefel** [comment]
@austinsteffes Whats the status of this?

**Comment by austinsteffes** [comment]
> @austinsteffes Whats the status of this?

Too big of divergence between release and master. commits that was to be ported rely on code already in master. Will have to re-engineer after I finish a different ticket I started when I was waiting to ask questions when people were out.

**Comment by coyotesqrl** [comment]
@austinsteffes, might it make more sense to close this PR as you'll need to do some significant redesigning of the change?

**Comment by austinsteffes** [comment]
@coyotesqrl Makes more sense to me. Thanks

**Pull request closed without merging**
