### PR TITLE
DDF-2125 Streamline default value injection for metacards

### PR DESCRIPTION
**Pull request by jrnorth**
#### What does this PR do?
Streamlines how default values are injected into metacards in the catalog framework.

#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?
@rzwiefel 
@glenhein 

#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@jlcsmith
@kcwire

#### How should this be tested?
Create a JSON file that includes some default attribute values as shown in the documentation, ingest some metacards, and verify that the default values were added where appropriate.

#### What are the relevant tickets?
[DDF-2125](https://codice.atlassian.net/browse/DDF-2125)

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by glenhein** [comment]
lgtm

**Comment by rzwiefel** [comment]
:+1:

**Comment by jlcsmith** [comment]
Built and tested - LGTM.  👍

**Comment by jlcsmith** [comment]
We'll need to get this in to 2.9.x as well

**Comment by kcwire** [comment]
👍

**Pull request merged**
