### PR TITLE
DDF-2278 [2.9.x]: Turn catalog-core-validationparser on by default

### PR DESCRIPTION
**Pull request by rzwiefel**
#### What does this PR do?
Turns catalog-core-validationparser on by default
#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?
@coyotesqrl @kcwire @jlcsmith @jrnorth 

#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).

@stustison 
@pklinef

#### What are the relevant tickets?
https://codice.atlassian.net/browse/DDF-2278

### CODE REVIEW

**Comment by coyotesqrl** [comment]
👍

**Comment by pklinef** [comment]
I agree that the validation parser should be enabled for 2.10 but I don't agree that this should be back ported to 2.9.  Is there a reason for enabling it on 2.9.2?  Does that fix a bug?

**Comment by rzwiefel** [comment]
I was told to make a 2.9.x pr, did not think to deeply about why or why not, maybe they didn't either. I'm not opposed to not backporting it and closing this PR unless there's any opposing reasoning someone would like to present.

**Comment by rzwiefel** [comment]
Closing because no need to backport this change to 2.9.X

**Pull request closed without merging**
