### PR TITLE
Ddf 1172 unit tests for missing items

### PR DESCRIPTION
**Pull request by NGoss**
@brendan-hofmann @mverret

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/90)

### CODE REVIEW

**Comment by brendan-hofmann** [comment]
admin-core-insecuredefaults needs coverage limits.

---

Reviewed 40 of 40 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/90)

**Comment by NGoss** [comment]
Added coverage. It successfully ran on my machine, so should be good now.

---

Review status: 40 of 41 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/90)

**Comment by brendan-hofmann** [comment]
LGTM :+1: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/90)

**Comment by shaundmorris** [comment]
Build was successful. Original PR comments were made here: https://github.com/codice/ddf-platform/pull/88

**Pull request merged**
