### PR TITLE
[2.26.x] Fix multi-value expports for RTF

### PR DESCRIPTION
**Pull request by alexabird**

### CODE REVIEW

**Review by jlcsmith — APPROVED** [review]

**Comment by jlcsmith** [comment]
that was an easy one :)

**Comment by jlcsmith** [comment]
build now

**Review by pvargas — APPROVED** [review]

**Comment by alexabird** [comment]
build now

**Review by pvargas — APPROVED** [review]

**Review by jrnorth — APPROVED** [review]

**Comment by alexabird** [comment]
build now

**Comment by jrnorth** [comment]
I'm verifying the changes.

**Pull request merged**
