### PR TITLE
DDF-2271- Adds Registry app to install profiles

### PR DESCRIPTION
**Pull request by vinamartin**
#### What does this PR do?
Adds registry-app to standard and development install profiles. 
#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?
@mcalcote 
@gordocanchola 
#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@lessarderic
@stustison
#### How should this be tested?
Full build, start up the DDF, install with Development setting and make sure registry-app has started.
#### What are the relevant tickets?
https://codice.atlassian.net/browse/DDF-2271
#### Checklist:
- [x] Documentation Updated
- [x] Update / Add Unit Tests
- [x] Update / Add Integration Tests

### CODE REVIEW

**Comment by mcalcote** [comment]
Assuming Bamboo -> 👍

**Comment by lessarderic** [comment]
LGTM 👍 

Out of curiosity, have you guys tried to do an export/import of the configurations (http://codice.org/ddf/managing.html#_importing_configurations) and see if all the registry configurations get cloned properly?

**Comment by vinamartin** [comment]
@lessarderic Good question. We haven't tried that yet.

**Comment by spearskw** [comment]
:+1: hero'd and manually tested

**Pull request merged**
