### PR TITLE
[2.26.x] DDF-6360 Upgrade to CXF 3.4.0

### PR DESCRIPTION
**Pull request by SmithJosh**
#### What does this PR do?
This is a clean backport of https://github.com/codice/ddf/pull/6361. I was able to cherry-pick all the commits over without any merge conflicts.

Upgrades to CXF 3.4.0, and along with it upgrades a bunch of other dependencies, including:

* OpenSAML -> 3.4.5
* WSS4J -> 2.3.0
* Santuario (xmlsec) -> 2.2.0
* JAXB API -> Jakarta JAXB API
* Sun JAXB impl to Glassfish JAXB impl
* Javax Annotation API -> Jakarta Annotation API
* JavaBeans Activation Framework API -> Jakarta Activation API

#### Who is reviewing it? 

@bakejeyner @emmberk @Lambeaux @stustison 

#### Select relevant component teams: 
@codice/security 

#### How should this be tested?

The major issues I ran into when upgrading were very slow installation times and JAXB errors. With that in mind, verify that:
* Installation is not abnormally slow
* Anything using JAXB still works (XML marshalling, unmarshalling)
  * Adding and querying sources: CSW & OpenSearch (loopback is fine) and WFS (I used http://geomap.reteunitaria.piemonte.it/ws/gsareprot/rp-01/areeprotwfs/wfs_gsareprot_1, which is WFS 1.1.0 and just tested that the source is shown as active)
  * XML transformer: ingest an XML document with geometry, then download it via the xml transformer

#### What are the relevant tickets?
Fixes: #6360

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by SmithJosh** [comment]
build now

**Comment by SmithJosh** [comment]
build now

**Review by emmberk — APPROVED** [review]

**Comment by SmithJosh** [comment]
build now

**Review by stustison — APPROVED** [review]

**Review by bakejeyner — APPROVED** [review]

**Comment by jlcsmith** [comment]
🎉 hero successful 🎉 
- verified normal build/install
- verified ingest of XML 
- verified CSW/WFS sources

**Pull request merged**
