### PR TITLE
DDF-04456 Fixing point/rad and excess boolean ANDS

### PR DESCRIPTION
**Pull request by Schachte**
#### What does this PR do?
1) Fixes incorrect deserialization of point-radius from geojson filtertree when rendering circles on map. 
2) Fixes issue where we would excessively render AND boolean clauses on queries in the advanced query editor. 
#### Select relevant component teams: 
@codice/ui 

#### Ask 2 committers to review/merge the PR and tag them here.

@andrewkfiedler
@bdeining 
@djblue 

#### How should this be tested?
Create a point radius from advanced query window, ensure that it renders correctly when re-editing. 

For GH Issues:
Fixes: #4456

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by Schachte** [comment]
build now

**Comment by willwill96** [comment]
hero started

**Comment by Schachte** [comment]
Build now

**Comment by willwill96** [comment]
🌮 Hero Successful 🌮 
1. Constructed Several Nested queries and made sure they were persisted and reloaded correctly.
2. Constructed point-radius queries and ensured they were re-rendered correctly while editing.

LGTM

**Comment by Schachte** [comment]
build now

**Pull request merged**
