### PR TITLE
DDF-4107 fixed formatter build

### PR DESCRIPTION
**Pull request by bdeining**
#### What does this PR do?
 fixed formatter build
#### Select relevant component teams: 
https://github.com/orgs/codice/teams
#### Ask 2 committers to review/merge the PR and tag them here.

@andrewkfiedler
@djblue
#### How should this be tested?
Build

#### What are the relevant tickets?
[](https://codice.atlassian.net/browse/)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by bdeining** [comment]
build now

**Comment by bdeining** [comment]
build now

**Comment by bdeining** [comment]
build now

**Comment by mcalcote** [comment]
Both of the builds failed with:
`[ERROR] error An unexpected error occurred: "http://nexus3.phx.connexta.com/repository/npmjs.org/caniuse-db/-/caniuse-db-1.0.30000884.tgz: Request failed \"404 Not Found\"".`
I don't think this will be resolved in the build that just got kicked off...

**Pull request closed without merging**
