### PR TITLE
DDF-4469 Address react workspace unique key js warnings in console

### PR DESCRIPTION
**Pull request by rymach**
See original PR that died from neglect: 
https://github.com/codice/ddf/pull/4226

I don't think the moment warning is showing up anymore I won't worry about that part

#### Ask 2 committers to review/merge the PR and tag them here.

@andrewkfiedler
@AzGoalie

#### What are the relevant tickets?
For Jira:
[](https://codice.atlassian.net/browse/)

For GH Issues:
Fixes: #____

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by rymach** [comment]
don't build now

**Comment by rymach** [comment]
> ❓ In what case would a workspace not have an ID?

for a split second when you first create the workspace it doesn't have an id

**Comment by willwill96** [comment]
> > ❓ In what case would a workspace not have an ID?
> 
> for a split second when you first create the workspace it doesn't have an id

I kind of wonder if we should defer creating the workspace object until we have an id for it. I don't know if the current workflow would make that difficult though.

**Comment by Lambeaux** [comment]
I agree with @ethantmanns. Let's get this a proper issue number or, at minimum, defer to the issue number that introduced this.

**Comment by Lambeaux** [comment]
@willwill96 Since workspaces are represented as metacards, we rely on IDs provided by the catalog framework. But there's no way to know an ID is valid / stable until the first persistence operation is successful. In order to persist something, you need the data structure you want to persist, otherwise you get in this contradictory situation: 
>Can't make a workspace because I don't have an ID
>Can't make/reserve an ID because I don't have a workspace

**Comment by mojogitoverhere** [comment]
build now

**Comment by mojogitoverhere** [comment]
## 🎉 Hero build was successful! 🎉 ##

Note: The error only appears while running the dev server
1. Verified the error is shown on master with the dev server
2. Checked out changes
3. Verified the error is no longer shown

**Comment by rymach** [comment]
build now and then ready for merge

**Pull request merged**
