### PR TITLE
DDF-2370 changed AuthNStatementProvider to only create RNG once

### PR DESCRIPTION
**Pull request by stustison**
#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?
@tbatie  @pklinef 

#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@coyotesqrl
@stustison
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by coyotesqrl** [comment]
That should be a big speedup. 👍

**Comment by pklinef** [comment]
:+1:

**Comment by stustison** [comment]
Yeah, I saw a difference of about half the latency during the query performance tests. So it does provide a nice bump in performance.

**Comment by tbatie** [comment]
:+1:

**Pull request merged**
