### PR TITLE
Update the paging to be entirely server side

### PR DESCRIPTION
**Pull request by andrewkfiedler**
#### What does this PR do?
Update the paging to be entirely server side

#### Who is reviewing it? 
@djblue 
@Schachte 
@adimka 
@tbatie 

#### How should this be tested?
Run searches and verify paging works as expected.

For GH Issues:
Fixes: #4492 

#### Screenshots
See the #4492 for screenshots

### CODE REVIEW

**Comment by troymohl** [comment]
How does this work with "Result Page Size" and "Result Count"? Does this only use Result Page Size? Does the user still have the ability to set their preferred number results (up to Result Count) for the page?

**Comment by andrewkfiedler** [comment]
@troymohl I went ahead and removed the page size configuration option since the result count option preceded it.  

So now the only configuration left for "page size" is result count, seen here: 
image

And as before, the user can set their actual result count to be anything up to that maximum set by the admin, shown here:
image

I think there is more cleanup work that can be done with the naming of this option, but I don't think we need to tackle it with this PR.

**Comment by Bdthomson** [comment]
Hero in Progress

**Comment by troymohl** [comment]
@andrewkfiedler With 250 per source, you could technically have 1000 results on your page if you had 4 sources selected correct?

**Comment by andrewkfiedler** [comment]
@troymohl it works the same way it does today.  So with 250 count and 4 sources, you still only get the top 250.

**Comment by Bdthomson** [comment]
Tested with local catalog and federated sources, discovered an existing bug where federated sources are sent the incorrect starting index when you hit "Update Results" button. (Works correctly with local catalog however).

In addition, when I change my sort from A -> Z to Z -> A using local catalog, the sort is per page, with a page size of 5 and the results A, B, C, D, E, F, G, H, I, and J, the first page displays E, D, C, B, A and the second page displays J, I, H, G, F. I don't know if this is the expected behavior.

**Comment by andrewkfiedler** [comment]
@Bdthomson thanks for testing this.

I confirmed the start index bug on master as well, hopefully we can address it in a future PR.

The sorting behavior is expected at the moment, at least if you were using the local sorting.  That doesn't issue a requery, but instead sorts the data that's already been returned locally.

**Comment by andrewkfiedler** [comment]
build now

**Comment by andrewkfiedler** [comment]
build now

**Comment by Bdthomson** [comment]
OWASP fix was merged, you just need to rebase.

**Comment by andrewkfiedler** [comment]
build now

**Pull request merged**
