### PR TITLE
DDF-4960 Fix Solr Relevancy configuration

### PR DESCRIPTION
**Pull request by troymohl**
#### What does this PR do?
Fixes problems with setting Solr relevancy after the changes to Solr authentication were made.

#### Who is reviewing it? 
@Schachte 
@Lambeaux 

#### Select relevant component teams: 
@codice/solr 

#### Ask 2 committers to review/merge the PR and tag them here.
@adimka 
@bdeining 
@millerw8 
@pklinef

#### Any background context you want to provide?
Navigate to the Admin UI -> Solr Catalog
Select Catalog Solr Relevancy Ranking
Change parameters to k1=1.11, b=.50
Click Save
Verify that Solr is updated: https://localhost:8994/solr/catalog/schema/fieldtypes?wt=json

#### What are the relevant tickets?
Fixes: #4960 

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [X] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by jrnorth** [comment]
build now

**Comment by troymohl** [comment]
build now

**Comment by Schachte** [comment]
hero in prog

**Comment by Schachte** [comment]
Screen Shot 2019-06-25 at 9 26 38 AM
Verification successful

**Pull request merged**
