### PR TITLE
DDF-1711: Removed 'Configuration Admin JMX Bridge'

### PR DESCRIPTION
**Pull request by brianfelix**
@mcalcote @vinamartin @gordocanchola @clockard @ricklarsen

### CODE REVIEW

**Comment by clockard** [comment]
LGTM :+1:

**Comment by vinamartin** [comment]
LGTM :+1:

**Comment by stustison** [comment]
:shipit:

**Comment by mcalcote** [comment]
Successfully Built on Latest -> :ship:it

**Comment by brianfelix** [comment]
@scott ready to merge :+1:

**Pull request merged**
