### PR TITLE
DDF-1818: reorganized documentation modules to avoid redundant rendering

### PR DESCRIPTION
**Pull request by ricklarsen**
@clockard @stustison @oscaritoro @vinamartin @djblue @gordocanchola

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/codice/ddf/pull/489" target="_blank">ReviewNinja

**Comment by clockard** [comment]
LGTM :+1:

**Comment by oscaritoro** [comment]
Built successfully and LGTM :+1:

**Comment by vinamartin** [comment]
Resolve conflicts, but LGTM :+1:

**Comment by ricklarsen** [comment]
fixed conflicts

**Comment by oscaritoro** [comment]
Still good!, Ship it! :+1:

**Pull request merged**
