### PR TITLE
DDF-1521 Added code fix and tests

### PR DESCRIPTION
**Pull request by harrison-tarr**
Added code fix to check bind status after call
and added 2 new test classes to test bind failures
in their corresponding classes.

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/198)

### CODE REVIEW

**Comment by harrison-tarr** [comment]
@AzGoalie @stustison @mverret

**Comment by AzGoalie** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/198)

**Comment by shaundmorris** [comment]
@harrison-tarr would you be willing to change the commit message. I think a bit more of your first comment on the PR here would be great for it. https://codice.atlassian.net/wiki/display/DDF/Git+Commit+Message+Guidelines

**Comment by AzGoalie** [comment]
Everything looks good, built fine, all tests pass except for the know issue with testX509TokenSTS

**Comment by mverret** [comment]
LGTM

**Comment by shaundmorris** [comment]
Is there a way to test for successful binds or is that covered elsewhere?

**Comment by harrison-tarr** [comment]
You mean are unit there tests written for it? I don't know. I assumed since the code in this file was already written, there was an appropriate amount of tests for it already. I just added my test since this was a case we hadn't considered before.


---

Review status: 3 of 6 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/198)

**Comment by AzGoalie** [comment]
I'm still having testX509TokenSTS fail... but it seems to be rebased with master.

**Comment by AzGoalie** [comment]
Prbs build and passed.
lgtm
:+1:

**Pull request merged**
