### PR TITLE
DDF-4962 NPE is thrown when the Solr Response results are empty

### PR DESCRIPTION
**Pull request by cantstoptheunk**
#### What does this PR do?
Fixes a potential NPE in SolrMetacardClientImpl in the case where the set of results returns null after a query is run. 
Also makes a small change to the spellcheck UI code for a downstream project, and added add unit tests

#### Who is reviewing it? 
@Bdthomson 
@bellcc 
@andrewkfiedler 
@vinamartin 

#### Select relevant component teams: 
@codice/solr 

#### Ask 2 committers to review/merge the PR and tag them here.
@paouelle
@pklinef

#### How should this be tested?
Test spellcheck features, did you mean and showing results for and regression testing on normal searches.

#### What are the relevant tickets?
Fixes: #____

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by jlcsmith** [comment]
Do we need to port to 2.15.x?

**Comment by cantstoptheunk** [comment]
I'd say yes since the error exists in 2.15.x. I can create a PR for backporting it

**Comment by cantstoptheunk** [comment]
build now

**Comment by cantstoptheunk** [comment]
build now

**Comment by rececoffin** [comment]
hero in progress

**Comment by rececoffin** [comment]
Hero successful
Ingested data and tested that all spellcheck, suggestion capabilities still function properly.
Ran a query that gave null results, no null pointer exception was thrown.

**Pull request merged**
