### PR TITLE
DDF-1722: added missing dependencies.

### PR DESCRIPTION
**Pull request by djblue**
@rzwiefel 
@stustison 
@pklinef 
@garrettfreibott

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/codice/ddf/pull/480" target="_blank">ReviewNinja

**Comment by stustison** [comment]
LGTM

**Comment by lessarderic** [comment]
:shipit:

**Comment by lessarderic** [comment]
Will run a "quick" prbs and merge if successful.

**Comment by garrettfreibott** [comment]
:+1:

**Comment by pklinef** [comment]
:+1:

**Comment by lessarderic** [comment]
Ran prbs and `dib.test.itests.distribution.TestDibRegistrySecure.testClientSourcePreference()` failed :-( That's the only failure I got. I'll take another look tomorrow.

**Comment by lessarderic** [comment]
Since other people have seen the same itest problem and this is breaking DDF, I'll go ahead and merge this PR.

**Pull request merged**
