### PR TITLE
[2.11.x] DDF-3105 Create Component test for REST endpoint

### PR DESCRIPTION
**Pull request by lessarderic**
#### What does this PR do?
Back-port of https://github.com/codice/ddf/pull/2090.
Created initial REST endpoint component tests and common test library.
Moved Pax Exam specific classes from itests-common to common test library.
Moved PaxExamRule to the new common test library, improved TestFailureLogger and added JavaDoc comments.
Updated itests to use new common test library.

#### Who is reviewing it? 
(please choose AT LEAST two reviewers that need to approve the PR before it can get merged)
@tbatie 
@vinamartin 

#### Select relevant component teams: 
https://github.com/orgs/codice/teams

#### Choose 2 committers to review/merge the PR. 
(please choose ONLY two committers from below, delete the rest)
@brendan-hofmann
@rzwiefel 

#### How should this be tested? (List steps with links to updated documentation)
Successful build.

#### Any background context you want to provide?
Back-port of https://github.com/codice/ddf/pull/2090.
Note that some manual changes were needed after the cherry-pick because `master` and `2.11.x` are starting to diverge, so some attention should be paid to the changes.

#### What are the relevant tickets?
[DDF-3105](https://codice.atlassian.net/browse/DDF_3105)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [x] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by lessarderic** [comment]
build now

**Comment by lessarderic** [comment]
build now

**Comment by brendan-hofmann** [comment]
Failure looks spurious. build now

**Comment by lessarderic** [comment]
build now

**Comment by lessarderic** [comment]
build now

**Pull request merged**
