### PR TITLE
DDF-2590: Suppressing OWASP warning because security vulnerability does not exist

### PR DESCRIPTION
**Pull request by brjeter**
#### What does this PR do?
Suppresses the OWASP warning for this vulnerability since our project does not use the Java class that has the vulnerabilty.
#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged)?
@lessarderic @shaundmorris @Lambeaux 
#### Select at least one member from relevant component team(s) from below (at least one component team member needs to approve the PR).
[Build](https://github.com/orgs/codice/teams/build)
[Security](https://github.com/orgs/codice/teams/security)
#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@lessarderic
@shaundmorris 
#### How should this be tested? (List steps with links to updated documentation)
Run a successful build with the owasp profile `mvn clean instal -Powasp`
#### What are the relevant tickets?
[DDF-2590](https://codice.atlassian.net/browse/DDF-2590)
#### Checklist:
- [ ] Documentation Updated
- [ ] Change Log Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by lessarderic** [comment]
Approved once we've confirmed that OWASP takes into consideration transitive dependencies, i.e., none of the libraries we depend on use the `DiskFileItem` class.

**Comment by brjeter** [comment]
Have confirmed that OWASP checks transitive dependencies for security vulnerabilities, so this should be good to go.

**Comment by shaundmorris** [comment]
Bamboo build was successful but had: java.lang.OutOfMemoryError: Java heap space

**Comment by bantillo** [comment]
Hero build was successful. 👍

**Pull request merged**
