### PR TITLE
DDF-5602 hide templates dropdown in Lists when none are defined

### PR DESCRIPTION
**Pull request by cassandrabailey293**
##### ABBREVIATED REVIEW
Link to 2.19.x PR : #5603 

_____

#### What does this PR do?

This PR hides the Template section in Lists when no system defined filters exist

#### Who is reviewing it? 

@hayleynorton @zta6 

#### Select relevant component teams: 

@codice/ui

#### Ask 2 committers to review/merge the PR and tag them here.

@bdeining 

#### How should this be tested?

1. Select list tab
2. create a new lists
3. Verify that if there are no system defined filters, the templates view is gone. 
**Note**: It should also be gone for this case when editing a list.

#### What are the relevant tickets?
Fixes: #5602 

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by cassandrabailey293** [comment]
build now

**Comment by andrewzimmer** [comment]
build now

**Comment by andrewzimmer** [comment]
build now

**Comment by andrewzimmer** [comment]
Hero Successful 🎉 
- Verified the templates view doesn't show if there are no system defined List Templates

**Pull request merged**
