### PR TITLE
DDF-3103 Upgrade libraries in non-Intrigue javascript

### PR DESCRIPTION
**Pull request by albany551**
#### What does this PR do?

Upgrades the following javascript libraries, in all non-Intrigue UIs, to the latest available from org.webjars:

- Bootstrap
- Cesium
- Font-Awesome
- Html5Shiv
- Jquery
- Jquery-ui
- Js-cookie
- Moment
- Perfect Scrollbar
- Q
- RequireJS
- RequireJS-plugins
- RequireCSS
- Spectrum
- spin.js

Backbone cannot be upgraded trivially because it didn't follow semantic versioning and its next minor revision breaks Marionette below 3.x.
To use Marionette 3.x would require additional refactoring work across our UIs.

As for lodash, in most places we are using it as a drop-in replacement for underscore (the latter being a fundamental dependency of backbone). The latest lodash (4.x) similarly breaks Marionette below 3.x, so in places where it is being used as an underscore replacement I simply substituted in the latest version of underscore.

#### Who is reviewing it? 
@andrewkfiedler 
@djblue 

#### Choose 2 committers to review/merge the PR. 
@andrewkfiedler
@millerw8

#### How should this be tested? (List steps with links to updated documentation)

Full manual regression of all admin UIs as well as standard and simple search UIs!

#### What are the relevant tickets?
https://codice.atlassian.net/browse/DDF-3103

### CODE REVIEW

**Comment by mackncheesiest** [comment]
build now

**Comment by mackncheesiest** [comment]
Hero process: checked out PR, rebased it against master, quick built, installed every feature in Admin UI that would install (a few gave bundle wiring issues that are likely unrelated to this PR), modified every config that appeared to change an UI option (i.e. adding headers/footers/system usage message), ingested some data (`catalog-transformer-pdf/.../sample.pdf` and `catalog-transformer-pptx/.../empty.ppt`), and tested UI components on Admin UI, Intrigue, Standard Search, and Simple Search. 

I haven't yet verified yet that all of these _are_ caused by this PR and weren't just existing bugs no one had found yet, but here are the results: 

* Platform UI Configuration (DDF :: Platform :: Configuration) the body of a system usage message doesn’t show up
```
Uncaught TypeError: Cannot read property 'href' of null
    at getSrc (:8993/search/catalog/webpack:/component/system-usage/system-usage.view.js:26)
    at HTMLDocument.<anonymous> (:8993/search/catalog/webpack:/component/system-usage/system-usage.view.js:35)
    at mightThrow (:8993/search/catalog/webpack:/Users/josh/ddf/ddf/catalog/ui/catalog-ui-search/~/jquery/dist/jquery.js:3583)
    at process (:8993/search/catalog/webpack:/Users/josh/ddf/ddf/catalog/ui/catalog-ui-search/~/jquery/dist/jquery.js:3651)
```

* Enabling "show tasks" in configuration for Catalogue UI Search doesn't enable a tasks menu in Intrigue (no exceptions thrown, however)

* Enabling login page header and footer in Security -> Login Page (`DDF :: Security :: Handler :: Guest`) configuration doesn't enable a header or footer on the login page (could be due to the IdP redirect?)

* Standard Search UI doesn't display any Record information about either of the two records I ingested. Clicking on a record shows an empty pane with the following JS exception
```
sliding.region.js:91 TypeError: Cannot read property 'length' of undefined
    at String.appendValue (HandlebarsHelpers.js:225)
    at eval (eval at createFunctionContext (handlebars.min.js:28), <anonymous>:4:115)
    at Object.h [as inverse] (handlebars.min.js:27)
    at String.isUrl (HandlebarsHelpers.js:215)
    at eval (eval at createFunctionContext (handlebars.min.js:28), <anonymous>:5:90)
    at h (handlebars.min.js:27)
    at c (handlebars.min.js:27)
    at Array.<anonymous> (handlebars.min.js:27)
    at eval (eval at createFunctionContext (handlebars.min.js:28), <anonymous>:6:31)
    at Object.h [as fn] (handlebars.min.js:27)
```

* Simple Search UI throws the following error when attempting to display resource metadata for PDF (the PPT works fine, however)
```
Search-min.js:1 Uncaught TypeError: Cannot read property 'documentElement' of null
    at buildMetadataHtml (Search-min.js:1)
    at Object.<anonymous> (Search-min.js:1)
    at Object.eval (eval at createFunctionContext (handlebars.js:1455), <anonymous>:121:104)
    at handlebars.js:2210
    at handlebars.js:2170
    at Object.success (Search-min.js:1)
    at k (jquery-1.8.2.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-1.8.2.min.js:2)
    at y (jquery-1.8.2.min.js:2)
    at XMLHttpRequest.d (jquery-1.8.2.min.js:2)
```

* NPE when using Standard Search UI, and user session doesn’t carry over even though I’m logged in already. Also, logging in again doesn't change that.
```
13:10:46,024 | INFO  | tp1566982762-311 | search-endpoint      | Exception while invoking listener org.cometd.annotation.ServerAnnotationProcessor$ListenerCallback@47c82200
java.lang.NullPointerException
	at java.io.StringReader.<init>(StringReader.java:50) [?:?]
	at org.codice.ddf.ui.searchui.query.service.UserService.getUser(UserService.java:90) [447:search-endpoint:2.11.0.SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:?]
	at org.cometd.annotation.AnnotationProcessor.invokePublic(AnnotationProcessor.java:217) [447:search-endpoint:2.11.0.SNAPSHOT]
	at org.cometd.annotation.ServerAnnotationProcessor$ListenerCallback.onMessage(ServerAnnotationProcessor.java:643) [447:search-endpoint:2.11.0.SNAPSHOT]
	at org.cometd.server.BayeuxServerImpl.notifyOnMessage(BayeuxServerImpl.java:991) [447:search-endpoint:2.11.0.SNAPSHOT]
	at org.cometd.server.BayeuxServerImpl.notifyListeners(BayeuxServerImpl.java:951) [447:search-endpoint:2.11.0.SNAPSHOT]
	at org.cometd.server.BayeuxServerImpl.doPublish(BayeuxServerImpl.java:878) [447:search-endpoint:2.11.0.SNAPSHOT]
	at org.cometd.server.ServerChannelImpl.publish(ServerChannelImpl.java:331) [447:search-endpoint:2.11.0.SNAPSHOT]
	at org.cometd.server.BayeuxServerImpl.handle(BayeuxServerImpl.java:734) [447:search-endpoint:2.11.0.SNAPSHOT]
	at org.cometd.server.BayeuxServerImpl.handle(BayeuxServerImpl.java:664) [447:search-endpoint:2.11.0.SNAPSHOT]
	at org.cometd.server.transport.AbstractHttpTransport.bayeuxServerHandle(AbstractHttpTransport.java:552) [447:search-endpoint:2.11.0.SNAPSHOT]
	at org.cometd.server.transport.AbstractHttpTransport.processMessages(AbstractHttpTransport.java:222) [447:search-endpoint:2.11.0.SNAPSHOT]
	at org.cometd.server.transport.AsyncJSONTransport$AbstractReader.process(AsyncJSONTransport.java:170) [447:search-endpoint:2.11.0.SNAPSHOT]
	at org.cometd.server.transport.AsyncJSONTransport$AbstractReader.onAllDataRead(AsyncJSONTransport.java:155) [447:search-endpoint:2.11.0.SNAPSHOT]
	at org.eclipse.jetty.server.HttpInput.run(HttpInput.java:680) [74:org.eclipse.jetty.server:9.3.14.v20161028]
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:1286) [74:org.eclipse.jetty.server:9.3.14.v20161028]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:418) [74:org.eclipse.jetty.server:9.3.14.v20161028]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [74:org.eclipse.jetty.server:9.3.14.v20161028]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [66:org.eclipse.jetty.io:9.3.14.v20161028]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [66:org.eclipse.jetty.io:9.3.14.v20161028]
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:202) [66:org.eclipse.jetty.io:9.3.14.v20161028]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [66:org.eclipse.jetty.io:9.3.14.v20161028]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [66:org.eclipse.jetty.io:9.3.14.v20161028]
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [66:org.eclipse.jetty.io:9.3.14.v20161028]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [77:org.eclipse.jetty.util:9.3.14.v20161028]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [77:org.eclipse.jetty.util:9.3.14.v20161028]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [77:org.eclipse.jetty.util:9.3.14.v20161028]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [77:org.eclipse.jetty.util:9.3.14.v20161028]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [77:org.eclipse.jetty.util:9.3.14.v20161028]
	at java.lang.Thread.run(Thread.java:748) [?:?]
```
(for the record, Intrigue displays information for both files fine)

Along with these issues that I'm fairly confident are unrelated to this PR
* `catalog-plugin-federationreplication` doesn't install (and prints no logs about it)
* `cxd-http-netty-server` throws a BundleException when attempting to install
* `cxf-jaxrs-cdi` doesn't install (and prints no logs about it)
* `cxf-management-web` throws a BundleException when attempting to install
* `security-cas-{client, cxfservletfilter, tokenvalidator}` all don't install
* `spatial-connected-sources` doesn't install

**Comment by albany551** [comment]
@mackncheesiest :1st_place_medal: 

> Platform UI Configuration (DDF :: Platform :: Configuration) the body of a system usage message doesn’t show up

This is an Intrigue issue, so not affected by changes here. It looks like the javascript tries to dynamically copy stylesheet tags from the container into the iframe that holds the system message body. I was only able to see it fail when running an Intrigue dev build, where the expected `<link>` tags are absent. 

> Enabling "show tasks" in configuration for Catalogue UI Search (DDF :: Catalog :: UI :: Catalog UI Search) doesn't enable a tasks menu in Intrigue (no exceptions thrown, however)

Didn't see the tasks menu when running master; perhaps a deprecated feature?

> Enabling login page header and footer in Security -> Login Page (DDF :: Security :: Handler :: Guest) configuration doesn't enable a header or footer on the login page (could be due to the IdP redirect?)

Didn't see headers in master; perhaps another deprecated feature?

> Standard Search UI doesn't display any Record information about either of the two records I ingested. Clicking on a record shows an empty pane with the following JS exception

Fixed.

> Simple Search UI throws the following error when attempting to display resource metadata for PDF (the PPT works fine, however)

Fixed, although this was an existing bug - it always tries to parse the metadata as xml and didn't handle failures therein.

> NPE when using Standard Search UI, and user session doesn’t carry over even though I’m logged in already. Also, logging in again doesn't change that.
> I think this issue is reproducible by logging in as a guest and then logging in as admin through the /search/catalog login menu. It seems that if I do that, I'm actually still unable to get to the admin page even after logging in as admin

Looks like this happens in master too. I reproduced it the same way, by logging in as a guest and then trying to log in as an admin (which fails).

> Along with these issues that I'm fairly confident are unrelated to this PR

Yeah, I think as long as these javascript changes build correctly, they probably can't affect the installation of bundles at runtime.

**Comment by bdeining** [comment]
build now

**Pull request merged**
