### PR TITLE
DDF-1545 - do not require https for basic auth header

### PR DESCRIPTION
**Pull request by kcwire**
@pklinef

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/251)

### CODE REVIEW

**Comment by pklinef** [comment]
I think we should add a system property that allows basic auth over http but still do the checks for https by default.  We have that https check code in several other places as well.  When basic auth over http is enabled for testing, there should be sufficient warnings that passwords will be sent in the clear.

@stustison

**Comment by stustison** [comment]
Agree. I do not want to remove this check entirely, because it is an incorrect configuration if someone actually sets up a connection in this way. Allowing a check that is entirely for testing, however, would be fine, assuming that there are sufficient warnings and log messages stating that you're in an insecure state.

**Comment by kcwire** [comment]
This is a regression of the previous behavior. If another service is configured for Basic auth over HTTP, then we should be able to support that.  There are already logs in place that warn an admin that this is a bad idea.

**Comment by jvettraino** [comment]
What about having a couple of methods.  One that forces the connection to be HTTPS in order to send it, and the other one that allows it to be sent using HTTP (or HTTPS).  I believe this was available in an older rev of the class (or maybe that was when it was sending over the cookie - I just remember a similar conversation).
What ever way you go, I think you need to be able to support sending this stuff over both HTTP and HTTPS (with whatever warnings necessary when using HTTP).

**Comment by stustison** [comment]
I'm fine with having some sort of system property to toggle on and off basic auth over HTTP. I just don't want the standard behavior to allow basic auth over HTTP. And if you've configured it to use basic over HTTP, then I want log messages stating that the system is in an insecure state and that you're potentially exposing credentials.

**Comment by kcwire** [comment]
Again, the log messages already exist.

**Comment by jvettraino** [comment]
I think the documentation updates might be made in a different ticket (and system.properties changes), but one thing to note is for the developer documentation it should be clear that the RESTSecurity class should *always* be used, otherwise the system.properties flag to allow/disallow won't matter (thinking custom applications and capabilities that people deploy to DDF).

**Comment by pklinef** [comment]
The log message saying that you are using RestSecurity in an insecure way needs to be in RestSecurity so all clients of that class will properly generate log messages if they use basic auth over HTTP.  It should not be the responsibility of the clients of the class to do that logging.  I agree that the developer/integrator documentation should say to use RestSecurity so that the proper logging and checks are done consistently.  We also need documentation for the system property to explicitly enable insecure mode.

**Comment by pklinef** [comment]
We should also be logging this to the security audit log as well.

**Comment by kcwire** [comment]
@pklinef @stustison @jvettraino - I pushed an update that I believe will satisfy the concerns. Let me know if there are any more questions.

**Comment by pklinef** [comment]
:+1:

**Comment by wmcnalli** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

<sup>**[distribution/ddf-common/src/main/resources/etc/system.properties, line 59 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/251#-K1Fhya4bjcLO90BE7cg)** ([raw file](https://github.com/codice/ddf/blob/29647809d61f274e38c4100cba8b1e718d0760a5/distribution/ddf-common/src/main/resources/etc/system.properties#L59)):</sup>
This doesn't match the key you are checking for in the RestSecurity class. 


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/251)

**Comment by wmcnalli** [comment]
Built and tested locally against clean repo.
org.codice.allowBasicAuthOverHttp=false and pointed to BasicAuth secured WFS endpoint - verified log messages show up and no credentials sent to server

org.codice.allowBasicAuthOverHttp=true and pointed to save endpoint - verified log messages warning of insecure connection and confirmed BasicAuth creds in  request header.

:+1:

**Pull request merged**
