### PR TITLE
[2.13.x] DDF-4171 - Resolved SAML compliance issues when DDF is configured behind a proxy

### PR DESCRIPTION
**Pull request by blen-desta**
#### What does this PR do?
Resolved SAML compliance issues when DDF is configured behind a proxy.

#### Who is reviewing it? 
@brjeter @bakejeyner 

#### Ask 2 committers to review/merge the PR and tag them here.
@coyotesqrl
@stustison 

#### How should this be tested?
- Verify that the [SAML-CTK](https://github.com/codice/saml-conformance) tests pass with out-the-box DDF
- Configure DDF behind a proxy both **with** and **without** an external context and verify that the [SAML-CTK](https://github.com/codice/saml-conformance) tests pass. 
See the testing steps on https://github.com/codice/ddf/pull/3692 for steps on how to configure DDF behind a proxy.

#### What are the relevant tickets?
[DDF-4171](https://codice.atlassian.net/browse/DDF-4171)

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by blen-desta** [comment]
build now

**Comment by blen-desta** [comment]
build now

**Comment by blen-desta** [comment]
build now

**Comment by clockard** [comment]
build now

**Comment by Kjames5269** [comment]
Hero'd ✅

**Comment by blen-desta** [comment]
build now

**Comment by blen-desta** [comment]
build now

**Comment by blen-desta** [comment]
build now

**Comment by clockard** [comment]
build now

**Pull request merged**
