### PR TITLE
[2.9.x] DDF-2368  - Fixed resource usage not counting user's first download

### PR DESCRIPTION
**Pull request by rzwiefel**
#### What does this PR do?
backport
#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).

@coyotesqrl
@jlcsmith

https://github.com/codice/ddf/pull/1141

### CODE REVIEW

**Comment by coyotesqrl** [comment]
Please add a link to the original PR this is associated with.

**Comment by jlcsmith** [comment]
Can you please add a better title @rzwiefel ?

**Comment by coyotesqrl** [comment]
👍

**Comment by jlcsmith** [comment]
👍

**Comment by jlcsmith** [comment]
Built and tested.  LGTM

**Pull request merged**
