### PR TITLE
DDF-1648 - removed circular dependency between platform & kernel

### PR DESCRIPTION
**Pull request by kcwire**
@tbatie @coyotesqrl @pklinef @stustison

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/codice/ddf/pull/543" target="_blank">ReviewNinja

**Comment by coyotesqrl** [comment]
:+1: lgtm

**Comment by tbatie** [comment]
:+1:

**Comment by stustison** [comment]
That looks much better!

**Pull request merged**
