### PR TITLE
DDF-4123 Update doc security-rest-intro with jetty authenticator

### PR DESCRIPTION
**Pull request by KalCramer**
#### What does this PR do?
Update the docs to make sense with jetty authenticator change.

#### Select relevant component teams: 
@codice/docs 
@codice/security 

#### Ask 2 committers to review/merge the PR and tag them here.
@ricklarsen - Documentation
@stustison

#### What are the relevant tickets?
[DDF-4123](https://codice.atlassian.net/browse/DDF-4123)

#### Screenshots

image

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by KalCramer** [comment]
build now

**Comment by KalCramer** [comment]
I'm going to update this a little more to be more accurate of how the response goes back to Jetty. Don't merge just yet.

**Comment by KalCramer** [comment]
build now - updated the doc to show that jetty is what handles the response from our authenticator.

**Comment by coyotesqrl** [comment]
@KalCramer What is the status on this PR?

**Comment by KalCramer** [comment]
@stustison Forgot to get your feedback after updating the doc image. Let me know what you think.

**Pull request merged**
