### PR TITLE
[2.19.x] DDF-6086 G-8302 Clear inspector view when new query is run

### PR DESCRIPTION
**Pull request by zta6**
#### What does this PR do?
Clears the selected result from the inspector view when a new query is run

#### Who is reviewing it? 
@hayleynorton 
@andrewzimmer 
@cassandrabailey293 
@abel-connexta 

#### Ask 2 committers to review/merge the PR and tag them here.
@bdeining
@bdthomson

#### How should this be tested?
Run a query
select a result to display it in the inspector view
run a new query
verify that the selected result is cleared from the inspector view.

#### What are the relevant tickets?
Fixes: #6086 

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by zta6** [comment]
build now

**Comment by millerw8** [comment]
Will this happen when the user initiates a new query?  or when the results from the new query load?  In an environment where the first response may take 10 - 60 seconds, it will make a notable difference in feel

**Comment by hayleynorton** [comment]
Hero successful
Uploaded some records, executed a wildcard search, opened one of the records in the Inspector view, executed a different search and no longer saw the previously selected record in the Inspector view

**Comment by zta6** [comment]
@millerw8 this happens when the user pressed play on the query. Is there a strong preference in either direction? I could see arguments for either.

**Comment by millerw8** [comment]
> @millerw8 this happens when the user pressed play on the query. Is there a strong preference in either direction? I could see arguments for either.

That is the better choice.  I was hoping that was the answer

**Pull request merged**
