### PR TITLE
DDF-2056 added an audit to newly created sessions

### PR DESCRIPTION
**Pull request by stustison**
#### What does this PR do?
adds an audit to new sessions
#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?
@roelens8 @tbatie 
#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@shaundmorris
@stustison
#### How should this be tested?
build is sufficient
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by roelens8** [comment]
👍

**Comment by tbatie** [comment]
:+1:

**Comment by shaundmorris** [comment]
we wouldn't want this to go in the the ddf.log right? 

LGTM 👍

**Comment by stustison** [comment]
No, I don't think so. Audit log is fine for this.

**Pull request merged**
