### PR TITLE
DDF-1582: Disable static analysis tools by default until we're ready to start using them

### PR DESCRIPTION
**Pull request by lessarderic**
Turned off FindBugs and PMD profiles by default.

@figliold: Hero!
@oconnormi: please take a quick look.

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/276)

### CODE REVIEW

**Comment by lessarderic** [comment]
Note: Most changes are related to formatting. The real two changes should be the `true` flags switched to `false` in the PMD and FindBugs profiles.

**Comment by coyotesqrl** [comment]
:+1: *merge it!!!*

**Comment by lessarderic** [comment]
@coyotesqrl: Don't get _too_ excited, let's at least wait until the Bamboo build is successful :-)

**Comment by oconnormi** [comment]
LGTM :+1:

**Pull request merged**
