### PR TITLE
DDF-3933 Add permission for catalog-core-resourcereader used by confluence

### PR DESCRIPTION
**Pull request by clockard**
##### ABBREVIATED REVIEW BETWEEN 2.13.X AND MASTER IS IN EFFECT
Link to 2.13.x PR: https://github.com/codice/ddf/pull/3545
____

#### What does this PR do?
Addes permission needed for downloading resources from confluence
#### Who is reviewing it? 

@coyotesqrl 
@shaundmorris

#### How should this be tested?
CI Build
#### What are the relevant tickets?
**[DDF-3933](https://codice.atlassian.net/browse/)**

### CODE REVIEW

**Comment by clockard** [comment]
build now

**Comment by rzwiefel** [comment]
@clockard Do we just need to resolve the conflicts and then run another build for this PR? Or are there other blockers prohibiting this from moving forward?

**Comment by clockard** [comment]
@rzwiefel should just need a rebase and ci build. I will try to get to that today.

**Comment by clockard** [comment]
build now

**Comment by coyotesqrl** [comment]
@clockard Is this just waiting on successful CI or is there another holdup?

**Comment by vinamartin** [comment]
@clockard Does this need to be rebased and built or is this good to go? It looks like sonarqube is having issues, but other than that it looks good

**Comment by clockard** [comment]
@vinamartin I had forgotten about this pr. Sonarqube shouldn't matter for this change so I will bypass and merge it.

**Pull request merged**
