### PR TITLE
DDF-1523 Remove use of ConfigurationWatcher

### PR DESCRIPTION
**Pull request by clockard**
- Updated ConfigurationManager to pull its values from the system properties
 - Replaced ConfigurationWatchers by injecting SystemBaseUrl and SystemInfo beans

@pklinef @ricklarsen @vinamartin

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/227)

### CODE REVIEW

**Comment by vinamartin** [comment]
:+1:

**Comment by pklinef** [comment]
Please use StrSubstitutor.replaceSystemProperties where values related to the base URL.  Then update the metatype defaults to use the system properties place holders.  For example, the external Solr provider would change its default from `https://localhost:8993/solr` to `${org.codice.ddf.system.protocol}://${org.codice.ddf.system.hostname}:${org.codice.ddf.system.httpsPort}/solr`.

https://commons.apache.org/proper/commons-lang/javadocs/api-2.6/org/apache/commons/lang/text/StrSubstitutor.html#replaceSystemProperties(java.lang.Object)

https://github.com/codice/ddf/search?l=xml&q=localhost&utf8=%E2%9C%93

These changes are not directly related to ConfigurationWatcher so you might want to do these changes in a new PR.

**Comment by stustison** [comment]
Also, to add to what Phil commented. I'd also like to be able to not specify "localhost" in the signature.properties and encryption.properties files. I believe what we can do is create our own Properties object using our PropertiesLoader class that can exchange those system property values for us. Then, anywhere we are using those properties files, will automatically get their values swapped. That should really, truly, bring us to the point where we only have "localhost" defined in a single location.

**Comment by clockard** [comment]
@stustison @pklinef The plan is to do the work you are talking about in https://codice.atlassian.net/browse/DDF-1524.

**Comment by ricklarsen** [comment]
Reviewed 67 of 73 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/227)

**Comment by ricklarsen** [comment]
Hero build successful & all tests passed.

**Pull request merged**
