### PR TITLE
DDF-4709 fixed session memory cleanup

### PR DESCRIPTION
**Pull request by stustison**
#### Ask 2 committers to review/merge the PR and tag them here.

@rzwiefel 
@bdeining
@blen-desta
@brjeter
@coyotesqrl
@garrettfreibott
@pklinef
@stustison
@troymohl

#### What are the relevant tickets?
For Jira:
[](https://codice.atlassian.net/browse/)

For GH Issues:
Fixes: #____

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by stustison** [comment]
build now

**Comment by brjeter** [comment]
I recommend addressing the synchronization concerns that @paouelle raised here: https://github.com/codice/ddf/pull/4741#pullrequestreview-229851912

**Comment by stustison** [comment]
I went ahead and fixed it, but to be clear, this should not be an issue in practice as the contexts are added to the data store as jetty is starting up, before any users are even able to access the server.

**Comment by stustison** [comment]
build now

**Comment by paouelle** [comment]
synchronization is not just to make sure things don't happen at the same time. It is to ensure caches are properly flushed and reloaded. If multiple threads can access/modify structures whether at the same time or not, you need to synchronize one way or another.

**Comment by stustison** [comment]
These structures are only read from, not modified by multiple threads, regardless, it is fixed :)

**Pull request merged**
