### PR TITLE
DDF-5854 Remove FTP Endpoint

### PR DESCRIPTION
**Pull request by shaundmorris**
#### What does this PR do?
Removes the FTP endpoint

#### Who is reviewing it? 

@peterhuffer 
@beyelerb 

#### Select relevant component teams: 
@codice/build 
@codice/continuous-integration 
@codice/io 
@codice/security - changed threat models

#### Ask 2 committers to review/merge the PR and tag them here.
@ricklarsen 

#### What are the relevant tickets?
Fixes: #5854 

#### Checklist:
- [X] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [X] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

---
This change is [Reviewable](https://reviewable.io/reviews/codice/ddf/5864)

### CODE REVIEW

**Comment by shaundmorris** [comment]
build now

**Comment by shaundmorris** [comment]
build now

**Comment by shaundmorris** [comment]
build now

**Comment by TonyMorrison** [comment]
i started up an instance of DDF locally from this branch
Ran "netstat -an", port 8021, no listening on port 8021

**Comment by shaundmorris** [comment]
> i started up an instance of DDF locally from this branch
Ran "netstat -an", port 8021, no listening on port 8021

@bakejeyner is this sufficient for a hero review? I also verified the ftp port configuration was no longer there when I started up my instance locally.

**Comment by bakejeyner** [comment]
From a security perspective: if the port is no longer listening then you are good.

**Comment by bakejeyner** [comment]
I give it the green light

**Comment by shaundmorris** [comment]
build now

**Comment by shaundmorris** [comment]
build now

Build error cloning repo

**Comment by shaundmorris** [comment]
build now 

Error in the dependency-check phase

**Pull request merged**
