### PR TITLE
DDF-3506 Replaced additional missing tokens in Jenkinsfile

### PR DESCRIPTION
**Pull request by mcalcote**
#### What does this PR do?
Pipelines build was failing with an unexpected token in the Jenkinsfile. This PR corrects the issue 🙏.

#### Who is reviewing it? 
@oconnormi @vinamartin @blen-desta @LinkMJB @emanns95 @mackncheesiest @clockard @rzwiefel 

#### How should this be tested? (List steps with links to updated documentation)
Wait to merge until the file can be evaluated in Jenkins.

### CODE REVIEW

**Comment by bdeining** [comment]
build now

**Comment by mcalcote** [comment]
`Jenkinsfile successfully validated.`

**Comment by mcalcote** [comment]
`Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6.CODICE:yarn (yarn install) on project catalog-ui-search: Failed to run task`
build now

**Comment by mcalcote** [comment]
`Failed to execute goal on project gitsetup: Could not resolve dependencies for project ddf:gitsetup:pom:2.11.5-SNAPSHOT: Could not transfer artifact com.jcraft:jsch:jar:0.1.46 from/to office (http://nexus.phx.connexta.com:8081/nexus/content/groups/public/): Connect to nexus.phx.connexta.com:8081 [nexus.phx.connexta.com/10.101.1.253] failed: Connection refused `

Not that this PR needs a build since the Jenkinsfile isn't evaluated under our current setup, but these build failures are still confounding.

**Comment by clockard** [comment]
CI build not needed as PR builds don't run the jenkins file right now.

**Pull request merged**
