### PR TITLE
[2.13.x]DDF-4087 Suppressing jetty CVEs that don't apply to DDF

### PR DESCRIPTION
**Pull request by brjeter**
#### What does this PR do?
Backport for https://github.com/codice/ddf/pull/3653
#### Who is reviewing it? 
@Kjames5269 @blen-desta 
#### Ask 2 committers to review/merge the PR and tag them here.
@clockard  
@stustison 
#### What are the relevant tickets?
[](https://codice.atlassian.net/browse/)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by brjeter** [comment]
build now

**Comment by brjeter** [comment]
build now (flaky yarn installation error)

**Comment by brjeter** [comment]
build now (failed on unrelated Surefire forked VM issue)

**Comment by brjeter** [comment]
build now (unrelated failure)

**Comment by vinamartin** [comment]
This commit is strictly an OWASP suppression but CI is failing for other reasons. I'm overriding this.

**Pull request merged**
