### PR TITLE
DDF-1198 Removed owasp profile from distribution pom.xml

### PR DESCRIPTION
**Pull request by jckilmer**
The owasp profile is now inherited from ddf-parent.

@coyotesqrl @rzwiefel @roelens8 @pklinef @tbatieConnexta

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/73)

### CODE REVIEW

**Comment by coyotesqrl** [comment]
:+1:

**Comment by rzwiefel** [comment]
:+1:

**Comment by coyotesqrl** [comment]
Clean repo build worked. Then went into the distribution module and ran with the `owasp` profile to ensure it would pick up the plugin settings from ddf-parent. :+1:

**Comment by roelens8** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/73)

**Comment by tbatieConnexta** [comment]
:+1:

**Pull request merged**
