### PR TITLE
DDF-04746 Automated improvements to js files

### PR DESCRIPTION
**Pull request by rymach**
#### What does this PR do?
Update: I cleaned up the commits - the plan is to NOT squash if/when this is merged so we can roll back individual commits easily 

it may be easier to review one commit at a time

Automated improvements to js files
- add missing license headers (see: https://github.com/connexta/ace/pull/5)
- run `rm-requires.js` `Conservatively converts var to const or let.`
- run `no-vars.js` `Removes any requires where the imported value is not referenced. Additionally if any module is required more than once the two requires will be merged.`

see https://github.com/cpojer/js-codemod/

#### Who is reviewing it? 
@andrewkfiedler 
@djblue 
#### Select relevant component teams: 
@codice/ui 

#### Ask 2 committers to review/merge the PR and tag them here.

@andrewkfiedler
@AzGoalie

#### How should this be tested?

ui tests, smoke test, integration tests, use the ui 
#### What are the relevant tickets?
For Jira:
[](https://codice.atlassian.net/browse/)

For GH Issues:
Fixes: #4746

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by mojogitoverhere** [comment]
Should we make some of these into yarn commands so they can be rerun in the future?

**Comment by mojogitoverhere** [comment]
build now

**Comment by rymach** [comment]
> Should we make some of these into yarn commands so they can be rerun in the future?

this is fixing legacy code - no new code should have these problems

**Comment by rymach** [comment]
build now

**Comment by rymach** [comment]
build now

**Comment by rymach** [comment]
hopefully smaller PRs will be easier to review https://github.com/codice/ddf/pull/4806

**Pull request closed without merging**
