### PR TITLE
DDF 1373

### PR DESCRIPTION
**Pull request by coyotesqrl**
Merges completed; pom files/versions updated and standardized; clean build & test.

As soon as I've finished submitting this PR, I'm going to attempt a release:prepare. There may be followup fixes from that, but I'd rather they go to separate tickets/PRs.

There are obviously a LOT of files to look at here, but if everyone could clone and take a quick look at

+ the catalog and platform root poms
+ the new parent/reactor pom
+ the poms in the libs module
+ the overall directory structure

that would be appreciated. I'm hoping to get approvals such that this can be merged by no later than COB on Tuesday (preferably much earlier in the day).

@pklinef 
@stustison 
@brendan-hofmann 
@tbatie  
@jckilmer
@rzwiefel
@roelens8

Tracy, I'd like you to be the hero on this.

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/87)

### CODE REVIEW

**Comment by coyotesqrl** [comment]
Unsurprisingly, I missed a couple of version updates. I'll fix, test, and push shortly.

**Comment by coyotesqrl** [comment]
Found the stale references and squashed them. Outside of any issues the reviewers may find, I believe this PR is in a sufficient state now. Property cleanup will be addressed in a subsequent ticket.

**Comment by jckilmer** [comment]
There are still three references to ddf-parent inside the scm tags in the parent/reactor pom.

**Comment by brendan-hofmann** [comment]
:+1:

**Comment by coyotesqrl** [comment]
Nice catch, Jason. I'll get those in a minute. I just pushed (squashed with the previous commit) a single change to another pom referencing an old library version as well.

**Comment by coyotesqrl** [comment]
There are, naturally, still version issues in the pom files. Running another build/test now after which I'll try the release plugin to help find the issues. I took a slightly more aggressive pass through this time, removing some of the now duplicate version properties.

**Comment by coyotesqrl** [comment]
I believe all the outstanding version issues have been addressed with the last commit. Have at it.

**Comment by tbatie** [comment]
:+1: Clean install, built and tested functionality. Everything looks good.

**Comment by roelens8** [comment]
Reviewed 3041 of 3041 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/87)

**Comment by rzwiefel** [comment]
Looks good as far as I can tell. Also built successfully! :+1: 

We'll just have to keep an eye out for anything that could have flown under the radar (like getting turned off)

**Comment by roelens8** [comment]
:+1:

**Comment by jckilmer** [comment]
Built successfully, for good measure I started up the ddf, ran through the installer, ingested a couple records, and poked around the search and admin UIs. All looks good to me.

**Pull request merged**
