### PR TITLE
DDF-2079 - upgrade to Karaf 4.0.5

### PR DESCRIPTION
**Pull request by kcwire**
#### What does this PR do?
Upgrades DDF to 2.9.0 and pax web 4.2.6
#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?
@coyotesqrl @peterhuffer 
#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@kcwire
@shaundmorris 
#### What are the relevant tickets?
DDF-2079
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by shaundmorris** [comment]
We can also get rid of property: https://github.com/codice/ddf/blob/master/distribution/ddf/src/main/filtered-resources/etc/org.apache.karaf.features.cfg#L24 based on this ticket https://issues.apache.org/jira/browse/KARAF-4258

**Comment by bcwaters** [comment]
It looks like the old Karaf version pops up somewhere too.
-AbstractIntegrationTest has KARAF_VERSION = "4.0.4" hardcoded as a final variable.

**Comment by kcwire** [comment]
Closing PR. There are no critical changes in 4.0.5 that are driving this upgrade. Recommend waiting for DDF-2132 & Karaf 4.1.0.

**Comment by lessarderic** [comment]
@kcwire, Karaf 4.0.5 did contain a bunch of dependency upgrades (https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12311140&version=12334629) which may include some security related changes that we want to pick up. Was this PR postpone because of the lack of major new features or the effort required to move from 4.0.4 to 4.0.5?

Since Karaf is our container and pulls in a lot of dependencies, should we try to keep up with _all_ Karaf releases, even bug fix versions, to make sure we stay on top of all potential security issues and make future minor/major upgrades easier?

**Pull request closed without merging**
