### PR TITLE
DDF-1459 Modified temporal only queries in WFS to translate During to…

### PR DESCRIPTION
**Pull request by bdeining**
-hero @kcwire 
@jrnorth 
@emanns95
@kguerriero
@jlcsmith 
@millerw8 
@beyelerb
@wmcnalli 
@shane-voisard 
@EIrwin

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/143)

### CODE REVIEW

**Comment by jrnorth** [comment]
Unit tests?

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsFilterDelegate.java, line 493 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/143#-Jy3dYUkB6lIIdjB-e3u)** ([raw file](https://github.com/codice/ddf/blob/d11efb21dbd8243fe239ff89e798286a1d8075bb/catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsFilterDelegate.java#L493)):</sup>
Perhaps more descriptive variable names than "xp" and "obj"?

---

<sup>**[catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsFilterDelegate.java, line 504 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/143#-Jy3dkkUzIu29Co-sDnl)** ([raw file](https://github.com/codice/ddf/blob/d11efb21dbd8243fe239ff89e798286a1d8075bb/catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/main/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/WfsFilterDelegate.java#L504)):</sup>
Don't need to check for `filterType.isSetTemporalOps()` here because the preceding case will be run if it's false.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/143)

**Comment by kcwire** [comment]
Reviewed 2 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/143)

**Comment by jrnorth** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/TestWfsFilterDelegate.java, line 1769 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/143#-JyEBSYPA6ezFtbCk9-H)** ([raw file](https://github.com/codice/ddf/blob/359d8d98bf4ffffecbfd1608b485f5be2d779062/catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/TestWfsFilterDelegate.java#L1769)):</sup>
timePeriodTpe

---

<sup>**[catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/TestWfsFilterDelegate.java, line 1835 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/143#-JyECKTffHw1saqvs7Bk)** ([raw file](https://github.com/codice/ddf/blob/359d8d98bf4ffffecbfd1608b485f5be2d779062/catalog/spatial/wfs/2.0.0/spatial-wfs-v2_0_0-source/src/test/java/org/codice/ddf/spatial/ogc/wfs/v2_0_0/catalog/source/TestWfsFilterDelegate.java#L1835)):</sup>
timePeriodTpe

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/143)

**Comment by wmcnalli** [comment]
:+1: 

---

Reviewed 2 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/143)

**Comment by beyelerb** [comment]
Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/143)

**Comment by jrnorth** [comment]
:+1:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/143)

**Comment by kcwire** [comment]
PR Built successfully and tested both relative & absolute temporal queries. LGTM.

**Pull request merged**
