### PR TITLE
DDF-1503 Changes move to copy for doc inclusion

### PR DESCRIPTION
**Pull request by andrewkfiedler**
- Using move causes issues during clean runs of release:prepare

https://codice.atlassian.net/browse/DDF-1503

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/188)

### CODE REVIEW

**Comment by andrewkfiedler** [comment]
@shaundmorris

**Comment by shaundmorris** [comment]
:+1: I did a build with a clean repo to verify, but I expected that to work as well. Thanks @andrewkfiedler! I remember running into this but forgot to fix it in the master branch :-(

**Comment by ricklarsen** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/188)

**Comment by ricklarsen** [comment]
:+1:

**Pull request merged**
