### PR TITLE
[2.25.x] DDF-6269 fixed branding registry by removing SortedServiceList usage and doing direct OSGi calls

### PR DESCRIPTION
**Pull request by stustison**
#### Who is reviewing it? 

@bakejeyner 

#### Select relevant component teams: 
@codice/security 

#### Ask 2 committers to review/merge the PR and tag them here.
@blen-desta
@emmberk
@garrettfreibott
@stustison

#### How should this be tested?
See https://github.com/codice/ddf/issues/6269

#### What are the relevant tickets?
#6269

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [x] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by stustison** [comment]
build now

**Comment by emmberk** [comment]
The hero was successful
image
image

**Comment by emmberk** [comment]
build now

**Comment by emmberk** [comment]
```
[WARNING] Rule violated for bundle branding-registry-impl: instructions covered ratio is 0.59, but expected minimum is 0.73
[WARNING] Rule violated for bundle branding-registry-impl: branches covered ratio is 0.16, but expected minimum is 0.73
[WARNING] Rule violated for bundle branding-registry-impl: complexity covered ratio is 0.50, but expected minimum is 0.73
```

**Comment by stustison** [comment]
build now

**Pull request merged**
