### PR TITLE
DDF-04909 entrySet() instead of keySet() when key and value are needed

### PR DESCRIPTION
**Pull request by dvmarcilio**
#### What does this PR do?
This PR aims to fix an issue from SonarQube rule ["entrySet()" should be iterated when both the key and value are needed](https://rules.sonarsource.com/java/RSPEC-2864)

"Iterating on a Map using `entrySet()`, when both key and value are needed, is more performant."

#### Ask 2 committers to review/merge the PR and tag them here.
Sorry, I don't know who I should tag.

#### Any background context you want to provide?
I asked whether PRs tackling SonarQube issues were welcome on [google groups](https://groups.google.com/forum/?fromgroups#!topic/ddf-developers/Ovdj2lohGow).
#### What are the relevant tickets?
For Jira:
[](https://codice.atlassian.net/browse/)

For GH Issues:
Fixes: #4909 (partially)

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by rzwiefel** [comment]
build now

**Comment by shaundmorris** [comment]
build now

**Comment by dvmarcilio** [comment]
My bad. Build was failing due to checkstyle error. Should be passing now.

**Comment by shaundmorris** [comment]
build now

**Pull request merged**
