### PR TITLE
DDF-1570 Latitude/longitude ordering should be handled more consisten…

### PR DESCRIPTION
**Pull request by dcruver**
…tly for CSW records

The CSW endpoint assumes incoming bounding box values are in lon/lat order and reverses
them before ingesting. The endpoint should use lat/lon order exclusively, only changing
the order when the data comes from a federated system which has been configured for lon/lat.

This change fixes a bug in the BoundingBoxReader class which was reversing the axis order
when it shouldn't be and not reversing it when it should.  Also updated tests.

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/262)

### CODE REVIEW

**Comment by dcruver** [comment]
@bdeining (Hero)
@shane-voisard 
@kcwire

**Comment by wmcnalli** [comment]
Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/262)

**Comment by wmcnalli** [comment]
Check those itest failures.  Looks like it may be related to your changes.

**Comment by shane-voisard** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

<sup>**[catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/BoundingBoxReader.java, line 60 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/262#-K10Nps3tvGF7tmQ9-co)** ([raw file](https://github.com/codice/ddf/blob/5f1fc234206bbe6affec7efe56d46f1c9541f0d3/catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/BoundingBoxReader.java#L60)):</sup>
There should be a test case for when `getWkt()` returns null.


---

<sup>**[catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/BoundingBoxReader.java, line 99 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/262#-K10PyTtpIt87mbSlI94)** ([raw file](https://github.com/codice/ddf/blob/5f1fc234206bbe6affec7efe56d46f1c9541f0d3/catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/BoundingBoxReader.java#L99)):</sup>
There should be test cases for when this condition is false and`getWkt()` returns null.


---

<sup>**[catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/BoundingBoxReader.java, line 147 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/262#-K10L9K2aoi7Z1x9JVoJ)** ([raw file](https://github.com/codice/ddf/blob/5f1fc234206bbe6affec7efe56d46f1c9541f0d3/catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/BoundingBoxReader.java#L147)):</sup>
per http://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html#CHDFCBAD , "(javadoc style) Documentation comments are recognized only when placed immediately before class, interface, constructor, method, or field declarations. Documentation comments placed in the body of a method are ignored. " Do you expect these comments to be in javadoc?


---

<sup>**[catalog/spatial/csw/spatial-csw-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/BoundingBoxReaderTest.java, line 76 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/262#-K10TIul9h1fm0H_od4J)** ([raw file](https://github.com/codice/ddf/blob/5f1fc234206bbe6affec7efe56d46f1c9541f0d3/catalog/spatial/csw/spatial-csw-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/BoundingBoxReaderTest.java#L76)):</sup>
The `HierarchicalStreamReader` dependency should be mocked in these tests,  and then we could eliminate parsing the xml document from the tests.


---

<sup>**[catalog/spatial/csw/spatial-csw-source/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/source/reader/TestGetRecordsMessageBodyReader.java, line 172 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/262#-K10Va1XV4CtLNo6epd_)** ([raw file](https://github.com/codice/ddf/blob/5f1fc234206bbe6affec7efe56d46f1c9541f0d3/catalog/spatial/csw/spatial-csw-source/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/source/reader/TestGetRecordsMessageBodyReader.java#L172)):</sup>
Should the order of the comma separated values be changing?


---

<sup>**[catalog/spatial/csw/spatial-csw-transformer/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/TestGetRecordsResponseConverter.java, line 219 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/262#-K10VkRknSVTuri-jqBw)** ([raw file](https://github.com/codice/ddf/blob/5f1fc234206bbe6affec7efe56d46f1c9541f0d3/catalog/spatial/csw/spatial-csw-transformer/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/TestGetRecordsResponseConverter.java#L219)):</sup>
Should the order of the comma separated values be changing?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/262)

**Comment by bdeining** [comment]
Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: 5 of 6 files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/262)

**Comment by bdeining** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/262)

**Comment by dcruver** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

<sup>**[catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/BoundingBoxReader.java, line 60 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/262#-K10Nps3tvGF7tmQ9-co)** ([raw file](https://github.com/codice/ddf/blob/5f1fc234206bbe6affec7efe56d46f1c9541f0d3/catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/BoundingBoxReader.java#L60)):</sup>
I think the proper behavior would be to throw an exception in the case where this returns null.  If this is returning null, then the BoundingBoxReader has been invoked on something that isn't a BoundingBox.  In this case, we're using null as a special value to represent that situation.  Do you agree?


---

<sup>**[catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/BoundingBoxReader.java, line 99 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/262#-K10PyTtpIt87mbSlI94)** ([raw file](https://github.com/codice/ddf/blob/5f1fc234206bbe6affec7efe56d46f1c9541f0d3/catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/BoundingBoxReader.java#L99)):</sup>
(Also should be an exception instead of null)


---

<sup>**[catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/BoundingBoxReader.java, line 147 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/262#-K10L9K2aoi7Z1x9JVoJ)** ([raw file](https://github.com/codice/ddf/blob/5f1fc234206bbe6affec7efe56d46f1c9541f0d3/catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/BoundingBoxReader.java#L147)):</sup>
This wasn't part of my change, so I can't really know what the original author's intent was.  The text of this comment wouldn't make sense in the context of API documentation, so I assume he intended it as an inline comment.  The use of the second * doesn't affect its applicability to that.


---

<sup>**[catalog/spatial/csw/spatial-csw-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/BoundingBoxReaderTest.java, line 76 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/262#-K10TIul9h1fm0H_od4J)** ([raw file](https://github.com/codice/ddf/blob/5f1fc234206bbe6affec7efe56d46f1c9541f0d3/catalog/spatial/csw/spatial-csw-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/BoundingBoxReaderTest.java#L76)):</sup>
I think this is pretty far outside the scope of this story.  We should probably create a story to refactor the tests and change the BoundingBoxReader to throw exceptions instead of returning null.


---

<sup>**[catalog/spatial/csw/spatial-csw-source/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/source/reader/TestGetRecordsMessageBodyReader.java, line 172 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/262#-K10Va1XV4CtLNo6epd_)** ([raw file](https://github.com/codice/ddf/blob/5f1fc234206bbe6affec7efe56d46f1c9541f0d3/catalog/spatial/csw/spatial-csw-source/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/source/reader/TestGetRecordsMessageBodyReader.java#L172)):</sup>
Yes, that's the change from LON/LAT order to LAT/LON.


---

<sup>**[catalog/spatial/csw/spatial-csw-transformer/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/TestGetRecordsResponseConverter.java, line 219 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/262#-K10VkRknSVTuri-jqBw)** ([raw file](https://github.com/codice/ddf/blob/5f1fc234206bbe6affec7efe56d46f1c9541f0d3/catalog/spatial/csw/spatial-csw-transformer/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/TestGetRecordsResponseConverter.java#L219)):</sup>
Yes, that's the change from LON/LAT order to LAT/LON.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/262)

**Comment by bdeining** [comment]
Review status: 5 of 6 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

<sup>**[catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/BoundingBoxReader.java, line 60 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/262#-K10Nps3tvGF7tmQ9-co)** ([raw file](https://github.com/codice/ddf/blob/5f1fc234206bbe6affec7efe56d46f1c9541f0d3/catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/BoundingBoxReader.java#L60)):</sup>
I think that a `CswException` (as opposed to null) would be more ideal in this situation.  This shouldn't be outside of the scope of the ticket to change and test.


---

<sup>**[catalog/spatial/csw/spatial-csw-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/BoundingBoxReaderTest.java, line 74 \[r4\]](https://reviewable.io:443/reviews/codice/ddf/262#-K11Cgr3Qz6PXLcxQNuz)** ([raw file](https://github.com/codice/ddf/blob/e65f556f7189c55a8a09b0a5b1808c0ce20f9d23/catalog/spatial/csw/spatial-csw-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/BoundingBoxReaderTest.java#L74)):</sup>
It might be good to move some of the setup into an @Before method.   Also, the classes in this package should follow the TestXXXX.java format.  


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/262)

**Comment by shane-voisard** [comment]
Review status: 5 of 6 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

<sup>**[catalog/spatial/csw/spatial-csw-source/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/source/reader/TestGetRecordsMessageBodyReader.java, line 172 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/262#-K10Va1XV4CtLNo6epd_)** ([raw file](https://github.com/codice/ddf/blob/5f1fc234206bbe6affec7efe56d46f1c9541f0d3/catalog/spatial/csw/spatial-csw-source/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/source/reader/TestGetRecordsMessageBodyReader.java#L172)):</sup>
Sorry, I'm not asking about the order of a single pair, but the order among the pairs. For example, "LON1 LAT1, LON2 LAT2, LON3 LAT3" changed to "LAT1 LON1, LAT3 LON3, LAT2 LON2" where pair 2 is after pair 3.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/262)

**Comment by dcruver** [comment]
Review status: 4 of 29 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

<sup>**[catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/BoundingBoxReader.java, line 60 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/262#-K10Nps3tvGF7tmQ9-co)** ([raw file](https://github.com/codice/ddf/blob/5f1fc234206bbe6affec7efe56d46f1c9541f0d3/catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/BoundingBoxReader.java#L60)):</sup>
I think some derivative of ParseException is better here since it's a problem in parsing and not in Csw logic. 


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/262)

**Comment by dcruver** [comment]
Review status: 4 of 29 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

<sup>**[catalog/spatial/csw/spatial-csw-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/TestBoundingBoxReader.java, line 74 \[r4\]](https://reviewable.io:443/reviews/codice/ddf/262#-K11Cgr3Qz6PXLcxQNuz)** ([raw file](https://github.com/codice/ddf/blob/e65f556f7189c55a8a09b0a5b1808c0ce20f9d23/catalog/spatial/csw/spatial-csw-common/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/common/TestBoundingBoxReader.java#L74)):</sup>
ok, I moved the 2 lines that don't vary between the tests into a setup() method and renamed the classes.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/262)

**Comment by shane-voisard** [comment]
There are alot of new files in the latest revision.  Are these really related to the lat/lon ticket?


---

Review status: 4 of 29 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/262)

**Comment by bdeining** [comment]
The branch just needs to be rebased, these revisions are from pulling the latest commits from codice ddf.


---

Review status: 4 of 29 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/262)

**Comment by bdeining** [comment]
Review status: 4 of 29 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/BoundingBoxReader.java, line 60 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/262#-K10Nps3tvGF7tmQ9-co)** ([raw file](https://github.com/codice/ddf/blob/5f1fc234206bbe6affec7efe56d46f1c9541f0d3/catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/BoundingBoxReader.java#L60)):</sup>
:thumbsup: 


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/262)

**Comment by bdeining** [comment]
Reviewed 27 of 27 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/262)

**Comment by bdeining** [comment]
Review status: 1 of 27 files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

<sup>**[catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/CswMarshallHelper.java, line 58 \[r6\]](https://reviewable.io:443/reviews/codice/ddf/262#-K1Zj-QPXMjjg9owiO_9)** ([raw file](https://github.com/codice/ddf/blob/544e112aed8ad234b339e93e64d76cf2d5617580/catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/CswMarshallHelper.java#L58)):</sup>
Explicit access modifier might be better here.


---

<sup>**[catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/CswRecordConverter.java, line 256 \[r6\]](https://reviewable.io:443/reviews/codice/ddf/262#-K1ZjnzCoFTl2uihg2F0)** ([raw file](https://github.com/codice/ddf/blob/544e112aed8ad234b339e93e64d76cf2d5617580/catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/CswRecordConverter.java#L256)):</sup>
Missing param descriptions.


---

<sup>**[catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/CswUnmarshallHelper.java, line 58 \[r6\]](https://reviewable.io:443/reviews/codice/ddf/262#-K1Zk5aM3hltcr_P0plQ)** ([raw file](https://github.com/codice/ddf/blob/544e112aed8ad234b339e93e64d76cf2d5617580/catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/CswUnmarshallHelper.java#L58)):</sup>
Explicit access modifier may better.


---

<sup>**[catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/CswUnmarshallHelper.java, line 332 \[r6\]](https://reviewable.io:443/reviews/codice/ddf/262#-K1ZkF4wrevhAwHQ4zRR)** ([raw file](https://github.com/codice/ddf/blob/544e112aed8ad234b339e93e64d76cf2d5617580/catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/CswUnmarshallHelper.java#L332)):</sup>
Missing param descriptions.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/262)

**Comment by bdeining** [comment]
Reviewed 26 of 27 files at r6.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/262)

**Comment by dcruver** [comment]
Review status: 25 of 27 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

<sup>**[catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/CswMarshallHelper.java, line 58 \[r6\]](https://reviewable.io:443/reviews/codice/ddf/262#-K1Zj-QPXMjjg9owiO_9)** ([raw file](https://github.com/codice/ddf/blob/544e112aed8ad234b339e93e64d76cf2d5617580/catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/CswMarshallHelper.java#L58)):</sup>
I think package-private is the right level.  If I make it private then I can't cover the methods with unit tests, which would force us to lower our coverage requirements.  It isn't designed to be extended, so protected is out (and default is more restrictive than protected anyway).  The Helpers aren't intended to be used outside the package, so public isn't appropriate either.


---

<sup>**[catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/CswRecordConverter.java, line 256 \[r6\]](https://reviewable.io:443/reviews/codice/ddf/262#-K1ZjnzCoFTl2uihg2F0)** ([raw file](https://github.com/codice/ddf/blob/544e112aed8ad234b339e93e64d76cf2d5617580/catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/CswRecordConverter.java#L256)):</sup>
added these.


---

<sup>**[catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/CswUnmarshallHelper.java, line 58 \[r6\]](https://reviewable.io:443/reviews/codice/ddf/262#-K1Zk5aM3hltcr_P0plQ)** ([raw file](https://github.com/codice/ddf/blob/544e112aed8ad234b339e93e64d76cf2d5617580/catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/CswUnmarshallHelper.java#L58)):</sup>
See previous reply.


---

<sup>**[catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/CswUnmarshallHelper.java, line 332 \[r6\]](https://reviewable.io:443/reviews/codice/ddf/262#-K1ZkF4wrevhAwHQ4zRR)** ([raw file](https://github.com/codice/ddf/blob/544e112aed8ad234b339e93e64d76cf2d5617580/catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/CswUnmarshallHelper.java#L332)):</sup>
added these.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/262)

**Comment by bdeining** [comment]
Reviewed 2 of 2 files at r7.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/262)

**Comment by bdeining** [comment]
Reviewed 2 of 2 files at r8, 1 of 1 files at r9, 2 of 2 files at r10.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/262)

**Comment by bdeining** [comment]
Reviewed 3 of 4 files at r11.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/262)

**Comment by bdeining** [comment]
PR builds successfully.  Tested the changes by using the Csw Endpoint as a Csw Federated source and verified that an ingested metacard is in the right Lat / Lon location on the Search UI based on the Coordinate Order drop down in Csw Federated Source.  


---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/262)

**Pull request merged**
