### PR TITLE
DDF-1850 updated the ingest command to batch and multithread at the same time

### PR DESCRIPTION
**Pull request by stustison**
@pklinef @harrison-tarr @ahoffer

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/codice/ddf/pull/523" target="_blank">ReviewNinja

**Comment by stustison** [comment]
This is just a quick PR to fix this command. I still think we should go in and rewrite this thing.

**Comment by brendan-hofmann** [comment]
I thought the catalog framework did batching and multithreading. Is there no way to just rely on that?

**Comment by stustison** [comment]
The catalog framework does neither.

**Comment by pklinef** [comment]
The `CachingFederationStrategy` uses the `CacheBulkProcessor` to help reduce the number of requests made to the metacard cache to reduce CPU load.  A similar approach might help here too.

**Comment by brendan-hofmann** [comment]
Yeah, I think I was somewhat mistaken. Interestingly, CatalogFrameworkImpl *does* have an [ExecutorService](https://github.com/codice/ddf/blob/ac668880fc008a39709614b54ac3ff6123e280cb/catalog/core/catalog-core-standardframework/src/main/java/ddf/catalog/impl/CatalogFrameworkImpl.java#L245-L245), but it doesn't appear to be actually used.

**Pull request merged**
