### PR TITLE
DDF-3778 Update Map toolbar buttons to be consistent with other buttons across the ui

### PR DESCRIPTION
**Pull request by alexaabrd**
#### What does this PR do?
Updated Cesium toolbar buttons to be consistent with other buttons across the ui
#### Who is reviewing it? 
@lcrosenbu 
@idperez 
@Lambeaux 
@adimka 
@djblue 
@Schachte 
#### Select relevant component teams: 
https://github.com/orgs/codice/teams/ui
#### Choose 2 committers to review/merge the PR. 
@andrewkfiedler
@bdeining
#### What are the relevant tickets?
[DDF-3778](https://codice.atlassian.net/browse/DDF-3778)
#### Screenshots
*Old:*
image
image

*New:*
image
image

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by bdeining** [comment]
@alexaabrd Is the toggle still visible in one case and not the other?  It may have been an oversight to not hide that slider in all cases

**Comment by alexaabrd** [comment]
@bdeining Yeah the toggle is visible only when the clustering is on. For this I was mimicking the _filter_ and _sort_ buttons, for which the toggle icon seems to be more of an indicator being like 'hey, this is on' rather than an actual toggle button. 

I could definitely update all of these buttons to always shows the toggle icon.

For reference:
_Filter_ and _sort_ off:
image

_Filter_ and _sort_ on:
image

**Comment by alexaabrd** [comment]
@bdeining I messed with having the toggle always showing and it didn't look right, so after talking with Andrew it was clarified that it is supposed to be an indicator rather than an actual toggle

**Comment by alexaabrd** [comment]
build now

**Comment by bdeining** [comment]
I don't think it's clear to the user that it's supposed to be an indicator; since it looks like a slider, it may be perceived as a bug

**Pull request merged**
