### PR TITLE
DDF-2511 removed blueprint hack and updated karaf to 4.0.7

### PR DESCRIPTION
**Pull request by stustison**
#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@kcwire 
@millerw8
@pklinef
@stustison
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by kcwire** [comment]
Assuming you've verified offline install locally. 👍

**Comment by pklinef** [comment]
Pax Web was upgrade to 4.3.0 but we still have the version set to 4.2.7.

https://issues.apache.org/jira/browse/KARAF-4696

**Comment by stustison** [comment]
Yes I tested it offline and it worked and I removed the pax web version we were defining because it was unused.

**Comment by millerw8** [comment]
+1

**Pull request merged**
