### PR TITLE
DDF-3684 Resolved NPE during logout when using POST binding

### PR DESCRIPTION
**Pull request by idperez**
#### What does this PR do?
Resolves a NPE exception that occurred during a logout using POST binding
#### Who is reviewing it? 
@brjeter @blen-desta @bakejeyner @SmithJosh 
#### Select relevant component teams: 
https://github.com/orgs/codice/teams
#### Choose 2 committers to review/merge the PR. 
@clockard
@coyotesqrl 
#### How should this be tested? (List steps with links to updated documentation)
 * Paste [idp metadata](https://github.com/codice/ddf/files/1827168/idp.txt) in: AdminConsole -> Security -> Configuration -> IdP Client
 * Paste [sp metadata](https://github.com/codice/ddf/files/1827167/sp.txt) in: AdminConsole -> Security -> Configuration -> IdP Server

Verify proper logout and login

#### What are the relevant tickets?
[DDF-3684](https://codice.atlassian.net/browse/DDF-3684)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by bakejeyner** [comment]
Hero ✔️

**Comment by idperez** [comment]
build now

**Comment by coyotesqrl** [comment]
build now

**Comment by idperez** [comment]
build now

**Pull request merged**
