### PR TITLE
DDF-1641: Update .cfg to .config in itests

### PR DESCRIPTION
**Pull request by garrettfreibott**
- Removed ddf.platform.config.cfg files as they are no longer used
 - Updated .cfg files in itest to .config

@andrewkfiedler hero

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/324)

### CODE REVIEW

**Comment by andrewkfiedler** [comment]
The integration tests are hanging with the current state of this PR.  The lines 404:406 which you deleted appear to be the culprit.

**Comment by lessarderic** [comment]
:+1: 


---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/AbstractIntegrationTest.java, line 415 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/324#-K2njskaXeSikRdedl-1)** ([raw file](https://github.com/codice/ddf/blob/905e0ec5d7231603c7de7b4e7a081b0c75063b55/distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/AbstractIntegrationTest.java#L415)):</sup>
Small favor :-) Can you see if it's worth using `installStartupFile()` instead of calling `replaceConfigutationFile()` directly? If so, can you update `installStartupFile()` to not create a temp file? If you feel it's not worth it, maybe we should just delete `installStartupFile()`.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/324)

**Comment by garrettfreibott** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/AbstractIntegrationTest.java, line 415 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/324#-K2njskaXeSikRdedl-1)** ([raw file](https://github.com/codice/ddf/blob/905e0ec5d7231603c7de7b4e7a081b0c75063b55/distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/AbstractIntegrationTest.java#L415)):</sup>
I updated it to use installStartupFile(). I had to modify this method to throw IOExceptions, but otherwise a was a simple change.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/324)

**Comment by lessarderic** [comment]
<sup>**[distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/AbstractIntegrationTest.java, line 415 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/324#-K2njskaXeSikRdedl-1)** ([raw file](https://github.com/codice/ddf/blob/905e0ec5d7231603c7de7b4e7a081b0c75063b55/distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/AbstractIntegrationTest.java#L415)):</sup>
Can you take a look at the `installStartupFile()` implementation and do what this was doing? The current implementation uses a temp file and I don't think that's needed.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/324)

**Comment by lessarderic** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/324)

**Comment by lessarderic** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/324)

**Pull request merged**
