### PR TITLE
DDF-2822 Update product name from Catalog to Intrigue

### PR DESCRIPTION
**Pull request by andrewkfiedler**
#### What does this PR do?
 - Updates product name from Catalog to Intrigue.
 - Updates namespace from ddf- to intrigue-.
 - Updates .html to be .text in application.js to remove injection opportunity.

#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged)?
@andrewkfiedler
@pklinef 
@rzwiefel 
@djblue 

#### How should this be tested? (List steps with links to updated documentation)
Go to the UI and verify that the name has been updated.  Verify that the namespace change had no adverse effects.

#### What are the relevant tickets?
https://codice.atlassian.net/browse/DDF-2822

#### Screenshots

screen shot 2017-02-21 at 9 47 40 pm
screen shot 2017-02-21 at 9 46 47 pm
screen shot 2017-02-21 at 9 46 37 pm
screen shot 2017-02-21 at 9 46 25 pm

### CODE REVIEW

**Comment by ricklarsen** [comment]
@pklinef @andrewkfiedler To update the name in the docs, just set the value of the `${catalog-ui} property in the pom.xml file. (might need to spot check that all references were set to the property, but as this section is relatively new, I'd expect they would be)

**Comment by vinamartin** [comment]
I've made a PR to your branch for the necessary docs changes https://github.com/andrewkfiedler/ddf/pull/1

**Comment by pklinef** [comment]
Update the feature to install Intrigue.

https://github.com/codice/ddf/blob/master/catalog/ui/search-ui-app/src/main/resources/features.xml#L20

Do others think we should just name that whole app the Intrigue app?  That will rename it in the installer and Admin UI.

**Comment by pklinef** [comment]
In master I see 592 references to catalog in the src folder for catalog-ui-search.  We should look at moving Java packages.  The project should be renamed to intrigue-ui too for consistency.  Hopefully we can also change the `Web-ContextPath` to /search/intrigue` or maybe even just `/intrigue`.

**Comment by andrewkfiedler** [comment]
build now

**Pull request merged**
