### PR TITLE
DDF-1367 updated backup command to get more reliable solr url and add…

### PR DESCRIPTION
**Pull request by wmcnalli**
…ed unit tests

@kcwire 
@jrnorth 
@emanns95 - HERO!
@kguerriero
@jlcsmith 
@millerw8 
@beyelerb

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/104)

### CODE REVIEW

**Comment by jrnorth** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[catalog/core/catalog-core-solrcommands/src/test/java/org/codice/ddf/commands/solr/TestBackupCommand.java, line 42 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/104#-JwSlzlWQPFjQ7ydZPjN)** ([raw file](https://github.com/codice/ddf/blob/362fdf079b37d6f0a20acfbb42ab059e96d5265e/catalog/core/catalog-core-solrcommands/src/test/java/org/codice/ddf/commands/solr/TestBackupCommand.java#L42)):</sup>
A lot of this code could go into a @Before method.

---

<sup>**[catalog/core/catalog-core-solrcommands/src/test/java/org/codice/ddf/commands/solr/TestBackupCommand.java, line 61 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/104#-JwSnRykz8yNSAt-3wYw)** ([raw file](https://github.com/codice/ddf/blob/362fdf079b37d6f0a20acfbb42ab059e96d5265e/catalog/core/catalog-core-solrcommands/src/test/java/org/codice/ddf/commands/solr/TestBackupCommand.java#L61)):</sup>
System.out should be reset after each test, right?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/104)

**Comment by kcwire** [comment]
Reviewed 8 of 9 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/BackupCommand.java, line 92 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/104#-JwTnWdtUErKpTZE04Oe)** ([raw file](https://github.com/codice/ddf/blob/db564eef4b42b030d7bb4275faaa1f5f540eaf69/catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/BackupCommand.java#L92)):</sup>
I forget seeing this in the features file, but I'm assuming the solrCommands bundle depends on the SolrCatalogProivder feature, so this would likely never fail.

---

<sup>**[catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/SolrHttpWrapper.java, line 71 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/104#-JwTq2mlD9ii0rLKJjGg)** ([raw file](https://github.com/codice/ddf/blob/db564eef4b42b030d7bb4275faaa1f5f540eaf69/catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/SolrHttpWrapper.java#L71)):</sup>
I could have sworn HttpClient supported these properties natively which was one big motivator to move them to system properties instead of in Platform Global Config.

http://hc.apache.org/httpclient-3.x/sslguide.html
https://hc.apache.org/httpcomponents-client-ga/tutorial/html/connmgmt.html

Seems like we should only have to create an SSLContext if we want to customize it. 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/104)

**Comment by wmcnalli** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/BackupCommand.java, line 92 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/104#-JwTnWdtUErKpTZE04Oe)** ([raw file](https://github.com/codice/ddf/blob/db564eef4b42b030d7bb4275faaa1f5f540eaf69/catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/BackupCommand.java#L92)):</sup>
Even if the bundle is there, I don't believe there is a config attached to it by default.

---

<sup>**[catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/SolrHttpWrapper.java, line 71 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/104#-JwTq2mlD9ii0rLKJjGg)** ([raw file](https://github.com/codice/ddf/blob/db564eef4b42b030d7bb4275faaa1f5f540eaf69/catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/SolrHttpWrapper.java#L71)):</sup>
I did try with the default client and I'm greeted with a 401 error.  

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/104)

**Comment by kcwire** [comment]
:+1:

**Comment by jrnorth** [comment]
LGTM

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/104)

**Comment by kcwire** [comment]
@wmcnalli who is heroing this?

**Comment by emanns95** [comment]
@kcwire I am, but with osgeo issues has me not able to actually try building it. I posted in slack the other day though about itest failures.

**Comment by wmcnalli** [comment]
@kcwire @emanns95 - still trying to get the itests fixed.

**Comment by emanns95** [comment]
@wmcnalli Having issues with Ryan's script. Can we rely on Bamboo? Not sure if those would be legitimate failures there.

**Pull request merged**
