### PR TITLE
DDF-1321 Make TikaInputTransformer declare the Transformer Factory Implementation.

### PR DESCRIPTION
**Pull request by shane-voisard**
@kcwire @jrnorth @bdeining 

- code change is one line in init() method.
- code formatter made many changes.

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/230)

### CODE REVIEW

**Comment by bdeining** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/230)

**Comment by jrnorth** [comment]
How does this affect `TikaInputTransformer`? Isn't the problem that `TikaInputTransformer` isn't explicitly declaring which factory class it wants to use to obtain transformer instances?
https://github.com/codice/ddf/blob/master/catalog/transformer/catalog-transformer-tika-input/src/main/java/ddf/catalog/transformer/input/tika/TikaInputTransformer.java#L73


---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/230)

**Comment by shane-voisard** [comment]
see description of https://jira.di2e.net/browse/GDIB-1181 by author @kcwire.


---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/230)

**Comment by shane-voisard** [comment]
sorry..see first comment by @kcwire.


---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/230)

**Pull request closed without merging**
