### PR TITLE
[2.26.x] DDF-6400 Upgrade to Camel 3.4.0

### PR DESCRIPTION
**Pull request by SmithJosh**
#### What does this PR do?
This is a backport of https://github.com/codice/ddf/pull/6401

It upgrades to Camel 3.4.0 to continue receiving security updates. This is the last Camel LTS release with Java 8 support, and will be supported through June of 2021 (see https://camel.apache.org/blog/2020/03/LTS-Release-Schedule/#release-schedule). Also, it upgrades a few other dependencies to match the version Camel uses, most notably moving to Guava 29.0.

#### Who is reviewing it? 

@emmberk 
@glenhein 
@jordanwilking 
@derekwilhelm 
@jlcsmith 

#### Select relevant component teams: 
@codice/security
@codice/io

#### How should this be tested?

See the testing instructions here: https://github.com/codice/ddf/pull/6401

#### What are the relevant tickets?
Fixes: #6400

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by SmithJosh** [comment]
build now

**Review by emmberk — APPROVED** [review]

**Comment by SmithJosh** [comment]
build now

**Review by ricklarsen — APPROVED** [review]
reviewed docs changes

**Comment by a-asaad** [comment]
Hero Successful ✅

Tested the HttpProxy, CDM, WFS source, and user account deletion with no issues.

**Comment by SmithJosh** [comment]
Flakey itest failure:
```
[2020-11-10T21:33:15.304Z] [ERROR] Failures: 
[2020-11-10T21:33:15.304Z] [ERROR]   TestSecurity.testBasicFederatedAuth:653 1 expectation failed.
14:33:15  Expected status code <200> doesn't match actual status code <500>.
```

build now

**Comment by SmithJosh** [comment]
Same test failed. Trying again.

build now

**Comment by SmithJosh** [comment]
Same itest failed for the third time... this has been happening on master as well with the same itest. It needs to be fixed.

build now

**Comment by SmithJosh** [comment]
build now

**Review by derekwilhelm — APPROVED** [review]

**Review by jlcsmith — APPROVED** [review]

**Pull request merged**
