### PR TITLE
DDF-1634 changed the MetadataConfigurationParser to retry HTTP metadata connections with an exponential backoff

### PR DESCRIPTION
**Pull request by stustison**
@pklinef 
@vinamartin 
@clockard (will hero)

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/322)

### CODE REVIEW

**Comment by clockard** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/322)

**Comment by clockard** [comment]
Built successfully with all tests passing. 
LGTM :+1:

**Comment by vinamartin** [comment]
LGTM :+1:

**Comment by djblue** [comment]
:+1:

**Pull request merged**
