### PR TITLE
DDF-1303 updated the version on javax.annotation and javax.annotation.…

### PR DESCRIPTION
**Pull request by jvettraino**
…processing to the correct version which is 1.0 (see ticket KARAF-3566 for more details of Karaf bug)

@shaundmorris and @mrmateo can you take a look at this.  It should probably be applied to master as well, so let me know if you want me to do that or if you want to just apply it.

This causes issues with certain CXF features from deploying.

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/65)

### CODE REVIEW

**Comment by jvettraino** [comment]
I built this and tested on Java 7 and Java 8, and didn't see any issues.

**Comment by stustison** [comment]
Is it possible to bump this version in custom.properties instead of us needing to maintain the Karaf jre.properties file. We've maintained that file in the past and it did not go well for us.

**Comment by brendan-hofmann** [comment]
Can you be more specific about exactly what functionality this fixes? We haven't seen any CXF issues with Java 8 yet.

**Comment by jvettraino** [comment]
I also submitted a PR to Karaf to fix it, so ideally that would get merged in, with the 2.4.3 release and then it can be removed.

@stustison these properties can be placed in the custom.properties if that is desired.  However, I have not seen a way to "add onto exsiting properties" - meaning just adding/updating the javax.annotation version for that property, instead it is a complete replacement, which means we would have to copy all 3 properties defined in the jre.properties file into the custom.properties file, which seems like more of a maintenance nightmare.  Remember that the jre.properties are essentially one property for each java version that then contains a long list of packages.  Let me know if you still want this done.

@brendan-hofmann it is likely that core DDF isn't using any of the CXF functionality that is impacted by this.  I updated the jira ticket with more details, but its basically anything that is using one of the new javax.annotations (added in 1.2) alongside Java 8, so I saw this with the Priority Annotation for JAXRS providers.

**Comment by pklinef** [comment]
:+1:

**Comment by mrmateo** [comment]
I agree with @stustison that keeping our own jre.properties added to upgrade complications. From the karaf tickets referenced it definitely looks like this was an oversight by the karaf team though.

I'm good with this with the understanding that it will be reverted once DDF uses a karaf version that is 'fixed'. Karaf labeled it as a 'major' bug so it would be good to get the fix in for the 2.7.0 release.

**Comment by jvettraino** [comment]
@brendan-hofmann here is an example of how this functionality impacts our app (https://github.com/di2e/ecdr/blob/master/endpoint/cdr-rest-search-endpoint/src/main/resources/OSGI-INF/blueprint/service-blueprint.xml#L47) the jaxrs:provider specifically is leveraging a CXF component that uses the Priority annotation (https://cxf.apache.org/javadoc/latest/org/apache/cxf/rs/security/cors/CrossOriginResourceSharingFilter.html)

There are other CXF components as well (OAuth, JAAS, etc.) that use this same Priority annotation (or any other new JAXRS annotations), so it would impact anyone deploying a component that leverages one of those.

Let me know if you still have questions.

**Comment by stustison** [comment]
:+1:  Thanks for the explanation.

**Comment by shaundmorris** [comment]
I verified build/tests passing. I can take care of cherry-picking to master as well.

**Pull request merged**
