### PR TITLE
DDF-2067 Improved TestSpatial to include compound csw queries

### PR DESCRIPTION
**Pull request by bcwaters**
#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?
@roelens8 @tbatie 
#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@kcwire
@shaundmorris 
#### How should this be tested?
Build ddf and run the integration test TestSpatial
#### Any background context you want to provide?
N/A
#### What are the relevant tickets?
N/A
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [x] Update / Add Integration Tests

### CODE REVIEW

**Comment by roelens8** [comment]
👍

**Comment by shaundmorris** [comment]
👍

**Comment by tbatie** [comment]
:+1:

**Comment by jaymcnallie** [comment]
LGTM 👍

**Pull request merged**
