### PR TITLE
DDF-3080 Updates pom files to not deploy duplicate source jars during release

### PR DESCRIPTION
**Pull request by kcrowe01**
#### What does this PR do?
Updates pom files to not deploy duplicate source jars when running a release. This caused a failure in nexus repositories that did not allow updates. Also updates the artifactId from catalog-plugin-metacardbackup to catalog-plugin-metacardbackup-storage-common based on changes in https://github.com/codice/ddf/pull/2012.
 
#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged)?
@vinamartin 
@emmberk 
@taz77 
#### Select relevant component teams: 
https://github.com/orgs/codice/teams
#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@clockard
@shaundmorris
#### How should this be tested? (List steps with links to updated documentation)
Download and unzip nexus: https://www.sonatype.com/download-oss-sonatype
Run nexus: ./\<nexus location\>/bin/nexus start
Update .m2/settings.xml to include:
```
<server>
    <id>releases</id>
    <username>admin</username>
    <password>admin123</password>
</server>
```
Prepare the release `mvn release:prepare -Prelease -DlocalCheckout=true -DignoreSnapshots=true` and accept all the defaults

Checkout to new tag `git checkout ddf-2.11.0`

Perform the release 
```
mvn deploy -DaltDeploymentRepository=releases::default::http://localhost:8081/repository/maven-releases -Prelease
```

#### What are the relevant tickets?
https://codice.atlassian.net/browse/DDF-3080
#### Checklist:
- [ ] Documentation Updated
- [ ] Change Log Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests
#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by kcrowe01** [comment]
build now

**Comment by clockard** [comment]
build now

**Comment by clockard** [comment]
build now

**Comment by LinkMJB** [comment]
build now

**Comment by LinkMJB** [comment]
build now

**Comment by LinkMJB** [comment]
build now

**Comment by clockard** [comment]
build now

**Comment by taz77** [comment]
I am working on the hero build.

**Comment by taz77** [comment]
build now

**Comment by taz77** [comment]
build now

**Pull request merged**
