### PR TITLE
DDF-5273 Adding an OAuth Plugin Exception

### PR DESCRIPTION
**Pull request by nsuvarna**
#### What does this PR do?
Adds the `OAuthPluginException` and its associated error handling to allow this error to be used downstream; note that this error will not be thrown in DDF until the DDF OAuth work has been completed. Also, the error announcements that will be displayed for `OAuthPluginException`s are a temporary implementation to notify the users of the problem; these will be replaced with notifications in the notification sidebar when OAuth is fully added to DDF.
#### Who is reviewing it? 

@Schachte 
@mcat97
#### Select relevant component teams: 
@codice/security 
@codice/ui 
#### Ask 2 committers to review/merge the PR and tag them here.

@bdeining
@blen-desta
@djblue

#### How should this be tested?

Execute a federated query against a source and verify that it works as expected
#### What are the relevant tickets?
Fixes: #5273 

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by bdeining** [comment]
build now

**Comment by nsuvarna** [comment]
build now (previous failure was a JNLP disconnect)

**Comment by nsuvarna** [comment]
build now (failed in metacard validation filter test, and I'm not getting any failures when I run that itest locally)

**Comment by mcat97** [comment]
Hero Was Successful 🎉

**Pull request merged**
