### PR TITLE
DDF 1722: Parallelize maven builds.

### PR DESCRIPTION
**Pull request by djblue**
@vinamartin 
@clockard 
@stustison 
@gordocanchola 
@ricklarsen 
@oscaritoro 
@rzwiefel 
@pklinef

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/codice/ddf/pull/386" target="_blank">ReviewNinja

**Comment by oscaritoro** [comment]
I think we need to investigate the error we sometimes see generating docs now: 
```java
[ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:1.5.2:process-asciidoc (generate-pdf-doc) on project docs: Execution generate-pdf-doc of goal org.asciidoctor:asciidoctor-maven-plugin:1.5.2:process-asciidoc failed: (NameError) uninitialized constant ThreadSafe::JRubyCacheBackend -> [Help 1]
```

I saw these in both `DDF :: solr :: DOCS`  and `DDF :: Security :: DOCS`

**Comment by vinamartin** [comment]
Built this multiple times on my machine and it has been faster than running in serial. It should be noted somewhere that a number of threads needs to be specified for this to work. 

Even with building docs, I don't seem to be having the issue that @oscaritoro is having. Nor can I reproduce it. That might be something you want to look into further. 
For example, my total time came in at `Total time: 14:16 min` without tests where 
DDF Docs is taking 13:48 min and Catalog Docs is taking 6:39 min, which seems to imply that the various docs are running in parallel. 

One possible solution is to run parallel builds without documentation (to test out something you are working on) and then a full serial build with documentation before committing/merging. 

After the docs issue is resolved, :+1:

**Comment by oscaritoro** [comment]
Just to be a little more clear...
I was running my tests with `mvncistfast -T 2.0C` which ends up creating 2 threads per core, on my machine that has a 4 core CPU (Intel(R) Core(TM) i7-4790 CPU) I would expect this to be 8 threads.

I believe the problem arise not only when more than one "DOCS" module is being build simultaneously, but they have to actually be using the jruby/asciidoc sub-sytem simultaneously... not just doing setup/download stuff.

**Pull request merged**
