### PR TITLE
Upgrade to CXF 3.4.2

### PR DESCRIPTION
**Pull request by abel-connexta**
#### What does this PR do?
Upgrades to CXF 3.4.2, and along with it upgraded Lucene dependency

#### Who is reviewing it? 

@kentmorrissey
@lavoywj
@frnkshin
@hayleynorton
@jMoneee
@shaundmorris
@zta6
@jlcsmith 

#### How should this be tested?

Note - When was building, occasionally had itest failure for `ddf.test.itests.core.DdfCoreIT.testCswUpdateByFilterConstraint(DdfCoreIT.java:216)`
Error
`Expected: an XML document with XPath //TransactionResponse/TransactionSummary/totalUpdated is "2"`

This was also occurring for the base master, so believe it is not related to this upgrade.

- build / run / profile install

1. Configure a loopback CSW source and make sure it goes to “available”
- Config Loopback via Admin console -> System -> Configuration -> "CSW Federation Profile Source" . Can create using all defaults
- Check CSW source status is "available" via hitting sources endpoint -> https://localhost:8993/services/catalog/sources
2. Ingest some data via one of the endpoints (like REST) and via a file ingest
- Some sample data I used were from catalog/core/catalog-core-commons/src/test/resources/data e.g. IngestMetadata_WithContent.xml
- Ingested via POST https://localhost:8993/services/catalog
- File ingest e.g. `curl -k -X POST -i -H "Content-Type: multipart/mixed" -basic --user admin:admin -F upload=@IMG_3808.png https://localhost:8993/services/catalog`
3. Play with some of the other endpoints … do a CSW query for example or an OpenSearch Query
- OpenSearch - e.g. "https://localhost:8993/services/catalog/query?q=*" more info at "3.8.5.6. OpenSearch Source" http://codice.org/ddf/docs/managing.html#_opensearch_source
- CSW - couple endpoints:
   https://localhost:8993/services/csw?version=2.0.2&service=CSW&request=describeRecord ; 
   https://localhost:8993/services/csw?version=2.0.2&service=CSW&request=getCapabilities

Ensure no error, and all is working and no regression 

#### What are the relevant tickets?
Fixes: #____

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by abel-connexta** [comment]
build now

**Review by zta6 — APPROVED** [review]

**Comment by abel-connexta** [comment]
build now

**Comment by abel-connexta** [comment]
build now

**Review by shaundmorris — APPROVED** [review]

**Review by frnkshin — APPROVED** [review]

**Comment by zta6** [comment]
🎉 Hero succesful 🎉 
Verified can configure CSW source, ingest data and query it successfully
verified getCapabailities and describeRecord both retun valid responses
LGTM!

**Review by AzGoalie — APPROVED** [review]

**Pull request merged**
