### PR TITLE
[2.11.x] DDF-3309 Convert templates to HTML 5

### PR DESCRIPTION
**Pull request by ahoffer**
#### What does this PR do?
2.11.x port of https://github.com/codice/ddf/pull/2350
#### Who is reviewing it? 
@mcalcote @josephthweatt @stustison @tbatie  
#### Select relevant component teams: 
https://github.com/orgs/codice/teams
#### Choose a few committers to review/merge the PR. 
@clockard
@coyotesqrl
@figliold 
#### How should this be tested? (List steps with links to updated documentation)
Build DDF or downstream project. 
Try logging in and out of search UI and admin UI on a Mac.
Try logging in and out of search UI and admin UI with IE11 on Windows.
#### What are the relevant tickets?
[DDF-3309](https://codice.atlassian.net/browse/DDF-3309)
#### Screenshots (if appropriate)
image

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests
#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by clockard** [comment]
build now

**Comment by clockard** [comment]
build now

**Comment by clockard** [comment]
Manually verified on Mac with Chrome.

**Comment by emanns95** [comment]
Manually verified that the bug this PR is set out to fix is resolved. I ran into other issues (see attachment), but it is a different set of issues. This passed Windows hero for the intended fix :+1: 
image

**Pull request merged**
