### PR TITLE
[2.19.x] G-8880 Fixed Antarctica Geometry

### PR DESCRIPTION
**Pull request by brianfelix**
#### What does this PR do?
Fixes the geometry for Antarctica

#### Who is reviewing it? 
@andrewzimmer 
@mojogitoverhere 
@Lambeaux 

#### Ask 2 committers to review/merge the PR and tag them here.
@andrewzimmer
@lambeaux
@mojogitoverhere

#### How should this be tested?
This should be tested on a downstream project that utilizes the gazetteer. Please contact me before testing to ensure you grant the downstream project permissions to access the gazetteer data.
Build/Install development profile
Navigate to Intrigue
In the gazetteer search text box, enter "Antarctica"
Verify you are suggested the feature for Antarctica
Click the Antarctica Feature and verify the map pans to Antarctica

#### Any background context you want to provide?
The geometry being used for Antarctica was not working in the gazetteer due to limitations in geo libraries that DDF uses which are not able to handle polygons that wrap around the poles. This modifies the geometry for Antarctica so that Antarctica now works correctly when selected in the gazetteer.

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Review by millerw8 — APPROVED** [review]

**Review by rymach — APPROVED** [review]

**Comment by mojogitoverhere** [comment]
Antarctica doesn't look quite right in the github geojson viewer. Is that expected?
Screen Shot 2021-03-24 at 8 40 35 AM

**Comment by mojogitoverhere** [comment]
Also not sure why Ivory Coast is missing
Screen Shot 2021-03-24 at 1 00 06 PM

**Comment by brianfelix** [comment]
@mojogitoverhere I'm not sure why the tool you are using is showing most of the world highlighted when using the geometry for Antarctica. To test out the geometry in something other than DDF, I added the geometry to the geojson viewer at geojson.io and the geometry appears to be correct. Here is a sceeenshot from geojson.io that shows only Antarctica is highlighted when I input the coordinates for Antarctica:

Geojson Antarctica

**Comment by mojogitoverhere** [comment]
@brianfelix Oh sorry, [github](https://github.com/codice/ddf/blob/18959817ac70acd8eda963e00607e72d55a23b79/distribution/ddf-common/src/main/resources/data/countries.geo.json) was just rendering the entire geojson file. The real issue I was referring to was the large patch of land on the left that the new geojson doesn't cover. Your screenshot shows the same issue. (Unless both of those tools are using old map data and that much ice has actually melted 😢 )

Github
Screen Shot 2021-03-24 at 6 45 20 PM

geojson.io
Screen Shot 2021-03-24 at 6 44 56 PM

**Review by shaundmorris — APPROVED** [review]

**Comment by shaundmorris** [comment]
build now

**Comment by millerw8** [comment]
> @brianfelix Oh sorry, [github](https://github.com/codice/ddf/blob/18959817ac70acd8eda963e00607e72d55a23b79/distribution/ddf-common/src/main/resources/data/countries.geo.json) was just rendering the entire geojson file. The real issue I was referring to was the large patch of land on the left that the new geojson doesn't cover. Your screenshot shows the same issue. (Unless both of those tools are using old map data and that much ice has actually melted 😢 )
> 
> Github
> Screen Shot 2021-03-24 at 6 45 20 PM
> 
> geojson.io
> Screen Shot 2021-03-24 at 6 44 56 PM

**Review by mojogitoverhere — APPROVED** [review]

**Comment by mojogitoverhere** [comment]
build now

**Comment by mojogitoverhere** [comment]
hero in progress

**Comment by mojogitoverhere** [comment]
## 🎉 Hero was successful! 🎉 ##


antarctica-zoom-min

**Pull request merged**
