### PR TITLE
DDF-1338: Documented how to configure and unconfigure HTTPS and both …

### PR DESCRIPTION
**Pull request by brianfelix**
…HTTP/HTTPS including 1-way and 2-way SSL

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/71)

### CODE REVIEW

**Comment by brianfelix** [comment]
Champion: @roelens8
@stustison

**Comment by stustison** [comment]
:+1:

**Comment by roelens8** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/71)

**Comment by roelens8** [comment]
Looks good!

**Comment by shaundmorris** [comment]
Verified build and viewed the documentation for accuracy.

**Pull request merged**
