### PR TITLE
DDF-3014 Update spatial-commands to use new Karaf command annotations

### PR DESCRIPTION
**Pull request by clockard**
#### What does this PR do?
Update spatial-commands to use new Karaf command annotations
#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged)?
@vinamartin @emmberk @josephthweatt
#### Select at least one member from relevant component team(s) from below (at least one component team member needs to approve the PR).

[Data](https://github.com/orgs/codice/teams/data)

#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@figliold
@shaundmorris

#### How should this be tested? (List steps with links to updated documentation)
Verify build passes and geonames:update all command works
#### What are the relevant tickets?
[DDF-3014](https://codice.atlassian.net/browse/DDF-3014)
#### Checklist:
- [ ] Documentation Updated
- [ ] Change Log Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by clockard** [comment]
build now

**Comment by josephthweatt** [comment]
Pulled down your code and tested it. Looks good to me

**Comment by clockard** [comment]
build now

**Comment by clockard** [comment]
build now

**Comment by clockard** [comment]
build now

**Comment by clockard** [comment]
build now

**Comment by clockard** [comment]
build now

**Pull request merged**
