### PR TITLE
[2.19.x] DDF-5730 edit wording of dropdown options to specify rows

### PR DESCRIPTION
**Pull request by cassandrabailey293**
#### What does this PR do?
Adds the word "Rows" to the options in the export dropdown to specify that export applies to rows, not columns

#### Select relevant component teams: 

@codice/ui 

#### How should this be tested?

* Conduct any search that returns 1 or more results
* Go to Table Inspector
* Click Export
* In the popup, click the dropdown under "Export"
* Verify that all the options now specify "rows"

#### What are the relevant tickets?
Fixes: #5730 

#### Screenshots

Before
image

After
image

@maryformanek Can you verify that this wording change is satisfactory? Any recommendations/changes?

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by maryformanek** [comment]
Looks good to me! UX approved.

**Comment by andrewzimmer** [comment]
build now

**Comment by andrewzimmer** [comment]
build now

**Comment by andrewzimmer** [comment]
Hero Successful 🎉 
- verified wording
- verified no regression

**Comment by bdeining** [comment]
this passes manually, merging because the CI is broken

**Pull request merged**
