### PR TITLE
DDF-5022 Fix dropdown left/right calculation

### PR DESCRIPTION
**Pull request by djblue**
#### What does this PR do?

Fixes dropdown left/right calculation

#### Who is reviewing it? 

@samuelechu
@Bdthomson 

#### Select relevant component teams: 

@codice/ui

#### Ask 2 committers to review/merge the PR and tag them here.

@adimka
@andrewkfiedler
@bdeining

#### How should this be tested?

Open dropdowns close to the sides of the window, verify they are completely visible.

#### What are the relevant tickets?

Fixes: #5022

##### Before

Screenshot from 2019-06-26 10-30-00

##### After

Screenshot from 2019-06-26 10-30-56

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by djblue** [comment]
Build now

**Comment by Bdthomson** [comment]
build now

**Comment by Bdthomson** [comment]
build now (fluke)

**Comment by lifenouveau** [comment]
@djblue What are the differences in these screenshots?

**Comment by djblue** [comment]
@lifenouveau the first one has the dropdown going outside the visible window space.

**Comment by andrewkfiedler** [comment]
Would it be worth doing a revert on the prior fix so it's easier to see that the only fix needed is that one line?

**Comment by djblue** [comment]
### Hero successful :tada: 
- git clone pr
- yarn install
- yarn start
- ensured menus open on the side of the window without overflowing
- ensure menus open up enough from the bottom of the window

**Pull request merged**
