### PR TITLE
DDF-4485 Adhoc workspace title is the search query text

### PR DESCRIPTION
**Pull request by Corey-Collins**
#### What does this PR do?
Replaces the name of the ahoc workspace with `New Workspace` rather than the search query text.
#### Who is reviewing it? 
@willwill96 
@hayleynorton 
@andrewzimmer 
@cantstoptheunk 

#### Ask 2 committers to review/merge the PR and tag them here.

@bdeining
@jrnorth 

#### How should this be tested?
- Navigate to Workspaces
- Under the `start a new workspace` label search using a query
- Verify that the new workspace is titled `New Workspace` instead of the query you entered

#### What are the relevant tickets?
For Jira:
[DDF-4485](https://codice.atlassian.net/browse/DDF-4485)

For GH Issues:
Fixes: #____

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by Corey-Collins** [comment]
build now

**Comment by willwill96** [comment]
Hero started

**Comment by willwill96** [comment]
🌮 🌮 Hero Succesful 🌮 🌮 
Created several workspaces from the search bar and ensured that the title was `New Workspace`, not the text entered for the search

**Comment by jlcsmith** [comment]
❓ I think the usage of the search text in the workspace name was done on purpose to avoid having lots of workspaces named "New Workspace".  What is the motivation for this change?

**Comment by bdeining** [comment]
build now

**Pull request merged**
