### PR TITLE
DDF-2278: Turn catalog-core-validationparser on by default

### PR DESCRIPTION
**Pull request by rzwiefel**
#### What does this PR do?
Turns catalog-core-validationparser on by default
#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?
@coyotesqrl @pklinef  @jlcsmith @jrnorth 

#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).

@stustison 
@kcwire

#### What are the relevant tickets?
https://codice.atlassian.net/browse/DDF-2278

### CODE REVIEW

**Comment by coyotesqrl** [comment]
lgtm

**Comment by jlcsmith** [comment]
👍

**Comment by coyotesqrl** [comment]
Update ticket, commit, and PR title to correctly reflect the fact that it's the `validationparser` that's being turned on.

**Comment by rzwiefel** [comment]
done @coyotesqrl

**Comment by jrnorth** [comment]
LGTM

**Comment by jrnorth** [comment]
Note: this will also turn on the metacard validation plugin.

**Comment by stustison** [comment]
👍

**Comment by pklinef** [comment]
👍

**Pull request merged**
