### PR TITLE
DDF-2235 Update ffmpeg to address related OWASP findings

### PR DESCRIPTION
**Pull request by bcwaters**
#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?
@ryeats @adimka @tbatie 

#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest)
@coyotesqrl 
@shaundmorris

#### How should this be tested?
A successful build is sufficient
#### Any background context you want to provide?
There is a PR to thirdparty that contains the new binaries.  This PR will not work until that one is merged
#### What are the relevant tickets?
DDF-2173
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by coyotesqrl** [comment]
👍

**Comment by glenhein** [comment]
I ingested a streaming video with Alliance that was built on top of this PR. The video thumbnails were created as expected.

**Comment by shaundmorris** [comment]
👍

**Comment by ryeats** [comment]
👍  hero'd

**Pull request merged**
