### PR TITLE
DDF-6554 Handles epoch dates in tika transformer 

### PR DESCRIPTION
**Pull request by jlcsmith**
#### What does this PR do?
Forward port of #6555 
#### Who is reviewing it? 
@derekwilhelm 
@glenhein 

#### Select relevant component teams: 
@codice/data 

#### Ask 2 committers to review/merge the PR and tag them here.
@derekwilhelm 
@glenhein 

#### How should this be tested?
See #6555 

#### What are the relevant tickets?
Fixes: #6554 

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by jlcsmith** [comment]
build now

**Review by jordanwilking — APPROVED** [review]

**Review by pklinef — APPROVED** [review]
We need to be careful about adding test files that are megabytes in size if possible.

**Comment by jlcsmith** [comment]
> We need to be careful about adding test files that are megabytes in size if possible.

Agreed - I thought I had resized that one but must have missed it.  I'll update it

**Comment by jlcsmith** [comment]
build now

**Comment by jlcsmith** [comment]
build now

**Pull request merged**
