### PR TITLE
DDF-04297 Refactoring location dropdown

### PR DESCRIPTION
**Pull request by Schachte**
#### What does this PR do?
Currently, as we extend the location component to support more items, BBOX, polygon etc. As the number of items in this section grows, the UI starts to look strange. 

Given that this plugin is extensible and used downstream, the numbers of items has already started to grow and makes for a poor user experience. 

This **UI enhancement** seeks to remediate this problem by placing everything in a scrollable dropdown. 

**Current** 
screen shot 2019-01-31 at 8 58 02 am

**Inevitable Issues (Mockup)** 
screen shot 2019-01-31 at 8 59 15 am

**Proposed Change**
screen shot 2019-01-31 at 8 42 11 am

#### Who is reviewing it? 
@bdeining 
@middlets719 
@zta6 
@adimka 
@gordocanchola 

#### Select relevant component teams: 
@codice/ui 

#### Ask 2 committers to review/merge the PR and tag them here.

@andrewkfiedler
@bdeining 
@djblue 
@gjvera 
@middlets719 

#### What are the relevant tickets?
For Jira:
[](https://codice.atlassian.net/browse/)

For GH Issues:
Fixes: #4297 

#### Screenshots
screen shot 2019-01-31 at 8 42 11 am

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by Schachte** [comment]
build now

**Comment by coyotesqrl** [comment]
I've updated the PR title with the corrected ticket prefix; once the commit has been fixed I will remove my block on this and leave it to others to review the contents.

**Comment by Schachte** [comment]
@vinamartin @coyotesqrl Updated commit message

**Comment by Schachte** [comment]
build now

**Comment by Schachte** [comment]
build now

**Comment by willwill96** [comment]
Hero Started

**Comment by willwill96** [comment]
🌮 🌮 Hero Successful 🌮 🌮 
Verified that the location radio button is now a dropdown and didn't notice any regressions

LG2M

**Comment by bdeining** [comment]
build now

**Pull request merged**
