### PR TITLE
DDF-1505: Add methods in integration test common classes to restart bundles and wait for configuration updates

### PR DESCRIPTION
**Pull request by lessarderic**
Added a method to ServiceManager to restart one or more bundles. Also added a 
waitForConfiguration() method to AdminConfig along with a ConfigurationPredicate
class that wait for a property value to match a regular expression.

@garrettfreibott, @figliold, please review.

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/189)

### CODE REVIEW

**Comment by coyotesqrl** [comment]
lgtm

**Comment by kcwire** [comment]
@lessarderic are there any tests this specifically fixes?

**Comment by figliold** [comment]
:thumbsup: 

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/189)

**Comment by figliold** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/189)

**Comment by lessarderic** [comment]
@kcwire: This doesn't fix anything specifically. It only adds a couple new methods to help write our integration tests.

**Comment by garrettfreibott** [comment]
lgtm, waiting for build to finish.

**Comment by tbatie** [comment]
Finished the build for garrett, it was successful :+1:

**Comment by garrettfreibott** [comment]
@tbatie thanks tracy!

**Pull request merged**
