### PR TITLE
DDF-3621 Downgraded logs during caching expiration when the failure is due to Solr being unavailable

### PR DESCRIPTION
**Pull request by paouelle**
#### What does this PR do?
It changes the logging of Solr failures while trying to expire the cache such that if it occurs because Solr is unavailable, only debug traces are generated such as not to pollute logs. 

It also changes the normal INFO log in all other cases to move the stack trace to DEBUG instead.

In addition, it addresses 2 SonarQube issue reported in that file.

#### Who is reviewing it? 
(please choose AT LEAST two reviewers that need to approve the PR before it can get merged)
#### Select relevant component teams: 
https://github.com/orgs/codice/teams
@tbatie 
@jhunzik 
@emanns95 

#### Ask 2 committers to review/merge the PR and tag them here. If you don't know who to ask, you can request reviews in https://groups.google.com/forum/#!forum/ddf-developers .
(please choose ONLY two committers from below, delete the rest)
@figliold
@lessarderic

#### How should this be tested? (List steps with links to updated documentation)
Startup DDF and verify that the following log not longer shows up at INFO level
```
... | SolrCache                        | ... | ... - catalog-core-standardframework - 2.12.0.SNAPSHOT | Unable to expire cache.
org.codice.solr.client.solrj.UnavailableSolrException: initializing 'XXXXX' client
```

#### What are the relevant tickets?
[DDF-3621](https://codice.atlassian.net/browse/DDF-3621)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by paouelle** [comment]
build now

**Comment by paouelle** [comment]
build now
Jenkins deployment issue

**Comment by paouelle** [comment]
build now
same Jenkins startup issue

**Comment by emanns95** [comment]
Confirmed the exception no longer appears in the logs during startup ✅

**Pull request merged**
