### PR TITLE
DDF-1616 SAMLAssertionHandler now checks session when using basic auth.

### PR DESCRIPTION
**Pull request by coyotesqrl**
(cherry picked from commit 2b6ac85)

@roelens8 
@kcwire 
@pklinef 
@shaundmorris

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/306)

### CODE REVIEW

**Comment by kcwire** [comment]
LGTM - merge today if no objections.

**Comment by kcwire** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/306)

**Comment by shaundmorris** [comment]
:+1: 


---

Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/306)

**Comment by roelens8** [comment]
:+1:

**Comment by coyotesqrl** [comment]
Can we get this merged into 2.8?

**Pull request merged**
