### PR TITLE
DDF-4333 Convert existing threat models to Threat Dragon format

### PR DESCRIPTION
**Pull request by brjeter**
#### What does this PR do?
See the screenshots on this PR for the diagrams.
#### Who is reviewing it? 
@Kjames5269 @blen-desta 
#### Select relevant component teams: 
@codice/security 
#### Ask 2 committers to review/merge the PR and tag them here.
@coyotesqrl 
@shaundmorris
@stustison 
#### What are the relevant tickets?
[DDF-4333](https://codice.atlassian.net/browse/DDF-4333)
#### Screenshots
image
image
image
image
image
image
image
image
image
image
image
image

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by coyotesqrl** [comment]
❓ This model doesn't appear to have an entry point; the WFS source makes requests in both directions but nothing is hitting it.

https://user-images.githubusercontent.com/8130140/49035029-d6f7df00-f170-11e8-94cf-842ffff0f425.png

**Comment by coyotesqrl** [comment]
✏️ I believe `flow 13` should be `Response`
https://user-images.githubusercontent.com/8130140/49035024-d19a9480-f170-11e8-8690-b70f3ff792f6.png

**Comment by coyotesqrl** [comment]
✏️ In this model, it seems weird to include the interactions between Solr and the file system as those are internal to how Solr works. Unless we should always be including minimized modeling of third-party internals.
https://user-images.githubusercontent.com/8130140/49034998-be87c480-f170-11e8-975c-dc789c474f36.png

**Comment by coyotesqrl** [comment]
❓ Are the two `External DDF Client`s on the left and right of this model different or the same client?
https://user-images.githubusercontent.com/8130140/49034984-b760b680-f170-11e8-918e-5dd175fa276e.png

**Comment by Kjames5269** [comment]
Hero'd ✅

**Comment by brjeter** [comment]
@coyotesqrl:
1. The flows between the `DDF Catalog` and `WFS Source` should be reversed. I will fix that.
2. `flow 13` should be `Response`. Fixing that.
3. I don't have much background on why the file system operations were included in this Solr diagram in the first place, but I can see there being some value in knowing that the file system is being accessed by an external entity. 🤷‍♂️ 
4. I think the `External DDF Client`s could be different or the same in this diagram.

**Comment by brjeter** [comment]
build now

**Comment by brjeter** [comment]
build now (OWASP failed to download from the NVD database)

**Pull request merged**
