### PR TITLE
DDF-3506 Suppress 'Downloading/Downloaded' status lines in logs

### PR DESCRIPTION
**Pull request by mackncheesiest**
#### What does this PR do?
Suppresses lines of the form 
```
18:43:23 [INFO] Downloading: http://NEXUS/PATH/TO/ARTIFACT
18:43:23 [INFO] Downloaded: http://NEXUS/PATH/TO/ARTIFACT (27 KB at 985.4 KB/sec)
```
from the Jenkins Pipeline build logs

#### Who is reviewing it? 
@vinamartin @blen-desta @oconnormi @mcalcote @LinkMJB 

#### Choose 2 committers to review/merge the PR. 
(please choose ONLY two committers from below, delete the rest)
@bdeining
@clockard

#### How should this be tested? (List steps with links to updated documentation)
It has been verified both in legacy DDF jobs and on a downstream project that only the desired logs are suppressed.

#### What are the relevant tickets?
[DDF-3506](https://codice.atlassian.net/browse/DDF-3506)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by rzwiefel** [comment]
Whats the background reasoning for this change?

**Comment by mackncheesiest** [comment]
Logs that do nothing but indicate that an artifact downloaded don't actually add anything meaningful. They just make it more difficult for developers to analyze.

We added this change to the legacy DDF jobs a while back, and would appear to reduce the final log size by around 5MB

**Comment by rzwiefel** [comment]
@mackncheesiest do we have some other indication of where the artifacts are being downloaded from in case the need arises that we need to determine where artifacts were downloaded from?

**Comment by mackncheesiest** [comment]
build now (even though this affects nothing related to the build)

**Pull request merged**
