### PR TITLE
DDF-1418: Move geocoder modules from ui to spatial

### PR DESCRIPTION
**Pull request by jrnorth**
@millerw8 @jlcsmith @kcwire @wmcnalli @beyelerb @emanns95 @kguerriero @shane-voisard @bdeining @pklinef @stustison

@shane-voisard is the hero

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/133)

### CODE REVIEW

**Comment by kguerriero** [comment]
Reviewed 34 of 34 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/133)

**Comment by emanns95** [comment]
Reviewed 34 of 34 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/133)

**Comment by kcwire** [comment]
Reviewed 34 of 34 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/133)

**Comment by stustison** [comment]
:+1:

**Comment by shane-voisard** [comment]
I was the hero for related PR. Initial building failed on the grunt test for the standard module, despite changing maven version, running the grunt test manually and repeatedly building over three days. Once the upstream master was patched to fix the grunt test failure, the build (mvn clean install with fresh m2) completed successfully. Then I verified the runtime with the following:

    1. Install DDF
    2. Go to Spatial -> Features -> Install offline-gazetteer
    3. Uninstall webservice-gazetteer
    4. Download US.zip from http://download.geonames.org/export/dump
    5. Ingest the data from the karaf console (geonames:update -c /path/to/US.zip)
    6. Go to the standard search UI
    7. Search for locations in the US in the gazetteer search box in the upper-right corner
    8. The searches should work (and they should be very fast).
    9. Go to Spatial -> Features -> Uninstall offline-gazetteer
    10. Re-install webservice-gazetteer
    11. Go back to the search UI and do some more searches (they should be slower since they're using a web service).

**Comment by kcwire** [comment]
@shane-voisard @jrnorth Is step 3 required? Ideally the offline-gazetteer would out rank the webservice without being uninstalled.

Also, what sort of error handling is in place when a search doesn't return any results? (ie search for Mordor which isn't in the US)

**Comment by jrnorth** [comment]
@kcwire No, it shouldn't be. A service ranking of 1 would be sufficient for the offline one to take precedence.

To your second question, there's a ticket for that: https://codice.atlassian.net/browse/DDF-1357. As of right now, the search box will say "(error)" after whatever you searched for, but it ought to say "(not found)".

**Comment by kcwire** [comment]
Thanks @jrnorth - Ticket LGTM. I'll look to merge today if there's no objections

**Pull request merged**
