### PR TITLE
DDF-3721 Display coordinate format options after criteria are selected

### PR DESCRIPTION
**Pull request by rymach**
#### What does this PR do?
Display coordinate format options after criteria are selected
#### Who is reviewing it? 
@BernardIgiri 
@andrewkfiedler 
#### Choose 2 committers to review/merge the PR. 
(please choose ONLY two committers from below, delete the rest)
@clockard
@jlcsmith
#### How should this be tested? (List steps with links to updated documentation)
Open the basic search ui and ensure that the coordinate format buttons only appear when appropriate
#### What are the relevant tickets?
[DDF-3721](https://codice.atlassian.net/browse/DDF-3721)

### CODE REVIEW

**Comment by jlcsmith** [comment]
@rymach can you post a screenshot please?

**Comment by rymach** [comment]
@jlcsmith https://codice.atlassian.net/secure/attachment/18230/screen.mp4

**Comment by rymach** [comment]
output
now in gif form!

**Comment by rymach** [comment]
changes applied

**Comment by AzGoalie** [comment]
Verified it works 👍

**Comment by jlcsmith** [comment]
build now

**Pull request merged**
