### PR TITLE
DDF-2132 offline install issue missing org.apache.felix.coordinator

### PR DESCRIPTION
**Pull request by ryeats**
#### What does this PR do?
Fix installing DDF with broker-app while offline.
#### Who is reviewing it? 
@emmberk 
@jrnorth 
@vinamartin 
(please choose AT LEAST two reviewers that need to approve the PR before it can get merged)
#### Select relevant component teams: 
https://github.com/orgs/codice/teams
#### Choose 2 committers to review/merge the PR. 
(please choose ONLY two committers from below, delete the rest)
@clockard
@jaymcnallie
#### How should this be tested? (List steps with links to updated documentation)
Install broker-app on a DDF while not connected to the internet and without an .m2/repository
#### What are the relevant tickets?
[](https://codice.atlassian.net/browse/)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests
#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by ryeats** [comment]
build now

**Comment by ryeats** [comment]
need to add something to the docs about updating org.codice.ddf.system.hostname

**Comment by bdeining** [comment]
build now

**Comment by ryeats** [comment]
build now

**Comment by ryeats** [comment]
build now

**Pull request merged**
