### PR TITLE
[2.20.x] DDF-5904 Adds readonly translation for USNG / DMS to Lines / Polygons

### PR DESCRIPTION
**Pull request by andrewkfiedler**
#### What does this PR do?
 - Adds a read only popup translation of USNG / MGRS to Lines and Polygons.  Similar with DMS.
 - In the future, we'll support the ability to enter coordinates in this format as well, but for now users at least need the ability to see what the translation from decimal degrees to these formats is.

#### Who is reviewing it? 
@jlcsmith 
@lifenouveau 
@stevenmalmgren 
@vinamartin 

#### How should this be tested?
Go to the basic search form and select somewhere specific.  Draw a line or polygon.  Verify that you can then click DMS or USNG and see the translation of the coordinates.  Verify that it handles incorrect inputs correctly (displays "cannot translate, please enter valid coordinates").

Do the same thing with advanced search form.

#### Any background context you want to provide?
For now the translation is read only.  In the future, we want to provide an actual editor that supports these formats.

#### What are the relevant tickets?
Fixes: #5904 

#### Screenshots
Screen Shot 2020-03-16 at 5 23 32 PM
Screen Shot 2020-03-16 at 5 23 42 PM
Screen Shot 2020-03-16 at 5 23 37 PM

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by jlcsmith** [comment]
@andrewkfiedler - getting a format build failure
```
[ERROR] - Running Format
[ERROR] ✖ 100%
[INFO]
[INFO] /projects/ddf/ui/packages/catalog-ui-search/src/main/webapp/react-component/location/conversion.tsx
[INFO] => has formatting issues
[INFO]
[INFO]
[INFO] This project uses prettier to format numerous file types.
[INFO] The files listed in yellow above did not follow the correct format.
```

**Comment by jlcsmith** [comment]
After the formatting build failure I got this lerna failure
`[INFO] $ istanbul check-coverage
[ERROR] lerna ERR! yarn run test exited 1 in 'catalog-ui-search'
[ERROR] lerna ERR! yarn run test stdout:
[ERROR] $ ace bundle --env=test
[ERROR] $ ace test
[ERROR] %cDownload the React DevTools for a better development experience: https://fb.me/react-devtools
[ERROR] You might need to use a local HTTP server (instead of file://): https://fb.me/react-devtools-faq font-weight:bold
[ERROR] Download the React DevTools and use an HTTP server (instead of a file: URL) for a better development experience: https://fb.me/react-devtools
[ERROR] MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 "pre-require" listeners added. Use emitter.setMaxListeners() to increase limit.
[ERROR]
[ERROR]
[ERROR]   1) Uncaught error outside test suite
[ERROR]
[ERROR]   0 passing (5ms)
[ERROR]   1 failing
[ERROR]
[ERROR]   1) Uncaught error outside test suite:
[ERROR]      Uncaught Error: TypeError: Cannot read property 'forEach' of undefined
[ERROR]     at Object.eval (webpack-internal:///./src/main/webapp/component/singletons/metacard-definitions.js:2015:48)
[ERROR]     at eval (webpack-internal:///./src/main/webapp/component/singletons/metacard-definitions.js:2270:30)
[ERROR]     at Object../src/main/webapp/component/singletons/metacard-definitions.js (file:///projects/ddf/ui/packages/catalog-ui-search/target/test/test.js:23718:1)
[ERROR]     at __webpack_require__ (file:///projects/ddf/ui/packages/catalog-ui-search/target/test/test.js:710:30)
[ERROR]     at fn (file:///projects/ddf/ui/packages/catalog-ui-search/target/test/test.js:95:20)
[ERROR]     at Object.eval (webpack-internal:///./src/main/webapp/js/model/QueryResponse.js:3469:51)
[ERROR]     at eval (webpack-internal:///./src/main/webapp/js/model/QueryResponse.js:4133:30)
[ERROR]     at Object../src/main/webapp/js/model/QueryResponse.js (file:///projects/ddf/ui/packages/catalog-ui-search/target/test/test.js:24149:1)
[ERROR]     at __webpack_require__ (file:///projects/ddf/ui/packages/catalog-ui-search/target/test/test.js:710:30)
[ERROR]     at fn (file:///projects/ddf/ui/packages/catalog-ui-search/target/test/test.js:95:20) (undefined:undefined)
[ERROR]   Error: Error: TypeError: Cannot read property 'forEach' of undefined
[ERROR]       at Object.eval (webpack-internal:///./src/main/webapp/component/singletons/metacard-definitions.js:2015:48)
[ERROR]       at eval (webpack-internal:///./src/main/webapp/component/singletons/metacard-definitions.js:2270:30)
[ERROR]       at Object../src/main/webapp/component/singletons/metacard-definitions.js (test.js:23718:1)
[ERROR]       at __webpack_require__ (test.js:710:30)
[ERROR]       at fn (test.js:95:20)
[ERROR]       at Object.eval (webpack-internal:///./src/main/webapp/js/model/QueryResponse.js:3469:51)
[ERROR]       at eval (webpack-internal:///./src/main/webapp/js/model/QueryResponse.js:4133:30)
[ERROR]       at Object../src/main/webapp/js/model/QueryResponse.js (test.js:24149:1)
[ERROR]       at __webpack_require__ (test.js:710:30)
[ERROR]       at fn (file:///projects/ddf/ui/packages/catalog-ui-search/target/test/test.js:95:20) (undefined:undefined)
[ERROR]       at global.onerror (eval at module.exports (webpack-internal:///../../node_modules/script-loader/addScript.js), <anonymous>:64:10)
[ERROR]       at message (<anonymous>:2:22)
[ERROR]
[ERROR]
[ERROR]
[ERROR] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[ERROR]
[ERROR] lerna ERR! yarn run test stderr:
[ERROR] Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade caniuse-lite browserslist`
[ERROR] Tests failed
[ERROR] error Command failed with exit code 1.
[ERROR]
[ERROR] lerna ERR! yarn run test exited 1 in 'catalog-ui-search'
[ERROR] error Command failed with exit code 1.`

**Comment by andrewkfiedler** [comment]
@jlcsmith should be good to build now 👍

**Comment by jlcsmith** [comment]
I'll re-hero

**Comment by jlcsmith** [comment]
Hero successful - verified point/polygons on 2D/3D map in Basic and Advanced Search.  Verified DMS/USNG/MGRS coordinates are accurate.

**Comment by andrewkfiedler** [comment]
build now

**Pull request merged**
