### PR TITLE
DDF 3512 - Adds search defaults, search interactions

### PR DESCRIPTION
**Pull request by andrewkfiedler**
#### What does this PR do?
-  Adds search defaults, search interactions

#### Who is reviewing it? 
@bdeining
@jlcsmith
@mojogitoverhere 
@mackncheesiest 

#### How should this be tested? (List steps with links to updated documentation)
Make various queries and play around with the new search interactions.

#### What are the relevant tickets?
https://codice.atlassian.net/browse/DDF-3512

#### Screenshots (if appropriate)
screen shot 2018-01-15 at 11 48 06 pm
screen shot 2018-01-15 at 11 47 52 pm
screen shot 2018-01-15 at 11 47 39 pm

### CODE REVIEW

**Comment by andrewkfiedler** [comment]
Need some help figuring out what to name the search interactions, and what icons to use.

**Comment by mojogitoverhere** [comment]
What do the `Change Forms` and `Change Settings` actions do? Also, I'd suggest renaming `Overwrite search with last known version` to `Clear unsaved changes` and `Overwrite search with defaults` to `Use default values`.

**Comment by andrewkfiedler** [comment]
The tough part with the default and last known version actions is that they currently overwrite the existing query with no way to go back barring a page refresh.  I struggled to get the wording to reflect that, but maybe it won't matter as much since we have the confirmation dialog.  We might be able to find an alternative way to do the actions in the future that's more reversible (or maybe we could expose history on workspaces / searches).

The change forms action allows you to switch between text, basic, and advanced.

The change settings action allows you to quickly access the search settings that are normally found in the sidebar.

**Comment by bdeining** [comment]
@andrewkfiedler looks like this needs a rebase

**Comment by bdeining** [comment]
@andrewkfiedler needs rebase

**Comment by bdeining** [comment]
build now

**Comment by millerw8** [comment]
I like the movement of the search types to a menu to avoid additional clicks, but it adds way too many clicks to start a query.  Can we have this start with an initial style pre-selected?  (maybe it does and I broke it in a merge...) but if it can launch with basic (or maybe text) then allow me to use that menu to change, it would improve the user experience.

**Comment by bdeining** [comment]
screen shot 2018-01-24 at 8 54 42 am
The selection of historical and archived are both selected on hover

**Comment by bdeining** [comment]
screen shot 2018-01-24 at 8 54 52 am
The edit query dialogue seems to be missing the ability to switch from advanced / basic

**Comment by bdeining** [comment]
screen shot 2018-01-24 at 9 02 53 am
The settings cog in the screenshots is not present on the actual build.  Have they been updated?

**Comment by andrewkfiedler** [comment]
@millerw8 in the future we had planned to add a default selection for what type of search the user wants (just another search preference).  I can through another commit on top of this PR to put that in if we want it earlier.

**Comment by millerw8** [comment]
@andrewkfiedler we can keep a separate ticket for letting the user select their preferred default... that would be great to have.  As long as this pops up with a system default, lets push this one forward

**Comment by mackncheesiest** [comment]
@bdeining that issue exists on master as well

**Comment by bdeining** [comment]
verified one last time, lgtm

**Pull request merged**
