### PR TITLE
DDF-04647 Fix bug preventing users from changing search forms

### PR DESCRIPTION
**Pull request by mojogitoverhere**
#### What does this PR do?
Fixes bug where users could not switch to another search form if they have a default configured

#### Who is reviewing it? 

@willwill96 @gjvera @rymach @Lambeaux 
#### Ask 2 committers to review/merge the PR and tag them here.

@bdeining
@djblue

#### How should this be tested?

- Click "Search DDF Intrigue"
- Verify text search is selected by default
- Create some new search forms
- Verify you can switch between the different search forms
- Make one of the search forms your default
- Refresh the page
- Verify the default form is now shown after clicking "Search DDF Intrigue"
- Switch to another form
- Verify the new form is correctly populated
- Run and save the search. Click the edit button (pencil) on the search and verify it is correct
- Refresh the page
- Find a search in the dropdown list and click the edit button (pencil). Verify it is still correct.
- Ensure all other search form functionality still works (search form editor, sharing, etc)

#### What are the relevant tickets?
For Jira:
[](https://codice.atlassian.net/browse/)

For GH Issues:
Fixes: #4647 

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by mojogitoverhere** [comment]
build now

**Comment by mojogitoverhere** [comment]
build now

**Comment by mojogitoverhere** [comment]
Accidentally clicked close 🤦‍♂️

**Comment by mojogitoverhere** [comment]
@gjvera found a bug that is not clear if it was introduced in this PR or not because the behavior cannot be verified on master since changing between search forms was completely broken. @djblue and I believe this should be addressed in a separate PR so I created https://github.com/codice/ddf/issues/4680

**Comment by mojogitoverhere** [comment]
build now

**Comment by gjvera** [comment]
### 🎉 Hero Successful 🎉 
Was able to switch between default search forms and other search forms 
Only thing I found was the bug that was mentioned above

LGTM

**Pull request merged**
