### PR TITLE
DDF-3372 Moved external reference logic out of FileSystemStorageProvider

### PR DESCRIPTION
**Pull request by AzGoalie**
#### What does this PR do?
@peterhuffer @emmberk 
#### Who is reviewing it? 
(please choose AT LEAST two reviewers that need to approve the PR before it can get merged)
#### Select relevant component teams: 
https://github.com/orgs/codice/teams
#### Choose 2 committers to review/merge the PR. 
(please choose ONLY two committers from below, delete the rest)
@clockard
@lessarderic
#### How should this be tested? (List steps with links to updated documentation)

1. Install DDF.
2. Setup a CDM with path of `inbox` and value of in-place monitoring. 
3. Create directory `inbox` inside of the installed ddf root directory.
4. Add any file (such as a text file).
5. Verify that you can search for it in the search ui.
6. Modify the file in the `inbox` directory.
7. Verify that the changes were ingested in the search ui.
8. Verify that there isn't a file inside the `ddf/data/content/store` directory (except for `tmp`).
9. Deleted the file in the `inbox` directory.
10. Verify that the file is deleted from the system via the search ui.

#### What are the relevant tickets?
[](https://codice.atlassian.net/browse/)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
For the general case, merging is gated on the following:

* Review by at least two contributors
* Review by at least two committers
* Successful CI
* Successful static analysis (SonarQube/Coverity/etc.)
* Heroing of change (details vary by ticket)

Certain exceptions may occur. For example, if there is a problem with the CI environment then a manually performed full build and static analysis check may be substituted _at the discretion of the repository maintainers_. Additionally, repository metadata such as this `PULL_REQUEST_TEMPLATE`, the repository `README`, and other non-functional items may be merged without requiring CI and static analysis.

Finally, an abbreviated review process may be in place for forward-port tickets immediately following branching and prior to branch divergence. In that case, approvals, CI, static analysis, and heroing that occur against the PR against the _release branch_ can be considered sufficient for reviewing the PR against the _master branch_.

Once the branches diverge, the process will return to normal.

Insofar as divergence is not a function of time but of change to the parent branch, the repository maintainers will determine when abbreviated review ends.

When abbreviated review is in effect, a note to that effect will be at the top of this template. Following is an example note:
```
##### ABBREVIATED REVIEW BETWEEN 2.12.X AND MASTER IS IN EFFECT
____

```

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by AzGoalie** [comment]
build now

**Comment by lessarderic** [comment]
The changes lgtm, but I'd like @brendan-hofmann and @rzwiefel to take a look as well since they are both familiar with the original reasons why we were creating an external file in the `FileSystemStorageProvider`.

We should also test what happens when someone ingests resources using an in-place CDM with DDF 2.10.x and upgrades to DDF 2.11.x. There may be problems retrieving those resources and their history, or problems with the resource is updated or deleted in the monitored directory, and we may need to figure out what to do in those cases.

**Comment by clockard** [comment]
Does this still work with webdav?

**Comment by AzGoalie** [comment]
This does work with WebDAV, as for the ResourceURI it will be blank and thus no resource retrieval. I am open to discussion on how we can improve this implementation. This was just a start to get a discussion going.

**Comment by lessarderic** [comment]
There's another concern here where if you ingest a NITF, you won't get a thumbnail for it. We'll need to revisit this before we can move forward.

**Pull request closed without merging**
