### PR TITLE
DDF-2505: Updated logback classic version

### PR DESCRIPTION
**Pull request by AzGoalie**
#### What does this PR do?
Updates the logback classic version to 1.1.7
#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?
@tbatie @vinamartin 
#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@lessarderic
@shaundmorris
#### How should this be tested?
Full build with tests pass.
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by vinamartin** [comment]
LGTM.

**Comment by tbatie** [comment]
Let's make sure to manually test that everything comes up properly :+1:

**Comment by AzGoalie** [comment]
It installs correctly and all apps start. Running some unit tests to make sure they work.

**Comment by AzGoalie** [comment]
This change makes unit tests more verbose. Mockito, Powermock and assertions now all log.

**Pull request merged**
