### PR TITLE
DDF-1189: updated parent pom version.

### PR DESCRIPTION
**Pull request by djblue**
[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/49)

### CODE REVIEW

**Comment by stustison** [comment]
Did you run the full build on these changes, because they shouldn't actually work until we refactor some of the things in this repo. That is why I didn't move them around earlier.

**Comment by djblue** [comment]
I ran the build locally for all the projects. It built successfully for me.

**Comment by shaundmorris** [comment]
I was testing this out with a clean repository using the PR equivalents for ddf-parent and ddf-support. Builds fine but getting checkstyle failures for TestFederation and DDFBrandingPlugin

**Comment by shaundmorris** [comment]
verified build with new checkstyle rules :+1:

**Pull request merged**
