### PR TITLE
DDF-4265 Fix feature itests

### PR DESCRIPTION
**Pull request by AzGoalie**
#### What does this PR do?
Fixes the feature itests
#### Who is reviewing it? 

@paouelle @peterhuffer 
#### Select relevant component teams: 

@codice/build 
@codice/test 
#### Ask 2 committers to review/merge the PR and tag them here.

@lessarderic
@tbatie
#### What are the relevant tickets?
[](https://codice.atlassian.net/browse/)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by AzGoalie** [comment]
build now

**Comment by tbatie** [comment]
Shouldn't the feature repository tag here https://github.com/codice/ddf/blob/master/features/kernel/src/main/feature/feature.xml#L24 be pointing to this repo instead https://github.com/codice/org.ops4j.pax.web/tree/master/pax-web-features instead? I'm confused as to how adding these dependencies will fix anything since all these artifacts are in a separate repo. What were the errors experienced?

**Comment by AzGoalie** [comment]
@paouelle Correct, they are only added as test dependencies.

**Comment by AzGoalie** [comment]
build now

**Comment by AzGoalie** [comment]
build now

**Pull request merged**
