### PR TITLE
DDF-1409: Delete commented out admin-ui tests

### PR DESCRIPTION
**Pull request by garrettfreibott**
Previous commit message stated that these tests are no longer
applicable. Another ticket was created to deal with replacing them with
mocha/chai. Right now, they use casper.

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/106)

### CODE REVIEW

**Comment by garrettfreibott** [comment]
@andrew.fiedler is the hero

**Comment by lessarderic** [comment]
Does the build still work if you delete the file? If so, I think I would delete the file and update the ticket we created to refer to the last version of the file before it was deleted. That way nobody will wonder what this is file is and why it still exists and it will help whoever picks up the new ticket have a starting point to write the tests.

**Comment by garrettfreibott** [comment]
Deleting it doesn't seem to break anything, hopefully @andrew-fiedler can verify. Went ahead and removed the file and committed it. Linked to the old file on the JIRA ticket for updatng the files.

**Comment by andrew-fiedler** [comment]
:+1: built!

**Comment by garrettfreibott** [comment]
I'm proud of you, Andrew :stuck_out_tongue:

**Pull request merged**
