### PR TITLE
DDF-04332 - Remove feature installation profiles from the installer

### PR DESCRIPTION
**Pull request by tbatie**
#### What does this PR do?
Removes the "profile selection" stage of the installer and the features composing the profile feature are added to the bootFeature section.

#### Select relevant component teams: 
@codice/core-apis 
@codice/ui 

#### How should this be tested?
Make sure installer works as expected and system boots properly.

#### What are the relevant tickets?
https://github.com/codice/ddf/issues/4332

#### Screenshots
N/A

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [X] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by tbatie** [comment]
@paouelle The profile:install command would return back 0 results when retrieving profiles from feature files. The json profile functionality is not impacted. I'm not sure what part of that command you're recommending to be reworked since its functionality isn't changing. Unless HA/migration have hard coded references to apps/profile features, I don't see how these changes will affect their functionality. Was there any particular change that indicates they will break? 

Downstream distributions will need to need no longer point to apps/profile features now. I was planning on putting those prs up.

**Comment by paouelle** [comment]
Its documentation has to be changed and I would strongly suggest we change its implementation is there is no such thing anymore as a profile feature that can be installed through it. We shouldn't just rely on the fact that its code will no longer find the profile features that no longer exist. It can be simplified. 

As for testing it, there is a difference now with how that command worked before. A Json profile was applied on top of nothing installed and at the end it would remove the admin installer bundle which no longer exist. Now, that profile will attempt to install features that is already installed (might not be an issue) and would expect features not specified not to be installed (which is no longer the case since you pre-install everything). I suspect that its functionality will no longer work as is which is why I recommend it be retested.

**Comment by tbatie** [comment]
:+1: I can remove the profile feature pulling and docs of the command.

I thought the json profiles would ensure only the features it has listed in the profile are installed and no other. If that's not the case, haven't additional bundles been installed outside of the ha profile over time as our boot features have changed? 

I'm having a hard time visualizing how these json profile definitions are maintainable if they don't have that functionality. It seems nearly impossible to ensure the expected dependencies are met without listing every single bundle expected to run. Which is also extremely fragile since they will likely break during upgrades or when new dependencies are introduced. If these profiles are expected to be maintained, they should have tests in place.

**Comment by paouelle** [comment]
@tbatie You are raising a different issue abut maintenance of the Json profiles. That is not something we should be looking into as part of this PR though.

The fact is that they are defined as a Json file which lists all the features to be installed. Anything not listed there was not being installed. This is similar to our the "apps" features were defined. Any features not listed in these "apps" features (and dependent on any listed there) were not installed. 

Fact is that for HA, which to my knowledge was the only Json profile we package although integrators may have created their own, only a subset of features should be installed.. Those not listed shouldn't even be started. This is going to change with this PR and as far as I can see, it is not a trivial change. 

If we are going to continue to support HA and the profile:install command then we need to make sure we do not break this functionality. If on the other end, a decision is made to remove that support ... then this PR becomes much simpler 😉

**Comment by austinsteffes** [comment]
Is someone taking over this PR? Just wondering what will be happening to this.

**Comment by Lambeaux** [comment]
@austinsteffes I spoke with @tbatie and I'd like to take over this work to achieve the same effect (more composable features, better feature decoupling from the top-down, etc), but I'd like to tackle it in a different order. 

Don't quite have the bandwidth to focus on bringing this PR up-to-date. I've already copied the branch onto my fork for later. Closing this for now.

**Pull request closed without merging**
