### PR TITLE
DDF-4077 Remove Standard Search UI and CometD from the codebase

### PR DESCRIPTION
**Pull request by clockard**
#### What does this PR do?
Removes Standard Search UI and CometD from the codebase. 
This reduces the distribution by ~95MB
#### Who is reviewing it? 
@peterhuffer @kcover 
#### Ask 2 committers to review/merge the PR and tag them here.

@andrewkfiedler 
@ricklarsen - Documentation
@shaundmorris
@vinamartin

#### How should this be tested?
Build and install DDF. Verify that DDF installs correctly and that there is no longer any standard search ui or cometD feature/bundle.

#### What are the relevant tickets?
[DDF-4077](https://codice.atlassian.net/browse/DDF-4077)

#### Checklist:
- [X] Documentation Updated
- [X] Update / Add Integration Tests

### CODE REVIEW

**Comment by clockard** [comment]
build now

**Comment by clockard** [comment]
build now

**Comment by clockard** [comment]
build now

**Comment by clockard** [comment]
build now

**Comment by clockard** [comment]
build now

**Comment by kcover** [comment]
Successfully Heroed ✔️

**Comment by peterhuffer** [comment]
❗️ Need to remove https://github.com/codice/ddf/blob/master/distribution/docs/src/main/resources/content/_transformers/html-metacard-xformer.adoc as well since the transformer was removed.

✏️https://github.com/codice/ddf/blob/master/distribution/docs/src/main/resources/content/_appReferences/mg-ui.adoc also has a deprecated note for the Search UI still. 

✏️ There are still a lot of phrases using `Search UI` or `Search UI App`. They still make sense in their context IMO, but `Search UI` is a pretty loaded term for some. To me it seems like we should get rid of the term `Search UI` altogether and use either `Simple Search` (not Simple Search UI) or `Intrigue`. It may even make sense to rename the `Search UI App`.

**Comment by clockard** [comment]
build now

**Pull request merged**
