### PR TITLE
[minor] turn off license header check on format

### PR DESCRIPTION
**Pull request by rymach**
turning this off until we can figure out why it's breaking for people
#### Ask 2 committers to review/merge the PR and tag them here.

@adimka
@ahoffer

#### What are the relevant tickets?
Fixes: #____

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by shaundmorris** [comment]
Is anybody actively working on figuring out why its breaking people?

**Comment by rymach** [comment]
> Is anybody actively working on figuring out why its breaking people?

I think the consensus is that it isn't worth fixing

**Comment by rymach** [comment]
ready for merge

**Comment by rymach** [comment]
build now

**Pull request merged**
