### PR TITLE
DDF-4472 Fixing a bug where DDF fails to start if the user has an empty M2

### PR DESCRIPTION
**Pull request by Kjames5269**
##### ABBREVIATED REVIEW BETWEEN 2.13.X AND MASTER IS IN EFFECT
Link to 2.13.x PR: #4386
____

#### Who is reviewing it?
@lamhuy @jhunzik 

#### Ask 2 committers to review/merge the PR and tag them here.
@millerw8 @brjeter @pklinef @vinamartin @emmberk 

#### What are the relevant tickets?
[DDF-4472](https://codice.atlassian.net/browse/DDF-4472)
#4385 

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by Kjames5269** [comment]
build now

**Comment by Kjames5269** [comment]
@millerw8 The hero steps include installing DDF, renaming their .m2 and disconnecting from the internet. I'll make sure they check that the aries/proxy/1.1.4 jar is there as well just to be sure.

**Comment by jhunzik** [comment]
Hero was successful, although we still include the old 1.1.3 .jar. Is this safe to remove or does something else rely on this version?

**Comment by Kjames5269** [comment]
@jhunzik I don't think it's worth removing, it should be fine

**Comment by rzwiefel** [comment]
@Kjames5269 Anything further needed for this PR?

**Comment by Kjames5269** [comment]
@rzwiefel Nope I was giving people time to review it and forgot about it 😅

**Pull request merged**
