### PR TITLE
DDF-3416 modified ddf-common to separate resources that needs filtering

### PR DESCRIPTION
**Pull request by paouelle**
#### What does this PR do?
This PR modified ddf-common to separate resources that doesn't require filtering to avoid issues with maven's resource plugin which tends to re-create the files (even those that doesn't require filtering) improperly by combining lines together.
#### Who is reviewing it? 
@tbatie 
@emanns95 
@figliold 
#### Select relevant component teams: 
https://github.com/orgs/codice/teams
#### Choose 2 committers to review/merge the PR. 
(please choose ONLY two committers from below, delete the rest)
@clockard
@coyotesqrl
@lessarderic
#### How should this be tested? (List steps with links to updated documentation)
Build DDF, unzip, and run to verify that it is still built properly.
#### What are the relevant tickets?
[DDF-3416](https://codice.atlassian.net/browse/DDF-3416)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests
#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by paouelle** [comment]
build now

**Comment by paouelle** [comment]
build now

**Comment by paouelle** [comment]
build now

**Comment by paouelle** [comment]
build now

**Comment by paouelle** [comment]
build now

**Comment by figliold** [comment]
Manually tested that DDF starts up correctly.

**Pull request merged**
