### PR TITLE
Ddf 2236 Update Documentation to latest release version

### PR DESCRIPTION
**Pull request by ricklarsen**
#### What does this PR do?

updates documentation to v. 2.9.1
updates javadoc to v. 2.9.1
adds link to snapshot version of documentation

#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?
@jrnorth @Lambeaux @mcalcote 
#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@jlcsmith
@shaundmorris
#### Checklist:
- [x] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by mcalcote** [comment]
So many files... How do you recommend we check this?

**Comment by ricklarsen** [comment]
Yeah, the javadoc is huge. the important changes are on the Documentation-versions.html page

Wouldn't hurt to check the version numbers on the javadoc pages as well.

**Comment by shaundmorris** [comment]
@ricklarsen it looks like on the documentation page the doc links still point to 2.9.0. Shouldn't those be 2.9.1 now? Looks like you actually the HTML and PDF versions of 2.9.0 in this PR.

**Comment by shaundmorris** [comment]
👍  Sorry @ricklarsen realized I forgot to pull the latest from your branch. 😃

**Comment by shaundmorris** [comment]
Can you do a quick update to the news and event section? Add 2.9.1 release in there.

**Comment by ricklarsen** [comment]
Will update the new & events section

**Comment by ricklarsen** [comment]
updated news & events

**Comment by shaundmorris** [comment]
Verified latest news and events, final testing on links

**Pull request merged**
