### PR TITLE
DDF-6636 adds IP and port to all audit events

### PR DESCRIPTION
**Pull request by jlcsmith**
#### What does this PR do?
Forward port of https://github.com/codice/ddf/pull/6637 and https://github.com/codice/ddf/pull/6641

#### Who is reviewing it? 
@derekwilhelm @pklinef 

#### Select relevant component teams: 
@codice/security 

#### Ask 2 committers to review/merge the PR and tag them here.
@derekwilhelm @pklinef 

#### How should this be tested?
See test steps in https://github.com/codice/ddf/pull/6637

#### Any background context you want to provide?
See https://github.com/codice/ddf/pull/6637 and https://github.com/codice/ddf/pull/6641

#### What are the relevant tickets?
Fixes: #6636 

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [X] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by jlcsmith** [comment]
build now

**Comment by derekwilhelm** [comment]
build now

**Review by clockard — APPROVED** [review]

**Comment by jlcsmith** [comment]
build now

**Comment by jlcsmith** [comment]
build now

**Comment by jlcsmith** [comment]
Verified client IP / port and thread ID included in security log.  Also verified X-FORWARDED-* headers handled correctly if present in request.

**Pull request merged**
