### PR TITLE
DDF-1475 Support SecurityUtils.getSubject() in SOAP endpoints

### PR DESCRIPTION
**Pull request by pklinef**
- Added binding the subject to the thread in PEPAuthorizingInterceptor.
- Added support in SecurityPolicyConfigurator to configure all policy
  options.
- Fixed whitelist context for SDK SOAP service in itests.
- Fixed potential NPE in search endpoint event controller.

@stustison @coyotesqrl @rzwiefel

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/155)

### CODE REVIEW

**Comment by coyotesqrl** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/SecurityPolicyConfigurator.java, line 110 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/155#-JyKr0Pe9L4ShFMhx8I4)** ([raw file](https://github.com/codice/ddf/blob/cf89acfffb141a8a0e5bd6923434977bfc777c35/distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/SecurityPolicyConfigurator.java#L110)):</sup>
Both of these need to be `containsAll`? Not a contains-any for the auth methods even?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/155)

**Comment by stustison** [comment]
lgtm

**Comment by pklinef** [comment]
Review status: 0 of 9 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/SecurityPolicyConfigurator.java, line 110 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/155#-JyKr0Pe9L4ShFMhx8I4)** ([raw file](https://github.com/codice/ddf/blob/cf89acfffb141a8a0e5bd6923434977bfc777c35/distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/SecurityPolicyConfigurator.java#L110)):</sup>
I am testing that the saved configuration is active so they both need to be containsAll.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/155)

**Comment by coyotesqrl** [comment]
:+1:

**Comment by rzwiefel** [comment]
LGTM :+1:  Built okay with PBBS and started up okay.

**Comment by rzwiefel** [comment]
:shipit:

**Comment by stustison** [comment]
lgtm

**Pull request merged**
