### PR TITLE
[2.19.x] CsvMetacardTransformer excludes binary and object attributes

### PR DESCRIPTION
**Pull request by jrnorth**
#### What does this PR do?
`CsvMetacardTransformer` now uses the same transformation logic as `CsvQueryResponseTransformer`, which correctly excludes binary and object attributes. `CsvMetacardTransformer` now also supports column sorting and hiding.

#### Who is reviewing it? 
@kcwire 
@millerw8 
@shaundmorris 

#### Select relevant component teams: 
@codice/core-apis 
@codice/io 

#### How should this be tested?
Screen Shot 2021-06-18 at 4 45 18 PM
To test the binary attribute filtering:
Upload some records with thumbnails. Search for them in Intrigue, select one or more of them and do a compressed export with CSV.
Unzip the exported file and open the CSV file(s) inside. Verify there is no `thumbnail` column.

To test the column sorting and hiding:
Use a REST client (e.g., Postman) to create a POST to `/search/catalog/internal/cql/transform/zipCompression` with the following body:
```json
{
  "searches": [
    {
      "srcs": [
        "ddf.distribution"
      ],
      "cql": "(((\"id\" ILIKE '8fac3064ac3c4caca1feead0a6431f40')))",
      "count": 1
    }
  ],
  "count": 1,
  "sorts": [
    {
      "attribute": "modified",
      "direction": "descending"
    }
  ],
  "args": {
    "columnOrder": [
      "id",
      "title"
    ],
    "columnAliasMap": {},
    "hiddenFields": [
      "title"
    ],
    "transformerId": "csv"
  }
}
```
You'll probably need to add the `X-Requested-With: XMLHttpRequest` and `Origin: https://localhost:8993` headers.
Replace the ID in the CQL with the ID of one of the metacards in your catalog. Try different sets of attributes for `columnOrder` and `hiddenFields`. `columnOrder` should determine which attributes are included in the CSV, and their order. `hiddenFields` should exclude the given attributes from the output, even if they are included in `columnOrder`.
Note: there is no way to test this in Intrigue (that I know of), since Intrigue does not support these options.

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [x] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by jrnorth** [comment]
build now

**Review by millerw8 — APPROVED** [review]

**Comment by jrnorth** [comment]
build now

**Review by shaundmorris — APPROVED** [review]

**Comment by shaundmorris** [comment]
Successfully Heroed with ingesting a metacard containing a thumbnail. The metacard was exported to CSV and the thumbnail field was not exported to the CSV. Might still need to do an object example.

**Comment by shaundmorris** [comment]
Successfully heroed testing the column order and hidden fields

**Pull request merged**
