### PR TITLE
DDF-3656 Update jpeg2000 library to latest codice version

### PR DESCRIPTION
**Pull request by clockard**
#### What does this PR do?
Update jpeg2000 library to latest codice version which has a fix for an infinite loop problem
Depends on https://github.com/codice/jai-imageio-jpeg2000/pull/3
#### Who is reviewing it? 
@emmberk @peterhuffer 

#### Choose 2 committers to review/merge the PR. 
@bdeining
@lessarderic

#### What are the relevant tickets?
[DDF-3656](https://codice.atlassian.net/browse/DDF-3656)

### CODE REVIEW

**Comment by vinamartin** [comment]
Manually verified looks good to me

**Comment by clockard** [comment]
build now

**Comment by clockard** [comment]
build now

**Comment by clockard** [comment]
yarn error
build now

**Comment by clockard** [comment]
sonarqube failed to run. 
build now

**Comment by clockard** [comment]
build now

**Comment by clockard** [comment]
yarn error
build now

**Pull request merged**
