### PR TITLE
DDF-2893 Refactor response filter to support cache-control (#1798)

### PR DESCRIPTION
**Pull request by brendan-hofmann**
#### What does this PR do?
Cherrypick of #1798 
Adds cache-control to the response filter to fix browser caching.
#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged)?
@mcalcote 
@AzGoalie 
#### Select at least one member from relevant component team(s) from below (at least one component team member needs to approve the PR).
[UI](https://github.com/orgs/codice/teams/ui)
#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@andrewkfiedler
@pklinef
#### How should this be tested? (List steps with links to updated documentation)
Install with `?dev=true` so the cert hostname matches your machine. Trust the new demo-CA in your browser. In the admin ui, verify that the platform-response module has the new cache-control configuration. Go to various pages such as admin or the catalog ui and verify that resources are shown as `cached` or `loaded from disk` instead of being fetched each time. You can check this using the network tab of the browser developer tools. Test this in Chrome and Firefox. Note that Firefox has an unrelated bug with url fragments, so it may not cache unless the url navigated to does not have a blank fragment in it.
#### What are the relevant tickets?
[DDF-2893](https://codice.atlassian.net/browse/DDF-2893)
#### Screenshots (if appropriate)
image
#### Checklist:
- [ ] Documentation Updated
- [ ] Change Log Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by brendan-hofmann** [comment]
build now

**Comment by brendan-hofmann** [comment]
build now

**Comment by emanns95** [comment]
Manually verified the changes 👍

**Comment by codymacdonald** [comment]
Manually verified 👍

**Comment by shaundmorris** [comment]
We'll keep an eye out for the un-related build failure

**Pull request merged**
