### PR TITLE
DDF-1174: Disabled JaCoCo in ddf project.

### PR DESCRIPTION
**Pull request by lessarderic**
Added a default <argLine> Maven property to pom file since JaCoCo is not configured for this project.

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/29)

### CODE REVIEW

**Comment by lessarderic** [comment]
@shaundmorris, @pklinef, can one of you guys take a quick look and merge this PR so we can go ahead and merge the ddf-parent changes and then all the PRs Andrew has worked on?

**Comment by pklinef** [comment]
Reviewed files:
- docs/pom.xml @ r2

---





Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/29)

**Comment by lessarderic** [comment]
@shaundmorris, these are the latest changes @pklinef and I worked on this morning that should get ddf to build properly without JaCoCo. Please review when you have a minute. Thanks!

**Comment by shaundmorris** [comment]
<sup>**[distribution/pom.xml, line 45 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/29#-JoAorqAWzw4vgHFMdcF)** ([raw file](https://github.com/codice/ddf/blob/03c40ef0ef676faf7047bacc8e0af4d2c831603d/distribution/pom.xml#L45)):</sup>
I believe we still need this repositories section. The Travis Build will not be able to resolve dependencies without it. Was it causing a problem?

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/29)

**Comment by shaundmorris** [comment]
<sup>**[distribution/pom.xml, line 45 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/29#-JoAorqAWzw4vgHFMdcF)** ([raw file](https://github.com/codice/ddf/blob/03c40ef0ef676faf7047bacc8e0af4d2c831603d/distribution/pom.xml#L45)):</sup>
Oh I see you moved it up to the pom.xml for the repo. I'll have to look at this a bit more...

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/29)

**Comment by lessarderic** [comment]
I'm still working on updating some of the pom files. Looks like we forgot to update some groupIds and artifactIds and that's causing builds to break when local dependencies don't exist, such as in Travis.

---





<sup>**[distribution/pom.xml, line 45 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/29#-JoAorqAWzw4vgHFMdcF)** ([raw file](https://github.com/codice/ddf/blob/03c40ef0ef676faf7047bacc8e0af4d2c831603d/distribution/pom.xml#L45)):</sup>
The org.codice.ddf:ddf pom file now inherits from ddf:ddf-parent, which has all the repositories so we shouldn't have to repeat them again.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/29)

**Comment by lessarderic** [comment]
This is forcing me to change too many pom files and causing a lot of risk that the wrong pom files/dependencies get picked up when we build and release 4.2. I'm going to roll the changes back for now and just go with the simple fix. I'll update the PR as soon as that's done.

---









Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/29)

**Pull request merged**
