### PR TITLE
DDF-1476 - Updating bounding box causes inconsistent behavior

### PR DESCRIPTION
**Pull request by EIrwin**
When using the numeric input boxes to adjust the bounding box
North and South values, the box is either removed or moved to a
unknown location on the 2d map. This was because the values are
not being treated as numeric. This was solved by ensuring they are
numeric once they are retrieved from model.

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/159)

### CODE REVIEW

**Comment by EIrwin** [comment]
@jrnorth @kcwire @kguerriero 

Hero is @jrnorth

**Comment by jrnorth** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[catalog/ui/search-ui/standard/src/main/webapp/js/model/Query.js, line 133 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/159#-JyirBMjJ7SGLbLFrdFo)** ([raw file](https://github.com/codice/ddf/blob/314da593f31f51f2dab7eb0f6a6cca46882759d8/catalog/ui/search-ui/standard/src/main/webapp/js/model/Query.js#L133)):</sup>
Can't the bounding box values be floating-point numbers? Also (and this is a nitpick), could each variable be declared + initialized in its own statement like in `modelToRectangle`? That way things are consistent.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/159)

**Comment by EIrwin** [comment]
<sup>**[catalog/ui/search-ui/standard/src/main/webapp/js/model/Query.js, line 133 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/159#-JyirBMjJ7SGLbLFrdFo)** ([raw file](https://github.com/codice/ddf/blob/314da593f31f51f2dab7eb0f6a6cca46882759d8/catalog/ui/search-ui/standard/src/main/webapp/js/model/Query.js#L133)):</sup>
I believe you are correct regarding the bounding box values being able to be floating-point.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/159)

**Comment by EIrwin** [comment]
<sup>**[catalog/ui/search-ui/standard/src/main/webapp/js/model/Query.js, line 133 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/159#-JyirBMjJ7SGLbLFrdFo)** ([raw file](https://github.com/codice/ddf/blob/314da593f31f51f2dab7eb0f6a6cca46882759d8/catalog/ui/search-ui/standard/src/main/webapp/js/model/Query.js#L133)):</sup>
Changed it to parseFloat(...) as well as changed the variable initialization to be consistent with the rest of the file.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/159)

**Comment by kcwire** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

<sup>**[catalog/ui/search-ui/standard/src/main/webapp/js/widgets/openlayers.bbox.js, line 66 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/159#-Jyj0g7eOCl7MwanYvM3)** ([raw file](https://github.com/codice/ddf/blob/b624ec7dd6d3a9ecfa6c5cd47438140d6afff474/catalog/ui/search-ui/standard/src/main/webapp/js/widgets/openlayers.bbox.js#L66)):</sup>
Wondering if this shouldn't use the projection provided from the UI configuration. Then the box may draw more appropriately if something other than EPSG:4326 is selected.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/159)

**Comment by millerw8** [comment]
<sup>**[catalog/ui/search-ui/standard/src/main/webapp/js/widgets/openlayers.bbox.js, line 66 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/159#-Jyj0g7eOCl7MwanYvM3)** ([raw file](https://github.com/codice/ddf/blob/b624ec7dd6d3a9ecfa6c5cd47438140d6afff474/catalog/ui/search-ui/standard/src/main/webapp/js/widgets/openlayers.bbox.js#L66)):</sup>
Let me do my great kcwire impression...  Great point, but not related to 1476.  Write a ticket :stuck_out_tongue: 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/159)

**Comment by wmcnalli** [comment]
:+1: 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/159)

**Comment by wmcnalli** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/159)

**Comment by millerw8** [comment]
This updates the main issue. There are seemingly other issues though.  For examples (all tests in chrome):  

1) Cesium Map: Open Search UI.  Draw a bounding box over Colorado.  Update South to 80.  This breaks Cesium with a range error.

2) Any Map: Draw a bounding box over the US.  Update the South value to 80.  Here we see two things, one, it renders with south as north and north as south, but does not flip them in the boxes.  Two, in Cesium, it renders strangely, sometimes a triangle, sometimes a mouth like shape.

3) 2d Map: Draw a bounding box over Arizona.  Change the west to be east of the east (-103).  This should result in a band wrapping all the way around the world except for New Mexico.  This works correctly in Cesium, however in 2D map the east and west are treated as if they were swapped when drawing the bounding box.

It may be that we want to close this ticket out as a success and let these more unusual cases become their own ticket.  Or it may be that we are still getting inconsistent behaviour and it needs to be fixed here.  I could be convinced either way.

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/159)

**Comment by beyelerb** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/159)

**Comment by EIrwin** [comment]
I would say that because this was already a derived fix of another ticket, that maybe this should be closed and the separate issues should be ticketed. Let me know what your guys' thoughts are so we can proceed.

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/159)

**Comment by kcwire** [comment]
I think a new ticket for these issues would be appropriate.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/159)

**Comment by kcwire** [comment]
<sup>**[catalog/ui/search-ui/standard/src/main/webapp/js/widgets/openlayers.bbox.js, line 66 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/159#-Jyj0g7eOCl7MwanYvM3)** ([raw file](https://github.com/codice/ddf/blob/b624ec7dd6d3a9ecfa6c5cd47438140d6afff474/catalog/ui/search-ui/standard/src/main/webapp/js/widgets/openlayers.bbox.js#L66)):</sup>
I'll write it up :(

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/159)

**Comment by millerw8** [comment]
That's fine.  Like I said, I could be convinced either way.  I would be 100% for calling this ticket complete and using a separate ticket if it weren't for the fact that in its current state we can get a cesium stack trace in front of the user, making a fix more urgent... but really priority shouldn't govern whether it is part of the ticket.

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/159)

**Comment by millerw8** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/159)

**Comment by jrnorth** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/159)

**Comment by kcwire** [comment]
@millerw8 review, comments, and bamboo look good. Any objections to merging?

**Comment by EIrwin** [comment]
not from my end.

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/159)

**Comment by millerw8** [comment]
all good.  merge away

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/159)

**Pull request merged**
