### PR TITLE
DDF-2017 Move registry-app under spatial and rename packages/modules …

### PR DESCRIPTION
**Pull request by clockard**
#### What does this PR do?
This PR moves the registry app and its modules from ddf/catalog/registry to ddf/catalog/spatial/registry.
This move was done because the registry uses some spatial libraries.
#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?
@gordocanchola @mcalcote 
#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@pklinef
@stustison
#### How should this be tested?
Right now the only real testing that can be done is to run the unit tests and itests.
#### Any background context you want to provide?
This change is coming from the ddf-registry repo where it was originally done under DDF-2017
All changes with the exception of one pom file are simple name/location refactoring changes.
#### What are the relevant tickets?
DDF-2017 (original work done on ddf-registry)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

…appropriately

### CODE REVIEW

**Comment by ryeats** [comment]
hero'd successfully

**Comment by clockard** [comment]
Bamboo build was successfull but ran out of memory after the build. This is why it is showing up as failed

**Comment by pklinef** [comment]
👍

**Comment by gordocanchola** [comment]
👍

**Comment by stustison** [comment]
Just skimmed it, but looks ok :+1:

**Pull request merged**
