### PR TITLE
DDF-4040 Removed unused platform/notifications module

### PR DESCRIPTION
**Pull request by kcover**
#### What does this PR do?

Removes the platform/notifications modules, which have been replaced by the persistent store and are no longer used.
 
#### Who is reviewing it? 

@peterhuffer @emmberk 

#### Ask 2 committers to review/merge the PR and tag them here.

@clockard
@coyotesqrl

#### How should this be tested?

Install ddf and make sure everything comes up correctly.

#### What are the relevant tickets?

[DDF-4040](https://codice.atlassian.net/browse/DDF-4040)

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by kcover** [comment]
build now

**Comment by kcover** [comment]
No, the notifications should still work the same. Apparently this was an initial attempt at implementing notifications but was abandoned in favor of the persistence store.

**Comment by kcover** [comment]
I looked over the docs and I don't see this notifications core specifically mentioned. @clockard is there any other reason this might require a change in the docs?

**Comment by clockard** [comment]
@kcover I did a quick scan of the docs and didn't see anything related to this code

**Comment by kcover** [comment]
build now

**Comment by kcover** [comment]
Not sure why that build failed but "Async process failed for: [/jenkins/workspace/DDF-Jobs/pr/Linux/distribution/test/itests/test-itests-ddf/target/solr/bin/solr, stop, -p, 9994]" makes me think a solr instance failed to shutdown for a itest. I'm gonna try again.
build now

**Comment by kcover** [comment]
These test have been known to fail together before. Made a ticket for it https://codice.atlassian.net/browse/DDF-4083.
build now

**Comment by kcover** [comment]
build now

**Comment by peterhuffer** [comment]
Successful hero. Monitored the logs and didn't see any errors/warning. Ingested a jpg and was able to search it.

**Comment by kcover** [comment]
I've heard recent build issues similar to the ones I've been experiencing have been resolved.
build now

**Pull request merged**
