### PR TITLE
DDF-1488 Errors encountered while processing CSW transaction requests should be handled according to the OGC specification

### PR DESCRIPTION
**Pull request by bdeining**
@millerw8 
@jrnorth is hero
@shane-voisard 
@kcwire 
@EIrwin

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/176)

### CODE REVIEW

**Comment by jrnorth** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

<sup>**[catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java, line 535 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/176#-JzMummDoKH5dNFHbm7B)** ([raw file](https://github.com/codice/ddf/blob/c15a52165abf1266fa05959a011345c7e0d316f6/catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java#L535)):</sup>
I wonder if we actually want to throw an exception and return an error report here. At this point, the insert has already happened and did not throw any exceptions. What does everyone else think?

---

<sup>**[catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java, line 610 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/176#-JzMwZcGUa5T90iFcsCK)** ([raw file](https://github.com/codice/ddf/blob/c15a52165abf1266fa05959a011345c7e0d316f6/catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java#L610)):</sup>
You can drop the (s) on record(s), since this case is responsible for handling updating a single record.

---

<sup>**[catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java, line 1327 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/176#-JzN1FqiRwdI4RpXb-1Z)** ([raw file](https://github.com/codice/ddf/blob/c15a52165abf1266fa05959a011345c7e0d316f6/catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java#L1327)):</sup>
Might want to make this a constant.

---

<sup>**[catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/TestCswEndpoint.java, line 1244 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/176#-JzN28bzbbTanM-A8oWa)** ([raw file](https://github.com/codice/ddf/blob/c15a52165abf1266fa05959a011345c7e0d316f6/catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/TestCswEndpoint.java#L1244)):</sup>
I understand the purpose of this test, but it's a bit confusing that there aren't any assertions. Maybe adding a comment would be useful.

---

<sup>**[catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/TestCswEndpoint.java, line 1251 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/176#-JzN1qJUAqogl_qN7i1n)** ([raw file](https://github.com/codice/ddf/blob/c15a52165abf1266fa05959a011345c7e0d316f6/catalog/spatial/csw/spatial-csw-endpoint/src/test/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/TestCswEndpoint.java#L1251)):</sup>
`CswConstants.CSW_OUTPUT_SCHEMA`

---

<sup>**[catalog/spatial/csw/spatial-csw-schema-bindings/src/main/resources/csw/2.0.2/CSW-discovery.xsd, line 232 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/176#-JzN42gSJXfzaY5UIY7O)** ([raw file](https://github.com/codice/ddf/blob/c15a52165abf1266fa05959a011345c7e0d316f6/catalog/spatial/csw/spatial-csw-schema-bindings/src/main/resources/csw/2.0.2/CSW-discovery.xsd#L232)):</sup>
If we're changing the schema, there should probably be a comment explaining why.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/176)

**Comment by bdeining** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

<sup>**[catalog/spatial/csw/spatial-csw-schema-bindings/src/main/resources/csw/2.0.2/CSW-discovery.xsd, line 232 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/176#-JzN42gSJXfzaY5UIY7O)** ([raw file](https://github.com/codice/ddf/blob/c15a52165abf1266fa05959a011345c7e0d316f6/catalog/spatial/csw/spatial-csw-schema-bindings/src/main/resources/csw/2.0.2/CSW-discovery.xsd#L232)):</sup>
After double-checking the OpenGIS spec, this actually doesn't need to be changed.  

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/176)

**Comment by jrnorth** [comment]
Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java, line 537 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/176#-JzX1IdV5XjiCi5UlTTe)** ([raw file](https://github.com/codice/ddf/blob/22a6ea37dfc8377ff83731f5bcbf15e4f0f19327/catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java#L537)):</sup>
It would be helpful to have the BoundingBox in the log message so we can see why it couldn't be parsed.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/176)

**Comment by jrnorth** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java, line 537 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/176#-JzX1IdV5XjiCi5UlTTe)** ([raw file](https://github.com/codice/ddf/blob/22a6ea37dfc8377ff83731f5bcbf15e4f0f19327/catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java#L537)):</sup>
The exception should be included in the log as well.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/176)

**Comment by coyotesqrl** [comment]
You should squash the commits.

---

Review status: 3 of 5 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/176)

**Comment by jrnorth** [comment]
Reviewed 1 of 2 files at r3.
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java, line 540 \[r4\]](https://reviewable.io:443/reviews/codice/ddf/176#-JzkiNHJOu_iUIc8JB8k)** ([raw file](https://github.com/codice/ddf/blob/382a0beb852d77d08993e2a70daf697f31dfadbf/catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java#L540)):</sup>
I think the correct way to call this is `LOGGER.warn("Unable to parse BoundingBox : {}", bbox, e);`. See https://github.com/codice/ddf/blob/c7704b1a402ae0e079fa32f5581de649c0aa856f/catalog/spatial/geocoding/spatial-geocoding-websearch/src/main/java/org/codice/ddf/spatial/geocoder/geonames/GeoNamesWebService.java#L64 for an example.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/176)

**Comment by bdeining** [comment]
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java, line 540 \[r4\]](https://reviewable.io:443/reviews/codice/ddf/176#-JzkiNHJOu_iUIc8JB8k)** ([raw file](https://github.com/codice/ddf/blob/382a0beb852d77d08993e2a70daf697f31dfadbf/catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java#L540)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/176)

**Comment by jrnorth** [comment]
Reviewed 1 of 2 files at r3, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswExceptionMapper.java, line 39 \[r5\]](https://reviewable.io:443/reviews/codice/ddf/176#-JzlETzelNJu0qRHvmXJ)** ([raw file](https://github.com/codice/ddf/blob/482d94658f89c3835d491c5e027db2c1bf34f0a8/catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswExceptionMapper.java#L39)):</sup>
What about using `exception.getMessage()` instead of this string? https://github.com/codice/ddf/blob/master/catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/reader/TransactionRequestConverter.java provides some detailed exception messages that may be helpful. However, I'm not sure how to handle the exception code since the spec says it can be either an invalid or missing parameter value.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/176)

**Comment by jrnorth** [comment]
Build passed. Verified that the proper exception reports are returned for invalid requests and that the `locator` attribute is included when appropriate.

**Pull request merged**
