### PR TITLE
DDF-1398 Changes default host for installer from 0.0.0.0 to localhost

### PR DESCRIPTION
**Pull request by andrew-fiedler**
- This solves the issue of certain things not working out of the box.

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/99)

### CODE REVIEW

**Comment by andrew-fiedler** [comment]
@ricklarsen, @roelens8

**Comment by wmcnalli** [comment]
:+1: 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/99)

**Comment by brendan-hofmann** [comment]
:+1:

**Comment by roelens8** [comment]
:+1: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/99)

**Comment by ricklarsen** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/99)

**Comment by shaundmorris** [comment]
Verified build and the default host during installation.

**Pull request merged**
