### PR TITLE
DDF-3029 Update broker docs to match Artemis 2.1 Jolokia call

### PR DESCRIPTION
**Pull request by harrison-tarr**
#### What does this PR do?
Fixes docs to give a working example, since we upgraded to Artemis 2.1
#### Who is reviewing it? 
@ryeats @jrnorth @roelens8 
#### Select relevant component teams: 
@codice/docs 
https://github.com/orgs/codice/teams
#### Choose 2 committers to review/merge the PR. 
(please choose ONLY two committers from below, delete the rest)
@jaymcnallie
@ricklarsen - Documentation
#### How should this be tested? (List steps with links to updated documentation)
Could try to set up two DDFs in a HA Artemis cluster 
#### Any background context you want to provide?
Artemis changed some of the mbeans in the transition from 1.X to 2.X, this bring us up to date.
#### What are the relevant tickets?
N/A
#### Checklist:
- [X] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests
#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by bdeining** [comment]
@harrison-tarr Is there an associated ticket for this?

**Comment by harrison-tarr** [comment]
@bdeining I haven't made one. I'm unsure on standard procedure for small doc fixes like this. Do they need a ticket?

**Comment by jaymcnallie** [comment]
This is just correcting a doc mistake that was merged in https://github.com/codice/ddf/pull/2075/files.  Use DDF-3029 if it needs to be tied to a ticket.

**Comment by bdeining** [comment]
Preferably we'd add `DDF-3029` to the title and commit message

**Comment by harrison-tarr** [comment]
anyone know how to edit/rebase a commit message from Github? if not i can pull it down, rebase/squash/reword and push it back up

**Comment by bdeining** [comment]
git commit --amend

**Comment by jaymcnallie** [comment]
build now

**Comment by jaymcnallie** [comment]
@harrison-tarr please backport this fix to 2.11.x

**Pull request merged**
