### PR TITLE
DDF-1869: Refactor the FilterDelegate and all classes extending it

### PR DESCRIPTION
**Pull request by tbatie**
@pklinef @coyotesqrl @ryeats @bcwaters 
@bcwaters do you mind heroing this?

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/codice/ddf/pull/531" target="_blank">ReviewNinja

**Comment by ryeats** [comment]
I was trying to find your changes 
> 348 additions, 555 deletions not shown because the diff is too large. Please use a local Git client to view these changes.

**Comment by ryeats** [comment]
:+1:

**Comment by pklinef** [comment]
I think we should add one more level for the `propertyIs*` methods.  I think all of those methods should call to a `propertyIs` method that takes an enumeration that defines the operator used.  You can already see that many of the filter delegates you changed already do something similar.

**Comment by coyotesqrl** [comment]
:+1:

**Comment by bcwaters** [comment]
Successfully hero'd
*Built and installed DDF
*Ingested metacards and queried for Dates, Integers, Doubles, Strings, and Spatial
  to ensure the FilterDelegate delegated properly.

**Pull request merged**
