### PR TITLE
[2.11.x] DDF-3372 Update WebDav to not get file when deleting

### PR DESCRIPTION
**Pull request by peterhuffer**
#### What does this PR do?
Back port of https://github.com/codice/ddf/pull/2604

#### Who is reviewing it? 
@AzGoalie @emmberk @brendan-hofmann

#### Select relevant component teams: 
https://github.com/orgs/codice/teams
#### Choose 2 committers to review/merge the PR. 
(please choose ONLY two committers from below, delete the rest)
@clockard 
@lessarderic

#### How should this be tested? (List steps with links to updated documentation)
Follow instructions in description of https://codice.atlassian.net/browse/DDF-3372, except verify the exception does not occur.

Also verify that there is no Camel NPE warning when deleting a monitored item.

#### What are the relevant tickets?
[DDF-3372](https://codice.atlassian.net/browse/DDF-3372)

#### Checklist:
- [ ] Documentation Updated
- [x] Update / Add Unit Tests
- [ ] Update / Add Integration Tests
#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by peterhuffer** [comment]
build now

**Comment by peterhuffer** [comment]
build now

**Comment by clockard** [comment]
Manually verified. :shipit:

**Comment by clockard** [comment]
Double checked the sonar lint findings and the only critical or blocking issues were pre-existing cognitive complexity issues.

**Pull request merged**
