### PR TITLE
DDF-4301 anyGeo BBox - upper-left northing field not cleared when switching shape tabs

### PR DESCRIPTION
**Pull request by samuelechu**
#### What does this PR do?
Fixes incorrect model attribute name which prevents clearing of field when switching tabs in the anyGeo component
#### Who is reviewing it? 
@Variadicism 
@Lambeaux 
@dimitry-sherman
@BernardIgiri 

#### Select relevant component teams: 
@codice/ui 

#### Ask 2 committers to review/merge the PR and tag them here.

@bdeining
@millerw8 
#### How should this be tested?
Verify that upper Left Northing field is cleared when switching tabs to/from Bounding Box in the anyGeo component.
image

#### Any background context you want to provide?
Tested switching to/from all different shapes
#### What are the relevant tickets?
[DDF-4301](https://codice.atlassian.net/browse/DDF-4301)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by andrewkfiedler** [comment]
build now

**Comment by Lambeaux** [comment]
❓ Technically, the hero was successful. Swapping between the bounding box tabs does indeed completely clear the UTM / UPS input fields. 

As an aside, I'm noticing when the user navigates **back** to the bounding box tab, and cycles through the sub types again (lat/lon, MGRS, etc) the data resurrects itself inconsistently. 

I think we need the converse behavior. Instead of clearing out the remaining field we need to keep the other fields from clearing. Also I'm noticing that clicking on a lat/lon powered sub tab will regenerate the data for other tabs using a derived format (MGRS & UTM/UPS). I wonder if, every time the bounding box tab is clicked, we should default to the left-most **Lat/Lon (DD)** sub tab to ensure consistency. 

After enough messing around, I was also able to make this error appear in the console: 
```
Uncaught Error: First and last Position are not equivalent.
    at t.exports.polygon (bundle.46ba18ae64bbd67b4ab0.js:39)
    at new e.exports (13.bundle.46ba18ae64bbd67b4ab0.js:1)
    at i.drawBorderedCircle (cesium.circle.js:135)
    at i.updatePrimitive (cesium.circle.js:112)
    at initialize (cesium.circle.js:48)
    at i.e.View (bundle.46ba18ae64bbd67b4ab0.js:39)
    at i.constructor (bundle.46ba18ae64bbd67b4ab0.js:161)
    at new i (bundle.46ba18ae64bbd67b4ab0.js:39)
    at i.show (cesium.circle.js:259)
    at i.<anonymous> (drawing.controller.js:29)
```

We might want to revisit this solution. I'm not sure what the right path forward is: 

1. Ensure the cached bounding box is destroyed like the other tabs **OR** have the other tabs preserve their state (like the bounding box tab) until the query is done being edited. 
2. Ensure clicking a top level tab (Line, Polygon, Point-Radius, Bounding Box, Keyword) always sets the initially selected sub tab (LL, MGRS, UTM, etc) to the left-most Lat/Lon option so all tabs regenerate the data correctly and consistently.

**Comment by samuelechu** [comment]
@Lambeaux it appears that the error you got might be the result of drawing a bounding box with the usng / mgrs tab, then attempting to switch to Point-Radius. The error I get has to do with open layers:
```
index.js?9c2f:88 Uncaught Error: First and last Position are not equivalent.
    at module.exports.polygon (index.js?9c2f:88)
    at new module.exports (index.js?ae8a:49)
    at child.drawBorderedPolygon (openlayers.circle.js?6cb6:133)
    at child.updateGeometry (openlayers.circle.js?6cb6:115)
    at child.initialize (openlayers.circle.js?6cb6:63)
    at child.Backbone.View (backbone.js?f0bc:1001)
    at child.constructor (backbone.marionette.js?5496:1239)
    at new child (backbone.js?f0bc:1566)
    at child.show (openlayers.circle.js?6cb6:251)
    at child.eval (drawing.controller.js?6f02:29)
```

**Comment by rzwiefel** [comment]
@samuelechu Whats the status of this?

**Comment by samuelechu** [comment]
@rzwiefel I took the ddf commit right before my https://github.com/codice/ddf/pull/3840 changes and verified that the issues found were preexisting behavior. Preexisting behavior/issues:
https://codice.atlassian.net/browse/DDF-4303
https://codice.atlassian.net/browse/DDF-4257
@Lambeaux's finding on regenerating data is also present in the version of ddf right before the UPS changes were brought in. I think that fixing these issues would be out of scope for this ticket.

**Pull request merged**
