### PR TITLE
DDF-4084 Intrigue fails to find results with Websockets enabled

### PR DESCRIPTION
**Pull request by Corey-Collins**
#### What does this PR do?
This is a bug fix for intrigue failing to find results when websockets are enabled. In a previous commit a `@JsonIgnore` annotation was added to the CqlQueryResponse class. Several classes use Boon to deserialize the response, but they need to specify that they include annotations. Since the JsonRpc mapper didn't include annotations the json failed to deserialize causing the `/wc` endpoint to fail.
#### Who is reviewing it? 
@bellcc 
@leo-sakh 
@peterhuffer 
@Schachte 

#### Select relevant component teams: 
https://github.com/orgs/codice/teams
#### Ask 2 committers to review/merge the PR and tag them here.

@bdeining
@millerw8
#### How should this be tested?
- Make sure websockets are enabled (System > Catalog Search UI)
- Inject one or more metacards and run a search query through intrigue, confirming that the metacards are found.

#### What are the relevant tickets?
[DDF-4048](https://codice.atlassian.net/browse/DDF-4084)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by bdeining** [comment]
build now

**Comment by Corey-Collins** [comment]
build now

**Comment by bdeining** [comment]
successfully hero'd

**Comment by Corey-Collins** [comment]
build now

**Pull request merged**
