### PR TITLE
[2.26.x] Query metrics update

### PR DESCRIPTION
**Pull request by zkirksey**
#### What does this PR do?
Separates query metrics into own log file and removes a few redundant logs. This new log file will be `query_metrics.log`.

#### Who is reviewing it?
@jlcsmith

#### Select relevant component teams: 
@codice/solr

#### Ask 2 committers to review/merge the PR and tag them here.
@jlcsmith 

#### How should this be tested?
1. Start DDF
2. Run `log:set DEBUG queryLogger`
3. Run a few queries
4. Verify the query metrics were logged in `query_metrics.log` and not in `ddf.log`

#### Any background context you want to provide?
Refer to #6763 for original metrics changes.

#### What are the relevant tickets?
Fixes: #____

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Review by jlcsmith — APPROVED** [review]

**Comment by jlcsmith** [comment]
build now

**Review by stustison — APPROVED** [review]

**Review by derekwilhelm — APPROVED** [review]

**Review by beyelerb — APPROVED** [review]

**Comment by alexabird** [comment]
build now

**Comment by alexabird** [comment]
build now

**Comment by zkirksey** [comment]
build now

**Comment by zkirksey** [comment]
build now

**Pull request merged**
