### PR TITLE
DDF-1650 added slider and dependencies to make slider available to th…

### PR DESCRIPTION
**Pull request by wmcnalli**
…e datetimepicker widget in the query view

@bdeining HERO!
@millerw8 
@shane-voisard 

image

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/341)

### CODE REVIEW

**Comment by bdeining** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/341)

**Comment by jlcsmith** [comment]
Nice improvement over the time drop down selections.  LGTM

**Comment by millerw8** [comment]
I see if slider is included it becomes the default.  And you cleaned up the dependency tree by taking advantage of transitive dependencies.  lgtm


---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/341)

**Comment by wmcnalli** [comment]
@millerw8 full disclosure - I think I hit the NOW button before that screenshot.  The date defaults to system current but the hour and minute sliders start at 0.  I'll take a quick look at the options and see if it's easy to default to current time.

**Comment by bdeining** [comment]
PR builds successfully.  Verified expected behavior by ingesting metacards and performing various temporal queries that fall inside and outside the time of ingestion.  Additionally verified by inspecting the query (ddf.catalog) in the logs.  LGTM.


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/341)

**Comment by shane-voisard** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/341)

**Comment by michaelmenousek** [comment]
the light grey color is off but we can deal with that later.

**Pull request merged**
