### PR TITLE
DDF-1876: consolidated all documentation into distribution/docs

### PR DESCRIPTION
**Pull request by ricklarsen**
#### What does this PR do?
Consolidates all documentation into the distribution/docs module.

#### Who is reviewing it?
@mcalcote @brianfelix @vinamartin @gordocanchola @clockard @stustison @pklinef @shaundmorris 

#### Choose 2 committers to review/merge the PR.

@shaundmorris
@stustison 
#### How should this be tested?
* successful build
* no 'unresolved directives' errors in finished documentation

#### Checklist:
- [x] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by pklinef** [comment]
What are the files in the root of the `_contents` folder?  Are those the distribution contents?  Should we group those into a folder?

**Comment by pklinef** [comment]
Is there a plan to put content into the readme in the distribution/docs project?  It currently just has a header that says temp.

**Comment by ricklarsen** [comment]
Yes, the files in `_content` are the distribution or system-wide documentation. They can certainly be put into folders. 

Possible uses for the README could be a general outline for how the documentation is organized (modeled on the introduction section, maybe), instructions for contributing, or something else... Or, maybe it's not needed at all.

**Comment by shaundmorris** [comment]
successfully built this PR

**Comment by shaundmorris** [comment]
Another successful build after final rebase.

**Pull request merged**
