### PR TITLE
DDF-1211: Draft of WSS security documentation.

### PR DESCRIPTION
**Pull request by ricklarsen**
@stustison @shaundmorris

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/38)

### CODE REVIEW

**Comment by shaundmorris** [comment]
Overall I like the new diagrams as they communicate and support the text much more than what we had before. I also like the changes associated with the managing vs extending in the documentation. So should clarify what is more at the code level vs what an administrator would be most interested in for configuration purposes.

---

Review status: all files reviewed, 1 unresolved discussion, some commit checks failed.
Reviewed files:
- docs/src/main/resources/Extending.adoc @ r1
- docs/src/main/resources/Managing.adoc @ r1

---

<sup>**[docs/src/main/resources/Extending.adoc, line 2654 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/38#-JqkcpBt2rSVxwWehO1z)** ([raw file](https://github.com/codice/ddf/blob/a37a10f09678674ce1a1f840ab1d3819ca8e32ab/docs/src/main/resources/Extending.adoc#L2654)):</sup>
Like the new diagrams like this one.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/38)

**Comment by stustison** [comment]
Review status: all files reviewed, 9 unresolved discussions, some commit checks failed.

---

<sup>**[docs/src/main/resources/Extending.adoc, line 865 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/38#-Jqkcg-sVefumkQLrxTb)** ([raw file](https://github.com/codice/ddf/blob/a37a10f09678674ce1a1f840ab1d3819ca8e32ab/docs/src/main/resources/Extending.adoc#L865)):</sup>
We should probably make the distinction here that this is the REST security architecture and only applies for REST calls. SOAP goes through a different path. It looks like we have a "Securing SOAP" header down below. We should probably have a "Securing REST" header up here somewhere.

---

<sup>**[docs/src/main/resources/Extending.adoc, line 1003 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/38#-JqkdaC3Dy6nKKIwsZZA)** ([raw file](https://github.com/codice/ddf/blob/a37a10f09678674ce1a1f840ab1d3819ca8e32ab/docs/src/main/resources/Extending.adoc#L1003)):</sup>
We should point them to https://localhost:8993 as http is now disabled. Lets also point them at /admin instead of /system/console. I would rather that people start getting familiar with that UI since the system console UI will be going away.

---

<sup>**[docs/src/main/resources/Extending.adoc, line 1077 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/38#-JqkeLzoUhFO9eoG5ulD)** ([raw file](https://github.com/codice/ddf/blob/a37a10f09678674ce1a1f840ab1d3819ca8e32ab/docs/src/main/resources/Extending.adoc#L1077)):</sup>
We should just say that the STS Server sends an assertion back to the requestor, rather than the login filter. Since it is used in both the SOAP and REST cases.

---

<sup>**[docs/src/main/resources/Extending.adoc, line 1106 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/38#-JqkehjvmG9JI0Ibbhp7)** ([raw file](https://github.com/codice/ddf/blob/a37a10f09678674ce1a1f840ab1d3819ca8e32ab/docs/src/main/resources/Extending.adoc#L1106)):</sup>
Lets use subject here instead of principal, since we seem to be using subject everywhere else.

---

<sup>**[docs/src/main/resources/Extending.adoc, line 2667 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/38#-Jqkgp2OFHasvO3lzjFb)** ([raw file](https://github.com/codice/ddf/blob/a37a10f09678674ce1a1f840ab1d3819ca8e32ab/docs/src/main/resources/Extending.adoc#L2667)):</sup>
We're missing a bit here on the SOAP Secure Client. It first does a call to retrieve the WSDL, which is shown, and then after that it makes a call out to the STS itself. The only time anything goes through the STS Realm on the SOAP side is when you have a Dumb SOAP client making a request. The Anonymous Interceptor will request an anonymous assertion to use on behalf of that request and it will do it through the same basic path that the REST architecture uses.

---

<sup>**[docs/src/main/resources/Extending.adoc, line 2705 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/38#-JqkhMBMetuWv_CybT9q)** ([raw file](https://github.com/codice/ddf/blob/a37a10f09678674ce1a1f840ab1d3819ca8e32ab/docs/src/main/resources/Extending.adoc#L2705)):</sup>
Looks like we have the right info here, we just need it reflected on the graphic.

---

<sup>**[docs/src/main/resources/Managing.adoc, line 1558 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/38#-Jqkhf8HTH3H7DJcLT3t)** ([raw file](https://github.com/codice/ddf/blob/a37a10f09678674ce1a1f840ab1d3819ca8e32ab/docs/src/main/resources/Managing.adoc#L1558)):</sup>
We should also note here that we do not recommend that anyone uses the default LDAP provided with DDF for production use. This is only really here for development purposes or extremely small server loads. They should be deploying their own LDAP server for an actual user facing deployment.

---

<sup>**[docs/src/main/resources/Managing.adoc, line 1595 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/38#-JqkhyeqUVo2ATuB0umg)** ([raw file](https://github.com/codice/ddf/blob/a37a10f09678674ce1a1f840ab1d3819ca8e32ab/docs/src/main/resources/Managing.adoc#L1595)):</sup>
Jaav -> Java

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/38)

**Comment by clockard** [comment]
Review status: all files reviewed, 12 unresolved discussions, some commit checks failed.

---

<sup>**[docs/src/main/resources/Extending.adoc, line 757 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/38#-JqkZF4pBnpFH-6jP2EP)** ([raw file](https://github.com/codice/ddf/blob/a37a10f09678674ce1a1f840ab1d3819ca8e32ab/docs/src/main/resources/Extending.adoc#L757)):</sup>
Should this be "how all of the pieces work together and where they are located within the system"

---

<sup>**[docs/src/main/resources/Extending.adoc, line 834 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/38#-Jqk_w41wLfmiLC_WWnz)** ([raw file](https://github.com/codice/ddf/blob/a37a10f09678674ce1a1f840ab1d3819ca8e32ab/docs/src/main/resources/Extending.adoc#L834)):</sup>
Should STS be spelled out since we haven't seen it yet in this document?

---

<sup>**[docs/src/main/resources/Extending.adoc, line 1101 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/38#-JqklXGkwX0QWNmB15o3)** ([raw file](https://github.com/codice/ddf/blob/a37a10f09678674ce1a1f840ab1d3819ca8e32ab/docs/src/main/resources/Extending.adoc#L1101)):</sup>
more claims?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/38)

**Comment by clockard** [comment]
Review status: all files reviewed, 12 unresolved discussions, some commit checks failed.

---

<sup>**[docs/src/main/resources/Managing.adoc, line 1450 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/38#-JqkwLsNZV0LMmC0TJDn)** ([raw file](https://github.com/codice/ddf/blob/a37a10f09678674ce1a1f840ab1d3819ca8e32ab/docs/src/main/resources/Managing.adoc#L1450)):</sup>
This section is using <FQDN> and not ddf for the host name

---

<sup>**[docs/src/main/resources/Managing.adoc, line 2083 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/38#-JqkvQTY1fg5zPbSSSAt)** ([raw file](https://github.com/codice/ddf/blob/a37a10f09678674ce1a1f840ab1d3819ca8e32ab/docs/src/main/resources/Managing.adoc#L2083)):</sup>
This section seem to be almost the same as the Configuring WSS Security section. Can we collapse it into one section?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/38)

**Comment by shaundmorris** [comment]
Review status: all files reviewed, 12 unresolved discussions, some commit checks failed.

---

<sup>**[docs/src/main/resources/Extending.adoc, line 757 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/38#-JqkZF4pBnpFH-6jP2EP)** ([raw file](https://github.com/codice/ddf/blob/a37a10f09678674ce1a1f840ab1d3819ca8e32ab/docs/src/main/resources/Extending.adoc#L757)):</sup>
:+1: 

---

<sup>**[docs/src/main/resources/Extending.adoc, line 834 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/38#-Jqk_w41wLfmiLC_WWnz)** ([raw file](https://github.com/codice/ddf/blob/a37a10f09678674ce1a1f840ab1d3819ca8e32ab/docs/src/main/resources/Extending.adoc#L834)):</sup>
:+1: 

---

<sup>**[docs/src/main/resources/Extending.adoc, line 865 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/38#-Jqkcg-sVefumkQLrxTb)** ([raw file](https://github.com/codice/ddf/blob/a37a10f09678674ce1a1f840ab1d3819ca8e32ab/docs/src/main/resources/Extending.adoc#L865)):</sup>
Added Securing REST

---

<sup>**[docs/src/main/resources/Extending.adoc, line 1003 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/38#-JqkdaC3Dy6nKKIwsZZA)** ([raw file](https://github.com/codice/ddf/blob/a37a10f09678674ce1a1f840ab1d3819ca8e32ab/docs/src/main/resources/Extending.adoc#L1003)):</sup>
:+1: 

---

<sup>**[docs/src/main/resources/Extending.adoc, line 1077 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/38#-JqkeLzoUhFO9eoG5ulD)** ([raw file](https://github.com/codice/ddf/blob/a37a10f09678674ce1a1f840ab1d3819ca8e32ab/docs/src/main/resources/Extending.adoc#L1077)):</sup>
changed

---

<sup>**[docs/src/main/resources/Extending.adoc, line 1101 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/38#-JqklXGkwX0QWNmB15o3)** ([raw file](https://github.com/codice/ddf/blob/a37a10f09678674ce1a1f840ab1d3819ca8e32ab/docs/src/main/resources/Extending.adoc#L1101)):</sup>
fixed

---

<sup>**[docs/src/main/resources/Extending.adoc, line 1106 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/38#-JqkehjvmG9JI0Ibbhp7)** ([raw file](https://github.com/codice/ddf/blob/a37a10f09678674ce1a1f840ab1d3819ca8e32ab/docs/src/main/resources/Extending.adoc#L1106)):</sup>
changed

---

<sup>**[docs/src/main/resources/Extending.adoc, line 2667 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/38#-Jqkgp2OFHasvO3lzjFb)** ([raw file](https://github.com/codice/ddf/blob/a37a10f09678674ce1a1f840ab1d3819ca8e32ab/docs/src/main/resources/Extending.adoc#L2667)):</sup>
Updated

---

<sup>**[docs/src/main/resources/Managing.adoc, line 1558 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/38#-Jqkhf8HTH3H7DJcLT3t)** ([raw file](https://github.com/codice/ddf/blob/a37a10f09678674ce1a1f840ab1d3819ca8e32ab/docs/src/main/resources/Managing.adoc#L1558)):</sup>
updated

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/38)

**Comment by ricklarsen** [comment]
Review status: all files reviewed, 12 unresolved discussions, some commit checks failed.

---

<sup>**[docs/src/main/resources/Managing.adoc, line 1595 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/38#-JqkhyeqUVo2ATuB0umg)** ([raw file](https://github.com/codice/ddf/blob/a37a10f09678674ce1a1f840ab1d3819ca8e32ab/docs/src/main/resources/Managing.adoc#L1595)):</sup>
fixed.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/38)

**Pull request merged**
