### PR TITLE
DDF-2407 use system user to install apps through the ApplicationConfigInstaller

### PR DESCRIPTION
**Pull request by ryeats**
#### What does this PR do?
give the ApplicationConfigInstaller the permissions it needs to install apps
#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?
@tbatie @adimka 
#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@coyotesqrl
@shaundmorris

#### How should this be tested?
unzip drop this file in and remove the .txt then start the ddf and verify that solr-app, catalog-app, and spatial-app are installed
[org.codice.ddf.admin.applicationlist.properties.txt](https://github.com/codice/ddf/files/425996/org.codice.ddf.admin.applicationlist.properties.txt)

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by ryeats** [comment]
I think this should be backported

**Comment by coyotesqrl** [comment]
👍 

And I agree that it should be backported. @stustison, what's your take on that?

**Comment by stustison** [comment]
Agree. Backport.

**Comment by shaundmorris** [comment]
👍

**Comment by adimka** [comment]
Hero'd 👍

**Pull request merged**
