### PR TITLE
DDF-1571 Removed @Ignore annotation related to this ticket

### PR DESCRIPTION
**Pull request by josephthweatt**
#### What does this PR do?
I just saw an @Ignore annotation that was waiting for an old ticket to be addressed (which it has been)

#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged)?
@clockard 
#### Select at least one member from relevant component team(s) from below (at least one component team member needs to approve the PR).
[Core APIs](https://github.com/orgs/codice/teams/core-apis)
#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@clockard 
#### How should this be tested? (List steps with links to updated documentation)
Test the method with the deleted @Ignore 

#### What are the relevant tickets?
[DDF-1571](https://codice.atlassian.net/browse/)
#### Checklist:
- [ ] Documentation Updated
- [ ] Change Log Updated
- [X] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by coyotesqrl** [comment]
I see that ticket is unassigned and open. If, as it appears, this issue has been OBE, the ticket should be closed as well.

**Comment by josephthweatt** [comment]
@coyotesqrl  Weird, I was looking at this merged PR which addressed the ticket: https://github.com/codice/ddf/pull/264

**Comment by coyotesqrl** [comment]
It does address it, by adding the ignored test; however, that PR did not resolve the issue. If the issue is now resolved and this test passes, then that ticket can be marked OBE and closed. Let's confirm it is resolved, of course.

**Comment by josephthweatt** [comment]
Alright, I'm running TestConfiguration again to make sure everything runs.

**Comment by josephthweatt** [comment]
Okay, oddly enough there are problems running the test. I had tested this last night and I didn't have any problem, though, so idk.

**Pull request closed without merging**
