### PR TITLE
DDF-05062 Adding permissions for Log4j2 to the default.policy file

### LINKED ISSUE #5062: Access control exception on log4j2.config.xml when a user goes through the hardening guide
### Description
During system hardening there's an Access Control exception that gets thrown when trying to read log4j2.config.xml.

Current workaround is to add the following to configurations.policy
```
grant codeBase "file:/pax-logging-log4j2" {
    permission java.io.FilePermission "${ddf.home.perm}etc${/}log4j2.config.xml", "read, write";
}
```

### Steps to Reproduce
1. Follow the steps in the hardening guide about log4j log rollover. 

#### Expected behavior :
There is not an exception.

#### Actual behavior:
There's an exception that gets thrown.

### Affects versions
master, 2.13.x, 2.14

### PR DESCRIPTION
**Pull request by Kjames5269**
#### What does this PR do?
Fixes an Access control exception encountered when hardening the system.

#### Select relevant component teams: 
@codice/security 
#### Ask 2 committers to review/merge the PR and tag them here.

@brjeter 
@garrettfreibott
@austinsteffes 
@tyler30clemens 

#### How should this be tested?

1. Build DDF:
2. edit <DDF_HOME>/etc/org.ops4j.pax.logging.cfg
3. Find the following line for log4j2: `"org.ops4j.pax.logging.log4j2.config.file = ${karaf.etc}/log4j2.xml"`,
uncomment it **AND** change it to `"org.ops4j.pax.logging.log4j2.config.file = ${karaf.etc}/log4j2.config.xml"`
4. delete all subsequent lines
5. Start DDF and experience no access control exceptions.

#### What are the relevant tickets?
Will fix #5062 the 2.16.x branch

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by Kjames5269** [comment]
build now

**Comment by brjeter** [comment]
The build got stuck in itests.
build now

**Comment by brjeter** [comment]
build now

**Comment by tyler30clemens** [comment]
Reading step 3 and the docs as well, would it better to change the `org.ops4j.pax.logging.log4j2.config.file = ${karaf.etc}/log4j2.xml` to `org.ops4j.pax.logging.log4j2.config.file = ${karaf.etc}/log4j2.config.xml` in the org.ops4j.pax.logging.cfg file? This way it is consistent with the documentation and saves the user from confusion and having to change it themselves.

**Comment by Kjames5269** [comment]
@tyler30clemens the .config.xml file is used in a downstream project, maybe there's an argument to be made for consistency though 🤔

**Comment by Kjames5269** [comment]
Closing this PR, the external documentation was out of date to the change made by #3609

**Pull request closed without merging**
