### PR TITLE
DDF-1197 created an HTTP to HTTPS proxy to use for legacy clients

### PR DESCRIPTION
**Pull request by stustison**
- added new HTTP to HTTPS camel proxy service
 - added integration test for anonymous SOAP HTTP access
 - disabled HTTP in pax web configuration file

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/35)

### CODE REVIEW

**Comment by stustison** [comment]
@pklinef @lessarderic

**Comment by stustison** [comment]
@shaundmorris

**Comment by lessarderic** [comment]
Review status: all files reviewed, all discussions resolved, some commit checks failed.
Reviewed files:
- distribution/ddf-common/src/main/resources/etc/org.ops4j.pax.web.cfg @ r1
- test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/AbstractIntegrationTest.java @ r1
- test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSecurity.java @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/35)

**Comment by pklinef** [comment]
Review status: all files reviewed, 1 unresolved discussion, some commit checks failed.

---

<sup>**[test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSecurity.java, line 203 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/35#-Jpo14Butny8Hp80Jdn1)** ([raw file](https://github.com/codice/ddf/blob/cbf3e7835c71044f044e56a92dfaeda7cab3f8b7/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSecurity.java#L203)):</sup>
I would suggest moving this into the startFeature method.  I can't think of too many cases when someone would want to start features but then do something before they are ready.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/35)

**Comment by pklinef** [comment]
:+1:

**Comment by stustison** [comment]
Review status: all files reviewed, 1 unresolved discussion, some commit checks failed.

---

<sup>**[test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSecurity.java, line 203 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/35#-Jpo14Butny8Hp80Jdn1)** ([raw file](https://github.com/codice/ddf/blob/cbf3e7835c71044f044e56a92dfaeda7cab3f8b7/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSecurity.java#L203)):</sup>
Sounds good.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/35)

**Comment by lessarderic** [comment]
Review status: all files reviewed, 1 unresolved discussion, some commit checks failed.
Reviewed files:
- test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/AbstractIntegrationTest.java @ r2
- test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSecurity.java @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/35)

**Pull request merged**
