### PR TITLE
DDF 2846 Remove version range from package.json for web apps

### PR DESCRIPTION
**Pull request by mweser**
#### What does this PR do?
Removes version range markings in package.json files and includes the updated yarn.lock files.

#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged)?
@ahoffer @AzGoalie @emanns95 @djblue 

#### Select at least one member from relevant component team(s) from below (at least one component team member needs to approve the PR).
[Build](https://github.com/orgs/codice/teams/build)

#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@pklinef
@stustison

#### How should this be tested? (List steps with links to updated documentation)
Run full build, then verify that catalog ui and log viewer works.

#### Any background context you want to provide?
Important for ensuring control over the version used for each dependency.

#### What are the relevant tickets?
[](https://codice.atlassian.net/browse/DDF-2846)

#### Checklist:
- [ ] Documentation Updated
- [ ] Change Log Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by pklinef** [comment]
This change should be backported to 2.10.x.

**Comment by mweser** [comment]
Passed manual build.

**Comment by mweser** [comment]
Good to merge?

**Comment by mweser** [comment]
Passes full local swarm build.

**Pull request merged**
