### PR TITLE
DDF-1670: removed incorrect include statement in Managing documentation.

### PR DESCRIPTION
**Pull request by ricklarsen**
Including config.adoc[] files only work at head of file.

@pklinef @vinamartin @djblue @stustison @clockard

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/codice/ddf/pull/349" target="_blank">ReviewNinja

**Comment by ricklarsen** [comment]
Updated my comment above for clarity.

**Comment by pklinef** [comment]
Does ManContents.adoc need the config file included at the top?  Looks like you completely removed it.

**Comment by ricklarsen** [comment]
No, this file only exists to be included in Managing.adoc and the Omnibus. Both of them have the include in the correct place.

**Comment by pklinef** [comment]
:+1:

**Comment by vinamartin** [comment]
:+1:

**Comment by clockard** [comment]
:+1:

**Comment by clockard** [comment]
Build documentation and verified that there were no "unresolved" imports in the omnibus document

**Comment by djblue** [comment]
:+1:

**Pull request merged**
