### PR TITLE
DDF-2324 The DDF Registry-App now stops when the user deactivates it

### PR DESCRIPTION
**Pull request by mcalcote**
#### What does this PR do?

The DDF Registry-App successfullly uninstalls when stopping it from the DDF Admin UI.

#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?
@clockard @gordocanchola @vinamartin @brianfelix @ani6gup 

#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@kcwire
@shaundmorris

#### How should this be tested?
Install Registry-App in Admin UI, then stop it

#### Any background context you want to provide?
On a fresh install, attempting to deactivate the DDF Registry-App resulted in the message "An application failed to stop".

The following would be present in the stacktrace:
09:48:33,717 | WARN  | tp1116445361-164 | tion.service.impl.ApplicationServiceBean  336 | dmin-core-appservice | Application registry-app was not successfully stopped.
org.codice.ddf.admin.application.service.ApplicationServiceException: java.lang.IllegalArgumentException: Feature named 'registry-core-api/2.10.0.SNAPSHOT' is not installed

In karaf the issue was traced down to the FeaturesServiceImpl uninstallFeatures method where the state was collecting all the running features, but then narrowing that list down to a “required” subset. It would then only succeed in uninstalling if each of the features were in that required subset.

According to the existing registry-app feature file, the two features that were set to install=“auto” were listed as required when using feature:list in the ddf console and came up in that “required” subset, so it would fail when the system tried to uninstall the third, “manual”, feature (registry-core-api).

This has now been changed.

#### What are the relevant tickets?
DDF-2324 The DDF Registry-App should stop when the user deactivates it.

#### Screenshots (if appropriate)
ddf2324

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by shaundmorris** [comment]
👍

**Comment by shaundmorris** [comment]
@mcalcote this should be back ported as well

**Comment by kcwire** [comment]
👍

**Comment by bcwaters** [comment]
Successfully hero'd
👍

**Pull request merged**
