### PR TITLE
DDF-5838 removed WFS 1.0.0

### PR DESCRIPTION
**Pull request by shaundmorris**
#### What does this PR do?
Removes WFS 1.0.0

#### Who is reviewing it? 

@ricklarsen 
@jrnorth 

#### Select relevant component teams: 
@codice/build 
@codice/continuous-integration 
@codice/io 
@codice/ogc 
@codice/test 

#### Ask 2 committers to review/merge the PR and tag them here.
@bdeining 

#### What are the relevant tickets?
Fixes: #5838 

#### Checklist:
- [X] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

---
This change is [Reviewable](https://reviewable.io/reviews/codice/ddf/5842)

### CODE REVIEW

**Comment by shaundmorris** [comment]
build now

**Comment by jrnorth** [comment]
There are probably some references to WFS 1.0.0 bundles in the security policy files that we should remove too.

**Comment by shaundmorris** [comment]
> There are probably some references to WFS 1.0.0 bundles in the security policy files that we should remove too.

Good point, must not have come up on my search for some reason I'll go check that out. Thanks!

**Comment by shaundmorris** [comment]
build now

**Pull request merged**
