### PR TITLE
DDF-1359 - updated CswSource to replace resource-uri with resource-do…

### PR DESCRIPTION
**Pull request by kcwire**
…wnload-url when available. Also, only use the UrlResourceReader by default.

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/134)

### CODE REVIEW

**Comment by kcwire** [comment]
@millerw8 @jlcsmith @wmcnalli @beyelerb @emanns95 @kguerriero @shane-voisard @bdeining

@jrnorth is hero

**Comment by jrnorth** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[catalog/opensearch/catalog-opensearch-source/src/main/java/ddf/catalog/source/opensearch/OpenSearchSource.java, line 718 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/134#-JxjqsqlBnjqeTbdQPYt)** ([raw file](https://github.com/codice/ddf/blob/393d919ec377d42d0768a4fffde4321e1e01bd38/catalog/opensearch/catalog-opensearch-source/src/main/java/ddf/catalog/source/opensearch/OpenSearchSource.java#L718)):</sup>
Is there a reason why we were checking whether restClient is null? Could it still be null here?

---

<sup>**[catalog/spatial/csw/spatial-csw-source/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/source/CswSource.java, line 982 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/134#-JxHVhNFJuyFXRVYWSTw)** ([raw file](https://github.com/codice/ddf/blob/393d919ec377d42d0768a4fffde4321e1e01bd38/catalog/spatial/csw/spatial-csw-source/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/source/CswSource.java#L982)):</sup>
tranformedMetacard

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/134)

**Comment by jrnorth** [comment]
Build passed. Confirmed that product retrieval works when federating via CSW using the DDF metacard output schema.

**Comment by jlcsmith** [comment]
Reviewed 7 of 14 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/134)

**Pull request merged**
