### PR TITLE
DDF-4118 When rerunning a query from the search ui, it will reset the pagnation

### PR DESCRIPTION
**Pull request by AzGoalie**
##### ABBREVIATED REVIEW BETWEEN 2.13.X AND MASTER IS IN EFFECT
Link to 2.13.x PR: #3705 
____

#### What does this PR do?
When rerunning a query from the search ui it will reset the pagnation to show the first result.
#### Who is reviewing it? 

@Bdthomson @hayleynorton 
#### Select relevant component teams: 
https://github.com/orgs/codice/teams/ui
#### Ask 2 committers to review/merge the PR and tag them here.

@andrewkfiedler
@djblue
@figliold
#### How should this be tested?
1. Build and install DDF
2. Ingest a large amount of data (250+). Ex reuters xml data set.
3. Create a query and search.
4. Click the >> button to go to the end of the current result set.
5. Click the more button to get to the next page.
6. Rerun the query and verify that the results start off at 1-25.

#### What are the relevant tickets?
[DDF-4118](https://codice.atlassian.net/browse/DDF-4118)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by AzGoalie** [comment]
Created 2.13.x PR: https://github.com/codice/ddf/pull/3705

**Comment by Bdthomson** [comment]
build now

**Comment by AzGoalie** [comment]
build now

**Comment by peterhuffer** [comment]
Successful hero following the listed steps 👍

**Comment by Bdthomson** [comment]
build now please

**Pull request merged**
