### PR TITLE
[2.19.x] DDF-UI-399 Exception occur for anyGeo Search with no Location selected

### PR DESCRIPTION
**Pull request by abel-connexta**
ddf-ui PRs:
3.4.x codice/ddf-ui#400

---------------------
#### What does this PR do?
When try to save or perform a search with anyGeo that has no location selected, an exception occurs.

#### Who is reviewing it? 

@andrewzimmer 
@hayleynorton
@cassandrabailey293 
@zta6 

#### Ask 2 committers to review/merge the PR and tag them here.
@bdeining 
@mojogitoverhere 

#### How should this be tested?

- Build/install

1.	Open 'Workspaces' via the main menu ('hamburger') button
2.	Open Existing Workspace or click ‘New Workspace’
3.	Click on 'Search DDF Intrigue' or 'Create a Search'
4.	Click ellipse menu and click on 'Advanced Search'
5.	Select the 'anyGeo' (note - Do not select any locations, should have 'Select Location Option' already selected)
6.	Pull up and clear inspector console log
7.	Click Search
8.	Ensure there is no exception in console log
9.	Click on the "Filter" under result returned
10.	Follow steps 5 to 8 
11.	Open 'Search Forms' via the main menu ('hamburger') button
12.	Create a Search Form such as set 5.
13.	Go to Workspaces, open or click create a New Workspace
14.	Click on 'Search DDF Intrigue' or 'Create a Search'
15.	Click ellipse menu and click on 'Use Another Search Form'
16.	Select the created Search Form from drop down
17.	Click Search or Save, and Ensure there is no exception in console log

#### What are the relevant tickets?
codice/ddf-ui#399

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Review by zta6 — APPROVED** [review]

**Review by mojogitoverhere — APPROVED** [review]

**Comment by mojogitoverhere** [comment]
build now

**Review by cassandrabailey293 — APPROVED** [review]

**Comment by cassandrabailey293** [comment]
hero in progress

**Comment by cassandrabailey293** [comment]
hero successful 🎉 
verified that the exception is no longer thrown in all of the above scenarios. 

Question: what is the expected behavior in these scenarios when Location Option isn't selected? We could make another ticket to address these issues; for example, when the user tries to search without selecting a Location Option, we should probably prevent the search, similarly to how we prevent it when other anyGeo fields are invalid. We probably shouldn't save it this way on the result filter or in a search form, either. This is more of an enhancement, though.

**Comment by abel-connexta** [comment]
> hero successful 🎉
> verified that the exception is no longer thrown in all of the above scenarios.
> 
> Question: what is the expected behavior in these scenarios when Location Option isn't selected? We could make another ticket to address these issues; for example, when the user tries to search without selecting a Location Option, we should probably prevent the search, similarly to how we prevent it when other anyGeo fields are invalid. We probably shouldn't save it this way on the result filter or in a search form, either. This is more of an enhancement, though.

Yes I agree, that will be a great enhancement. As of now, when Location Option isn't selected, it does not include it in the search that is sent out (cql) to backend.

**Review by vinamartin — APPROVED** [review]

**Pull request merged**
