### PR TITLE
DDF-1684 Fixes resource leaks discovered in unit tests by Coverity.

### PR DESCRIPTION
**Pull request by coyotesqrl**
Discovered in scan for ddf-2.8.0-185-g54bc9cb

Some quick try/resources changes and a small bit of refactoring. While I was in there, I also applied the new code formatter.

@rzwiefel
@roelens8
@gordocanchola 
@pklinef

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/codice/ddf/pull/363" target="_blank">ReviewNinja

**Comment by gordocanchola** [comment]
:+1:

**Comment by coyotesqrl** [comment]
Can I get some more ninja stars on this?

**Comment by rzwiefel** [comment]
good job @codice/green

**Comment by roelens8** [comment]
:+1:

**Pull request merged**
