### PR TITLE
DDF-1487: corrected typo in cswendpoint

### PR DESCRIPTION
**Pull request by ricklarsen**
[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/263)

### CODE REVIEW

**Comment by roelens8** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/263)

**Comment by roelens8** [comment]
:+1:

**Comment by AzGoalie** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/263)

**Comment by AzGoalie** [comment]
Successfully build and passed!
:+1:

**Comment by ricklarsen** [comment]
Closing as duplicate.

**Pull request closed without merging**
