### PR TITLE
DDF-4397 Reduce soft commit timings for persistent store

### PR DESCRIPTION
**Pull request by Bdthomson**
#### What does this PR do?
Reduce soft commit timings for persistent store to reduce lag for user preferences.

#### Who is reviewing it? 

@GabrielFabian 
@Schachte 
@djblue

#### Select relevant component teams: 
@codice/solr

#### Ask 2 committers to review/merge the PR and tag them here.

@bdeining 
@pklinef

#### How should this be tested?

Change your theme and see if it's immediately persisted on page refresh.

#### What are the relevant tickets?
[DDF-4397](https://codice.atlassian.net/browse/DDF-4397)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by bdeining** [comment]
I'm assuming we want the persistent store to be updated immediately;  this makes sense for things that are stored in the user prefs such as the theme.  Otherwise the change in theme is not immediate?

**Comment by Bdthomson** [comment]
build now

**Comment by djblue** [comment]
Hero Successful

**Comment by Bdthomson** [comment]
build now

**Comment by Bdthomson** [comment]
build now

**Comment by Bdthomson** [comment]
build now

**Comment by Bdthomson** [comment]
build now

**Comment by Bdthomson** [comment]
build now

**Pull request merged**
