### PR TITLE
DDF-1535: Update mygrid repository URL

### PR DESCRIPTION
**Pull request by lessarderic**
Updated mygrid repository URL in all the pom files that were using the
deprecated one.

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/208)

### CODE REVIEW

**Comment by coyotesqrl** [comment]
lgtm :+1:

**Comment by shaundmorris** [comment]
Why don't we have this repository in the ddf pom.xml?

**Comment by lessarderic** [comment]
@shaundmorris: Looks like we still have some repositories defined in child pom files. Created https://codice.atlassian.net/browse/DDF-1536 to address this at some point in the future.

**Comment by shaundmorris** [comment]
Okay thanks @lessarderic was just trying to get some thoughts there. I believe it is easier to maintain the repositories there particularly when they are used in multiple child poms. :+1:

**Pull request merged**
