### PR TITLE
DDF-4135 Don't overwite internal ports with external ports

### PR DESCRIPTION
**Pull request by kcover**
Link to 2.13.x PR: #3728 

#### Who is reviewing it? 

@peterhuffer @emmberk 

#### Ask 2 committers to review/merge the PR and tag them here.

@clockard
@vinamartin 

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by kcover** [comment]
build now

**Comment by kcover** [comment]
likely intermittent network issues
build now

**Comment by kcover** [comment]
build now

**Comment by kcover** [comment]
Couldn't get the dependency from nexus but I was able to download it.
build now

**Comment by kcover** [comment]
rebased with karaf upgrade
build now

**Comment by vinamartin** [comment]
```
15:29:12 [ERROR] Failed to execute goal com.googlecode.maven-download-plugin:download-maven-plugin:1.4.0:wget (default) on project solr-distro: IO Error: Could not get content -> [Help 1]
15:29:12 org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.googlecode.maven-download-plugin:download-maven-plugin:1.4.0:wget (default) on project solr-distro: IO Error
```

**Comment by kcover** [comment]
rebased with solr download fix
build now

**Pull request merged**
