### PR TITLE
DDF-2901 Fix source tab configuration filtering

### PR DESCRIPTION
**Pull request by brendan-hofmann**
#### What does this PR do?
Fixes the sources tab to not create undesired configs, and fixes the filtering in the main view so only existing configurations are shown.
#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged)?
@codymacdonald 
@emanns95 
@clockard 
#### Select at least one member from relevant component team(s) from below (at least one component team member needs to approve the PR).
[UI](https://github.com/orgs/codice/teams/ui)
#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@andrewkfiedler
@pklinef
#### How should this be tested? (List steps with links to updated documentation)
Create a source and verify only one config is created. Click in and out of the source modal, click cancel, and verify the dropdown never displays erroneous configs.
#### What are the relevant tickets?
[DDF-2901](https://codice.atlassian.net/browse/DDF-2901)

### CODE REVIEW

**Comment by emanns95** [comment]
I've manually verified these changes :+1:

**Comment by brendan-hofmann** [comment]
test this please

**Comment by brendan-hofmann** [comment]
something  unique

**Comment by brendan-hofmann** [comment]
something unique

**Comment by pklinef** [comment]
Is this being backported?

**Comment by pklinef** [comment]
Is this going to be ported to master as well?

**Pull request merged**
