### PR TITLE
DDF-1551 Fixed typo in action description

### PR DESCRIPTION
**Pull request by bdeining**
@EIrwin is hero
@shane-voisard 
@wmcnalli

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/228)

### CODE REVIEW

**Comment by shane-voisard** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/228)

**Comment by millerw8** [comment]
there is something strange about this review... the diff doesn't show up.  But I do see the string is correct now


---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/228)

**Comment by jrnorth** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/228)

**Comment by EIrwin** [comment]
Smoke tested this (jk...no I didn't), but everything builds


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/228)

**Pull request merged**
