### PR TITLE
DDF-2671: Added length limit to source bindingUrl column

### PR DESCRIPTION
**Pull request by oconnormi**
#### What does this PR do?

Limits the size of the bindingUrl column introduced in #1524 

If max size is exceeded overflow is hidden and an ellipsis is displayed.

#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged)?

@lessarderic 
@Lambeaux 

#### Select at least one member from relevant component team(s) from below (at least one component team member needs to approve the PR).

@codice/ui 
@andrewkfiedler 

#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).

@figliold 
@pklinef 

#### What are the relevant tickets?

[DDF-2671](https://codice.atlassian.net/browse/DDF-2671)

#### Screenshots (if appropriate)

image

### CODE REVIEW

**Comment by oconnormi** [comment]
Not sure if this is really the ideal solution. The max-width needs to be pretty small in order to not cause issues with the whole overall table and almost renders the column useless. The main purpose of the column is to provide a quick look at the value of the current url without having click into the source edit modal. Even with this limit it could be argued that an admin should still be able to see if anything is extremely off or unexpected. It might also be better in the future to look into a way of combining this and it's associated loopback warning into the status badge at some point instead

**Comment by coyotesqrl** [comment]
@oconnormi, could you add a hover-over tooltip, maybe? One that displayed the full name?

**Comment by oconnormi** [comment]
Alright, I actually originally had that but thought it looked sorta odd. I'll put up a screenshot for that as well

**Comment by andrewkfiedler** [comment]
Unless there's a reason to leave them there, I think the solution should involve moving the buttons outside of the table.  On smaller screens, it's likely that the buttons will still get pushed off of the screen.

**Comment by lessarderic** [comment]
@andrewkfiedler, are you suggesting to move the buttons _and_ truncate the URL, or just move the buttons?

**Comment by oconnormi** [comment]
Added a tooltip to make it possible to see urls that are overflowing. Also moved the buttons out of the table

screenshots: 

image

**Comment by lessarderic** [comment]
Is there an easy way to reduce the blank spaces on both sides of the Binding URLs?

**Comment by oconnormi** [comment]
@lessarderic I had tried, but nothing seemed to work other than increasing the binding url column's max-width

**Comment by lessarderic** [comment]
:shipit:

**Comment by pklinef** [comment]
@oconnormi Can you please address @andrewkfiedler's comment about the buttons being pushed out of view?

**Comment by lessarderic** [comment]
@pklinef, @oconnormi has already moved the buttons above the table (see most recent screenshot). We're just waiting on @andrewkfiedler's approval and @Joy603 to complete the heroing and we should be good to merge.

**Comment by Lambeaux** [comment]
Hero was successful 👍

**Pull request merged**
