### PR TITLE
Upgrade to Solr 9.0

### PR DESCRIPTION
**Pull request by pklinef**
#### What does this PR do?
- Updated Solr schema to the latest version.
- Removed deprecated HttpSolrClientFactory and SolrClientProxy.
- Removed Solr core and Lucene dependencies since the embedded Solr server was removed in a previous release.
- Embedded JTS and Spatial4j in Solr related bundles since the version of JTS required for Spatial4j is not compatible with Geotools and JTS does not follow semantic versioning.

#### Select relevant component teams: 

@codice/solr 

#### Ask 2 committers to review/merge the PR and tag them here.

@ryeats
@ahoffer

#### How should this be tested?

Verify CI passes

#### What are the relevant tickets?
Fixes: #____

#### Checklist:
- [x] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [x] Update / Add Unit Tests
- [x] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Review by ahoffer — APPROVED** [review]

**Comment by pklinef** [comment]
build now

**Review by bakejeyner — APPROVED** [review]

**Comment by pklinef** [comment]
build now

**Comment by pklinef** [comment]
build now

**Comment by pklinef** [comment]
build now

**Comment by pklinef** [comment]
build now

**Comment by pklinef** [comment]
build now

**Comment by pklinef** [comment]
build now

**Pull request merged**
