### PR TITLE
[2.15.X] DDF-04953 Update setenv script to not override EXTRA_JAVA_OPTS if it already contains a value

### PR DESCRIPTION
**Pull request by roelens8**
#### What does this PR do?
https://github.com/codice/ddf/pull/4953

#### Who is reviewing it? 
@brjeter
@beyelerb

### CODE REVIEW

**Comment by roelens8** [comment]
build now

**Comment by roelens8** [comment]
build now

**Comment by roelens8** [comment]
build now

**Comment by shaundmorris** [comment]
merging to help stabilize 2.15.x

**Pull request merged**
