### PR TITLE
DDF-2407 use system user to install apps through the ApplicationConfigInstaller

### PR DESCRIPTION
**Pull request by ryeats**
#### What does this PR do?
2.9.x cherry pick of a fix that gives ApplicationConfigInstaller the correct permissions to install applications 
#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?
@tbatie @adimka 
#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@coyotesqrl
@shaundmorris
#### How should this be tested?
unzip drop this file in and remove the .txt then start the ddf and verify that solr-app, catalog-app, and spatial-app are installed
[org.codice.ddf.admin.applicationlist.properties.txt](https://github.com/codice/ddf/files/425996/org.codice.ddf.admin.applicationlist.properties.txt)
#### Checklist:
- [ ] Documentation Updated
- [x ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by coyotesqrl** [comment]
👍

**Comment by tbatie** [comment]
:+1:

**Comment by adimka** [comment]
👍

**Comment by shaundmorris** [comment]
👍

**Comment by adimka** [comment]
Successfully hero'd :+1:

**Pull request merged**
