### PR TITLE
DDF-1261: Add support for CSW delete transaction

### PR DESCRIPTION
**Pull request by jrnorth**
@millerw8 @jlcsmith @kcwire @wmcnalli @beyelerb @emanns95 @kguerriero @shane-voisard @bdeining

@kguerriero is the hero.

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/126)

### CODE REVIEW

**Comment by kguerriero** [comment]
Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/126)

**Comment by kcwire** [comment]
Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

<sup>**[catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/transaction/CswTransactionRequest.java, line 63 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/126#-Jx6jiSHDLotZjo1qfhj)** ([raw file](https://github.com/codice/ddf/blob/a2f291d18f5978ee7060f5347e1ff4473a46dc47/catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/transaction/CswTransactionRequest.java#L63)):</sup>
Seems kind of unnecessary. You could just call `getInsertTransactions().add(blah)`

---

<sup>**[catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/transaction/DeleteTransaction.java, line 25 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/126#-Jx6jt6xf-InWjkYEzua)** ([raw file](https://github.com/codice/ddf/blob/a2f291d18f5978ee7060f5347e1ff4473a46dc47/catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/transaction/DeleteTransaction.java#L25)):</sup>
javadoc?

---

<sup>**[catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java, line 476 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/126#-Jx6kKjUo4H9K385nQyS)** ([raw file](https://github.com/codice/ddf/blob/a2f291d18f5978ee7060f5347e1ff4473a46dc47/catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java#L476)):</sup>
why `+=` ? shouldn't it just be equal to the size?

---

<sup>**[catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java, line 486 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/126#-Jx6kQ_igFVO1WI3R5u6)** ([raw file](https://github.com/codice/ddf/blob/a2f291d18f5978ee7060f5347e1ff4473a46dc47/catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java#L486)):</sup>
same here.

---

<sup>**[catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java, line 549 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/126#-Jx6kbydA-UZgNVsXuod)** ([raw file](https://github.com/codice/ddf/blob/a2f291d18f5978ee7060f5347e1ff4473a46dc47/catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java#L549)):</sup>
`-1` does that mean return all?

---

<sup>**[catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java, line 556 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/126#-JxGoo-uqi2FnXWhnz1A)** ([raw file](https://github.com/codice/ddf/blob/a2f291d18f5978ee7060f5347e1ff4473a46dc47/catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java#L556)):</sup>
Should we return an error if nothing was found via the constraint?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/126)

**Comment by jlcsmith** [comment]
Reviewed 11 of 18 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/126)

**Comment by jrnorth** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

<sup>**[catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java, line 476 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/126#-Jx6kKjUo4H9K385nQyS)** ([raw file](https://github.com/codice/ddf/blob/a2f291d18f5978ee7060f5347e1ff4473a46dc47/catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java#L476)):</sup>
There could be multiple <Insert>s within a single transaction, so we want to calculate the total number of metacards added in the entire transaction. The same goes for deletion.

---

<sup>**[catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java, line 549 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/126#-Jx6kbydA-UZgNVsXuod)** ([raw file](https://github.com/codice/ddf/blob/a2f291d18f5978ee7060f5347e1ff4473a46dc47/catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java#L549)):</sup>
Yes.

---

<sup>**[catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java, line 556 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/126#-JxGoo-uqi2FnXWhnz1A)** ([raw file](https://github.com/codice/ddf/blob/a2f291d18f5978ee7060f5347e1ff4473a46dc47/catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java#L556)):</sup>
Possibly. The OGC spec states that one of the possible exceptions for the transaction operation is "Transaction Failed" -- I'm not sure that a delete request for no records truly represents a failed transaction. If the response comes back with a 0 for the total number deleted, that should indicate to whoever sent the request that they need to fix something if they expected something to be deleted.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/126)

**Comment by jrnorth** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/transaction/DeleteTransaction.java, line 25 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/126#-JxH7tcfGtLXPoUevl9a)** ([raw file](https://github.com/codice/ddf/blob/a2f291d18f5978ee7060f5347e1ff4473a46dc47/catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/transaction/DeleteTransaction.java#L25)):</sup>
Perhaps this class and InsertTransaction should be renamed to DeleteAction and InsertAction?  That would be more in line with the naming conventions in the OGC spec which states that the <Transaction> element "defines an atomic unit of work and is a container for one or more insert, update, and/or delete actions". 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/126)

**Comment by kcwire** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

<sup>**[catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/transaction/DeleteTransaction.java, line 25 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/126#-JxH7tcfGtLXPoUevl9a)** ([raw file](https://github.com/codice/ddf/blob/a2f291d18f5978ee7060f5347e1ff4473a46dc47/catalog/spatial/csw/spatial-csw-common/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/common/transaction/DeleteTransaction.java#L25)):</sup>
:+1:

---

<sup>**[catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java, line 476 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/126#-Jx6kKjUo4H9K385nQyS)** ([raw file](https://github.com/codice/ddf/blob/a2f291d18f5978ee7060f5347e1ff4473a46dc47/catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java#L476)):</sup>
whoops didn't see the for loop. nevermind.

---

<sup>**[catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java, line 556 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/126#-JxGoo-uqi2FnXWhnz1A)** ([raw file](https://github.com/codice/ddf/blob/a2f291d18f5978ee7060f5347e1ff4473a46dc47/catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java#L556)):</sup>
That sounds good to me.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/126)

**Comment by emanns95** [comment]
Reviewed 9 of 18 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/126)

**Pull request merged**
