### PR TITLE
DDF-1567 - Implement Checksum Provider

### PR DESCRIPTION
**Pull request by EIrwin**
Implemented Checksum capabilities that can be used by a CheckSumPlugin. CheckSumPlugin is an implementation of a newly created PreCreateStoragePlugin.

@kcwire is hero
@jrnorth

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/296)

### CODE REVIEW

**Comment by jlcsmith** [comment]
<sup>**[catalog/content/core/content-core-api/src/main/java/ddf/content/plugin/PostCreateStoragePlugin.java, line 38 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/296#-K1oEnST3PRc2QIJToSp)** ([raw file](https://github.com/codice/ddf/blob/b13aa95230b703defda2ba65f5119980fbcee4bc/catalog/content/core/content-core-api/src/main/java/ddf/content/plugin/PostCreateStoragePlugin.java#L38)):</sup>
Should this say PostUpdateStoragePlugin?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/296)

**Comment by jlcsmith** [comment]
<sup>**[catalog/content/core/content-core-api/src/main/java/ddf/content/plugin/PostCreateStoragePlugin.java, line 39 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/296#-K1oEvZMcjaKrrZPa9oi)** ([raw file](https://github.com/codice/ddf/blob/b13aa95230b703defda2ba65f5119980fbcee4bc/catalog/content/core/content-core-api/src/main/java/ddf/content/plugin/PostCreateStoragePlugin.java#L39)):</sup>
Does throwing this exception cause further plugins to be skipped?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/296)

**Comment by jlcsmith** [comment]
<sup>**[catalog/content/core/content-core-api/src/main/java/ddf/content/plugin/PostCreateStoragePlugin.java, line 49 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/296#-K1oF37vHfkuf9C_ZJcW)** ([raw file](https://github.com/codice/ddf/blob/b13aa95230b703defda2ba65f5119980fbcee4bc/catalog/content/core/content-core-api/src/main/java/ddf/content/plugin/PostCreateStoragePlugin.java#L49)):</sup>
Should this be PostDeleteStoragePlugin?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/296)

**Comment by jlcsmith** [comment]
<sup>**[catalog/content/core/content-core-api/src/main/java/ddf/content/plugin/PostCreateStoragePlugin.java, line 49 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/296#-K1oF37vHfkuf9C_ZJcW)** ([raw file](https://github.com/codice/ddf/blob/b13aa95230b703defda2ba65f5119980fbcee4bc/catalog/content/core/content-core-api/src/main/java/ddf/content/plugin/PostCreateStoragePlugin.java#L49)):</sup>
Disregard.  The create plugin handles updates/delete (similar to our other plugins)


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/296)

**Comment by jlcsmith** [comment]
<sup>**[catalog/content/core/content-core-api/src/main/java/ddf/content/plugin/PreCreateStoragePlugin.java, line 28 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/296#-K1oGFIj6W4CnNX5BKRm)** ([raw file](https://github.com/codice/ddf/blob/b13aa95230b703defda2ba65f5119980fbcee4bc/catalog/content/core/content-core-api/src/main/java/ddf/content/plugin/PreCreateStoragePlugin.java#L28)):</sup>
Does throwing this exception cause other plugins to be skipped?  Does the create/update/delete operation still occur?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/296)

**Comment by jlcsmith** [comment]
<sup>**[libs/checksum/pom.xml, line 68 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/296#-K1oHtpmxE6PpV6kX94L)** ([raw file](https://github.com/codice/ddf/blob/b13aa95230b703defda2ba65f5119980fbcee4bc/libs/checksum/pom.xml#L68)):</sup>
Why are these set to 0?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/296)

**Comment by jlcsmith** [comment]
<sup>**[libs/checksum/src/main/java/org/codice/ddf/checksum/CheckSumProvider.java, line 18 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/296#-K1oIvCGhQ5dbSFbFDpK)** ([raw file](https://github.com/codice/ddf/blob/b13aa95230b703defda2ba65f5119980fbcee4bc/libs/checksum/src/main/java/org/codice/ddf/checksum/CheckSumProvider.java#L18)):</sup>
javadoc?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/296)

**Comment by jlcsmith** [comment]
<sup>**[libs/checksum/src/main/java/org/codice/ddf/checksum/impl/CRC32CheckSumProvider.java, line 49 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/296#-K1oJel-S3H__Ij0QWGX)** ([raw file](https://github.com/codice/ddf/blob/b13aa95230b703defda2ba65f5119980fbcee4bc/libs/checksum/src/main/java/org/codice/ddf/checksum/impl/CRC32CheckSumProvider.java#L49)):</sup>
If you aren't going to throw the exception, then the exception itself should be logged.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/296)

**Comment by jlcsmith** [comment]
<sup>**[libs/checksum/src/main/java/org/codice/ddf/checksum/impl/MD5CheckSumProvider.java, line 47 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/296#-K1oJlO0lrMTWK3P0UCn)** ([raw file](https://github.com/codice/ddf/blob/b13aa95230b703defda2ba65f5119980fbcee4bc/libs/checksum/src/main/java/org/codice/ddf/checksum/impl/MD5CheckSumProvider.java#L47)):</sup>
Need to log these exceptions


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/296)

**Comment by jlcsmith** [comment]
<sup>**[libs/checksum/src/main/java/org/codice/ddf/checksum/impl/package-info.java, line 18 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/296#-K1oK_7kgta2kqt4RW4t)** ([raw file](https://github.com/codice/ddf/blob/b13aa95230b703defda2ba65f5119980fbcee4bc/libs/checksum/src/main/java/org/codice/ddf/checksum/impl/package-info.java#L18)):</sup>
If you need this, then it should be updated with the correct words (ie, replace "Event" stuff)


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/296)

**Comment by jrnorth** [comment]
Looks like you need to run the code formatter on these files.

Also, this is a nitpick, but "checksum" is one word so it's somewhat confusing to see it camel-cased everywhere.


---

Reviewed 24 of 24 files at r1.
Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

<sup>**[catalog/content/core/content-core-catalogerplugin/src/main/java/ddf/content/plugin/cataloger/CatalogContentPlugin.java, line 107 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/296#-K1oM2Ka25C4dmbUxNs5)** ([raw file](https://github.com/codice/ddf/blob/b13aa95230b703defda2ba65f5119980fbcee4bc/catalog/content/core/content-core-catalogerplugin/src/main/java/ddf/content/plugin/cataloger/CatalogContentPlugin.java#L107)):</sup>
What does this change do?


---

<sup>**[catalog/content/core/content-core-catalogerplugin/src/main/java/ddf/content/plugin/cataloger/CatalogContentPlugin.java, line 308 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/296#-K1oSSMHPYGDQTkogusQ)** ([raw file](https://github.com/codice/ddf/blob/b13aa95230b703defda2ba65f5119980fbcee4bc/catalog/content/core/content-core-catalogerplugin/src/main/java/ddf/content/plugin/cataloger/CatalogContentPlugin.java#L308)):</sup>
`checksumAlgorithm`


---

<sup>**[catalog/content/core/content-core-checksumplugin/src/main/java/ddf/content/plugin/checksum/CheckSum.java, line 49 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/296#-K1oTe2Wxgj2Y1DBPZcY)** ([raw file](https://github.com/codice/ddf/blob/b13aa95230b703defda2ba65f5119980fbcee4bc/catalog/content/core/content-core-checksumplugin/src/main/java/ddf/content/plugin/checksum/CheckSum.java#L49)):</sup>
Log the exception as well.


---

<sup>**[catalog/content/core/content-core-impl/pom.xml, line 68 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/296#-K1oU2-NBePO4MNpqvbT)** ([raw file](https://github.com/codice/ddf/blob/b13aa95230b703defda2ba65f5119980fbcee4bc/catalog/content/core/content-core-impl/pom.xml#L68)):</sup>
No comma


---

<sup>**[catalog/content/core/content-core-impl/pom.xml, line 70 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/296#-K1oUAK8jFO9bfgHd2Xl)** ([raw file](https://github.com/codice/ddf/blob/b13aa95230b703defda2ba65f5119980fbcee4bc/catalog/content/core/content-core-impl/pom.xml#L70)):</sup>
`<Import-Package>` is * by default, so you don't need to specify it.


---

<sup>**[catalog/content/core/content-core-impl/src/main/java/ddf/content/data/impl/ContentMetacardType.java, line 1 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/296#-K1oUOpxmbLaRUHXKdVJ)** ([raw file](https://github.com/codice/ddf/blob/b13aa95230b703defda2ba65f5119980fbcee4bc/catalog/content/core/content-core-impl/src/main/java/ddf/content/data/impl/ContentMetacardType.java#L1)):</sup>
Missing the header comment?


---

<sup>**[libs/checksum/pom.xml, line 94 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/296#-K1oUyDaKARigYn8Wltq)** ([raw file](https://github.com/codice/ddf/blob/b13aa95230b703defda2ba65f5119980fbcee4bc/libs/checksum/pom.xml#L94)):</sup>
Dependencies usually go before plugins.


---

<sup>**[libs/checksum/src/main/java/org/codice/ddf/checksum/AbstractCheckSumProvider.java, line 16 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/296#-K1oVNbiylFONpD8VUNu)** ([raw file](https://github.com/codice/ddf/blob/b13aa95230b703defda2ba65f5119980fbcee4bc/libs/checksum/src/main/java/org/codice/ddf/checksum/AbstractCheckSumProvider.java#L16)):</sup>
Is this class supposed to be `abstract`?


---

<sup>**[libs/checksum/src/test/java/org/codice/ddf/checksum/TestCRCCheckSumProvider.java, line 35 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/296#-K1oW_fA-Hi7L2rdm_Xo)** ([raw file](https://github.com/codice/ddf/blob/b13aa95230b703defda2ba65f5119980fbcee4bc/libs/checksum/src/test/java/org/codice/ddf/checksum/TestCRCCheckSumProvider.java#L35)):</sup>
This is Java's `assert` keyword; it's not a JUnit test method. We should use `assertThat`.


---

<sup>**[libs/checksum/src/test/java/org/codice/ddf/checksum/TestCRCCheckSumProvider.java, line 62 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/296#-K1oXXoiixHfLK0VRjE9)** ([raw file](https://github.com/codice/ddf/blob/b13aa95230b703defda2ba65f5119980fbcee4bc/libs/checksum/src/test/java/org/codice/ddf/checksum/TestCRCCheckSumProvider.java#L62)):</sup>
This comment isn't really correct.


---

<sup>**[libs/checksum/src/test/java/org/codice/ddf/checksum/TestCRCCheckSumProvider.java, line 74 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/296#-K1oXafEuDbeJxW1425P)** ([raw file](https://github.com/codice/ddf/blob/b13aa95230b703defda2ba65f5119980fbcee4bc/libs/checksum/src/test/java/org/codice/ddf/checksum/TestCRCCheckSumProvider.java#L74)):</sup>
This comment isn't that useful.


---

<sup>**[libs/checksum/src/test/java/org/codice/ddf/checksum/TestCRCCheckSumProvider.java, line 87 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/296#-K1oXDxp3ijPInb8UlSU)** ([raw file](https://github.com/codice/ddf/blob/b13aa95230b703defda2ba65f5119980fbcee4bc/libs/checksum/src/test/java/org/codice/ddf/checksum/TestCRCCheckSumProvider.java#L87)):</sup>
Why catch the exception? I would imagine any test using this method should fail if it occurs, in which case you can just ignore it.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/296)

**Comment by jlcsmith** [comment]
Reviewed 12 of 24 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

<sup>**[catalog/content/core/content-core-checksumplugin/pom.xml, line 104 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/296#-K1oZx3WBuXXHr4HO35L)** ([raw file](https://github.com/codice/ddf/blob/b13aa95230b703defda2ba65f5119980fbcee4bc/catalog/content/core/content-core-checksumplugin/pom.xml#L104)):</sup>
update these values


---

<sup>**[catalog/content/core/content-core-checksumplugin/src/main/java/ddf/content/plugin/checksum/CheckSum.java, line 50 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/296#-K1o_K1c06hfhySMs98b)** ([raw file](https://github.com/codice/ddf/blob/b13aa95230b703defda2ba65f5119980fbcee4bc/catalog/content/core/content-core-checksumplugin/src/main/java/ddf/content/plugin/checksum/CheckSum.java#L50)):</sup>
Should this throw a PluginExecutionException instead of returning null?  What are the effects of returning null?


---

<sup>**[catalog/content/core/content-core-impl/src/main/java/ddf/content/impl/ContentFrameworkImpl.java, line 144 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/296#-K1oaUE8Zxv3I0-YQNRc)** ([raw file](https://github.com/codice/ddf/blob/b13aa95230b703defda2ba65f5119980fbcee4bc/catalog/content/core/content-core-impl/src/main/java/ddf/content/impl/ContentFrameworkImpl.java#L144)):</sup>
Currently aren't there cases where the plugin can return null?  Also, it seems like this piece of code should handle the plugin exception.  Should the plugin exception stop the create?  Or should the next plugin get called?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/296)

**Comment by jlcsmith** [comment]
Reviewed 12 of 24 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/296)

**Comment by jlcsmith** [comment]
I see there are 2 checksum implementations, but the blueprint for the checksum project only defines the CRC32 checksum implementation.  Do we only want CRC32?  We could potentially have a single checksum implementation with a metatype config to choose one algo over the other.  


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/296)

**Comment by EIrwin** [comment]
<sup>**[catalog/content/core/content-core-impl/src/main/java/ddf/content/impl/ContentFrameworkImpl.java, line 144 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/296#-K1oaUE8Zxv3I0-YQNRc)** ([raw file](https://github.com/codice/ddf/blob/b13aa95230b703defda2ba65f5119980fbcee4bc/catalog/content/core/content-core-impl/src/main/java/ddf/content/impl/ContentFrameworkImpl.java#L144)):</sup>
I am making fixes to it so it is consistent with the plugin invocation in the CatalogFrameworkImpl where a PluginException is caught and execution continues on remaining plugins.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/296)

**Comment by EIrwin** [comment]
<sup>**[catalog/content/core/content-core-checksumplugin/src/main/java/ddf/content/plugin/checksum/CheckSum.java, line 50 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/296#-K1o_K1c06hfhySMs98b)** ([raw file](https://github.com/codice/ddf/blob/b13aa95230b703defda2ba65f5119980fbcee4bc/catalog/content/core/content-core-checksumplugin/src/main/java/ddf/content/plugin/checksum/CheckSum.java#L50)):</sup>
yeah I think this should throw a PluginExecutionException instead of returning null


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/296)

**Comment by EIrwin** [comment]
<sup>**[catalog/content/core/content-core-catalogerplugin/src/main/java/ddf/content/plugin/cataloger/CatalogContentPlugin.java, line 107 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/296#-K1oM2Ka25C4dmbUxNs5)** ([raw file](https://github.com/codice/ddf/blob/b13aa95230b703defda2ba65f5119980fbcee4bc/catalog/content/core/content-core-catalogerplugin/src/main/java/ddf/content/plugin/cataloger/CatalogContentPlugin.java#L107)):</sup>
not sure what I am looking at


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/296)

**Comment by beyelerb** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

<sup>**[catalog/content/core/content-core-catalogerplugin/src/main/java/ddf/content/plugin/cataloger/CatalogContentPlugin.java, line 244 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/296#-K1pALy0HltywqSPVgvz)** ([raw file](https://github.com/codice/ddf/blob/b13aa95230b703defda2ba65f5119980fbcee4bc/catalog/content/core/content-core-catalogerplugin/src/main/java/ddf/content/plugin/cataloger/CatalogContentPlugin.java#L244)):</sup>
Why not use the second constructor instead of this and the for loop below?
contentMetacard = new ContentMetacardType(CONTENT_METACARD_TYPE_NAME, generatedMetacard.getAttributeDescriptors());


---

<sup>**[catalog/content/core/content-core-checksumplugin/src/main/java/ddf/content/plugin/checksum/CheckSum.java, line 23 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/296#-K1pOxIKnGPl5XgirSUX)** ([raw file](https://github.com/codice/ddf/blob/b13aa95230b703defda2ba65f5119980fbcee4bc/catalog/content/core/content-core-checksumplugin/src/main/java/ddf/content/plugin/checksum/CheckSum.java#L23)):</sup>
I think we are trying to get away from XLogger and just use the straight logger classes in any new code that we are writing (or modifying).


---

<sup>**[catalog/content/core/content-core-checksumplugin/src/main/java/ddf/content/plugin/checksum/CheckSum.java, line 58 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/296#-K1pKyi1NK4_piK3eS2_)** ([raw file](https://github.com/codice/ddf/blob/b13aa95230b703defda2ba65f5119980fbcee4bc/catalog/content/core/content-core-checksumplugin/src/main/java/ddf/content/plugin/checksum/CheckSum.java#L58)):</sup>
What if there are IOExceptions during generation? Looks like you will get a null returned value. Do you want to throw a plugin exception in that case? Or just put a null in for the checksum value? Seems like if we add the property, we should have a real value there.


---

<sup>**[catalog/content/core/content-core-impl/src/main/java/ddf/content/data/impl/ContentMetacardType.java, line 15 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/296#-K1pLSLRL1_M0q9QXRRm)** ([raw file](https://github.com/codice/ddf/blob/b13aa95230b703defda2ba65f5119980fbcee4bc/catalog/content/core/content-core-impl/src/main/java/ddf/content/data/impl/ContentMetacardType.java#L15)):</sup>
public? so others can use it and check against it?


---

<sup>**[libs/checksum/src/main/java/org/codice/ddf/checksum/impl/CRC32CheckSumProvider.java, line 41 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/296#-K1pNoD79XOJAWIbdemU)** ([raw file](https://github.com/codice/ddf/blob/b13aa95230b703defda2ba65f5119980fbcee4bc/libs/checksum/src/main/java/org/codice/ddf/checksum/impl/CRC32CheckSumProvider.java#L41)):</sup>
This pulls the whole inputStream into memory - can the CRC32 handle an input stream directly? For large NITFs, etc. we could quickly run out of memory.


---

<sup>**[libs/checksum/src/main/java/org/codice/ddf/checksum/impl/MD5CheckSumProvider.java, line 41 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/296#-K1pO4T_6WluMihqDdsy)** ([raw file](https://github.com/codice/ddf/blob/b13aa95230b703defda2ba65f5119980fbcee4bc/libs/checksum/src/main/java/org/codice/ddf/checksum/impl/MD5CheckSumProvider.java#L41)):</sup>
same comment as above - pulling the whole file into memory...


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/296)

**Comment by beyelerb** [comment]
Reviewed 24 of 24 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/296)

**Comment by EIrwin** [comment]
<sup>**[catalog/content/core/content-core-checksumplugin/src/main/java/ddf/content/plugin/checksum/CheckSum.java, line 58 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/296#-K1pKyi1NK4_piK3eS2_)** ([raw file](https://github.com/codice/ddf/blob/b13aa95230b703defda2ba65f5119980fbcee4bc/catalog/content/core/content-core-checksumplugin/src/main/java/ddf/content/plugin/checksum/CheckSum.java#L58)):</sup>
I saw this too and am making the change. Thanks


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/296)

**Comment by EIrwin** [comment]
<sup>**[libs/checksum/src/main/java/org/codice/ddf/checksum/impl/CRC32CheckSumProvider.java, line 41 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/296#-K1pNoD79XOJAWIbdemU)** ([raw file](https://github.com/codice/ddf/blob/b13aa95230b703defda2ba65f5119980fbcee4bc/libs/checksum/src/main/java/org/codice/ddf/checksum/impl/CRC32CheckSumProvider.java#L41)):</sup>
I don't see the ability to do this without reading it into memory through CRC32.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/296)

**Comment by EIrwin** [comment]
<sup>**[libs/checksum/src/main/java/org/codice/ddf/checksum/impl/MD5CheckSumProvider.java, line 41 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/296#-K1pO4T_6WluMihqDdsy)** ([raw file](https://github.com/codice/ddf/blob/b13aa95230b703defda2ba65f5119980fbcee4bc/libs/checksum/src/main/java/org/codice/ddf/checksum/impl/MD5CheckSumProvider.java#L41)):</sup>
same with this one


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/296)

**Comment by jlcsmith** [comment]
<sup>**[libs/checksum/src/main/java/org/codice/ddf/checksum/impl/CRC32CheckSumProvider.java, line 41 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/296#-K1pNoD79XOJAWIbdemU)** ([raw file](https://github.com/codice/ddf/blob/b13aa95230b703defda2ba65f5119980fbcee4bc/libs/checksum/src/main/java/org/codice/ddf/checksum/impl/CRC32CheckSumProvider.java#L41)):</sup>
We should probably talk about this.  We need an algo that can handle a BufferedInputStream or similar so that we aren't reading the entire thing.  It is certainly possible that we could be reading large files into the DDF content framework.  


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/296)

**Pull request closed without merging**
