### PR TITLE
[2.13.x] DDF-2824 Update Solr scripts and documentation

### PR DESCRIPTION
**Pull request by ahoffer**
##### ABBREVIATED REVIEW BETWEEN 2.13.X AND MASTER IS IN EFFECT
Link to merged master PR: https://github.com/codice/ddf/pull/3612

#### What does this PR do?
- Adds Solr service definition file for systemd services 
- Updates to Solr-related documentation
- Updates to Windows BAT files for starting DDF and Solr

#### Who is reviewing it? 
@mcalcote 
@ricklarsen 
@austinsteffes 

#### Ask 2 committers to review/merge the PR and tag them here.
@clockard
@figliold

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by ahoffer** [comment]
build now

**Comment by ahoffer** [comment]
build now

**Comment by garrettfreibott** [comment]
Hero'd - Solr starts by default. If `start.solr` is set to `false` in `etc/system.properties`, Solr is not started when DDF is started.

**Comment by ahoffer** [comment]
build now

**Pull request merged**
