### PR TITLE
DDF-3353 Made delete button in Map Layers red

### PR DESCRIPTION
**Pull request by josephthweatt**
#### What does this PR do?
The trash can icon in Map Layers is now the "error" color in the chosen theme. This is to make the icon stand out and be consistent with the admin-console-beta trash icon.

#### Who is reviewing it? 
@djblue  @garrettfreibott 

#### Choose 2 committers to review/merge the PR. 
@clockard 
@shaundmorris

#### How should this be tested? (List steps with links to updated documentation)
Build DDF and make sure that the map layers trash icon is red and is aligned correctly. Observe that its correct in Chrome, Firefox and IE

#### What are the relevant tickets?
[DDF-3353](https://codice.atlassian.net/browse/)
#### Screenshots
image

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests
#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by vinamartin** [comment]
screen shot 2017-10-10 at 9 40 17 am

Manually verified that the trash can is red. ✔️

**Comment by josephthweatt** [comment]
build now

**Comment by josephthweatt** [comment]
build now

**Comment by josephthweatt** [comment]
build now

**Pull request merged**
