### PR TITLE
DDF-1534 Support PKCS12 keystorefiles

### PR DESCRIPTION
**Pull request by ahoffer**
[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/243)

### CODE REVIEW

**Comment by AzGoalie** [comment]
Build and tests all passed!
:+1:

**Comment by harrison-tarr** [comment]
lgtm :+1:

**Comment by ricklarsen** [comment]
Reviewed 12 of 12 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/243)

**Comment by roelens8** [comment]
:+1:

**Comment by ricklarsen** [comment]
LGTM :+1:

**Comment by brendan-hofmann** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/SolrHttpWrapper.java, line 111 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/243#-K0C1hqeq36ZAV96noOx)** ([raw file](https://github.com/codice/ddf/blob/b3251bed30fb32dafd53031dfa2132a6190ebb78/catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/SolrHttpWrapper.java#L111)):</sup>
Raw strings concern me, especially for security stuff. This string really should be a constant somewhere. This might be a good place: https://github.com/codice/ddf/blob/master/platform/security/platform-security-core-api/src/main/java/ddf/security/SecurityConstants.java


---

<sup>**[catalog/spatial/ogc/spatial-ogc-common/src/test/java/org/codice/ddf/spatial/ogc/catalog/common/TestTrustedRemoteSource.java, line 155 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/243#-K0BziRyat_pYa9me1_D)** ([raw file](https://github.com/codice/ddf/blob/b3251bed30fb32dafd53031dfa2132a6190ebb78/catalog/spatial/ogc/spatial-ogc-common/src/test/java/org/codice/ddf/spatial/ogc/catalog/common/TestTrustedRemoteSource.java#L155)):</sup>
Perhaps you should check for and restore the original value of this property, if any? Otherwise this unit test will alter machines it is run on in potentially undesirable ways. I guess you could use PowerMock too.


---

<sup>**[platform/security/platform-security-settings/src/test/java/ddf/security/settings/impl/KeystoreFormatTest.java, line 80 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/243#-K0C26K2QS3-EjJul9p8)** ([raw file](https://github.com/codice/ddf/blob/b3251bed30fb32dafd53031dfa2132a6190ebb78/platform/security/platform-security-settings/src/test/java/ddf/security/settings/impl/KeystoreFormatTest.java#L80)):</sup>
Again, lots of system property changing that could affect the machine this test is run on.


---

<sup>**[platform/security/sts/security-sts-pkivalidator/src/test/java/org/codice/ddf/security/validator/pki/TestPKITokenValidator.java, line 64 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/243#-K0C-rhhDycogLeLUoM5)** ([raw file](https://github.com/codice/ddf/blob/b3251bed30fb32dafd53031dfa2132a6190ebb78/platform/security/sts/security-sts-pkivalidator/src/test/java/org/codice/ddf/security/validator/pki/TestPKITokenValidator.java#L64)):</sup>
Same concern here.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/243)

**Comment by ahoffer** [comment]
Review status: 11 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

<sup>**[catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/SolrHttpWrapper.java, line 111 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/243#-K0C1hqeq36ZAV96noOx)** ([raw file](https://github.com/codice/ddf/blob/b3251bed30fb32dafd53031dfa2132a6190ebb78/catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/SolrHttpWrapper.java#L111)):</sup>
Are there any potential negative impacts of having *org.codice.ddf.commands.solr.SolrHttpWrapper* depend on *ddf.security.SecurityConstants*? I assume there are none, or else you would not have recommended it. :smile:  I am moving the string literals there.

Why do raw strings concern you? I thought about adding them as constants as we do in the *Test classes, but I couldn't justify the extra level of indirection and a new package dependency to myself.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/243)

**Comment by brendan-hofmann** [comment]
Review status: 11 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

<sup>**[catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/SolrHttpWrapper.java, line 111 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/243#-K0C1hqeq36ZAV96noOx)** ([raw file](https://github.com/codice/ddf/blob/b3251bed30fb32dafd53031dfa2132a6190ebb78/catalog/core/catalog-core-solrcommands/src/main/java/org/codice/ddf/commands/solr/SolrHttpWrapper.java#L111)):</sup>
Because we are all imperfect, fallible creatures. ;) You could quantify the level of risk as `charactersInString*repetitionsOfString`. If you write once and use a constant everywhere, you gain the twin benefits of compile-time checking and traceability (e.g. `find usages` and the like), as well as reducing future maintenance costs.

Since that class is exported at runtime, there's no real performance or resource cost to the dependency either, so I view it as a much more benign alternative.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/243)

**Comment by ahoffer** [comment]
Review status: 8 of 14 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[catalog/spatial/ogc/spatial-ogc-common/src/test/java/org/codice/ddf/spatial/ogc/catalog/common/TestTrustedRemoteSource.java, line 155 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/243#-K0BziRyat_pYa9me1_D)** ([raw file](https://github.com/codice/ddf/blob/b3251bed30fb32dafd53031dfa2132a6190ebb78/catalog/spatial/ogc/spatial-ogc-common/src/test/java/org/codice/ddf/spatial/ogc/catalog/common/TestTrustedRemoteSource.java#L155)):</sup>
Now restoring original value.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/243)

**Comment by coyotesqrl** [comment]
Review status: 8 of 14 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[catalog/spatial/ogc/spatial-ogc-common/src/test/java/org/codice/ddf/spatial/ogc/catalog/common/TestTrustedRemoteSource.java, line 155 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/243#-K0BziRyat_pYa9me1_D)** ([raw file](https://github.com/codice/ddf/blob/b3251bed30fb32dafd53031dfa2132a6190ebb78/catalog/spatial/ogc/spatial-ogc-common/src/test/java/org/codice/ddf/spatial/ogc/catalog/common/TestTrustedRemoteSource.java#L155)):</sup>
@ricklarsen This test is going to be deleted with your ticket, right? We should get the test right for now regardless, but I don't think it's going to around much longer.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/243)

**Comment by ricklarsen** [comment]
<sup>**[catalog/spatial/ogc/spatial-ogc-common/src/test/java/org/codice/ddf/spatial/ogc/catalog/common/TestTrustedRemoteSource.java, line 155 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/243#-K0BziRyat_pYa9me1_D)** ([raw file](https://github.com/codice/ddf/blob/b3251bed30fb32dafd53031dfa2132a6190ebb78/catalog/spatial/ogc/spatial-ogc-common/src/test/java/org/codice/ddf/spatial/ogc/catalog/common/TestTrustedRemoteSource.java#L155)):</sup>
Correct. There is still one more thing dependent on it, but as soon as that's fixed, I can merge my branch that has removed it entirely.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/243)

**Comment by shaundmorris** [comment]
So that means merge this PR before https://github.com/codice/ddf/pull/245 right?

**Comment by ahoffer** [comment]
I think that would be fine, yes.


---

Review status: 8 of 14 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/243)

**Comment by AzGoalie** [comment]
rebuilt and passed
:+1:

**Pull request merged**
