### PR TITLE
DDF-1260: Add support for CSW update transaction

### PR DESCRIPTION
**Pull request by jrnorth**
@millerw8 @jlcsmith @kcwire @wmcnalli @beyelerb @emanns95 @kguerriero @shane-voisard @bdeining

@jlcsmith is the hero.

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/142)

### CODE REVIEW

**Comment by jlcsmith** [comment]
<sup>**[catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java, line 603 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/142#-Jy88Kyzu6XtuDLCOUTl)** ([raw file](https://github.com/codice/ddf/blob/62896ec364e50bf1b5cd8a1490522a5a84dc3824/catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java#L603)):</sup>
probably want to log an error or warning even though this is an unlikely casee

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/142)

**Comment by jlcsmith** [comment]
<sup>**[catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java, line 636 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/142#-Jy8BajBDk3VqCMJnFiC)** ([raw file](https://github.com/codice/ddf/blob/62896ec364e50bf1b5cd8a1490522a5a84dc3824/catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java#L636)):</sup>
what if updatedMetacardIdsList is empty?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/142)

**Comment by jlcsmith** [comment]
<sup>**[catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java, line 497 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/142#-Jy8E47ymaDPg4gyW_nv)** ([raw file](https://github.com/codice/ddf/blob/62896ec364e50bf1b5cd8a1490522a5a84dc3824/catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java#L497)):</sup>
Don't we need to capture the error and include it in the exception report?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/142)

**Comment by jlcsmith** [comment]
How about updated documentation?  I don't think we have captured csw transactions in the asciidoc documentation, but we should.  

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/142)

**Comment by jlcsmith** [comment]
Reviewed 10 of 14 files at r1, 1 of 1 files at r2.
Review status: 11 of 14 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/142)

**Comment by jlcsmith** [comment]
Reviewed 3 of 14 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/142)

**Comment by jlcsmith** [comment]
Clean PR build was successful.

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/142)

**Comment by jrnorth** [comment]
There's a ticket for documentation in the next sprint.

---

Review status: 11 of 14 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

<sup>**[catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java, line 497 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/142#-Jy8E47ymaDPg4gyW_nv)** ([raw file](https://github.com/codice/ddf/blob/62896ec364e50bf1b5cd8a1490522a5a84dc3824/catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java#L497)):</sup>
Yes - I made a ticket for CSW transaction exception reports a while back since we haven't been doing a good job of handling them correctly so far.

---

<sup>**[catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java, line 603 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/142#-Jy88Kyzu6XtuDLCOUTl)** ([raw file](https://github.com/codice/ddf/blob/62896ec364e50bf1b5cd8a1490522a5a84dc3824/catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java#L603)):</sup>
Done.

---

<sup>**[catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java, line 636 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/142#-Jy8BajBDk3VqCMJnFiC)** ([raw file](https://github.com/codice/ddf/blob/62896ec364e50bf1b5cd8a1490522a5a84dc3824/catalog/spatial/csw/spatial-csw-endpoint/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/endpoint/CswEndpoint.java#L636)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/142)

**Comment by kcwire** [comment]
@jlcsmith were you able to do a quick smoke test of the added functionality in addition to the clean PR build?

**Comment by jlcsmith** [comment]
Yes.  Evidently I forgot to mention this here but I did a quick test to verify updates via the endpoint.  

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/142)

**Comment by wmcnalli** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/142)

**Comment by wmcnalli** [comment]
Reviewed 11 of 14 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/142)

**Comment by kguerriero** [comment]
Reviewed 11 of 14 files at r1, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/142)

**Pull request merged**
