### PR TITLE
DDF-1519 Encode relay state before sending to IdP

### PR DESCRIPTION
**Pull request by pklinef**
Relay state cannot exceed 80 characters and it should not leak
information about the user action.  Relay state is now a GUID that
can be used to lookup the original redirect url after the user has
successfully logged into the IdP.  Relay state will expire if the
user does not return.

@coyotesqrl @rzwiefel @ryeats

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/265)

### CODE REVIEW

**Comment by rzwiefel** [comment]
:+1:  looks good
:shipit:

**Comment by coyotesqrl** [comment]
:shipit:

**Comment by ryeats** [comment]
:+1:

**Comment by roelens8** [comment]
:+1:

**Pull request merged**
