### PR TITLE
DDF-2244 Updated ValidatePrinter.printEntry to print when errors or warnings occur

### PR DESCRIPTION
**Pull request by emanns95**
#### What does this PR do?
Fixes bad logic which hides validation errors from being printed.

#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?
@spearskw 
@harrison-tarr 

#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@coyotesqrl
@jaymcnallie
@shaundmorris

#### How should this be tested?
Full Build

#### What are the relevant tickets?
DDF-2244

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by coyotesqrl** [comment]
👍

**Comment by emanns95** [comment]
@brendan-hofmann @ahoffer @AzGoalie I should've just added you as reviewers at the top

**Comment by mcalcote** [comment]
LGTM 👍

**Comment by brendan-hofmann** [comment]
I still think there needs to be more test coverage here, but that can be part of a separate PR. 👍

**Comment by spearskw** [comment]
👍

**Comment by jaymcnallie** [comment]
👍

**Pull request merged**
