### PR TITLE
DDF-1458 Combined config.js and main.js in admin ui modules

### PR DESCRIPTION
**Pull request by clockard**
Fixes require js race condition.

@stustison @djblue @vinamartin

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/148)

### CODE REVIEW

**Comment by stustison** [comment]
lgtm

**Comment by vinamartin** [comment]
Verified built and UI comes up.

**Comment by djblue** [comment]
:+1:

**Comment by shaundmorris** [comment]
Verified build and respective modules affected were functioning properly.

**Pull request merged**
