### PR TITLE
DDF-3862 SAML Fixes for AuthnRequest Generation and Metadata Parsing

### PR DESCRIPTION
**Pull request by brjeter**
#### What does this PR do?
* Renamed all instances of `entityDescription(s)` to `entityDescriptor(s)`.
* IdpHandler sends POST for the `ProtocolBinding` of the `AuthnRequest` instead of pulling from IdPMetadata which led to Redirect. Redirect **cannot** be used (see Background Context).
* MetadataConfigurationParser now accounts for an `EntitiesDescriptor` element which could contain multiple `EntityDescriptor` elements
#### Who is reviewing it? 
(please choose AT LEAST two reviewers that need to approve the PR before it can get merged)
@bakejeyner @blen-desta 
#### Select relevant component teams: 
https://github.com/orgs/codice/teams
#### Ask 2 committers to review/merge the PR and tag them here. If you don't know who to ask, you can request reviews in https://groups.google.com/forum/#!forum/ddf-developers .
(please choose ONLY two committers from below, delete the rest)
@coyotesqrl 
@stustison
#### How should this be tested? (List steps with links to updated documentation)
* Install DDF
* Provide the IdP with SP metadata that has an `EntitiesDescriptor` element (SamlConf metadata can be used)
* Verify the IdP parsed it correctly (run the SamlConf tests)
* Verify the SP is sending POST for the `ProtocolBinding` on the `AuthnRequests`
#### Any background context you want to provide?
It is invalid to set the `AuthnRequest`'s `ProtocolBinding` attribute to Redirect:

From section `3.4.1 Element <AuthnRequest>` of the SAML Core document:
> ProtocolBinding [Optional]
> A URI reference that identifies a SAML protocol binding to be used when returning the \<Response\> message...

And section `4.1.2 [SSO] Profile Overview` of the SAML Profiles document:
> 5. Identity Provider issues \<Response\> to Service Provider
>     ... The HTTP Redirect binding MUST NOT be used, as the response will typically exceed the URL length permitted by most user agents.
#### What are the relevant tickets?
[DDF-3862](https://codice.atlassian.net/browse/DDF-3862)
#### Checklist:
- [ ] Documentation Updated
- [X] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by coyotesqrl** [comment]
build now

**Comment by brjeter** [comment]
build now

**Comment by brjeter** [comment]
build now

**Comment by coyotesqrl** [comment]
Intentionally skipping an additional CI/static analysis run after rebase of unrelated code.

**Pull request merged**
