### PR TITLE
[2.19.x] G-9207 allow query results to be cleared

### PR DESCRIPTION
**Pull request by andrewzimmer**
#### What does this PR do?
Allow query results to be cleared

#### Who is reviewing it? 
@cassandrabailey293 @hayleynorton @zta6 @abel-connexta 

#### How should this be tested?
- build / install / verify no regression with query results

#### What are the relevant tickets?
Fixes: #____

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Review by hayleynorton — APPROVED** [review]

**Review by abel-connexta — APPROVED** [review]

**Review by cassandrabailey293 — APPROVED** [review]

**Comment by andrewzimmer** [comment]
build now

**Comment by zta6** [comment]
build now

**Comment by zta6** [comment]
🎉 Hero Successful 🎉 
Verified no regressions in query results

**Comment by andrewzimmer** [comment]
build now

**Comment by andrewzimmer** [comment]
build now

**Comment by shaundmorris** [comment]
Merging. Build failed due to known docker issue.

**Pull request merged**
