### PR TITLE
DDF-1653 Removes erroneous instructions blocks from pom files.

### PR DESCRIPTION
**Pull request by coyotesqrl**
During a routine scan of poms for cruft, these two blocks were found.

@pklinef 
@tbatie 
@jckilmer
@ryeats

Jason, please hero.

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/335)

### CODE REVIEW

**Comment by tbatie** [comment]
:+1:

**Comment by ryeats** [comment]
:+1:

**Comment by shaundmorris** [comment]
Did these <instructions> only exist in lib pom files? Wonder if it was old copy/paste.

**Comment by coyotesqrl** [comment]
Almost positive that's what happened.

**Comment by jckilmer** [comment]
:+1: Built successfully, lgtm.

**Pull request merged**
