### PR TITLE
DDF-3948 Fixed Map Layer Configuration

### PR DESCRIPTION
**Pull request by willwill96**
#### What does this PR do?
Fixes a bug in adding/saving map layers in the catalog  
Servlet is expecting 'X-Requested-With' header from the client in [CsrfFilter.java](https://github.com/codice/ddf/blob/826e07f8ec132d6102e35c4977aa93f5fb2e0295/platform/security/filter/security-filter-csrf/src/main/java/org/codice/ddf/security/filter/csrf/CsrfFilter.java#L106), which wasn't present before  

#### Who is reviewing it? 
@dcruver 
@GabrielFabian 

#### Select relevant component teams: 
https://github.com/orgs/codice/teams
#### Ask 2 committers to review/merge the PR and tag them here. If you don't know who to ask, you can request reviews in https://groups.google.com/forum/#!forum/ddf-developers .
@bdeining
@jlcsmith

#### How should this be tested? (List steps with links to updated documentation)
1. Launch DDF and login to the admin console  
2. Click on Catalog  
3. You should be in a tab labeled "Map Layers Configuration". Click the + button to add a new layer
4. Enter a name and a valid provider (e.g: https://server.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer) and the respective provider type (e.g. ArcGIS Map Server)
5. Click save at the top. At the bottom of the page, you should see a popup that says "Map layers successfully saved"
    - Before my change, the message said "Unexpected end of JSON" and received a 403 Response Forbidden in the console
#### What are the relevant tickets?
[DDF-3948](https://codice.atlassian.net/browse/DDF-3948)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by shaundmorris** [comment]
ok to test

**Comment by shaundmorris** [comment]
@willwill96 can you please add the ticket number on the commits? There is some info here on it as well: https://codice.atlassian.net/wiki/spaces/DDF/pages/6291518/Git+Commit+Message+Guidelines

**Comment by jlcsmith** [comment]
build now

**Comment by gjvera** [comment]
🎉 Hero Successful 🎉 
added a new map layer as specified. 
`Map layers successfully saved`  came up after saving. 

LG2M!

**Pull request merged**
