### PR TITLE
[2.19.x] Update styling for save/cancel buttons in search and result forms

### PR DESCRIPTION
**Pull request by samuelechu**
#### What does this PR do?
Updates styling of save/cancel buttons in search and result forms to match styling of other save/cancel buttons downstream.
 
#### How should this be tested?

- Verify that styling for adding and editing an advanced search within a workspace has not changed (these two components utilize the same styling file used by the search form creation component).
- Bring these changes to the downstream project and verify that the save/cancel buttons are unified across the app

#### What are the relevant tickets?
Fixes: #____

#### Screenshots

image
image

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by rymach** [comment]
dumb question: what's the purpose of the empty ``?

**Review by jrnorth — APPROVED** [review]

**Review by shaundmorris — APPROVED** [review]
Approving assuming we answer @rymach's question. Looks like a comment, but this is why @samuelechu is making the updates

**Comment by samuelechu** [comment]
> dumb question: what's the purpose of the empty `<!-- -->`?

I actually didn't notice those :eyes: I think Shaun is right, they seem to just be empty comments. I'll try removing them.

**Comment by samuelechu** [comment]
build now

**Comment by jrnorth** [comment]
I'll hero this.

**Comment by jrnorth** [comment]
Hero successful. The button styles have been updated in DDF and downstream.

**Comment by shaundmorris** [comment]
@samuelechu, @jrnorth do you think needs to be forwardported to the DDF-UI repo?

**Pull request merged**
