### PR TITLE
DDF-4437 Bumps usng.js version to the latest

### PR DESCRIPTION
**Pull request by BernardIgiri**
Upgraded to newer usng.js library with fixed northing values in lat long to utm conversions.

#### What does this PR do?

Updates the USNG.js library to the latest version which fixes the northing values of UTM coordinates when converted from lat lon coordinates in the southern hemisphere. This fixes the display of UTM coordinates on the 2D and 3D maps when you choose UTM coordinate display from the config menu in the southern hemisphere. This also fixes the display of UTM coordinates when copying UTM coordinates from the 2D and 3D maps in the southern hemisphere.

#### Who is reviewing it? 
@rymach @dimitry-sherman @samuelechu 
#### Ask 2 committers to review/merge the PR and tag them here.
@andrewkfiedler @bdeining 

#### How should this be tested?
Build DDF on the 2D and 3D maps change the coordinate display to UTM/UPS and move to the southern hemisphere any where between the equator and 80 degrees south. Verify that the northing value is NOT negative. Right click and attempt to copy the coordinate and verify that northing coordinate is NOT negative.
#### What are the relevant tickets?
[DDF-4437](https://codice.atlassian.net/browse/DDF-4437)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by BernardIgiri** [comment]
build now

**Comment by rymach** [comment]
usng.js PR https://github.com/codice/usng.js/pull/26
I've tested this version of usng.js in DDF as part of the hero process for that PR

**Comment by rymach** [comment]
00:17:27 [ERROR] error An unexpected error occurred: "http://nexus3.phx.connexta.com/repository/npmjs.org/usng.js/-/usng.js-0.4.1.tgz: Request failed \"404 Not Found\"".

**Comment by BernardIgiri** [comment]
Build now.

**Pull request merged**
