### PR TITLE
DDF-4150 Text Fields in Inspector are Truncated

### PR DESCRIPTION
**Pull request by Corey-Collins**
#### What does this PR do?
Text fields in the inspector (most importantly the description field) are truncated with ellipses `...` which don't let the user view the entire field.

This allows the text field to break into multiple lines, but also has a max height in place so that once it reaches a certain point it will automatically scroll vertically. This is so that an extremely long text field doesn't take up the entire inspector component.

#### Who is reviewing it? 
@brianfelix 
@leo-sakh 
@bellcc 
@jrnorth 

#### Select relevant component teams: 
https://github.com/orgs/codice/teams
#### Ask 2 committers to review/merge the PR and tag them here.
@bdeining 
@millerw8 

#### How should this be tested?
* Upload a metacard
* In the inspector view edit a text field to show that instead of truncating the text with ellipses it will break into a new line.
* Add more text to the field so that the max height is reached and the text is now vertically scrollable.

#### What are the relevant tickets?
[DDF-4150](https://codice.atlassian.net/browse/DDF-4150)
#### Screenshots
Before:
screen shot 2018-09-17 at 9 16 28 am
After fix:
screen shot 2018-09-14 at 3 30 30 pm
screen shot 2018-09-14 at 3 30 47 pm

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by rzwiefel** [comment]
image

The before and after images are rather confusing to me as they don't appear to be really comparing the same things. Could we update these to perhaps show a more apples to apples comparison?

**Comment by willwill96** [comment]
Hero Build Started

**Comment by rzwiefel** [comment]
Much clearer! Thanks!

**Comment by Corey-Collins** [comment]
build now

**Comment by willwill96** [comment]
🎉 Hero Successful 🎉 
- Quickbuilt and installed.
- Ingested a metacard
- Edited the metacard attributes to force a scroll bar to appear.
- Ensured that the attributes are completely visible even when the scroll bar appears. 
- Ensured that multivalued attributes are still distinguishable from each other

capture

**Comment by Corey-Collins** [comment]
build now

**Pull request merged**
