### PR TITLE
DDF-2209 Only decrypt passwords if they are going to be used

### PR DESCRIPTION
**Pull request by singhdan**
#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@pklinef
@stustison
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

Moved decryption of keystore and truststore passwords so that it only occurs if ssl or tls is being used. Minor performance improvement especially if this gets called a lot

### CODE REVIEW

**Comment by shaundmorris** [comment]
@singhdan Is there an open Jira ticket that is associated with this PR?

**Comment by singhdan** [comment]
No, there isn't a PR. Just noticed it as I was browsing the code.

-------- Original message --------

**Comment by stustison** [comment]
Change looks good 👍  We just need the commit message prepended with the issue number (DDF-2209). I took the liberty of creating one for you this time: https://codice.atlassian.net/browse/DDF-2209 You'll need to make an account. Thanks for the PR!

**Comment by singhdan** [comment]
Thanks. I've pre-pended the PR number to the title

**Comment by pklinef** [comment]
It looks like the commit message still does not have the ticket number prepended.  You can use the following directions to update the commit message to include the ticket as well.

https://help.github.com/articles/changing-a-commit-message/

**Comment by pklinef** [comment]
👍  once the commit message includes the ticket number.

**Pull request merged**
