### PR TITLE
DDF-2122 - updated EndpointOperationInfoResourceComparator to return …

### PR DESCRIPTION
**Pull request by kcwire**
#### What does this PR do?
Addresses EndpointOperationInfoResourceComparator returning 0 when 2 operations were not equal.
#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?
@peterhuffer @mweser
#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@jaymcnallie 
@kcwire
#### How should this be tested?
itests :) - also visually verify the logs from CXF are no longer present by running DDF & submitting various requests to the CSW Endpoint (HTTP GET & POST)
#### Any background context you want to provide?
n/a
#### What are the relevant tickets?
DDF-2122
#### Checklist:
- [ ] Documentation Updated
- [x] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

…-1 when no match is found

### CODE REVIEW

**Comment by peterhuffer** [comment]
Ran and passed itests. Verified CXF logs are no longer present.

**Comment by mweser** [comment]
LGTM

**Comment by kcwire** [comment]
👍 
@jaymcnallie any objections?

**Comment by jaymcnallie** [comment]
👍

**Pull request merged**
