### PR TITLE
[2.18.x] DDF-5300 Extract CatalogServiceImpl into separate module to facilitat…

### PR DESCRIPTION
**Pull request by Schachte**
@nsuvarna 
@aj-brooks 
@bdeining 
@harrison-tarr 

#### What does this PR do?
see https://github.com/codice/ddf/issues/5300

### CODE REVIEW

**Comment by Schachte** [comment]
build now

**Comment by bdeining** [comment]
build now

**Comment by Schachte** [comment]
build now (version changes)

**Comment by nsuvarna** [comment]
Hero Successful 🎉 
Intrigue still loads correctly and sources work as expected

**Pull request merged**
