### PR TITLE
DDF-4161 DDF-4176 Master ports

### PR DESCRIPTION
**Pull request by clockard**
##### ABBREVIATED REVIEW BETWEEN 2.13.X AND MASTER IS IN EFFECT
Link to 2.13.x PR: #3802 #3771 
____

#### What does this PR do?
DDF-4161 Fix registry date field validation error
DDF-4176 Update ConfluenceFilterDelegate to handle propertyIsGreaterThan

#### Ask 2 committers to review/merge the PR and tag them here.

@coyotesqrl
@shaundmorris
@tbatie

#### How should this be tested?
CI Build
#### What are the relevant tickets?
[DDF-4161](https://codice.atlassian.net/browse/4161)
[DDF-4176](https://codice.atlassian.net/browse/4176)

### CODE REVIEW

**Comment by clockard** [comment]
build now

**Comment by clockard** [comment]
yarn error
build now

**Comment by kcover** [comment]
I've been seeing this error pretty often lately. I think if you run `yarn format -w` in the ui directory and push up the changes that should fix it.

**Comment by clockard** [comment]
Thanks @kcover! 
build now

**Pull request merged**
