### PR TITLE
[2.20.x] DDF-5928 Renames "src" to "sources" so RPC doesn't fail

### PR DESCRIPTION
**Pull request by stevenmalmgren**
#### What does this PR do?
The front end stores the sources on a query metacard in a property called src. When submitting with an RPC request the src property will be ignored as it doesn't match the "sources" definition on the metacard. 
#### Who is reviewing it? 

@andrewkfiedler
@rzwiefel
@bellcc 
#### What are the relevant tickets?
Fixes: #____

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by bellcc** [comment]
build now

**Comment by bellcc** [comment]
**Hero Successful 🎉** 

1. Created a couple of queries. 
2. Verified that the sources are saving properly on each query.

**Comment by jlcsmith** [comment]
build now

**Comment by bellcc** [comment]
build now

**Comment by jordanwilking** [comment]
build now

**Comment by jlcsmith** [comment]
build now

**Pull request merged**
