### PR TITLE
DDF-1865 Cleanup Based on Review Comments

### PR DESCRIPTION
**Pull request by oscaritoro**
#### What does this PR do?
Cleans up some non logic issues that where brought up during the review of the 2.9.0.Alpha2 backport
#### Who is reviewing it?
@pklinef @jckilmer @mcalcote @shaundmorris @stustison @brianfelix @clockard 
#### How should this be tested?
Build ddf
#### What are the relevant tickets?
DDF-1865
#### Checklist:
- [ ] Documentation Updated - No updates necessary for this.
- [X] Update / Add Unit Tests
- [ ] Update / Add Integration Tests - No updates or new integration tests necessary for this.

### CODE REVIEW

**Comment by shaundmorris** [comment]
:+1:

**Comment by stustison** [comment]
Looks like there is a legit bamboo compile error on this one. :+1: after bamboo completes

**Comment by oscaritoro** [comment]
Fixed... file renames (letter case) had not gone through to git.

**Comment by clockard** [comment]
:+1:

**Comment by pklinef** [comment]
I am not a fan of commit messages that basically say they are working off PR comments since you lose context when viewing it from git but other than that it looks :+1: to me.

**Comment by brianfelix** [comment]
:+1:

**Comment by kcwire** [comment]
If documentation or itests are not going to be updated, please provide an explanation as to why.

**Pull request merged**
