### PR TITLE
Implemented CRC32 and MD5 CheckSumProvider

### PR DESCRIPTION
**Pull request by EIrwin**
Implemented Checksum capabilities that can be used by a CheckSumPlugin. CheckSumPlugin is an implementation of a newly created PreCreateStoragePlugin.

@jlcsmith  is hero
@jrnorth
@beyelerb

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/310)

### CODE REVIEW

**Comment by jrnorth** [comment]
Reviewed 23 of 26 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 15 unresolved discussions.

---

<sup>**[catalog/content/core/content-core-catalogerplugin/src/main/java/ddf/content/plugin/cataloger/CatalogContentPlugin.java, line 107 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/310#-K2i5ONa8iWQI11C96jV)** ([raw file](https://github.com/codice/ddf/blob/a13390df8dd95f16b792cb7c05b633aa03645534/catalog/content/core/content-core-catalogerplugin/src/main/java/ddf/content/plugin/cataloger/CatalogContentPlugin.java#L107)):</sup>
Why did this change from `response` to `input`?


---

<sup>**[catalog/content/core/content-core-catalogerplugin/src/main/java/ddf/content/plugin/cataloger/CatalogContentPlugin.java, line 254 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/310#-K2i5jJMYBL1cGZn_Dct)** ([raw file](https://github.com/codice/ddf/blob/a13390df8dd95f16b792cb7c05b633aa03645534/catalog/content/core/content-core-catalogerplugin/src/main/java/ddf/content/plugin/cataloger/CatalogContentPlugin.java#L254)):</sup>
Is this check necessary? I don't think it's possible for `contentMetacard` to be `null` here.


---

<sup>**[catalog/content/core/content-core-catalogerplugin/src/main/java/ddf/content/plugin/cataloger/CatalogContentPlugin.java, line 303 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/310#-K2i9AN2CRDN_hPH-AqG)** ([raw file](https://github.com/codice/ddf/blob/a13390df8dd95f16b792cb7c05b633aa03645534/catalog/content/core/content-core-catalogerplugin/src/main/java/ddf/content/plugin/cataloger/CatalogContentPlugin.java#L303)):</sup>
Might be better to just cast to a `String` since it's more explicit: http://stackoverflow.com/a/676378/2480705.


---

<sup>**[catalog/content/core/content-core-checksumplugin/src/main/java/ddf/content/plugin/checksum/Checksum.java, line 47 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/310#-K2i9jy1ke685J3kiN56)** ([raw file](https://github.com/codice/ddf/blob/a13390df8dd95f16b792cb7c05b633aa03645534/catalog/content/core/content-core-checksumplugin/src/main/java/ddf/content/plugin/checksum/Checksum.java#L47)):</sup>
Extra parentheses.


---

<sup>**[catalog/content/core/content-core-checksumplugin/src/main/java/ddf/content/plugin/checksum/Checksum.java, line 54 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/310#-K2iA0nQUzcSBP8c_TP-)** ([raw file](https://github.com/codice/ddf/blob/a13390df8dd95f16b792cb7c05b633aa03645534/catalog/content/core/content-core-checksumplugin/src/main/java/ddf/content/plugin/checksum/Checksum.java#L54)):</sup>
These two cases could be merged into one `catch` since they're the same.


---

<sup>**[catalog/content/core/content-core-checksumplugin/src/test/java/ddf/content/plugin/checksum/TestChecksum.java, line 43 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/310#-K2iAQbTyKJ1eJGhYkx3)** ([raw file](https://github.com/codice/ddf/blob/a13390df8dd95f16b792cb7c05b633aa03645534/catalog/content/core/content-core-checksumplugin/src/test/java/ddf/content/plugin/checksum/TestChecksum.java#L43)):</sup>
`String`


---

<sup>**[catalog/content/core/content-core-checksumplugin/src/test/java/ddf/content/plugin/checksum/TestChecksum.java, line 78 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/310#-K2iAhAzEzCmCO4Ej_Jq)** ([raw file](https://github.com/codice/ddf/blob/a13390df8dd95f16b792cb7c05b633aa03645534/catalog/content/core/content-core-checksumplugin/src/test/java/ddf/content/plugin/checksum/TestChecksum.java#L78)):</sup>
We should use `assertThat` instead of `assertEquals`.


---

<sup>**[catalog/content/core/content-core-checksumplugin/src/test/java/ddf/content/plugin/checksum/TestChecksum.java, line 85 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/310#-K2iAaYEzQSrcjsVCiEM)** ([raw file](https://github.com/codice/ddf/blob/a13390df8dd95f16b792cb7c05b633aa03645534/catalog/content/core/content-core-checksumplugin/src/test/java/ddf/content/plugin/checksum/TestChecksum.java#L85)):</sup>
Don't need to cast `null`.


---

<sup>**[catalog/content/core/content-core-impl/src/main/java/ddf/content/data/impl/ContentMetacardType.java, line 43 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/310#-K2iB2EVC8CN0r_ePD6x)** ([raw file](https://github.com/codice/ddf/blob/a13390df8dd95f16b792cb7c05b633aa03645534/catalog/content/core/content-core-impl/src/main/java/ddf/content/data/impl/ContentMetacardType.java#L43)):</sup>
Will these attributes need to be indexed? Do we think we'll need to search on these attributes?


---

<sup>**[libs/checksum/src/main/java/org/codice/ddf/checksum/ChecksumProvider.java, line 31 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/310#-K2iDCLzOGId3ioPPvKp)** ([raw file](https://github.com/codice/ddf/blob/a13390df8dd95f16b792cb7c05b633aa03645534/libs/checksum/src/main/java/org/codice/ddf/checksum/ChecksumProvider.java#L31)):</sup>
`getChecksumAlgorithm`?


---

<sup>**[libs/checksum/src/main/java/org/codice/ddf/checksum/impl/CRC32ChecksumProvider.java, line 27 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/310#-K2iJLDoUdhgiptjNMyE)** ([raw file](https://github.com/codice/ddf/blob/a13390df8dd95f16b792cb7c05b633aa03645534/libs/checksum/src/main/java/org/codice/ddf/checksum/impl/CRC32ChecksumProvider.java#L27)):</sup>
Maybe `BaseChecksumProvider` should be an abstract class and implement `ChecksumProvider`?


---

<sup>**[libs/checksum/src/main/java/org/codice/ddf/checksum/impl/CRC32ChecksumProvider.java, line 36 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/310#-K2iDSYyyu2Wq1zCzSvv)** ([raw file](https://github.com/codice/ddf/blob/a13390df8dd95f16b792cb7c05b633aa03645534/libs/checksum/src/main/java/org/codice/ddf/checksum/impl/CRC32ChecksumProvider.java#L36)):</sup>
Are you sure you want to return `null`? Seems like an `IllegalArgumentException` would be more appropriate.


---

<sup>**[libs/checksum/src/main/java/org/codice/ddf/checksum/impl/CRC32ChecksumProvider.java, line 49 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/310#-K2iDoE3sBAdSNtn78Cl)** ([raw file](https://github.com/codice/ddf/blob/a13390df8dd95f16b792cb7c05b633aa03645534/libs/checksum/src/main/java/org/codice/ddf/checksum/impl/CRC32ChecksumProvider.java#L49)):</sup>
`IOException`s will also return `null`. If this is the desired behavior, it should be documented in the javadoc. Have you considered throwing an exception instead?


---

<sup>**[libs/checksum/src/main/java/org/codice/ddf/checksum/impl/MD5ChecksumProvider.java, line 47 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/310#-K2iJZ5LFk2rEapDgV74)** ([raw file](https://github.com/codice/ddf/blob/a13390df8dd95f16b792cb7c05b633aa03645534/libs/checksum/src/main/java/org/codice/ddf/checksum/impl/MD5ChecksumProvider.java#L47)):</sup>
I think `LOGGER.error("Error obtaining MessageDigest using algorithm: {}", DIGEST_ALGORITHM, e);` would be preferable.


---

<sup>**[libs/checksum/src/test/java/org/codice/ddf/checksum/TestCRCChecksumProvider.java, line 56 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/310#-K2iKTfObkRUPpVu3bU_)** ([raw file](https://github.com/codice/ddf/blob/a13390df8dd95f16b792cb7c05b633aa03645534/libs/checksum/src/test/java/org/codice/ddf/checksum/TestCRCChecksumProvider.java#L56)):</sup>
`assertThat`


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/310)

**Comment by EIrwin** [comment]
<sup>**[catalog/content/core/content-core-impl/src/main/java/ddf/content/data/impl/ContentMetacardType.java, line 43 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/310#-K2iB2EVC8CN0r_ePD6x)** ([raw file](https://github.com/codice/ddf/blob/a13390df8dd95f16b792cb7c05b633aa03645534/catalog/content/core/content-core-impl/src/main/java/ddf/content/data/impl/ContentMetacardType.java#L43)):</sup>
yes and yes


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/310)

**Comment by EIrwin** [comment]
<sup>**[libs/checksum/src/main/java/org/codice/ddf/checksum/impl/CRC32ChecksumProvider.java, line 49 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/310#-K2iDoE3sBAdSNtn78Cl)** ([raw file](https://github.com/codice/ddf/blob/a13390df8dd95f16b792cb7c05b633aa03645534/libs/checksum/src/main/java/org/codice/ddf/checksum/impl/CRC32ChecksumProvider.java#L49)):</sup>
Good idea


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/310)

**Comment by jrnorth** [comment]
Looks like you need to run the code formatter on these files.


---

Reviewed 10 of 10 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

<sup>**[catalog/content/core/content-core-checksumplugin/src/test/java/ddf/content/plugin/checksum/TestChecksum.java, line 80 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/310#-K2nCFCUEzzzXd5d-gRQ)** ([raw file](https://github.com/codice/ddf/blob/eb0980b1c3042e76417f7157aae0e1df1b245890/catalog/content/core/content-core-checksumplugin/src/test/java/ddf/content/plugin/checksum/TestChecksum.java#L80)):</sup>
You could do `is(SAMPLE_CHECKSUM_VALUE)` instead since there is a shortcut `is` method to `is(equalTo(x))`: http://hamcrest.org/JavaHamcrest/javadoc/1.3/org/hamcrest/Matchers.html#is(T).


---

<sup>**[libs/checksum/src/main/java/org/codice/ddf/checksum/impl/CRC32ChecksumProvider.java, line 49 \[r2\]](https://reviewable.io:443/reviews/codice/ddf/310#-K2iDoE3sBAdSNtn78Cl)** ([raw file](https://github.com/codice/ddf/blob/a13390df8dd95f16b792cb7c05b633aa03645534/libs/checksum/src/main/java/org/codice/ddf/checksum/impl/CRC32ChecksumProvider.java#L49)):</sup>
Typically if you throw an exception you don't log it, since someone else higher up the chain will.


---

<sup>**[libs/checksum/src/test/java/org/codice/ddf/checksum/TestCRCChecksumProvider.java, line 93 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/310#-K2nF3UL36aX9pef8RHX)** ([raw file](https://github.com/codice/ddf/blob/eb0980b1c3042e76417f7157aae0e1df1b245890/libs/checksum/src/test/java/org/codice/ddf/checksum/TestCRCChecksumProvider.java#L93)):</sup>
This test can be shortened since you're just testing that an input of `null` will result in an `IllegalArgumentException`.  I think your test body could just be `checksumProvider.calculateChecksum(null)`; you don't have to handle the `IOException` (and you shouldn't, because the test should fail if an `IOException` occurs).


---

<sup>**[libs/checksum/src/test/java/org/codice/ddf/checksum/TestMD5ChecksumProvider.java, line 79 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/310#-K2nq8R2Idzo3OhhZ8mr)** ([raw file](https://github.com/codice/ddf/blob/eb0980b1c3042e76417f7157aae0e1df1b245890/libs/checksum/src/test/java/org/codice/ddf/checksum/TestMD5ChecksumProvider.java#L79)):</sup>
Should this test be expecting an `IllegalArgumentException`?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/310)

**Comment by EIrwin** [comment]
<sup>**[libs/checksum/src/test/java/org/codice/ddf/checksum/TestCRCChecksumProvider.java, line 93 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/310#-K2nF3UL36aX9pef8RHX)** ([raw file](https://github.com/codice/ddf/blob/eb0980b1c3042e76417f7157aae0e1df1b245890/libs/checksum/src/test/java/org/codice/ddf/checksum/TestCRCChecksumProvider.java#L93)):</sup>
Correct, good call


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/310)

**Comment by jlcsmith** [comment]
Global comment  - on exceptions handling, avoid log & throw logic: http://rolf-engelhard.de/2013/04/logging-anti-patterns-part-ii/.  Either log the exception or throw it, but don't do both.


---

Reviewed 6 of 27 files at r1, 2 of 10 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

<sup>**[catalog/content/core/content-core-catalogerplugin/src/main/java/ddf/content/plugin/cataloger/CatalogContentPlugin.java, line 282 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/310#-K2rF5b-NKVQZJO7JCTw)** ([raw file](https://github.com/codice/ddf/blob/eb0980b1c3042e76417f7157aae0e1df1b245890/catalog/content/core/content-core-catalogerplugin/src/main/java/ddf/content/plugin/cataloger/CatalogContentPlugin.java#L282)):</sup>
Can we limit the size of this try/catch block?  Also, why not throw a MetacardCreationException here from the root exception?  We are losing the details of the original exception by only logging at debug and not re-throwing. 


---

<sup>**[libs/checksum/src/main/java/org/codice/ddf/checksum/impl/CRC32ChecksumProvider.java, line 36 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/310#-K2rGY8IjfyIk--owx2a)** ([raw file](https://github.com/codice/ddf/blob/eb0980b1c3042e76417f7157aae0e1df1b245890/libs/checksum/src/main/java/org/codice/ddf/checksum/impl/CRC32ChecksumProvider.java#L36)):</sup>
Just throw the exception - no need to also log it.


---

<sup>**[libs/checksum/src/main/java/org/codice/ddf/checksum/impl/CRC32ChecksumProvider.java, line 49 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/310#-K2rGhJDNynxOcbp7gYg)** ([raw file](https://github.com/codice/ddf/blob/eb0980b1c3042e76417f7157aae0e1df1b245890/libs/checksum/src/main/java/org/codice/ddf/checksum/impl/CRC32ChecksumProvider.java#L49)):</sup>
just throw the exception


---

<sup>**[libs/checksum/src/main/java/org/codice/ddf/checksum/impl/MD5ChecksumProvider.java, line 47 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/310#-K2rH4MxeHua-qKI4via)** ([raw file](https://github.com/codice/ddf/blob/eb0980b1c3042e76417f7157aae0e1df1b245890/libs/checksum/src/main/java/org/codice/ddf/checksum/impl/MD5ChecksumProvider.java#L47)):</sup>
In the CRC checksum provider, you threw exceptions instead of logging and returning null.  I think we should handle error cases consistently. 


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/310)

**Comment by EIrwin** [comment]
<sup>**[catalog/content/core/content-core-catalogerplugin/src/main/java/ddf/content/plugin/cataloger/CatalogContentPlugin.java, line 282 \[r3\]](https://reviewable.io:443/reviews/codice/ddf/310#-K2rF5b-NKVQZJO7JCTw)** ([raw file](https://github.com/codice/ddf/blob/eb0980b1c3042e76417f7157aae0e1df1b245890/catalog/content/core/content-core-catalogerplugin/src/main/java/ddf/content/plugin/cataloger/CatalogContentPlugin.java#L282)):</sup>
I don't disagree on any of this, but this is original code not specific to this ticket. I would suggest that we create a separate ticket for both of your suggestions as they fall out of the scope of this ticket.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/310)

**Comment by jrnorth** [comment]
Reviewed 9 of 9 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

<sup>**[libs/checksum/src/main/java/org/codice/ddf/checksum/ChecksumProvider.java, line 27 \[r4\]](https://reviewable.io:443/reviews/codice/ddf/310#-K2xxw-uYHw0orNpmiCL)** ([raw file](https://github.com/codice/ddf/blob/974965f0aeef37b4d8f82d366969c7b0b4b2154c/libs/checksum/src/main/java/org/codice/ddf/checksum/ChecksumProvider.java#L27)):</sup>
I wonder whether having `NoSuchAlgorithmException` as part of the method signature is appropriate. If the client of the `ChecksumProvider` caught this exception, I don't think there's anything they could do because the `ChecksumProvider` doesn't allow them to use a different algorithm. You could make something like a `ChecksumException` class and use it to wrap other exceptions thrown inside the `ChecksumProvider`, but that seems like it might be overkill. I'm not sure what the best option would be.


---

<sup>**[libs/checksum/src/main/java/org/codice/ddf/checksum/impl/CRC32ChecksumProvider.java, line 49 \[r4\]](https://reviewable.io:443/reviews/codice/ddf/310#-K2xutvAjyKcImHeTAat)** ([raw file](https://github.com/codice/ddf/blob/974965f0aeef37b4d8f82d366969c7b0b4b2154c/libs/checksum/src/main/java/org/codice/ddf/checksum/impl/CRC32ChecksumProvider.java#L49)):</sup>
If all you're going to do is rethrow the exception, then you don't need to catch it.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/310)

**Pull request merged**
