### PR TITLE
DDF-1729 Renames platform-configuration-listener module

### PR DESCRIPTION
**Pull request by andrewkfiedler**
- Renames platform-configuration-listener module to platform-configuration-migration

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/codice/ddf/pull/413" target="_blank">ReviewNinja

**Comment by andrewkfiedler** [comment]
@figliold , @lessarderic

**Comment by lessarderic** [comment]
:+1:

**Comment by figliold** [comment]
PRBS passed. :+1:

**Pull request merged**
