### PR TITLE
DDF-1787: As an administrator, I want the config-export command to exclude files that are symlinked

### PR DESCRIPTION
**Pull request by bantillo**
Added code to handle sybolic links during export. Also updated documentation with comment with symbolic links.

@lessarderic @figliold @garrettfreibott @Lambeaux @oconnormi @andrewkfiedler

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/codice/ddf/pull/473" target="_blank">ReviewNinja

**Comment by garrettfreibott** [comment]
I think something weird happened with the last push
screen shot 2016-01-19 at 10 26 03

**Comment by bantillo** [comment]
@garrettfreibott: i did a rebase merge, not quite sure how to fix that

**Comment by bantillo** [comment]
This pull request is superseded by https://github.com/codice/ddf/pull/477 and is no longer needed.

**Pull request closed without merging**
