### PR TITLE
DDF-3584 - Collapses UI modules into a single maven module

### PR DESCRIPTION
**Pull request by djblue**
#### What does this PR do?

It centralizes the dependency installation, building and packaging of all UI modules into a single maven module.

*NOTE: when reviewing look at commits separately*

The following are the consequences of collapsing all the UI modules into a
single maven module:

- Reduces build overhead by requiring only a single instance of node/yarn
  to be installed for all UI builds.

- Increases build stability by reducing the chance of multiple yarn
  processes dead-locking as they read/write from the cache.

- Reduces build IO as project `node_modules` tend to be smaller because
  most of their dependencies get hoisted and written once into the parent
  project. This was accomplished using [yarn workspaces](https://yarnpkg.com/lang/en/docs/workspaces/).

- Developers can more easily skip all ui builds by specifying the `-pl \!ui`
  maven flag.

- Easier to share common tooling among the projects, specifically for
  testing and building.

- Improves utilization of the browser cache enabled by sharing the
  `/webjars` context path and the cache busting query parameter
  `?bust=${timestamp}`. All the webjars have been packaged into a
  single web application bundle at the context path `/webjars`. As a
  consequence the context path does need to be whitelisted.

- Reduces tech debt by not embedding `jetty-servlets` in every web
  application bundle.

- Reduces boilerplate as each project does not need to maintain it's own
  web.xml. It is now generated as part of the packaging at build time
  which also improves consistency.

- Allows experimentation with sharing code among various ui projects. An
  example would be sharing the query tool in Intrigue with the Sources
  Wizard to allow admins to test sources before adding them to DDF.

- Allows experimentation with using other means of composition reducing the
  need for iframe composition.

#### Who is reviewing it?

@tbatie
@garrettfreibott 
@stustison 

Since this PR has a lot of moving pieces, some of the things I want reviewers to pay attention to are:

- A lot of the names in the `package.json` are inconsistent with the directory names and `pom.xml`s. Any suggestion on which names to use would be very helpful.

- What should be documented to ease development for future developers?

#### Select relevant component teams: 

@codice/ui 
@codice/build 

#### Choose 2 committers to review/merge the PR. 

@andrewkfiedler 
@pklinef

#### How should this be tested? (List steps with links to updated documentation)

- Full build (`mvn clean install`) new ui maven module
- Quick build
- Ensure distribution starts up correctly and no errors in the logs
- Navigate to all the UI's and ensure they load correctly

*NOTE: The testing should be performed on multiple platforms.*

#### Any background context you want to provide?

Previously, every UI module was managed as an independent maven module. This PR collapses all of those modules into a single maven module in an effort to improve build performance and build stability.

#### What are the relevant tickets?

[DDF-3584](https://codice.atlassian.net/browse/DDF-3584)

#### Checklist:

- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by pklinef** [comment]
Please verify that a release dry run with a clean repository still works.
https://codice.atlassian.net/wiki/spaces/DDF/pages/1179841/Release+Guide

**Comment by andrewkfiedler** [comment]
Found two issues, haven't verified if they're related or not yet.

screen shot 2018-02-12 at 4 38 07 pm

screen shot 2018-02-12 at 4 35 16 pm

**Comment by djblue** [comment]
@andrewkfiedler this issue was related to generating a new `yarn.lock` file. The new one was bringing it two versions of jquery which was causing this error. After generating a correct `yarn.lock` everything seems to be working correctly again.

**Comment by andrewkfiedler** [comment]
🌮 🎉 

Looks good to me.

**Comment by djblue** [comment]
build now

**Comment by djblue** [comment]
build now

**Comment by djblue** [comment]
build now

**Pull request merged**
