### PR TITLE
DDF-1491: Fix TestSolrCommands.testSolrBackupNumToKeep()

### PR DESCRIPTION
**Pull request by lessarderic**
Changed tests to poll or file creation to prevent tests from failing
because of timing issues.

@wmcnalli, @kcwire, @roelens8 please review.

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/195)

### CODE REVIEW

**Comment by wmcnalli** [comment]
:+1: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/195)

**Comment by kcwire** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSolrCommands.java, line 104 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/195#-JzveJq5hidv6T9zqBVq)** ([raw file](https://github.com/codice/ddf/blob/82301321d6ff61be8f6587b9026173c673c8fa7e/distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSolrCommands.java#L104)):</sup>
Safe to assume that if this thing isn't written within 10 seconds it's a failure (probably is just want to be reassured). Could we query solr directly and get the status of the current backup (not sure if we have all the info we need to make that call)?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/195)

**Comment by wmcnalli** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSolrCommands.java, line 104 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/195#-JzveJq5hidv6T9zqBVq)** ([raw file](https://github.com/codice/ddf/blob/82301321d6ff61be8f6587b9026173c673c8fa7e/distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestSolrCommands.java#L104)):</sup>
Yes - I think it's safe to assume.  It was backing up indexes of 2GB in 1-2 seconds when i was initially testing the command.  Does not appear there is a way to query Solr for the status  of a backup.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/195)

**Comment by lessarderic** [comment]
@wmcnalli, the PR build failed on the last assert which seems to indicate that too many backup files got created. Any idea how could that be?

**Comment by roelens8** [comment]
This test is only failing during bamboo builds and not during local builds or when running the test locally.

**Comment by kcwire** [comment]
@lessarderic my guess is the upgrade to Solr 4.10.4 actually fixed the -1 issue.  Couldn't find it in Solr JIRA but my money is removing the `-1` and it will work consistently.

**Comment by roelens8** [comment]
@kcwire I actually added the -1 to fix this test because it started failing on my local machine when I upgraded to Solr 4.10.4 by always creating one less backup than "numToKeep". So, I thought maybe the behavior changed in the new Solr version. Maybe that's not the case, however, can't explain why it's only in Bamboo.

**Comment by wmcnalli** [comment]
@lessarderic I don't know what is going on.  :(   I'm fine if you want to push an @Ignore on that test and then I can take a look at it later.

**Comment by lessarderic** [comment]
@wmcnalli, just added the `@Ignore`. As soon as the build passes I'll go ahead and merge to master. I'll keep the ticket open until we can find the root cause. I'll be in sprint planning most of the day today so if you have time to look into it in the mean time, go ahead. Otherwise I'll take another look later on today or tomorrow.

**Pull request merged**
