### PR TITLE
DDF-3244 CacheBulkProcessor does not account for size of bulk reques…

### PR DESCRIPTION
**Pull request by dcruver**
…t when flushing

#### What does this PR do?
Adds the concept of a CacheBulkProcessor CacheStrategy with three available options: 'All', 'None' and 'Federated'.The strategy is configurable through the Admin UI, so a metatype was also added.

#### Who is reviewing it? 
@gordocanchola 
@spearskw 

(please choose AT LEAST two reviewers that need to approve the PR before it can get merged)
#### Select relevant component teams: 
@beyelerb
@jlcsmith
@kcwire
@pklinef
@clockard 

#### How should this be tested? (List steps with links to updated documentation)
// Test the 'All' (default) setting

    Configure a federated source
    Perform a query
    go to http://localhost:8993/solr and verify that both local and federated query results are in SOLR's cache core

//Test the 'Federated' setting

    In the Karaf console, issue the 'catalog:removeall' command
    in the Karaf console, issue the 'catalog:removeall --cache' command
    With the previous federated source still configured, perform a query
    go to http://localhost:8993/solr and verify that only the federated query results are in SOLR's cache core

//Test the 'None' setting

    In the Karaf console, issue the 'catalog:removeall' command
    in the Karaf console, issue the 'catalog:removeall --cache' command
    With the previous federated source still configured, perform a query
    go to http://localhost:8993/solr and verify that SOLR's cache core is empty

#### Any background context you want to provide?
During the development of this story, it was determined that calculating the size of a given item is too expensive to rely on to determine which results to cache. We settled on separating cached results based on whether they're local or federated.

#### What are the relevant tickets?
DDF-3244

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests
#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by kcwire** [comment]
build now

**Comment by kcwire** [comment]
build now

**Comment by dcruver** [comment]
build now

**Comment by kcwire** [comment]
build now

**Comment by dcruver** [comment]
build now

**Comment by dcruver** [comment]
build now

**Comment by dcruver** [comment]
build now

**Comment by dcruver** [comment]
build now

**Comment by dcruver** [comment]
build now

**Comment by dcruver** [comment]
build now

**Comment by dcruver** [comment]
build now

**Pull request merged**
