### PR TITLE
[2.19.x] G-8885; Use window.event instead of event

### PR DESCRIPTION
**Pull request by cassandrabailey293**
#### What does this PR do?
This PR fixes an issue where the anyGeo component was jumping off the search form in a specific version of Firefox. The problem was the usage of `event` in the `padEndWithZeros` method, which was being called many times by the pipe function. I removed the pipe function since we only want to call `padEndWIthZeros` when switching to the DMS tab from other tabs.

#### Who is reviewing it? 

@hayleynorton @andrewzimmer @zta6 @abel-connexta 

#### Select relevant component teams: 

@codice/ui 
#### How should this be tested?

0. build, profile/install
1. Verify no regression with DMS coordinate entry/switching tabs
2. Download Firefox 60 ESR: https://ftp.mozilla.org/pub/firefox/releases/60.0esr/mac/en-US/
3. Go to the UI and Advanced Search -> anyGeo
4. Select Bounding Box
5. Switch to the DMS tab
6. Verify that there is no `event is not defined` error in the console and that the component works as expected
7. Repeat for Point Radius

#### What are the relevant tickets?
Fixes: #

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Review by mojogitoverhere — APPROVED** [review]

**Review by andrewzimmer — APPROVED** [review]

**Comment by mojogitoverhere** [comment]
hero in progress

**Comment by mojogitoverhere** [comment]
build now

**Review by abel-connexta — APPROVED** [review]

**Comment by mojogitoverhere** [comment]
build now

**Comment by mojogitoverhere** [comment]
build now

**Comment by mojogitoverhere** [comment]
build now

**Review by zta6 — APPROVED** [review]

**Review by mojogitoverhere — APPROVED** [review]

**Comment by mojogitoverhere** [comment]
build now

**Comment by mojogitoverhere** [comment]
## 🎉 Hero build was successful! 🎉 ##

1. Verified no regressions with DMS coord entry / switching tabs for point radii and bounding boxes
2. Ran the same tests with Firefox v60 and no errors were thrown in the console

**Review by Lambeaux — APPROVED** [review]

**Pull request merged**
