### PR TITLE
DDF-1534 p12-keystore-types

### PR DESCRIPTION
**Pull request by ahoffer**
Add system property for truststore type

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/256)

### CODE REVIEW

**Comment by stustison** [comment]
KeystoreValidator? MetricsWebConsolePlugin?

**Comment by AzGoalie** [comment]
Reviewed 2 of 5 files at r1, 5 of 6 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/256)

**Comment by roelens8** [comment]
Reviewed 2 of 5 files at r1, 4 of 6 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/256)

**Comment by ahoffer** [comment]
Travis hero-ed it and declared success.

I hero-ed it as well. The PRBS script build DDF and DIB fine, but failed to execute any DIB itests.
i ran mvn test in my itests directory and all itests then passed with out issue. Results of 

```
/private/tmp/prbs/dib/dib/distribution/test/itests/test-itests-dib $ mvn test 
```

<pre>
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 37:07 min
[INFO] Finished at: 2015-10-15T14:38:43-07:00
[INFO] Final Memory: 47M/661M
[INFO] ------------------------------------------------------------------------
</pre>

**Comment by shaundmorris** [comment]
Verified with a local build and verified bamboo build

**Pull request merged**
