### PR TITLE
[2.11.x] DDF-2824 corrected typo in docs template and jbake.properties file

### PR DESCRIPTION
**Pull request by ricklarsen**
#### What does this PR do?

- fixes jbake type declaration that was not following convention. All type names should be camel case.

#### Who is reviewing it? 
@mcalcote @oconnormi 

#### Choose 2 committers to review/merge the PR. 
@clockard
@coyotesqrl
@lessarderic
@pklinef
@ricklarsen - Documentation
@rzwiefel
@shaundmorris

#### How should this be tested? (List steps with links to updated documentation)

- build logs were showing a null pointer exception. Docs still rendered as expected. Error should be gone now.

#### What are the relevant tickets?
[DDF-2824](https://codice.atlassian.net/browse/DDF-2824)

#### Checklist:
- [x] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests
#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by ricklarsen** [comment]
build now

**Comment by ricklarsen** [comment]
build now

**Comment by bdeining** [comment]
build now

**Comment by ricklarsen** [comment]
build now

**Pull request merged**
