### PR TITLE
[2.26.x] Add missing features to the distribution

### PR DESCRIPTION
**Pull request by SmithJosh**
#### What does this PR do?
https://github.com/codice/ddf/pull/6371 was supposed to remove only unused features from DDF, but it also removed a few that were used, causing installation to fail with a clean m2. This PR adds the missing features
 
#### Select relevant component teams: 
@codice/build 

#### How should this be tested?

Build and run these changes. Verify the standard profile can be installed with a clean .m2 repo. 

#### What are the relevant tickets?
Fixes: #____

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Review by jordanwilking — APPROVED** [review]

**Review by jzstern — APPROVED** [review]

**Review by vinamartin — APPROVED** [review]

**Review by emmberk — APPROVED** [review]

**Comment by jordanwilking** [comment]
🗺️ Hero Successful 🗺️

#### Steps

1. Built, changed my .m2 name to simulated an empty .m2, and started ddf
2. Ran "profile:install standard" without any issues

**Comment by SmithJosh** [comment]
build now

**Comment by jlcsmith** [comment]
build now

**Comment by SmithJosh** [comment]
Failed on known flakey itest. build now

**Pull request merged**
