### PR TITLE
DDF-3753 Re-enable CDM component tests

### PR DESCRIPTION
**Pull request by lessarderic**
#### What does this PR do?
Updated CDM component tests to use PortFinder class and re-enabled.
Also changed how the ContentDirectoryMonitor detroy() method cleaned
up routes.

#### Who is reviewing it? 
(please choose AT LEAST two reviewers that need to approve the PR before it can get merged)
@peterhuffer 
@tbatie 

#### Select relevant component teams: 
https://github.com/orgs/codice/teams/test
#### Choose 2 committers to review/merge the PR.
@brendan-hofmann
@clockard

#### How should this be tested? (List steps with links to updated documentation)

1. Configure multiple CDMs, shut down DDF, restart and make sure CDMs are still working as expected.
2. Configure multiple CDMs, delete one, shut down DDF, restart and make sure only the ones that were not deleted are still there and working as expected.
3. Run a full parallel build and make sure there are no port conflicts.

#### What are the relevant tickets?
[DDF-3753](https://codice.atlassian.net/browse/DDF-3753)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [x] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by brendan-hofmann** [comment]
build now

**Comment by brendan-hofmann** [comment]
build now

**Comment by brendan-hofmann** [comment]
build now

**Comment by lessarderic** [comment]
build now

**Comment by lessarderic** [comment]
build now

**Comment by lessarderic** [comment]
build now

**Pull request merged**
