### PR TITLE
DDF-1744 fix owasp findings

### PR DESCRIPTION
**Pull request by ryeats**
@rzwiefel @coyotesqrl @wbarnie @tbatie @jckilmer @roelens8

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/codice/ddf/pull/443" target="_blank">ReviewNinja

**Comment by coyotesqrl** [comment]
:+1:

**Comment by roelens8** [comment]
:+1:

**Comment by coyotesqrl** [comment]
Heroed successfully. :+1:

**Pull request merged**
