### PR TITLE
DDF-1481: Add the capability to find the nearest cities to a metacard

### PR DESCRIPTION
**Pull request by jrnorth**
Added to the GeoNames Query OSGi service.

@kcwire 
@EIrwin is the hero
@bdeining 
@wmcnalli

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/165)

### CODE REVIEW

**Comment by bdeining** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[catalog/spatial/geocoding/spatial-geocoding-query/src/main/java/org/codice/ddf/spatial/geocoding/query/GeoNamesQueryLuceneDirectoryIndex.java, line 158 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/165#-JyrUor9htbMgpopOqp5)** ([raw file](https://github.com/codice/ddf/blob/fb69cbff09f4e5125d6ff2cdfd4ea7ce6a727cbc/catalog/spatial/geocoding/spatial-geocoding-query/src/main/java/org/codice/ddf/spatial/geocoding/query/GeoNamesQueryLuceneDirectoryIndex.java#L158)):</sup>
I'm wondering about the conversion between the bearing and the cardinal direction.  Should a bearing of 359 be considered "NW"?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/165)

**Comment by jrnorth** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[catalog/spatial/geocoding/spatial-geocoding-query/src/main/java/org/codice/ddf/spatial/geocoding/query/GeoNamesQueryLuceneDirectoryIndex.java, line 158 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/165#-JyrUor9htbMgpopOqp5)** ([raw file](https://github.com/codice/ddf/blob/fb69cbff09f4e5125d6ff2cdfd4ea7ce6a727cbc/catalog/spatial/geocoding/spatial-geocoding-query/src/main/java/org/codice/ddf/spatial/geocoding/query/GeoNamesQueryLuceneDirectoryIndex.java#L158)):</sup>
The bearings [337.5, 360) will be mapped to the "N" at the end of `directions`.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/165)

**Comment by bdeining** [comment]
:thumbsup: 

---

Reviewed 8 of 8 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/165)

**Comment by kcwire** [comment]
Have you written another ticket to display this information to a user?

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[catalog/spatial/geocoding/spatial-geocoding-index/pom.xml, line 59 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/165#-JzH-mJSfe0D6KhiZFKV)** ([raw file](https://github.com/codice/ddf/blob/fb69cbff09f4e5125d6ff2cdfd4ea7ce6a727cbc/catalog/spatial/geocoding/spatial-geocoding-index/pom.xml#L59)):</sup>
we don't call out this version anywhere else?

---

<sup>**[catalog/spatial/geocoding/spatial-geocoding-query/pom.xml, line 79 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/165#-JzH0AjXJogtigYiLPMb)** ([raw file](https://github.com/codice/ddf/blob/fb69cbff09f4e5125d6ff2cdfd4ea7ce6a727cbc/catalog/spatial/geocoding/spatial-geocoding-query/pom.xml#L79)):</sup>
here's that version again.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/165)

**Comment by EIrwin** [comment]
<sup>**[catalog/spatial/geocoding/spatial-geocoding-api/src/main/java/org/codice/ddf/spatial/geocoding/GeoEntryQueryable.java, line 54 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/165#-JzLdCIDyjYvV5XhrF27)** ([raw file](https://github.com/codice/ddf/blob/fb69cbff09f4e5125d6ff2cdfd4ea7ce6a727cbc/catalog/spatial/geocoding/spatial-geocoding-api/src/main/java/org/codice/ddf/spatial/geocoding/GeoEntryQueryable.java#L54)):</sup>
I would spent the minimal time refactoring this to return an object that contains `Distance`, `Direction` and `City` properties on it. Since nothing is consuming this besides the tests right now, it would be easier to just do it up front. Additionally, since this is in DDF, you are assuming whatever is consuming this will want it as a string, but if they only want to display the  nearest city for example, or want to format it differently, the would have to parse it out.

Also, it might not hurt to include a property to describe the unit of measurement instead of hardcoding `km`. That is not as important, but is equally as simple to do up front and would reduce a headache later on.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/165)

**Comment by millerw8** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[catalog/spatial/geocoding/spatial-geocoding-api/src/main/java/org/codice/ddf/spatial/geocoding/GeoEntryQueryable.java, line 54 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/165#-JzMqDAhWCtpY9W55yD3)** ([raw file](https://github.com/codice/ddf/blob/fb69cbff09f4e5125d6ff2cdfd4ea7ce6a727cbc/catalog/spatial/geocoding/spatial-geocoding-api/src/main/java/org/codice/ddf/spatial/geocoding/GeoEntryQueryable.java#L54)):</sup>
I would consider using meters.  Seems to be a more common default unit in other APIs, and gives you better granularity considering this is an int.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/165)

**Comment by EIrwin** [comment]
<sup>**[catalog/spatial/geocoding/spatial-geocoding-api/src/main/java/org/codice/ddf/spatial/geocoding/GeoEntryQueryable.java, line 54 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/165#-JzMqDAhWCtpY9W55yD3)** ([raw file](https://github.com/codice/ddf/blob/fb69cbff09f4e5125d6ff2cdfd4ea7ce6a727cbc/catalog/spatial/geocoding/spatial-geocoding-api/src/main/java/org/codice/ddf/spatial/geocoding/GeoEntryQueryable.java#L54)):</sup>
Yeah, I don't have any opinion on which unit, I am just saying to not hardcode it in the description and to use a property because it might change based on downstream usage.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/165)

**Comment by kcwire** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[catalog/spatial/geocoding/spatial-geocoding-api/src/main/java/org/codice/ddf/spatial/geocoding/GeoEntryQueryable.java, line 54 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/165#-JzMqDAhWCtpY9W55yD3)** ([raw file](https://github.com/codice/ddf/blob/fb69cbff09f4e5125d6ff2cdfd4ea7ce6a727cbc/catalog/spatial/geocoding/spatial-geocoding-api/src/main/java/org/codice/ddf/spatial/geocoding/GeoEntryQueryable.java#L54)):</sup>
I could see the desire to make this configurable - which probably falls in a new ticket.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/165)

**Comment by wmcnalli** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/165)

**Comment by jrnorth** [comment]
Done.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[catalog/spatial/geocoding/spatial-geocoding-api/src/main/java/org/codice/ddf/spatial/geocoding/GeoEntryQueryable.java, line 54 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/165#-JzLdCIDyjYvV5XhrF27)** ([raw file](https://github.com/codice/ddf/blob/fb69cbff09f4e5125d6ff2cdfd4ea7ce6a727cbc/catalog/spatial/geocoding/spatial-geocoding-api/src/main/java/org/codice/ddf/spatial/geocoding/GeoEntryQueryable.java#L54)):</sup>
Sounds like a good idea.

---

<sup>**[catalog/spatial/geocoding/spatial-geocoding-api/src/main/java/org/codice/ddf/spatial/geocoding/GeoEntryQueryable.java, line 54 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/165#-JzMqDAhWCtpY9W55yD3)** ([raw file](https://github.com/codice/ddf/blob/fb69cbff09f4e5125d6ff2cdfd4ea7ce6a727cbc/catalog/spatial/geocoding/spatial-geocoding-api/src/main/java/org/codice/ddf/spatial/geocoding/GeoEntryQueryable.java#L54)):</sup>
Meters are an interesting option, but I don't think a user would need that level of granularity considering what this API does.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/165)

**Comment by kcwire** [comment]
Reviewed 13 of 13 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/165)

**Comment by wmcnalli** [comment]
Reviewed 10 of 13 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/165)

**Comment by bdeining** [comment]
Reviewed 13 of 13 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/165)

**Comment by EIrwin** [comment]
:thumbsup: 

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/165)

**Comment by EIrwin** [comment]
Pulled this down review was good and build passed.

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/165)

**Comment by EIrwin** [comment]
Reviewed 2 of 8 files at r1, 13 of 13 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/165)

**Pull request merged**
