### PR TITLE
[2.19.x] DDF-5439 Decouple UI and Service Facet Whitelist

### PR DESCRIPTION
**Pull request by willwill96**
#### What does this PR do?
Backport of https://github.com/codice/ddf/pull/5440
#### What are the relevant tickets?
Fixes: #____

#### Checklist:
- [x] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by hayleynorton** [comment]
Hero successful
Verified that attributes on the suggestion list but not on the whitelist did not populate with suggestions, attributes on the whitelist but not on the suggestion list did not populate with suggestions, and attributes on both lists did populate with suggestions. Tested with attributes that were present on at least one result. Attributes on both lists but not present on any results did not populate with suggestions as expected.

**Comment by bdeining** [comment]
build now

**Comment by hayleynorton** [comment]
build now

**Comment by andrewzimmer** [comment]
build now

**Comment by andrewzimmer** [comment]
build now

**Pull request merged**
