### PR TITLE
DDF-05424: [2.19.x] Enum marionette view forced re-render

### PR DESCRIPTION
**Pull request by leo-sakh**
#### What does this PR do?
Please see #5424 

#### Who is reviewing it? 
@bdeining 
@gjvera 
@bennuttle 
@lavoywj 
@jrnorth 

#### Select relevant component teams: 
@codice/ui

#### Ask 2 committers to review/merge the PR and tag them here.
@bdeining
@jrnorth

#### How should this be tested?
Same as: https://github.com/codice/ddf/pull/5429

#### Any background context you want to provide?
Here: https://github.com/codice/ddf/pull/5429

#### What are the relevant tickets?
Fixes: #5424 

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by jrnorth** [comment]
build now

**Comment by gjvera** [comment]
build now

**Comment by jrnorth** [comment]
I'll hero this.

**Comment by jrnorth** [comment]
Hero successful. The coordinate format setting is now synchronized between the two maps.

**Pull request merged**
