### PR TITLE
DDF-3660 Update CDM permissions and docs

### PR DESCRIPTION
**Pull request by peterhuffer**
##### ABBREVIATED REVIEW BETWEEN 2.13.X AND MASTER IS IN EFFECT
Link to 2.13.x PR: #3435

#### Who is reviewing it? 
@emmberk @bakejeyner @jefchng 

#### Ask 2 committers to review/merge the PR and tag them here.
@clockard
@vinamartin

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by peterhuffer** [comment]
build now

**Comment by peterhuffer** [comment]
build now

**Comment by peterhuffer** [comment]
I couldn't reproduce the 2 itest failures locally
build now

**Comment by shaundmorris** [comment]
build now

**Comment by shaundmorris** [comment]
Yarn Error: Error Installing packages from yarn.

build now

**Comment by shaundmorris** [comment]
@peterhuffer  you may want to look at the feedback I got on the URL Resource reader in the configurations.policy file on this PR: https://github.com/codice/ddf/pull/3495

**Pull request merged**
