### PR TITLE
Upgrade to Java 11 for ddf-docker

### PR DESCRIPTION
**Pull request by frnkshin**
#### What does this PR do?
Pulls from ddf-base 2.27-alpine which includes upgrade to java 11.

#### Who is reviewing it? 

@lavoywj 
@shaundmorris 
@jMoneee 
@zta6 
@kentmorrissey 

#### Ask 2 committers to review/merge the PR and tag them here.

@oconnormi
@shaundmorris

#### How should this be tested?

1. Build DDF
2. Build ddf-docker in /distribution/docker/ddf-docker
3. Run ddf-docker image
4. Log into the karaf shell and verify that DDF is working by installing `standard` profile. **(Make sure to increase RAM to somewhere around 6GB, I had personally set it to 6GB)**

#### What are the relevant tickets?
Fixes: #N/A.

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by frnkshin** [comment]
build now

**Review by shaundmorris — APPROVED** [review]

**Review by lavoywj — APPROVED** [review]

**Review by pklinef — APPROVED** [review]

**Comment by zta6** [comment]
hero in progress

**Comment by shaundmorris** [comment]
Just for referenced merged: https://github.com/codice/docker-ddf-base/pull/2

**Comment by zta6** [comment]
🎉 Hero Successful (finally) 🎉 
built and ran docker image
installed standard profile successfully

**Pull request merged**
