### PR TITLE
DDF-1343: Updated ldap filter to look at the whole string and updated documentation

### PR DESCRIPTION
**Pull request by AzGoalie**
Allows for factoryPids that don't end in Source or Service
@mverret Will hero
@shaundmorris 
@brendan-hofmann

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/92)

### CODE REVIEW

**Comment by brendan-hofmann** [comment]
Is that commit message really correct? You didn't make the ldap filter case sensitive, you fixed the match to take place anywhere in a string instead of just at the end.

Other than that, lgtm.

**Comment by brendan-hofmann** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/92)

**Comment by mverret** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/92)

**Comment by mverret** [comment]
Build, tests and manual verification were successful.  Looks good to me.

**Comment by shaundmorris** [comment]
Verified build. Itest failure was caused by another PR.

**Pull request merged**
