### PR TITLE
[2.13.x] DDF-3983 Add paging to PersistentStore

### PR DESCRIPTION
**Pull request by Bdthomson**
#### What does this PR do?
- Adds `removeSubscriptions` method to `SubscriptionsPersistentStore.java` interface
- Calls `removeSubscriptions` method on workspace deletion
- Adds `get` method with start index and page size to `PersistentStore.java` interface.
- Changes `SubscriptionsPersistentStore.java` to call `get` with a start of 0 and a page size of 1000 when retrieving workspace subscriptions.
#### Who is reviewing it? 

@brendan-hofmann 
@jrnorth 
@glenhein 
@ryeats 
 

#### Select relevant component teams: 
https://github.com/orgs/codice/teams
#### Ask 2 committers to review/merge the PR and tag them here.

@bdeining
@rzwiefel

#### How should this be tested?

1. Create 20 workspaces
2. Subscribe to all of them and get all workspaces again, they should all be marked with `subscribed: true`.

I've included a postman script to help.
[DDF.postman_collection.json.zip](https://github.com/codice/ddf/files/2207484/DDF.postman_collection.json.zip)

#### What are the relevant tickets?
[DDF-3983](https://codice.atlassian.net/browse/DDF-3983)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by Bdthomson** [comment]
build now

**Comment by samuelechu** [comment]
build now

**Comment by Bdthomson** [comment]
build now

**Comment by samuelechu** [comment]
Verified that workspaces marked with subscribed: true when subscribing to 20 workspaces.

Full build still needed

**Pull request merged**
