### PR TITLE
DDF-4010 Updating a documentation hyperlink to point to the most recent version of jts

### PR DESCRIPTION
**Pull request by Kjames5269**
Uncomment this block and include PR # of change against 2.13.x where appropriate.
When doing so, it is reasonable to delete much of the rest of the PR description, leaving only:
- This uncommented block with link to 2.13.x PR
- Reviewers tagged
- Teams tagged
- Committers tagged
- The link to the "Notes on Review Process"

##### ABBREVIATED REVIEW BETWEEN 2.13.X AND MASTER IS IN EFFECT
[Link to 2.13.x PR: #3498](https://github.com/codice/ddf/pull/3498)

Who is reviewing it?
@bakejeyner @brjeter

Select relevant component teams:
https://github.com/orgs/codice/teams

Ask 2 committers to review/merge the PR and tag them here.
@brendan-hofmann
@coyotesqrl

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by Kjames5269** [comment]
build now

**Comment by Kjames5269** [comment]
build now
(jenkins issue)

**Comment by Kjames5269** [comment]
build now
(CI issues)

**Comment by coyotesqrl** [comment]
Sidestepped CI for this documentation-only change.

**Pull request merged**
