### PR TITLE
DDF-04410 Ensures UI properties are initialized before first usage

### PR DESCRIPTION
**Pull request by djblue**
#### What does this PR do?

Fixes a slight regression around application initialization introduced by #4777.

#### Who is reviewing it? 

@andrewkfiedler 
@dimitry-sherman 
@Bdthomson 
@bdeining 

#### How should this be tested?

UI should not fail to initialize.

#### What are the relevant tickets?

Fixes: #4410

### CODE REVIEW

**Comment by djblue** [comment]
Build now

**Comment by djblue** [comment]
build now

**Comment by djblue** [comment]
build now

**Comment by djblue** [comment]
build now

**Comment by mojogitoverhere** [comment]
hero in progress

**Comment by mojogitoverhere** [comment]
## 🎉 Hero build was successful! 🎉 ##

UI loaded successfully. I also ran some queries and saved the workspace for fun.

**Pull request merged**
