### PR TITLE
DDF-04459 Fixes zip compression and dump command unit tests on windows

### PR DESCRIPTION
**Pull request by bellcc**
#### What does this PR do?
- Fixes unit tests on windows by using the proper file separator. 

#### Who is reviewing it? 
@willwill96 
@GabrielFabian 

#### Select relevant component teams: 
@codice/build 

#### Ask 2 committers to review/merge the PR and tag them here.
@andrewkfiedler
@tbatie

#### How should this be tested?
- Build the changed modules on windows

#### Any background context you want to provide?
- None

#### What are the relevant tickets?
For GH Issues:
Fixes: #4459 

#### Screenshots
- N/A

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by bellcc** [comment]
build now

**Comment by bellcc** [comment]
Build failed on `solr-distro` which builds successfully locally. The error seems to be related to artifacts.

**Comment by bellcc** [comment]
build now

**Comment by willwill96** [comment]
Hero Successful
Ran full build of modules changed and all unit tests passed

**Pull request merged**
