### PR TITLE
DDF-1355: Default Geocoder using the local Lucene index

### PR DESCRIPTION
**Pull request by jrnorth**
@millerw8 @jlcsmith @kcwire @wmcnalli @beyelerb @emanns95 @kguerriero @shane-voisard

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/94)

### CODE REVIEW

**Comment by jlcsmith** [comment]
<sup>**[catalog/spatial/geocoding/spatial-geocoding-api/src/main/java/org/codice/ddf/spatial/geocoding/GeoCodingConstants.java, line 17 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/94#-Jw3YM9Fc7cqVxXaBpHH)** ([raw file](https://github.com/codice/ddf/blob/c459064194122c871caf4d8377e062428768eea7/catalog/spatial/geocoding/spatial-geocoding-api/src/main/java/org/codice/ddf/spatial/geocoding/GeoCodingConstants.java#L17)):</sup>
I think we have been trying to use interfaces for constant classes like these. 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/94)

**Comment by jlcsmith** [comment]
<sup>**[catalog/ui/search-ui/search-geonames/src/main/java/org/codice/ddf/ui/searchui/geocoder/geonames/GeoResultCreator.java, line 33 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/94#-Jw3ZMWlTij2PiBk9OPp)** ([raw file](https://github.com/codice/ddf/blob/c459064194122c871caf4d8377e062428768eea7/catalog/ui/search-ui/search-geonames/src/main/java/org/codice/ddf/ui/searchui/geocoder/geonames/GeoResultCreator.java#L33)):</sup>
Any need to perform a null checking here?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/94)

**Comment by jlcsmith** [comment]
<sup>**[catalog/spatial/geocoding/spatial-geocoding-api/src/main/java/org/codice/ddf/spatial/geocoding/GeoEntryQueryable.java, line 31 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/94#-Jw3_kzRLJwaSu-pVm9U)** ([raw file](https://github.com/codice/ddf/blob/c459064194122c871caf4d8377e062428768eea7/catalog/spatial/geocoding/spatial-geocoding-api/src/main/java/org/codice/ddf/spatial/geocoding/GeoEntryQueryable.java#L31)):</sup>
looks like the javadocs are out of date with the code with regard to these exceptions

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/94)

**Comment by jlcsmith** [comment]
<sup>**[catalog/spatial/geocoding/spatial-geocoding-index/src/main/java/org/codice/ddf/spatial/geocoding/index/GeoNamesLuceneIndexer.java, line 209 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/94#-Jw3cOl3GoBuk1BtJvlL)** ([raw file](https://github.com/codice/ddf/blob/c459064194122c871caf4d8377e062428768eea7/catalog/spatial/geocoding/spatial-geocoding-index/src/main/java/org/codice/ddf/spatial/geocoding/index/GeoNamesLuceneIndexer.java#L209)):</sup>
How did you derive this scoring calculation?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/94)

**Comment by jlcsmith** [comment]
<sup>**[catalog/ui/search-ui/search-geonames/src/main/java/org/codice/ddf/ui/searchui/geocoder/geonames/GeoNamesLocalIndex.java, line 39 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/94#-Jw3e-bDytQlvjwYh5qe)** ([raw file](https://github.com/codice/ddf/blob/c459064194122c871caf4d8377e062428768eea7/catalog/ui/search-ui/search-geonames/src/main/java/org/codice/ddf/ui/searchui/geocoder/geonames/GeoNamesLocalIndex.java#L39)):</sup>
Can location be null here? 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/94)

**Comment by jlcsmith** [comment]
<sup>**[catalog/ui/search-ui/search-geonames/src/main/java/org/codice/ddf/ui/searchui/geocoder/geonames/GeoNamesLocalIndex.java, line 39 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/94#-Jw3e-bDytQlvjwYh5qe)** ([raw file](https://github.com/codice/ddf/blob/c459064194122c871caf4d8377e062428768eea7/catalog/ui/search-ui/search-geonames/src/main/java/org/codice/ddf/ui/searchui/geocoder/geonames/GeoNamesLocalIndex.java#L39)):</sup>
Can location be null here? 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/94)

**Comment by jlcsmith** [comment]
Reviewed 27 of 27 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/94)

**Comment by kguerriero** [comment]
Reviewed 27 of 27 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/94)

**Comment by wmcnalli** [comment]
Reviewed 20 of 27 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

<sup>**[catalog/spatial/geocoding/spatial-geocoding-index/pom.xml, line 93 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/94#-Jw3aMOHU0gWI5JL7-KS)** ([raw file](https://github.com/codice/ddf/blob/c459064194122c871caf4d8377e062428768eea7/catalog/spatial/geocoding/spatial-geocoding-index/pom.xml#L93)):</sup>
Update this comment to reflect removal of the BRANCH counter (instead of lowering of the limit) so it can be added back in later.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/94)

**Comment by beyelerb** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

<sup>**[catalog/spatial/geocoding/spatial-geocoding-api/src/main/java/org/codice/ddf/spatial/geocoding/GeoEntryQueryException.java, line 20 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/94#-Jw3j86jbpVWVH3ycg1l)** ([raw file](https://github.com/codice/ddf/blob/c459064194122c871caf4d8377e062428768eea7/catalog/spatial/geocoding/spatial-geocoding-api/src/main/java/org/codice/ddf/spatial/geocoding/GeoEntryQueryException.java#L20)):</sup>
Why extend RuntimeException instead of Exception? Do we want to allow the exception to bubble up out of the client's code without their knowledge? If not, then extend Exception and update the interface to throw GeoEntryQueryException (or create a GeoEntryException base class that GeoEntryQueryException, GeoEntryIndexException, etc. all extend and throw that.)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/94)

**Comment by jrnorth** [comment]
Review status: 26 of 27 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

<sup>**[catalog/spatial/geocoding/spatial-geocoding-api/src/main/java/org/codice/ddf/spatial/geocoding/GeoCodingConstants.java, line 17 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/94#-Jw3YM9Fc7cqVxXaBpHH)** ([raw file](https://github.com/codice/ddf/blob/c459064194122c871caf4d8377e062428768eea7/catalog/spatial/geocoding/spatial-geocoding-api/src/main/java/org/codice/ddf/spatial/geocoding/GeoCodingConstants.java#L17)):</sup>
Shouldn't interfaces be used to state provided services rather than data?

---

<sup>**[catalog/spatial/geocoding/spatial-geocoding-api/src/main/java/org/codice/ddf/spatial/geocoding/GeoEntryQueryable.java, line 31 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/94#-Jw3_kzRLJwaSu-pVm9U)** ([raw file](https://github.com/codice/ddf/blob/c459064194122c871caf4d8377e062428768eea7/catalog/spatial/geocoding/spatial-geocoding-api/src/main/java/org/codice/ddf/spatial/geocoding/GeoEntryQueryable.java#L31)):</sup>
How so? The implementation I've provided will throw all these exceptions as described.

---

<sup>**[catalog/spatial/geocoding/spatial-geocoding-index/pom.xml, line 93 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/94#-Jw3aMOHU0gWI5JL7-KS)** ([raw file](https://github.com/codice/ddf/blob/c459064194122c871caf4d8377e062428768eea7/catalog/spatial/geocoding/spatial-geocoding-index/pom.xml#L93)):</sup>
Don't I need to explicitly provide limits only for the ratios that I don't want to be 0.75? I removed this because the actual branch coverage ratio is > 0.75.

---

<sup>**[catalog/spatial/geocoding/spatial-geocoding-index/src/main/java/org/codice/ddf/spatial/geocoding/index/GeoNamesLuceneIndexer.java, line 209 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/94#-Jw3cOl3GoBuk1BtJvlL)** ([raw file](https://github.com/codice/ddf/blob/c459064194122c871caf4d8377e062428768eea7/catalog/spatial/geocoding/spatial-geocoding-index/src/main/java/org/codice/ddf/spatial/geocoding/index/GeoNamesLuceneIndexer.java#L209)):</sup>
Lots of experimentation. I can make a note of that in the comments.

---

<sup>**[catalog/ui/search-ui/search-geonames/src/main/java/org/codice/ddf/ui/searchui/geocoder/geonames/GeoResultCreator.java, line 33 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/94#-Jw3ZMWlTij2PiBk9OPp)** ([raw file](https://github.com/codice/ddf/blob/c459064194122c871caf4d8377e062428768eea7/catalog/ui/search-ui/search-geonames/src/main/java/org/codice/ddf/ui/searchui/geocoder/geonames/GeoResultCreator.java#L33)):</sup>
No. This method is only called after a GeoEntry object has been retrieved (either from the Lucene index or from the Web service), and GeoNames data always has a value for each of these fields.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/94)

**Comment by jrnorth** [comment]
Review status: 21 of 33 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

<sup>**[catalog/ui/search-ui/search-geonames/src/main/java/org/codice/ddf/ui/searchui/geocoder/geonames/GeoNamesLocalIndex.java, line 39 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/94#-Jw3e-bDytQlvjwYh5qe)** ([raw file](https://github.com/codice/ddf/blob/c459064194122c871caf4d8377e062428768eea7/catalog/ui/search-ui/search-geonames/src/main/java/org/codice/ddf/ui/searchui/geocoder/geonames/GeoNamesLocalIndex.java#L39)):</sup>
No, the gazetteer search box won't submit a query if nothing's been entered (or even if the string is only whitespace).

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/94)

**Comment by jrnorth** [comment]
Review status: 20 of 33 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

<sup>**[catalog/spatial/geocoding/spatial-geocoding-api/src/main/java/org/codice/ddf/spatial/geocoding/GeoEntryQueryException.java, line 20 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/94#-Jw3j86jbpVWVH3ycg1l)** ([raw file](https://github.com/codice/ddf/blob/c459064194122c871caf4d8377e062428768eea7/catalog/spatial/geocoding/spatial-geocoding-api/src/main/java/org/codice/ddf/spatial/geocoding/GeoEntryQueryException.java#L20)):</sup>
While it's true that many of these exceptions represent invalid conditions in areas outside the program's control rather than logic errors, I'm not sure that callers can be reasonably expected to recover from many of them.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/94)

**Comment by wmcnalli** [comment]
Review status: 20 of 33 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

<sup>**[catalog/spatial/geocoding/spatial-geocoding-index/pom.xml, line 93 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/94#-Jw3aMOHU0gWI5JL7-KS)** ([raw file](https://github.com/codice/ddf/blob/c459064194122c871caf4d8377e062428768eea7/catalog/spatial/geocoding/spatial-geocoding-index/pom.xml#L93)):</sup>
You're right.  I missed the memo that jacoco rules were cascading down from parent projects.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/94)

**Pull request merged**
