### PR TITLE
DDF-2118: Remove orphaned projects

### PR DESCRIPTION
**Pull request by tbatie**
#### What does this PR do?
Removes any module not listed from it's parent pom.
`distribution/ddf-distro-src`
`distribution/ddf-distro-repo`
`catalog/fanout`
`catalog/core/catalog-fanout-events`
`catalog/transformer/catalog-transformer-responsequeue-html`
`catalog/transformer/catalog-transformer-service-xml`

From what I found, either the modules were ancient and unused or there was a point in time the module were moved without deleting the original. I did make an exception to the ddf-sso-widget in the sdk. I listed it as a module and fixed a findbugs error within it. 
#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?
@ryeats @roelens8 @coyotesqrl 
#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@pklinef
@shaundmorris
#### How should this be tested?
All itests pass
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by tbatie** [comment]
The easiest way to review this pr may be to pull down the pr and look at changed files by directory in your IDE

**Comment by shaundmorris** [comment]
@tbatie What was your method for discovering orphaned projects? Was it manual or did you utilize a script?

**Comment by tbatie** [comment]
@shaundmorris Intellij will indicate whether a folder is a registered module with a blue square icon on the folder. I did a search for any folder with a pom but no icon.

**Comment by shaundmorris** [comment]
haha sweet @tbatie I never noticed that before :-) Glad to see ddf-distro-repo and ddf-distro-src finally go. They were created prior to the Github and Nexus environment we use now.

**Comment by tbatie** [comment]
I was just speaking with @pklinef about ddf-distro-repo and ddf-distro-src. It seems rather than remove them we should move them. I was considering to ddf-support

**Comment by shaundmorris** [comment]
Interesting, curious to hear the use cases for them.

**Comment by shaundmorris** [comment]
@tbatie @pklinef are we sure that ddf-distro-repo and ddf-distro-src still work?

**Comment by tbatie** [comment]
@shaundmorris I'm positive neither of them work. On top of incorrect groupId's, we must have been deploying a ddf with a `project` classifier that I have never seen https://github.com/codice/ddf/blob/master/distribution/ddf-distro-repo/pom.xml#L78. I'll have to back track through commits and see how it is being packaged

**Comment by pklinef** [comment]
@tbatie can you include a list of project directories you plan to remove in this PR in the PR description.  For example, `catalog/core/catalog-fanout-events` would be in the list.

**Comment by shaundmorris** [comment]
@tbatie that should be packaged as a zip https://github.com/codice/ddf/blob/master/distribution/ddf-distro-repo/pom.xml#L79

**Comment by tbatie** [comment]
@shaundmorris I meant more of the  contents of that zip. I assume it's different from the standard distribution else why use a classifier at all

**Comment by shaundmorris** [comment]
Oh thanks @tbatie for clarifying. So distro-rep was used to basically re-create a local maven repository necessary to build DDF. Basically it is the equivalent of doing a build and pointing to a new local repo like using `maven.repo.local`. So the original use case was to be able to re-create a zipped version of the maven repo so DDF could always be built locally without needing to connect to some remote maven repository (Nexus).

**Comment by lessarderic** [comment]
I added a comment to the ticket and then realized that there was already a PR up for this.

Here's a copy of the comment I added to the ticket. You may want to take a look at the few more modules that were flagged to see if they can be removed as well.

> I ran pom-explorer on ddf a couple days ago and got the follow list of unresolvable projects that we may want to look at:
```
sadly, there was 7 unresolvable projects:
ddf.catalog.core:fanout-events:2.8.0-SNAPSHOT (/Users/elessard/Documents/ddf/ddf/catalog/core/catalog-fanout-events/pom.xml)
ddf.catalog.fanout:catalog-fanout-pom:2.8.0-SNAPSHOT (/Users/elessard/Documents/ddf/ddf/catalog/fanout/pom.xml)
ddf.catalog.transformer:catalog-responsequeuetransformer-html:2.8.0-SNAPSHOT (/Users/elessard/Documents/ddf/ddf/catalog/transformer/catalog-transformer-responsequeue-html/pom.xml)
ddf.catalog.transformer:service-xml:2.8.0-SNAPSHOT (/Users/elessard/Documents/ddf/ddf/catalog/transformer/catalog-transformer-service-xml/pom.xml)
ddf.distribution:ddf-distro-repo:2.8.0-SNAPSHOT (/Users/elessard/Documents/ddf/ddf/distribution/ddf-distro-repo/pom.xml)
ddf.distribution:ddf-distro-source:2.8.0-SNAPSHOT (/Users/elessard/Documents/ddf/ddf/distribution/ddf-distro-src/pom.xml)
org.codice.ddf.ui:ddf-sso-widget:2.8.0-SNAPSHOT (/Users/elessard/Documents/ddf/ddf/distribution/sdk/ddf-sso-widget/pom.xml)
```

**Comment by tbatie** [comment]
@lessarderic All the modules you listed were removed :) With the exception of distro-repo & source (still figuring out what to do about those) and ddf-sso-widget which was fixed and added back to the parent pom.

**Comment by pklinef** [comment]
:+1:

**Comment by shaundmorris** [comment]
👍

**Pull request merged**
