### PR TITLE
DDF-1492 - removed content-type list from CSW Source and the logic to…

### PR DESCRIPTION
**Pull request by kcwire**
… update it

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/172)

### CODE REVIEW

**Comment by kcwire** [comment]
@dcruver is hero
@millerw8 
@coyotesqrl

**Comment by coyotesqrl** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[catalog/spatial/csw/spatial-csw-source/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/source/CswSource.java, line 1279 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/172#-JzC098BVXeKuJYJAih5)** ([raw file](https://github.com/codice/ddf/blob/ce65c5429de8939135d3b57c95753ef215fc33cf/catalog/spatial/csw/spatial-csw-source/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/source/CswSource.java#L1279)):</sup>
The old code doesn't care either, but access to the `contentTypes` map should probably be threadsafe. Either with a sync on this `put` and on the `getContentTypes()` method, or by using a threadsafe collection.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/172)

**Comment by jlcsmith** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/172)

**Comment by kcwire** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[catalog/spatial/csw/spatial-csw-source/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/source/CswSource.java, line 499 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/172#-JzH4FUqM08sLiKqb51R)** ([raw file](https://github.com/codice/ddf/blob/3065be7b650db13e74e966c516cfacabb312e99a/catalog/spatial/csw/spatial-csw-source/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/source/CswSource.java#L499)):</sup>
I added this back in - deleted too much.

---

<sup>**[catalog/spatial/csw/spatial-csw-source/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/source/CswSource.java, line 1279 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/172#-JzC098BVXeKuJYJAih5)** ([raw file](https://github.com/codice/ddf/blob/ce65c5429de8939135d3b57c95753ef215fc33cf/catalog/spatial/csw/spatial-csw-source/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/source/CswSource.java#L1279)):</sup>
updated to ConcurrentHashMap.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/172)

**Comment by coyotesqrl** [comment]
Lgtm

**Pull request merged**
