### PR TITLE
DDF-1674 Move the catalog sources admin ui beneath /admin

### PR DESCRIPTION
**Pull request by coyotesqrl**
To simplify security settings, all admin uis should be beneath /admin

@pklinef 
@tbatie 
@jckilmer (hero)

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/codice/ddf/pull/353" target="_blank">ReviewNinja

**Comment by pklinef** [comment]
:+1:

**Comment by tbatie** [comment]
https://i.imgur.com//qmb0T20.gif

**Comment by jckilmer** [comment]
**Heroed**
- Built successfully
- Verified configuration of catalog sources (added, modified, and deleted sources)
- Observed removal of /sources from Web Context Policy Manager

**Pull request merged**
