### PR TITLE
DDF-3915 Add os agnostic path separator to solr itest policy

### PR DESCRIPTION
**Pull request by rzwiefel**
#### What does this PR do?
Fixes path separator character
#### Who is reviewing it? 
@stustison 
`@anyone`

#### What are the relevant tickets?
https://codice.atlassian.net/browse/DDF-3915
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by coyotesqrl** [comment]
❓ Should this not be opened against `2.13.x`?

**Comment by rzwiefel** [comment]
@coyotesqrl it will *also* need to be against 2.13, yes.

**Comment by mcalcote** [comment]
I manually verified this change allowed me to run TestCatalog locally on Windows.

**Comment by rzwiefel** [comment]
manually verified change is working for mac itests as well

**Pull request merged**
