### PR TITLE
DDF-3915 Updated Automatically Starting Solr as a Process Documentation

### PR DESCRIPTION
**Pull request by mcalcote**
##### ABBREVIATED REVIEW BETWEEN 2.13.X AND MASTER IS IN EFFECT
Link to 2.13.x PR: #3450 
____

#### What does this PR do?
Revise steps in Automatically Starting Solr to account for the file structure in the distribution.

#### Who is reviewing it? 
@ricklarsen @rzwiefel @ahoffer @austinsteffes @garrettfreibott @JGatley @kcover 

#### How should this be tested?
Read through the changes.

#### Any background context you want to provide?
These steps were updated by following them to test automatic starting of the solr process.

#### Screenshots
image

image

#### Checklist:
- [x] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by ryeats** [comment]
I can't tell from the diff but does this support systemd?

**Comment by mcalcote** [comment]
@ryeats This was tested and confirmed to work on Centos7 though the Solr docs only say `Solr is tested on several versions of Linux, MacOS, and Windows.`

**Comment by mcalcote** [comment]
build now

**Comment by mcalcote** [comment]
Updated with changes from 2.13.X comments - build now

**Pull request merged**
