### PR TITLE
DDF-3811 Changed order for workspace delete

### PR DESCRIPTION
**Pull request by bdeining**
#### What does this PR do?
Changed order for workspace delete to occur before the queries are deleted.  This allows for access to the queries that belong to the workspace metacard before they are deleted.
#### Ask 2 committers to review/merge the PR and tag them here.
@bellcc @leo-sakh 

@andrewkfiedler
@jrnorth
#### How should this be tested?
CI Build ; functionality remains unchanged

#### What are the relevant tickets?
[DDF-3811](https://codice.atlassian.net/browse/DDF-3811)
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by bdeining** [comment]
build now

**Comment by andrewkfiedler** [comment]
It would be worth adding a test to make sure we don't regress on this.

**Comment by bdeining** [comment]
This class doesn't appear to have unit tests; so imo it's out of scope to write out all the unit tests for this one line change.  Ticket opened https://codice.atlassian.net/browse/DDF-4387

**Comment by andrewkfiedler** [comment]
Sounds good, thanks!

**Comment by vinamartin** [comment]
```
20:53:01 [INFO] ------------------------------------------------------------------------
20:53:01 [INFO] BUILD SUCCESS
20:53:01 [INFO] ------------------------------------------------------------------------
20:53:01 [INFO] Total time: 01:08 h
20:53:01 [INFO] Finished at: 2018-12-07T20:53:01+00:00
20:53:03 [INFO] Final Memory: 555M/1327M
20:53:03 [INFO] ------------------------------------------------------------------------
```

**Pull request closed without merging**
