### PR TITLE
DDF-2914 Upgrade Solr to 6.4.2

### PR DESCRIPTION
**Pull request by clockard**
#### What does this PR do?
Upgrades solr to version 6.4.2 to fix performance issue
#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged)?
@figliold 
#### Select at least one member from relevant component team(s) from below (at least one component team member needs to approve the PR).

[Solr](https://github.com/orgs/codice/teams/solr)

#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@lessarderic
@pklinef

#### How should this be tested? (List steps with links to updated documentation)
Verify build passes.
Verify sure solr admin ui still function
Verify Ingest/query functions still work
#### What are the relevant tickets?
[DDF-2914](https://codice.atlassian.net/browse/DDF-2914)
#### Checklist:
- [ ] Documentation Updated
- [ ] Change Log Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by clockard** [comment]
build now

**Comment by pklinef** [comment]
@clockard No changes to the Solr Admin UI that need to be copied over?

https://github.com/codice/ddf/tree/2.10.x/platform/solr/platform-solr-server-standalone/src/main/webapp

https://github.com/apache/lucene-solr/tree/releases/lucene-solr/6.4.2/solr/webapp/web

**Comment by pklinef** [comment]
Make sure the dependency versions match as well.

https://github.com/codice/ddf/blob/2.10.x/platform/solr/solr-dependencies/pom.xml
solr-6.4.2/server/solr-webapp/webapp/WEB-INF/lib

**Comment by clockard** [comment]
@pklinef There are no dependency changes between 6.4.1 and 6.4.2 so I think we are good with just the version updates. I am testing downstream dependencies to verify that everything still works.

**Comment by clockard** [comment]
Downstream project checks out.

**Pull request merged**
