### PR TITLE
DDF-1683 Simplify XACML configuration 

### PR DESCRIPTION
**Pull request by clockard**
Simplify XACML configuration by putting policy files in ddf-common and removing SampleXACML module
@stustison @vinamartin @gordocanchola

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/codice/ddf/pull/366" target="_blank">ReviewNinja

**Comment by vinamartin** [comment]
![Thumbsup]
(https://media.giphy.com/media/11S8BnxmNvYPpS/giphy.gif)

**Comment by stustison** [comment]
:+1:

**Comment by shaundmorris** [comment]
:thumbsup:

**Comment by gordocanchola** [comment]
:+1: Built and all tests passed.

**Pull request merged**
