### PR TITLE
DDF-2409 upgraded Jruby version used by docs module

### PR DESCRIPTION
**Pull request by ricklarsen**
#### What does this PR do?
 Upgrades jRuby dependency for documentation module

#### Select relevant component teams: 
@codice/build 
@codice/docs 

#### Ask 2 committers to review/merge the PR and tag them here.
@clockard
@mcalcote
@shaundmorris

#### How should this be tested?
Documentation module builds as expected

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by shaundmorris** [comment]
Can you check if we can remove these suppressions? I can help if needed. https://github.com/codice/ddf/blob/master/dependency-check-maven-config.xml#L70

**Comment by shaundmorris** [comment]
@ricklarsen what kind of things should look for to determine if this is good. I assume the documentation is generated, but anything else?

**Comment by ricklarsen** [comment]
> @ricklarsen what kind of things should look for to determine if this is good. I assume the documentation is generated, but anything else?

Ideally, this upgrade should be pretty invisible, so I think just getting the same results in both html and pdf versions should be enough

**Comment by ricklarsen** [comment]
build now

**Comment by shaundmorris** [comment]
I tried out jruby 9.2.6 and  9.2.11. Verified HTML and PDF docs were good (images, links). Can we use 9.2.11. I think it is the latest?

**Comment by ricklarsen** [comment]
upgraded jruby version to 9.2.11.1. Will rerun build now

**Comment by ricklarsen** [comment]
build now

**Comment by ricklarsen** [comment]
previous build timeout. rerunning 
build now

**Pull request merged**
