### PR TITLE
DDF-1773: Search UI issues related to return status and exception handling

### PR DESCRIPTION
**Pull request by jlcsmith**
Cherry-picked several commits from master into 2.8.x branch
- Search UI exception handling on search responses
- Google collection dependency causing erroneous exceptions in search endpoint

@codice/ui @pklinef @kcwire

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/codice/ddf/pull/439" target="_blank">ReviewNinja

**Comment by kcwire** [comment]
Looks like bamboo failed.

**Comment by jlcsmith** [comment]
Re-ran the bamboo build and it was successful this time.  It looks like an intermittent test failure in the content framework.  I wasn't able to duplicate it locally even from a clean build.

**Comment by pklinef** [comment]
:+1:

**Comment by millerw8** [comment]
I reviewed it for fun, looks good to me, tossed in a star :+1:

**Comment by andrewkfiedler** [comment]
LGTM :+1:

**Pull request merged**
