### PR TITLE
DDF-1563: removed vestiges of TrustedRemoteSource.

### PR DESCRIPTION
**Pull request by ricklarsen**
@stustison @clockard @vinamartin @djblue @shaundmorris

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/245)

### CODE REVIEW

**Comment by shaundmorris** [comment]
This looks like it works, you may have been able to add the disableCnCheck property to WfsConstants, but this seems good.

**Comment by shaundmorris** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/245)

**Comment by clockard** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/245)

**Comment by clockard** [comment]
lgtm :+1:

**Comment by vinamartin** [comment]
LGTM :+1:

**Comment by kcwire** [comment]
Reviewed 3 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/245)

**Comment by roelens8** [comment]
:+1:

**Comment by ahoffer** [comment]
Hero-ing complete. Ran
 `groovy PRBS.groovy https://github.com/codice/ddf/pull/245 dib --verbose`

No failures.

**Pull request merged**
