### PR TITLE
DDF-3566: Update Intrigue to use CQL query syntax with the CQL endpoint

### PR DESCRIPTION
**Pull request by garrettfreibott**
#### What does this PR do?
Intrigue now exclusively uses the characters `* ? \` to represent wildcard, single character wildcard, and escape respectively. These characters are translated to their CQL-equivalent syntax before querying the CQL endpoint and workspaces are saved with their queries in CQL format. Any user-inputted CQL special characters are escaped before sending. If a user wants to utilize these CQL characters, they must the `* ? \` syntax mentioned above.

#### Who is reviewing it? 
@djblue 
@vinamartin 
@rzwiefel

#### Select relevant component teams: 
@codice/ui 
@codice/io 

#### Choose 2 committers to review/merge the PR. 
@andrewkfiedler
@pklinef 

#### How should this be tested?
Install DDF, create a workspace with a query that uses CQL and Intrigue special characters, and ensure that when the query is run and the workspace is created, all outgoing requests have the following character transformations:
`* `=> `%`
`?` => `_`
`%` =>`\%`
`_` => `\_`
And that the queries displayed to the user within Intrigue use the original-inputted search text and not the CQL-translated versions. Also make sure that other searches behave normally.

#### Any background context you want to provide?
Previously, Intrigue would send a CQL query to the CQL endpoint and put the user-inputted search string into the query verbatim. This caused issues when the CQL endpoint tried to incorrectly interpret underscores and percentages. The solution decided on was to exclusively enforce the use of the already-commonly used `* _ \` on the frontend so it can be translated accurately to and from CQL syntax.

#### What are the relevant tickets?
[DDF-3566](https://codice.atlassian.net/browse/DDF-3566)

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by garrettfreibott** [comment]
build now

**Comment by garrettfreibott** [comment]
build now

**Comment by garrettfreibott** [comment]
build now

**Comment by garrettfreibott** [comment]
build now

**Comment by rzwiefel** [comment]
Heroed successfully

**Pull request merged**
