### PR TITLE
DDF-1389 Updates maven coordinates for distrubution/ddf and distribut…

### PR DESCRIPTION
**Pull request by roelens8**
…ion/kernel and distribution/ddf-common

Updates the maven coordinates to the requested values:

ddf.distribution:kernel to org.codice.ddf:kernel,
ddf.distribution:ddf to org.codice.ddf:ddf,
ddf.distribution:ddf-common to org:codice.ddf:ddf-common

@coyotesqrl 
@pklinef 
@jckilmer

Jason, could you please hero this?

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/138)

### CODE REVIEW

**Comment by coyotesqrl** [comment]
This is definitely not sufficient.

1. https://github.com/roelens8/ddf/blob/DDF-1389/distribution/ddf/pom.xml#L81 needs the coordinate update
2. https://github.com/codice/ddf/blob/master/distribution/test/itests/pom.xml#L90 needs to be updated

**Comment by roelens8** [comment]
Updated those.

**Comment by roelens8** [comment]
When changing the coordinates for distribution/ddf-common, I was receiving initialization errors when running various integration tests. For now, I am reverting that change.

**Comment by roelens8** [comment]
Integration tests now pass. Made a change in configureDistribution() within AbstractIntegrationTest.java to use org.codice.ddf instead of ddf.distribution.

**Comment by pklinef** [comment]
:+1:

**Comment by coyotesqrl** [comment]
Imma reserve my judgment until the Bamboo build finishes AND we get another clean hero build followed by a successful installation of the zip artifact. I think we're there now.

**Pull request merged**
