### PR TITLE
DDF-1889 Add "full-height" class to applications div

### PR DESCRIPTION
**Pull request by NGoss**
hero: @zryan3

### CODE REVIEW

**Comment by brendan-hofmann** [comment]
Can you include before/after screenshots?

**Comment by NGoss** [comment]
As far as I know, the issue that this fixes was only visible on DIB, not on DDF. Screenshots of DDF before/after wouldn't show any difference.

**Comment by NGoss** [comment]
Before: 
Before
After:
After

**Comment by brendan-hofmann** [comment]
LGTM pending hero results. :+1:

**Comment by zryan3** [comment]
Hero'ed and viewed on OSX successfully. Did a quickbuild on Windows to verify and the placement was fine. :+1:

**Comment by NGoss** [comment]
Rebased with codice master, no merge conflicts. @shaundmorris I think this is ready to go in.

**Comment by stustison** [comment]
This doesn't look correct to me. You actually want to add that full-height class to the application.handlebars template for the div with the id="wrapper" then the inner content will scroll correctly and not push the button off the page. Can you make those updates and new screenshots?

**Comment by NGoss** [comment]
After screenshot for the new change:
after

**Comment by zryan3** [comment]
Tested new changes on windows. Buttons are placed appropriately.

**Pull request merged**
