### PR TITLE
DDF-1735 Move SimpleSignTest from security-idp-client to security-core-api

### PR DESCRIPTION
**Pull request by ryeats**
Moved SimpleSignTest from security-idp-client to security-core-api and removed the dependencies it had on security-idp-client classes

@codice/green
Armand (can you hero this)

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/codice/ddf/pull/396" target="_blank">ReviewNinja

**Comment by coyotesqrl** [comment]
You added `platform/security/idp/security-idp-client/src/test/resources/serverKeystore.jks`? Or is the diff coming up weird?

**Comment by ryeats** [comment]
I modified the keystore to remove the alias that I had added for the dsa SimpleSign tests

**Comment by coyotesqrl** [comment]
:+1:

**Comment by roelens8** [comment]
Built successfully. :+1:

**Pull request merged**
