### PR TITLE
DDF-1386: Fix intermittent test failure

### PR DESCRIPTION
**Pull request by jrnorth**
@millerw8 @jlcsmith @kcwire @wmcnalli @beyelerb @emanns95 @kguerriero @shane-voisard

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/93)

### CODE REVIEW

**Comment by wmcnalli** [comment]
:+1: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/93)

**Comment by emanns95** [comment]
:+1:

**Comment by jlcsmith** [comment]
:+1:

**Comment by kguerriero** [comment]
:+1:

**Comment by kcwire** [comment]
:+1: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/93)

**Pull request merged**
