### PR TITLE
DDF-2337 changed the filter plugin logs for create to use metacard.getTitle instead of metacard.getId

### PR DESCRIPTION
**Pull request by stustison**
#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?
@coyotesqrl 
#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).
@pklinef
@stustison
#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by coyotesqrl** [comment]
👍

**Comment by pklinef** [comment]
Should we fall back to the ID if the title is blank?  Should we truncate the title if it is too long?  Are we concerned with duplicated titles?

**Comment by stustison** [comment]
Chances are pretty high that the ID is going to be null. It is only non-null when ingesting files as opposed to metacards. I could still use the ID if it is filled out and then fallback to the title, I just thought that might be a little confusing if you ended up with some records with titles and some with IDs in the same log message. I, personally, am not concerned with duplicates as this is just meant to be an aid to an integrator as to why a particular ingest failed.

**Comment by pklinef** [comment]
👍

**Pull request merged**
