### PR TITLE
Deleted catalog-ui-search

### PR DESCRIPTION
**Pull request by rzwiefel**
#### What does this PR do?
It is gone. It now lives over at https://github.com/codice/ddf-ui .
It will undergo another rebase to pull over any remaining commits so that people can switch. 

The artifacts have bumped versions to help make the switch to new artifacts easier. (3.0.0-SNAPSHOT)
#### Who is reviewing it? 
anyone
#### How should this be tested?
Ensure DDF still builds. 👌 
#### What are the relevant tickets?
Fixes: #5705

#### Screenshots
Check out what the UI looks like now:

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by rzwiefel** [comment]
build now

**Comment by rzwiefel** [comment]
build now

**Comment by pklinef** [comment]
build now

**Comment by rzwiefel** [comment]
build now

**Comment by rzwiefel** [comment]
build now

**Comment by rzwiefel** [comment]
build now

**Comment by rzwiefel** [comment]
build now

**Comment by rzwiefel** [comment]
build now

**Comment by rzwiefel** [comment]
build now

**Comment by rzwiefel** [comment]
build now

**Comment by rzwiefel** [comment]
build now

**Pull request merged**
