### PR TITLE
DDF-04748 Ban duplicate dependencies in pom files

### PR DESCRIPTION
**Pull request by rymach**
Ban duplicate dependencies in pom files

#### Who is reviewing it? 
@codice/build 

#### Ask 2 committers to review/merge the PR and tag them here.
@troymohl
@vinamartin

#### What are the relevant tickets?
Fixes: #4748

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by rymach** [comment]
build now

**Comment by rymach** [comment]
build now

**Comment by willwill96** [comment]
Is there ever a case where we might want two different versions of the same dependency?

**Comment by jrnorth** [comment]
@willwill96 I'm not sure but modules can always override the plugin configuration if they need to.

**Comment by jrnorth** [comment]
build now

**Comment by rymach** [comment]
build now

**Pull request merged**
