### PR TITLE
DDF-5168 Added missing dependencies to test-commons module

### PR DESCRIPTION
**Pull request by bdeining**
#### What does this PR do?
Added missing dependencies to test-commons module
#### Ask 2 committers to review/merge the PR and tag them here.

@bdthomson
@stustison

#### How should this be tested?

Build.  
#### Any background context you want to provide?
From a new M2 that is not hooked up to the local mirror, the build will fail to resolve these artifacts when building.
#### What are the relevant tickets?
Fixes: #____

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by bdeining** [comment]
build now

**Comment by troymohl** [comment]
build now

**Comment by troymohl** [comment]
Manual Hero: Full build on mac with empty .m2/repository was successful.

**Comment by bdeining** [comment]
build now

**Comment by bdeining** [comment]
build now

**Pull request merged**
