### PR TITLE
DDF-5291 fix goldenlayout titles: minimise maximise should be in US En…

### PR DESCRIPTION
**Pull request by rymach**
…glish (minimize, maximize) 🇺🇸 

Maybe we can push this change through and do the internationalization in a separate PR

#### Who is reviewing it? 
@millerw8 
@bdeining 
@djblue 

#### How should this be tested?

roll over icons
#### What are the relevant tickets?
Fixes: #____

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by rymach** [comment]
build now

**Comment by rymach** [comment]
build now

**Comment by jlcsmith** [comment]
Please update commits / PR with ticket number prior to merging

**Comment by vinamartin** [comment]
I accidentally merged these with the wrong commit #. It's a small change and hopefully we'll have a localization PR soon so I don't see any reason to revert this.

**Pull request merged**
