### PR TITLE
DDF-2376: moved search-ui help page into documentation profile

### PR DESCRIPTION
**Pull request by ricklarsen**
#### What does this PR do?

The "Help" page used by the search ui has been moved to within the documentation profile to allow rendering to be skipped, specifically in a Windows environment.

#### Who is reviewing it?
@Lambeaux @harrison-tarr 
#### Choose 2 committers to review/merge the PR.

@coyotesqrl
@shaundmorris

#### How should this be tested?

Windows builds will succeed if documentation profile is skipped.

#### What are the relevant tickets?

https://codice.atlassian.net/browse/DDF-2376

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by coyotesqrl** [comment]
:+1:

**Comment by ricklarsen** [comment]
Looks like bamboo didn't activate the documentation profile by default. Adding a fix for that.

**Comment by Lambeaux** [comment]
👍  Perfect! Let's :shipit: !!!

**Comment by shaundmorris** [comment]
👍

**Comment by shaundmorris** [comment]
Backport as well, right @ricklarsen ?

**Comment by Lambeaux** [comment]
Windows hero has started.

**Comment by ricklarsen** [comment]
@shaundmorris Will do

**Comment by Lambeaux** [comment]
Hero'd! 👍  :shipit: 
Passed yesterday just before the internet died.

**Comment by Lambeaux** [comment]
Hero'd for real now! :)

**Pull request merged**
