### PR TITLE
DDF-1498 Fixes issue where magically and non-deterministically null authorization field causes auth failures.

### PR DESCRIPTION
**Pull request by coyotesqrl**
In the case where the authorization bean is null, we can simply create a new one and move forward.

@kcwire is the hero
@AzGoalie 
@stustison

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/183)

### CODE REVIEW

**Comment by stustison** [comment]
LGTM

**Comment by rzwiefel** [comment]
:+1:

**Comment by kcwire** [comment]
I like the fix - annoyed that bamboo failed...

**Comment by coyotesqrl** [comment]
Pushed some pom changes for @lessarderic

**Comment by lessarderic** [comment]
:+1: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/183)

**Comment by lessarderic** [comment]
There's a chance that the itests failure was caused by the fact that catalog wasn't rebuilt as part of the PR build. Since we need the changes no matter what, @kcwire and I agreed that we should go ahead and merge to master anyways and see if the original itest failure still happens.

**Pull request merged**
