### PR TITLE
DDF-1470 - Added a newline following successfull ingestion

### PR DESCRIPTION
**Pull request by EIrwin**
@bdeining 
@jrnorth is hero

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/180)

### CODE REVIEW

**Comment by jrnorth** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/IngestCommand.java, line 208 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/180#-JzMsprct55ZNsJZOCPO)** ([raw file](https://github.com/codice/ddf/blob/9a94c4ae9718e2325f25325952b7e0573a293a64/catalog/core/catalog-core-commands/src/main/java/org/codice/ddf/commands/catalog/IngestCommand.java#L208)):</sup>
This will work fine, but it may be better to just add `%n` to the end of the string being printed.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/180)

**Comment by bdeining** [comment]
:thumbsup: 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/180)

**Comment by jrnorth** [comment]
Build was successful. Confirmed that there is a newline after a successful ingest.

**Comment by jrnorth** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/180)

**Pull request merged**
