### PR TITLE
DDF-1507 Added Fix for CSW ResultType query and related iTests

### PR DESCRIPTION
**Pull request by EIrwin**
Additionally had to make some refactorings in order to not use
embeeded classes due to failed equality comparisons with serialized
ResultType class.

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/240)

### CODE REVIEW

**Comment by millerw8** [comment]
There was a conscious decision to embed and get away from the design of having the schemas as their own bundle... which if I remember correctly, is how it was originally done.  However, I can no longer remember why we decided to do that. 


---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/240)

**Comment by jrnorth** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/240)

**Comment by kcwire** [comment]
Reviewed 1 of 7 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/240)

**Comment by millerw8** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/GetRecordsResponseConverter.java, line 86 \[r4\]](https://reviewable.io:443/reviews/codice/ddf/240#-K0RuEBJ4f-SlWpqiOjY)** ([raw file](https://github.com/codice/ddf/blob/2f6ad8f1898ffb8477ac6d71f1adab6d16822c1a/catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/GetRecordsResponseConverter.java#L86)):</sup>
What's the explanation of this change?  Was this an unused capability?  Do we do this another way now or are we losing functionality?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/240)

**Comment by EIrwin** [comment]
<sup>**[catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/GetRecordsResponseConverter.java, line 86 \[r4\]](https://reviewable.io:443/reviews/codice/ddf/240#-K0RuEBJ4f-SlWpqiOjY)** ([raw file](https://github.com/codice/ddf/blob/2f6ad8f1898ffb8477ac6d71f1adab6d16822c1a/catalog/spatial/csw/spatial-csw-transformer/src/main/java/org/codice/ddf/spatial/ogc/csw/catalog/converter/GetRecordsResponseConverter.java#L86)):</sup>
This section is now obsolete due to changes from Shane to `CswQueryResponseTransformer` where this is now done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/240)

**Comment by millerw8** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/240)

**Pull request merged**
