### PR TITLE
[2.20.x] DDF-5925 Adds query form id endpoint 

### PR DESCRIPTION
**Pull request by stevenmalmgren**
#### What does this PR do?
Adds an id based endpoint for query forms to allow skipping the soft commit delay. 
#### Ask 2 committers to review/merge the PR and tag them here.

@bdthomson
@andrewkfiedler 

#### How should this be tested?

Create a form. 
Access the newly created record in solr to view its id. 
Using that id, hit the new endpoint `internal/forms/query/<id>` with a tool like Postman.
Ensure the expected template form is returned.
#### What are the relevant tickets?
Fixes: #5925

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by jordanwilking** [comment]
I'm able to hit the endpoint with postman, but `getMetacardIfExistsOrNull` is returning null. I can see it in Solr though. 

I think it's worth someone else heroing. It may be ddf nonsense on my end.

**Comment by astagg** [comment]
**Hero Successful** 

- Configured basic auth for the purposes of testing.
image (2)

- Created a new `Search Form` in DDF.
- Hit https://localhost:8993/search/catalog/internal/forms/query/{search-form-id} with a GET request containing the metacard ID.
- Retrieved a JSON response of the `Search Form`.

**Comment by jlcsmith** [comment]
build now

**Comment by jlcsmith** [comment]
CI is having issues.  Local build passed.  Merging

**Pull request merged**
