### PR TITLE
Add null checking to SubjectUtils

### PR DESCRIPTION
**Pull request by bakejeyner**
#### What does this PR do?
Adds null checking to `SubjectUtils.getSubjectAttributes`.

#### Who is reviewing it? 
@blen-desta 
@garrettfreibott 
@stustison 
@bdeining 

#### How should this be tested?
Easy:
1. Build, run, and install DDF.
2. Login and logout using 2 different methods (PKI and BASIC, for example).

More Involved:
1. Build, run, and install DDF with debugging enabled.
2. Put a breakpoint at the top of `SubjectUtils.getSubjectAttributes`.
3. Log into DDF and perform operations until the breakpoint is hit.
4. (Feel free to message me about clarifying this one) Modify the subject object so on of its attributes contains a list containing only `null`.
5. Step through the rest of the `getSubjectAttributes` method. It should not error out.

#### What are the relevant tickets?
Fixes: #5160 

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by blen-desta** [comment]
build now

**Comment by bakejeyner** [comment]
build now
(failing test passed locally)

**Comment by bakejeyner** [comment]
build now
(looks like a random SecurityManager issue came up, assuming flaky since its the first time)

**Comment by bakejeyner** [comment]
build now
(added ehcache suppression)

**Comment by troymohl** [comment]
Hero: performed quick build and verified I could login, upload, and query data.

**Pull request merged**
