### PR TITLE
DDF-5041 Update Ace to Latest Version

### PR DESCRIPTION
**Pull request by willwill96**
#### What does this PR do?
Updates Ace to Latest version which fixes Windows builds
Renames .ts typescript files to .tsx so that line endings are handled properly
#### Who is reviewing it? 
@hayleynorton 
@zta6 
@Corey-Collins 
#### Ask 2 committers to review/merge the PR and tag them here
@adimka 
@djblue 
#### How should this be tested?
Ensure build passes on windows
Ensure build passes on mac
Remove license header from a file in the ui directory and verify that `yarn format` fails
#### What are the relevant tickets?
Fixes: #5041 

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by willwill96** [comment]
build now

**Comment by willwill96** [comment]
build now

**Comment by djblue** [comment]
@willwill96 why do ts files not work?

**Comment by willwill96** [comment]
@djblue Because .ts files are also a video file format, we have this line: https://github.com/codice/ddf/blob/master/.gitattributes#L16. 

which means the line endings are committed dependent on the operating system.
When video files are committed it's a good thing, because it ensures integrity of the file.
But when it's a typescript file, it makes the line endings inconsistent which messes with the license header logic.

**Comment by zta6** [comment]
Hero successful on windows
successful quickbuild
removed a license header, `yarn format` detected the missing header
ran `yarn format -w` and it re-added the missing header`
LGTM!

**Comment by Corey-Collins** [comment]
Hero successful on mac :tada: 
successful quickbuild, removed a license header, `yarn format` detected the missing header
ran yarn `format -w` and it re-added the missing header

**Pull request merged**
