### PR TITLE
DDF-04746 Conservatively convert var to const or let

### PR DESCRIPTION
**Pull request by rymach**
Reviewers may find it more efficient to review the method used to generate the var conversion changes instead of reviewing every changed line:
```
git clone git@github.com:cpojer/js-codemod.git
npm install -g jscodeshift
jscodeshift -t js-codemod/transforms/no-vars.js ddf/ui/**/*
```

#### Select relevant component teams: 
@codice/ui 

#### Ask 2 committers to review/merge the PR and tag them here.
@andrewkfiedler
@djblue

#### How should this be tested?
full build
#### What are the relevant tickets?
For Jira:
[](https://codice.atlassian.net/browse/)

For GH Issues:
Fixes: #04746

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Threat Dragon models
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Notes on Review Process
Please see [Notes on Review Process](https://codice.atlassian.net/wiki/spaces/DDF/pages/71946981/Pull+Request+Guidelines) for further guidance on requirements for merging and abbreviated reviews. 

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by rymach** [comment]
build now

**Comment by djblue** [comment]
build now

**Comment by djblue** [comment]
Hero in progress

**Comment by djblue** [comment]
Hero successful :tada:  no obvious regressions.

**Comment by bdeining** [comment]
build now

**Comment by djblue** [comment]
build now

**Pull request merged**
