### PR TITLE
DDF-2322 close InputStream objects returned by ContentItem#getInputStream

### PR DESCRIPTION
**Pull request by glenhein**
#### What does this PR do?
Close InputStream objects returned by ContentItem#getInputStream.

#### Who is reviewing it (please choose AT LEAST two reviewers that need to approve the PR before it can get merged; if a component team is listed, at least one of its members needs to approve)?

@bdeining
@jrnorth
@kcwire
@lcrosenbu 

#### Choose 2 committers to review/merge the PR (please choose ONLY two committers from below, delete the rest).

@beyelerb
@jlcsmith

#### How should this be tested?

Build and run under Windows. Configure the content directory monitor. Copy multiple files into the monitored directory. Watch the log file and verify that no errors are thrown. 

#### What are the relevant tickets?

DDF-2322

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

### CODE REVIEW

**Comment by jlcsmith** [comment]
This is the PR to fix this in 2.9.x  The one for master is already merged: https://github.com/codice/ddf/pull/1031

**Comment by bdeining** [comment]
:+1:

**Comment by jlcsmith** [comment]
👍

**Comment by jrnorth** [comment]
LGTM

**Comment by shaundmorris** [comment]
👍

**Pull request merged**
