### PR TITLE
DDF-3414 Adds missing iframe-resizer script to sources ui.

### PR DESCRIPTION
**Pull request by djblue**
#### What does this PR do?

Adds missing iframe-resizer script to sources ui.

#### Who is reviewing it?

@jefchng
@garrettfreibott 

#### Choose 2 committers to review/merge the PR.

@andrewkfiedler 
@rzwiefel

#### How should this be tested? (List steps with links to updated documentation)

- Quick build
- Go to Sources UI
- Add ~15 dummy sources
- Ensure that the iframe increases in size to accommodate all the sources

#### What are the relevant tickets?

[DDF-3414](https://codice.atlassian.net/browse/DDF-3414)

#### Checklist:
- [ ] Documentation Updated
- [ ] Update / Add Unit Tests
- [ ] Update / Add Integration Tests

#### Review Comment Legend:
- ✏️ (Pencil) This comment is a nitpick or style suggestion, no action required for approval. This comment should provide a suggestion either as an in line code snippet or a gist. 
- ❓ (Question Mark) This comment is to gain a clearer understanding of design or code choices, clarification is required but action may not be necessary for approval.
- ❗ (Exclamation Mark) This comment is critical and requires clarification or action before approval.

### CODE REVIEW

**Comment by djblue** [comment]
build now

**Comment by clockard** [comment]
We should make sure we backport this to the 2.11.x branch

**Comment by djblue** [comment]
@clockard I am going to open the backport PR after this PR gets merged.

**Comment by jefchng** [comment]
hero'd successfully.

**Pull request merged**
