### PR TITLE
DDF-1289 Added BeforeExam and AfterExam annotations

### PR DESCRIPTION
**Pull request by pklinef**
[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/55)

### CODE REVIEW

**Comment by pklinef** [comment]
@lessarderic @kcwire @garrettfreibott @roelens8

**Comment by roelens8** [comment]
I was able to fully build the ddf with a mvn clean install. Everything looks good with this pull request.

**Comment by roelens8** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/55)

**Comment by kcwire** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

<sup>**[distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestCatalog.java, line 41 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/55#-JsVP9JHiQpct0t7y_-F)** ([raw file](https://github.com/codice/ddf/blob/f42c20a8cf907ef8bb3f0ce4fe2366629e1b0b3e/distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestCatalog.java#L41)):</sup>
Shouldn't this be static?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/55)

**Comment by pklinef** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

<sup>**[distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestCatalog.java, line 41 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/55#-JsVP9JHiQpct0t7y_-F)** ([raw file](https://github.com/codice/ddf/blob/f42c20a8cf907ef8bb3f0ce4fe2366629e1b0b3e/distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestCatalog.java#L41)):</sup>
It should not be.  BeforeExam annotated methods have access to the test instance.  This particular method doesn't right now but I would rather not make it static so it does not waste anyone's time if they add instance members in the future.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/55)

**Comment by lessarderic** [comment]
<sup>**[distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestCatalog.java, line 71 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/55#-JsXtyI1jrYDlPlEmyir)** ([raw file](https://github.com/codice/ddf/blob/f42c20a8cf907ef8bb3f0ce4fe2366629e1b0b3e/distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestCatalog.java#L71)):</sup>
Not sure that I like other test classes having a dependency on this one. Shouldn't we have a separate class (e.g., CatalogAdaptor or CatalogFacade) instead that contains those utility methods? Also, since those methods are meant to be re-used, we should add JavaDoc comments explaining what they assert and what value they return.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/55)

**Comment by lessarderic** [comment]
Since AbstractIntegrationTest is a common class, can we move it under test-itests-common?

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---

<sup>**[distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/PaxExamRule.java, line 129 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/55#-JsY-GJYNVYMS3w6SuWo)** ([raw file](https://github.com/codice/ddf/blob/f42c20a8cf907ef8bb3f0ce4fe2366629e1b0b3e/distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/PaxExamRule.java#L129)):</sup>
invokeExplosively(). I like that! :-)

---

<sup>**[distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/PaxExamRuleTest.java, line 70 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/55#-JsY-ZsEGNqgXGYymnaS)** ([raw file](https://github.com/codice/ddf/blob/f42c20a8cf907ef8bb3f0ce4fe2366629e1b0b3e/distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/PaxExamRuleTest.java#L70)):</sup>
What happens if the sub-class also defines a PaxExamRule? Is that supported? Should we test this?

---

<sup>**[distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/PaxExamRuleTest.java, line 92 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/55#-JsY-tng2h5vqGYI_Y3A)** ([raw file](https://github.com/codice/ddf/blob/f42c20a8cf907ef8bb3f0ce4fe2366629e1b0b3e/distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/PaxExamRuleTest.java#L92)):</sup>
Do we need to test @Test(expected=...) too?

---

<sup>**[distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/PaxExamRuleTest.java, line 184 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/55#-JsY1TxCmuye9V00qPE7)** ([raw file](https://github.com/codice/ddf/blob/f42c20a8cf907ef8bb3f0ce4fe2366629e1b0b3e/distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/PaxExamRuleTest.java#L184)):</sup>
If an exception is thrown in the AfterExam method, should we expect one or two failures? Is that how the @AfterClass annotation works?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/55)

**Comment by pklinef** [comment]
I think AbstractIntegrationTest needs to be moved as suggested but also split up.  The majority could be split into another class and only the subset needed for extension would remain.  But I did not want to refactor too much under this ticket.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

<sup>**[distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestCatalog.java, line 71 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/55#-JsXtyI1jrYDlPlEmyir)** ([raw file](https://github.com/codice/ddf/blob/f42c20a8cf907ef8bb3f0ce4fe2366629e1b0b3e/distribution/test/itests/test-itests-catalog/src/test/java/ddf/catalog/test/TestCatalog.java#L71)):</sup>
This and a lot more from AbstractIntegrationTest should be moved to a common itest helper class.  That seemed like a much larger effort to design that properly so I changed these to static methods for anyone that might have been extending this class before can still get to these functions.  Long term they should not be using this methods on this class so I do not want to advertise it with JavaDoc here.

---

<sup>**[distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/PaxExamRuleTest.java, line 70 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/55#-JsY-ZsEGNqgXGYymnaS)** ([raw file](https://github.com/codice/ddf/blob/f42c20a8cf907ef8bb3f0ce4fe2366629e1b0b3e/distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/PaxExamRuleTest.java#L70)):</sup>
The rule should only be defined once like most of the out of the box JUnit rules.  It is not supported and I don't think it needs to be tested but I am now interested what would happen if someone did it.  My guess is it might execute the annotations once for each rule.  Anyone using AbstractIntegrationTest should not have to worry about the rule.

---

<sup>**[distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/PaxExamRuleTest.java, line 92 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/55#-JsY-tng2h5vqGYI_Y3A)** ([raw file](https://github.com/codice/ddf/blob/f42c20a8cf907ef8bb3f0ce4fe2366629e1b0b3e/distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/PaxExamRuleTest.java#L92)):</sup>
JUnit captures any exceptions thrown by the annotations and returns the failures.  There should be no un-handled exceptions returned from JUnit unless something is very wrong.

---

<sup>**[distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/PaxExamRuleTest.java, line 184 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/55#-JsY1TxCmuye9V00qPE7)** ([raw file](https://github.com/codice/ddf/blob/f42c20a8cf907ef8bb3f0ce4fe2366629e1b0b3e/distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/PaxExamRuleTest.java#L184)):</sup>
No, the first failure is from failingTest() which is always failing.  The second failure is the failure from the annotation.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/55)

**Comment by lessarderic** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

<sup>**[distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/PaxExamRuleTest.java, line 70 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/55#-JsY-ZsEGNqgXGYymnaS)** ([raw file](https://github.com/codice/ddf/blob/f42c20a8cf907ef8bb3f0ce4fe2366629e1b0b3e/distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/PaxExamRuleTest.java#L70)):</sup>
Should we add a comment about that of refer to the jUnit doc?

---

<sup>**[distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/PaxExamRuleTest.java, line 184 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/55#-JsY1TxCmuye9V00qPE7)** ([raw file](https://github.com/codice/ddf/blob/f42c20a8cf907ef8bb3f0ce4fe2366629e1b0b3e/distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/PaxExamRuleTest.java#L184)):</sup>
So this is basically what we talked about yesterday, i.e., if there's a failure in the @AfterExam, the last test will fail, right? If that's the case then I'm ok with this.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/55)

**Comment by pklinef** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

<sup>**[distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/PaxExamRuleTest.java, line 70 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/55#-JsY-ZsEGNqgXGYymnaS)** ([raw file](https://github.com/codice/ddf/blob/f42c20a8cf907ef8bb3f0ce4fe2366629e1b0b3e/distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/PaxExamRuleTest.java#L70)):</sup>
Adding a note in the PaxExamRule JavaDoc.

---

<sup>**[distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/PaxExamRuleTest.java, line 184 \[r1\]](https://reviewable.io:443/reviews/codice/ddf/55#-JsY1TxCmuye9V00qPE7)** ([raw file](https://github.com/codice/ddf/blob/f42c20a8cf907ef8bb3f0ce4fe2366629e1b0b3e/distribution/test/itests/test-itests-common/src/test/java/ddf/common/test/PaxExamRuleTest.java#L184)):</sup>
Yes, that is what is happening here.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/55)

**Comment by lessarderic** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/55)

**Comment by garrettfreibott** [comment]
Pulled and built with tests :+1: looks good!

**Comment by roelens8** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/55)

**Pull request merged**
