### PR TITLE
DDF-1615 Add color/logo customization to landing page

### PR DESCRIPTION
**Pull request by brendan-hofmann**
- change index.html to index.handlebars, since that's how it's being used
 - update default description
 - work around felix's handling of empty vectors by changing our few negative cardinalities to positive cardinalities

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf/298)

### CODE REVIEW

**Comment by brendan-hofmann** [comment]
@AzGoalie will hero.

**Comment by AzGoalie** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/298)

**Comment by NGoss** [comment]
Built successfully


---

Reviewed 7 of 7 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf/298)

**Comment by stustison** [comment]
selfie-2

**Comment by andrewkfiedler** [comment]
selfie-1

**Comment by AzGoalie** [comment]
Did a full build and passed all tests. Manually changed settings and worked. LGTM!

selfie-0

**Pull request merged**
