### PR TITLE
DDF-3103 Downgrade Marionette to 2.4.5 to avoid Windows build issue

### PR DESCRIPTION
**Pull request by albany551**
#### What does this PR do?
The 2.4.7 Marionette webjar added a wildcard to its pom.xml for its backbone dependency, which breaks windows builds. This downgrades all Marionette webjars to 2.4.5, which doesn't have a wildcard.

#### Who is reviewing it? 
@djblue 
@brendan-hofmann 
@emanns95 

#### Choose 2 committers to review/merge the PR. 
(please choose ONLY two committers from below, delete the rest)
@andrewkfiedler
@pklinef

#### How should this be tested? (List steps with links to updated documentation)
Build should succeed.

#### What are the relevant tickets?
https://codice.atlassian.net/browse/DDF-3103

### CODE REVIEW

**Comment by emanns95** [comment]
Confirmed Windows builds succeed with this change 👍

**Comment by albany551** [comment]
Yarn locks definitely need updating, but that's unrelated to this PR (although I'd be glad to throw it in here if that sounds appropriate).

**Comment by brendan-hofmann** [comment]
@mackncheesiest it should. Our convention is to fix regressions under the ticket that introduced them, as long as it was a recent change.

**Comment by albany551** [comment]
@_thatguy_ Fixed! :+1:

**Comment by bdeining** [comment]
build now

**Comment by pklinef** [comment]
❓ Is there a reason we do not just make our own webjar for Marionette 2.4.7?  We have done it for previous versions.

https://github.com/codice/webjars/tree/master/marionette-2.4.5

**Pull request merged**
